res/composer-schema.json

Editors such as Visual Studio leverages JSON Schema draft v4, but this schema was authored in the old draft v3. With just a few minor changes, the schema is now draft v4.
* Added `$schema` property to state it is using schema draft v4
* Changed `required` properties to arrays instead of strings. This is the only real difference from v3 to v4 in this schema

Converted to draft v4 schema

---

tests/Composer/Test/Repository/ArtifactRepositoryTest.php

It is required for some tests to run.

skip some tests when the zip extension misses

---

CONTRIBUTING.md
README.md

A link to the CONTRIBUTING.md will show up on Github's pull request
creation form. Plus, this makes the README shorter and more relevant for
users.

move contributing instructions to a separate file

---

src/Composer/EventDispatcher/EventDispatcher.php

Missing variable triggers ```PHP Notice: Undefined property: Composer\EventDispatcher\EventDispatcher::$listeners``` which throws ```ErrorException```

Added missing $listeners variable into EventDispatcher

---

src/Composer/Command/ShowCommand.php

Working with RedHat/CentOS systems I can't count the times I typed `composer info <package>` instead of `composer show <package>` since the equivalent `yum` command is `info`. So I open this PR to add an alias. I suppose I'm not the only one doing this mistake regularly and I think it improves the user experience.

Add 'info' alias for 'show' command

---

doc/articles/aliases.md
src/Composer/Package/Loader/ArrayLoader.php
src/Composer/Package/Loader/ValidatingArrayLoader.php
src/Composer/Package/Version/VersionParser.php
tests/Composer/Test/Package/Loader/ArrayLoaderTest.php
tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php
tests/Composer/Test/Package/Version/VersionParserTest.php
tests/Composer/Test/Package/Version/VersionSelectorTest.php

The issue seems to be that aliased branches were checked for `dev-` prefix, where numeric branches are named with `-dev` as a suffix instead.
Fixes https://github.com/composer/composer/issues/3461

Fix broken aliases for numeric branches. Fixes #3461

---

doc/02-libraries.md
doc/04-schema.md

Document how the VersionParser also accepts shorthand variations of `alpha`, `beta`, and `patch`.

Update documententation for version shorthand parsing

---

src/Composer/Config.php
tests/Composer/Test/ConfigTest.php

This is the fix for this issue:
https://github.com/composer/composer/issues/3654
Take a look at the screenshots:
Before fix:
After fix:

Fix error handling for incorrect "repositories" array

---

doc/04-schema.md
res/composer-schema.json
src/Composer/Autoload/AutoloadGenerator.php
src/Composer/Autoload/ClassLoader.php
src/Composer/Command/ConfigCommand.php
src/Composer/Command/DumpAutoloadCommand.php
src/Composer/Command/InstallCommand.php
src/Composer/Command/UpdateCommand.php
src/Composer/Config.php
tests/Composer/Test/Autoload/AutoloadGeneratorTest.php

Add a "classmap-authoritative" configuration setting that can be used to
disable searching the various prefix and fallback directories for
classes that have not been registered with the
Composer\Autoload\ClassLoader class map. This setting can be used to
optimize performance by avoiding a potentially large number of
`file_exists` calls when Composer is being used in a program with
additional autoloader facilities. Use of the setting implies
"optimize-autoloader" to ensure that the most complete class map
possible is generated.
Closes #3603

Add classmap-authoritative config setting

---

src/Composer/Package/Version/VersionParser.php

According to http://php.net/manual/en/function.preg-match.php and some other sources named groups should contain a 'P' character after the '?'
Without this, I receive the following error when running an update:
[ErrorException]                                                                
preg_match(): Compilation failed: unrecognized character after (?< at offset 4  
Exception trace:
() at phar:///directory/composer.phar/src/Composer/Package/Version/VersionParser.php:181

Add the P character to the regex pattern

---

src/Composer/Command/HomeCommand.php

Small but useful option to show instead of launching the repository or homepage URL.
use:  with -s or --show option
$composer home monolog/monolog -Hs
Homepage URL: http://github.com/Seldaek/monolog
$composer home monolog/monolog --show  (or -s)
Repository URL: http://github.com/Seldaek/monolog

Only show instead of open the repository or homepage URL

---

src/Composer/Command/SelfUpdateCommand.php

In selfupdate command, reuse original file's permission instead of using `umask`

Reuse current file permissions in selfupdate

---

src/Composer/Command/InstallCommand.php
src/Composer/Command/UpdateCommand.php

The option isn't used for a long time already, but there was no warning about the usage of it. This could lead to confusion, as people could be thinking that no-dev is the default.

Added deprecated warning for the dev option

---

src/Composer/Command/DiagnoseCommand.php
src/Composer/Util/GitHub.php
tests/Composer/Test/Repository/Vcs/GitHubDriverTest.php
tests/Composer/Test/Util/GitHubTest.php

With the new changes to the GitHub authorizations API endpoint, it will no longer be possible to retrieve existing token values. As composer currently does not use an application token, but rather a personal token, I couldn't think of any solution other than simply creating a new token whenever one is not available in the auth configuration.
I also had to change the note to always include the timestamp. A 422 error regarding duplicate content creation would be thrown otherwise as this field has to be unique.
Alternatively, we could still retrieve a user's current authorizations. Then notify the user in case of an existing one with an identical note and instruct them to remove it from https://github.com/settings/applications before proceeding, or merely warn them and proceeding …

GitHub api v3 deprecations, closes #3566

---

src/Composer/Json/JsonValidationException.php

The Exception classname has been imported with `use` statement.

Simplified syntax

---

src/Composer/Repository/Vcs/GitDriver.php

for some reason it does not work (in packagist) without the $output param. I don't get any error message here, maybe someone has an idea, why?
Anyway, need this ;)

fix bug in GitDriver::supports for remote repo

---

doc/04-schema.md
res/composer-schema.json
src/Composer/Package/Loader/RootPackageLoader.php
tests/Composer/Test/Package/Loader/RootPackageLoaderTest.php

Hello!
We had a problem on handling our release and testing branches with composer correctly, when using "self.version" on dependencies, when the release branch has a non-numeric / non-version name, like "latest" or "latest-testing" or "latest-production".
If the root package branch name does not look like a version number, then composer handles the branch as feature branch, which means, it checks all ancestors until it finds a parent branch or tag that looks like a version number or at least ends on master/develop/trunk.
This is a problem if during a testing or release phase you are working with (and also releasing) branches that are named "latest-testing" "current-release" or whatever, when you have dependencies defined with self.version. Since latest-testing is a branch created from …

added non-feature-branches

---

src/Composer/Installer.php
tests/Composer/Test/Fixtures/installer/root-requirements-do-not-affect-locked-versions.test

Concerning https://github.com/composer/composer/issues/3720
Original PR was https://github.com/composer/composer/pull/3736
After a healthy discussion in the original PR this is my alternative proposal, that is way less intrusive than the original solution.
Now the installer itself removes the requirements from the root package, should it install from a locked state.

Ignore root requirements in installer when installing from locked state

---

tests/Composer/Test/Fixtures/installer/replaced-packages-should-not-be-installed-when-installing-from-lock.test
tests/Composer/Test/Fixtures/installer/replaced-packages-should-not-be-installed.test

If you require a package, that replaces another package in a specific version, an installation from the json file will install a conflicting version of the replaced package alongside the replacing package.
An install attempt from the resulting lock file will then fail as it recognizes the conflict.
This problem became apparent after this PR: https://github.com/composer/composer/pull/3740, as an install request with an existing lock file will now ignore the json completely. Before the patch it seems to have ignored the conflict even when installing from lock.
This PR currently just contains two tests, that reproduce the problem. No fix has been implemented, yet.
As requested by @Seldaek I hereby /cc @naderman for this PR.

Requiring conflicting, replaced packages

---

src/Composer/DependencyResolver/Solver.php

Missing property triggers ```PHP Notice: Undefined property: Composer\DependencyResolver\Solver::$learnedWhy``` which throws ```ErrorException```

Added missing $learnedWhy property

---

src/Composer/Console/HtmlOutputFormatter.php

According to Symfony Coding Standards, a single space must be added around binary operators excluding the concatenation operator.
"Add a single space around binary operators (==, &&, ...), with the exception of the concatenation (.) operator" (http://symfony.com/doc/current/contributing/code/standards.html)

Conform with Symfony Coding Standards

---

tests/Composer/Test/AllFunctionalTest.php

Hopefully fixes sporadic failure of test suite.
Alternatively, we could replace
```
$proc = new Process($cmd, __DIR__.'/Fixtures/functional');
```
with
```
$proc = new Process($cmd, __DIR__.'/Fixtures/functional', null, null, $timeout);
```
where `$timeout` is something higher than the default of 60.
/cc @Seldaek @stof suggestions / feedback?

retry slow test if timeout occurs

---

composer.json
composer.lock

PHPUnit 5.4 provides [prophecy out-of-the-box](http://thephp.cc/news/2015/02/phpunit-4-5-and-prophecy). This mocking framework is good to have to write composer tests.
Related to https://github.com/composer/composer/pull/3765

Upgrade PHPUnit to 4.5 to get prophecy

---

src/Composer/Command/LicensesCommand.php

Unlike the `TableHelper`, the `render()` method of the `Table` class
does not make use of an `$output` argument. The actual `OutputInterface`
to send the table to is passed in the constructor instead.

remove unused method argument

---

doc/05-repositories.md

If you want to use a custom branch as a requirement in your `composer.json`, that branch must be prefixed with "dev-" or you'll get an error:
```sh
[UnexpectedValueException]
Could not parse version constraint some-branch: Invalid version string "some-branch".
```
It took me a while to find that info on forums and blogs, so I figured I'd rather update the doc. :grin: 
Let me know.

VCS section: add requirements for the branch name

---

src/Composer/Util/ProcessExecutor.php

For some reason, I ran composer with LANGUAGE=fr_FR, and that breaks parsing git's output.

Run processes with predictable LANGUAGE=C

---

src/Composer/Command/CreateProjectCommand.php

When I use `create-project` with `--no-progress`, the no-progress is used only with root package but not dependencies.
```
$ composer create-project composer/composer --stability=dev --prefer-dist --no-progress
Installing composer/composer (dev-master b8ac790b4f2db1f718e640015636f005401c1c71)
- Installing composer/composer (dev-master master)
Downloading
Created project in /var/www/composer
Installing dependencies (including require-dev) from lock file
- Installing justinrainbow/json-schema (1.3.7)
Downloading: 100%
- Installing seld/jsonlint (1.3.1)
Downloading: 100%
- Installing symfony/console (v2.6.4)
Downloading: 100%
```
This PR fix the problem:
```
$ composer create-project composer/composer --stability=dev --prefer-dist …
```

[create-project] Used no progress value for dependencies

---

src/Composer/Json/JsonFile.php

Null is given to parseJson() when there is some problem with getContents().
With PHP < 7 the json_last_error would return JSON_ERROR_NONE but with PHP > 7 it will return JSON_ERROR_SYNTAX and this is causing the tests to fail because they enter the validateSyntax() which will return an exception because of the null.
I'm not sure if this is the best solution for the failing test but I think it makes the parseJson safer at least.
Related:
PHP issue: https://bugs.php.net/bug.php?id=69187
Upgrading PHP info https://github.com/php/php-src/commit/9d037d574cc359405c7a818c2235644633705999

Make parseJson safer

---

.travis.yml

Nightly releases could change in unpredictable way.  So they should not fail the whole build.
However we could catch problems and breaking changes on next versions of HHVM early.
I suspect Composer have some problems on HHVM nightly, because of this build: https://travis-ci.org/erusev/parsedown/jobs/53556585#L94

Test on HHVM nightly releases. Allow to fail.

---

src/Composer/Factory.php

If I understood this correctly, we have no guarantee that the COMPOSER_HOME will not end with ```/``` or ```\``` so we should rely on the Config instead.

Use get home from Config instead of factory

---

.travis.yml

This will report the build has succceeded even if allowed to fail jobs are still running.
See https://github.com/composer/composer/pull/3828.
Docs: http://docs.travis-ci.com/user/build-configuration/#Fast-finishing
Props to @fonsecas72.

Report Travis CI build success early

---

src/Composer/Autoload/ClassMapGenerator.php
tests/Composer/Test/Autoload/ClassMapGeneratorTest.php
tests/Composer/Test/Autoload/Fixtures/hhvm3.3/Generics.php
tests/Composer/Test/Autoload/Fixtures/hhvm3.3/HackEnum.php
tests/Composer/Test/Autoload/Fixtures/hhvm3.3/NamespacedHackEnum.php

fixes composer/composer#3823
Ran tests with both PHP5.5.9-1ubuntu4.5 and HHVM 3.6. Test fails on HHVM only
if I back out the ClassMapGenerator.php change.

Add support for using classmap to autoload Hack enums

---

src/Composer/Command/InitCommand.php

It's really strange to say that `zendframework zend-eventmanager` is a full package name, since Composer always uses `zendframework/zend-eventmanager`.

Updated validator

---

composer.json

justinrainbow/json-schema version 1.4.0 has been tagged (https://github.com/justinrainbow/json-schema/releases/tag/1.4.0), which fixes naming conflicts with Scalar Type Hints in (what will be) PHP 7.

Use justinrainbow/json-schema 1.4

---

doc/00-intro.md

It is best practice to use `__DIR__` constant. Also it's used in `autoload.php` itself.

Readme: 00-intro - use __DIR__

---

src/Composer/Installer/LibraryInstaller.php

If not silenced it gives "symlink(): Operation not supported" on my ubuntu system with mounted cifs share.

Silence symlink() error

---

tests/Composer/Test/Repository/RepositoryManagerTest.php

Updates RepositoryManager tests to use the data provider that was defined and adds an additional repository to assert the exception for unrecognized repository types.

Use data provider in RepositoryManager tests

---

tests/Composer/Test/Util/FilesystemTest.php

The testsuite didn't run through for me because the php symlink() function
was missing.
It is only available on Windows Visa/Server 2008 or higher.
This commit fixes the issue by checking if the method exists, and if not,
marks the test as skipped because of a non-matching precondition.

Prevent fatal error on missing symlink() function in tests

---

src/Composer/Downloader/GitDownloader.php
tests/Composer/Test/Downloader/GitDownloaderTest.php

This fixes a minor inaccuracy issue when creating git checkout commands
for branches.
The git checkout command used within `GitDownloader::updateToCommit()`
does  not use the "`--`" sequence to separate branch from file parameters.
This leads to an inaccuary as git tries as well the branch name as file
name. If the non-existent branch is actually the name of a file, the file
is checked out. If the non-existent branch is not the name of a file, an
error message is given:
> error: pathspec 'non-existent-branch' did not match any file(s) known to
git.
Both cases are not expected for the program flow in
`GitDownloader::updateToCommit()`.
The only thing that is expected is a non-existent branch to fail to
checkout - but with a different error message:
> // reference was not found (prints …

Git Checkout Branch / File Differentiation

---

src/Composer/Command/RequireCommand.php

Using the require command, if there is a blank composer.json a parser error is thrown:
[Seld\JsonLint\ParsingException]
"./composer.json" does not contain valid JSON
Parse error on line 1:
^
Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

Avoid parser error if composer.json existing but empty

---

src/Composer/Command/DiagnoseCommand.php

Fixed undefined var ```$domain``` in DiagnoseCommand::execute().
I introduced [this bug](https://github.com/phansys/composer/commit/5b2a7e6bad10bd2f0622973c03e907647a92b0bc#diff-834340f065067888bcc9eccd566b600eR121) in #3929. My apologies.

[bugfix] Fixed undefined var in DiagnoseCommand::execute().

---

src/Composer/Command/InitCommand.php

This PR adds the ability to set the package's type from the `composer init` command.
Adds support for `help init` command output, `init --type` flag, and interactive input.

allow package type to be set with init command

---

src/Composer/Command/InitCommand.php
tests/Composer/Test/Command/InitCommandTest.php

Could also change it to just accept whatever. Do we really want to enforce strict rules regarding valid author names?
Closes #3948

Allow numeric author name

---

doc/05-repositories.md

I'm not a native English speaker, but I think that we must use _a_ (and not _an_) in front of a _u_ when it is pronounced _you_ (like in _user_).
Source: https://www.englishclub.com/pronunciation/a-an.htm

[Docs] [Typo] Correct a misused article in the docs

---

src/Composer/Config.php
src/Composer/Installer.php
src/Composer/Repository/PlatformRepository.php

Here's my attempt at #1522.
If a package is present in the 'platform'  config option, that package will override whatever PlatformRepository finds.
The "1.0.0" value is a version and not a constraint, so you can't do `"ext-pdo":"*"`. I don't know if that's a good idea though.
```
"config":{
"platform": {
"ext-pdo": "1.0.0"
}
}
```
It also assumes that only a single version of each platform package will be found.
Finally, no tests in there. I wouldn't know where to start...
I have tested it locally though with success.

Ignore platform packages

---

src/Composer/Package/Version/VersionSelector.php
tests/Composer/Test/Package/Version/VersionParserTest.php
tests/Composer/Test/Package/Version/VersionSelectorTest.php

Should not be merged until the ^ op is in a release IMO.

Use caret operator for 0.x releases when guessing versions, fixes #3518

---

doc/dev/DefaultPolicy.md
src/Composer/DependencyResolver/DefaultPolicy.php
tests/Composer/Test/Fixtures/installer/install-prefers-repos-over-package-versions.test

In practice it is quite rare to have a package in multiple repos unless you intend to install your own fork of it, so I don't think this breaks any real use case, and it would improve security by preventing hijacks from packagist using a higher version of a private package.
@naderman I'd be happy to get your feedback in case you think of something I missed, otherwise I'll go ahead and merge.
Fixes #3509

Prioritize repository over package versions in the default policy

---

src/Composer/Cache.php

When Composer copies a file from its cache to a vendor directory, it does a `touch` on the cached file which sets both the modification time and access time of the file to the current time. This is to ensure that only the least-recently used files are pruned from the Composer cache when garbage collection runs. However, Composer's cache garbage collection seems to only test the access time of cached files, not the modification time, which means the `touch` doesn't actually need to update the modification time of the cache files when they are read.
Changing the modification time of files causes issues on Travis CI when the _cache_ feature is used on the `$HOME/.composer/cache` directory, as Travis checks the modification times of the files in that directory on every build.
The idea of this …

Fix Travis cache issue (~/.composer/cache changes on every build)

---

src/Composer/Util/AuthHelper.php

This fixes the issue described in https://github.com/composer/composer/issues/3987 which causes an exception to always be thrown when asked if you want to store your authentication credentials.

AuthHelper Exception Fix on Store Credentials

---

src/Composer/Command/ShowCommand.php
src/Composer/Installer.php
tests/Composer/Test/Fixtures/installer/abandoned-listed.test

Currently the abandoned package messages use `<error>` which displays a red message. [This](https://github.com/reactphp/http/issues/24) [seems](https://github.com/ratchetphp/Ratchet/issues/309) [to](https://github.com/ratchetphp/Ratchet/issues/285) [lead](https://github.com/ratchetphp/Ratchet/pull/287) [to](https://github.com/ratchetphp/Ratchet/issues/305) some confusion by users thinking the the message is an error not an warning. Therefore I'm proposing by this PR to use `<warning>` displaying a yellow message instead.
Using an abandoned package:
Showing a package's using `composer show vendor/package`:

Replaced <error> with <warning> for abandoned package messages

---

src/Composer/Json/JsonManipulator.php
tests/Composer/Test/Json/JsonManipulatorTest.php

This PR
Follows #3549.
:bulb: Not sure if anyone but me uses that feature, but it would be a lot nicer if packages were sorted by importance (platform packages first), then followed by PHP dependencies, both sorted alphabetically.
See https://getcomposer.org/doc/02-libraries.md#platform-packages.
> 
* `php` represents the PHP version of the user, allowing you to apply constraints, e.g. `>=5.4.0`. To require a 64bit version of php, you can require the php-64bit package.
>* `hhvm` represents the version of the HHVM runtime (aka HipHop Virtual Machine) and allows you to apply a constraint, e.g., `>=2.3.3`.
> * `ext-<name>` allows you to require PHP extensions (includes core extensions). Versioning can be quite inconsistent here, so it's often a good idea to just set the constraint to *. An …

Enhancement: Sort packages by importance, then alphabetically

---

tests/Composer/Test/Json/JsonFileTest.php

Hi all,
It seems there is a little problem with Json parsing (testing).
The JsonFileTest.php (https://github.com/composer/composer/blob/master/tests/Composer/Test/Json/JsonFileTest.php#L60) keeps failing for my setup.
A little test script for some background info:
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';
$json = '{
\'foo\': "bar"
}';
$data = json_decode($json, true);
var_dump($data);
var_dump(json_last_error());
$a = extension_loaded('json');
var_dump($a);
$a = phpversion('json');
var_dump($a);
// made "public" for testing
\Composer\Json\JsonFile::validateSyntax($json);
```
Result
```
array(1) {
'foo' =>
string(3) "bar"
}
int(0)
bool(true)
string(5) "1.3.2"
PHP Fatal error:  Uncaught exception 'Seld\JsonLint\ParsingException' with message '"" does not contain valid JSON …
```

On Json tests failures show more test failure details

---

src/Composer/Util/Svn.php

=> Fails before attempting to use authentication provided in auth.json because the svn command outputs to STDOUT *and* STDERR, which breaks the condition that checks for an authentication issue before throwing a RuntimeException.

Fixed svn update command

---

src/Composer/Autoload/ClassMapGenerator.php
src/Composer/Command/DiagnoseCommand.php
src/Composer/Command/InitCommand.php
src/Composer/Console/Application.php
src/Composer/Json/JsonFile.php
src/Composer/Util/RemoteFilesystem.php
src/Composer/Util/StreamContextFactory.php
tests/Composer/Test/Autoload/ClassMapGeneratorTest.php
tests/Composer/Test/Json/JsonFileTest.php
tests/Composer/Test/Util/StreamContextFactoryTest.php

`PHP_VERSION_ID` is available since PHP 5.2.7 and already used in Composer. This will speeds up PHP version checking. With `Composer requires PHP 5.3.2+ to run.` this should be safe to do.

PHP version checks tweaking

---

doc/articles/custom-installers.md

The link was pointing to Composer\Plugin\PluginInterface since
commit 98e5eab. Fix the link by updating the reference from
`[3]` to `[4]`.

Fix link to Composer\Installer\InstallerInterface.

---

src/Composer/Downloader/GitDownloader.php
tests/Composer/Test/Downloader/GitDownloaderTest.php

This should fix issue #3417.
I've tested it against the `composer.json` that replicates the issue and confirmed the download works properly.

Fix Git failures due to ambiguous argument (issue #3417)

---

src/Composer/Downloader/PearPackageExtractor.php
tests/Composer/Test/Downloader/PearPackageExtractorTest.php

If the entity loader is disabled on a system, loading files, even from the local file system, is considered as external to the running php process, and thus not allowed by the libxml extension. Reading the file contents and loading the xml as a string is a valid alternative however.
Fixes #3942

load xml as string from local file, fixes #3942

---

src/Composer/Repository/PlatformRepository.php

This happens on `new PlatformRepository(array($somePackage))`.
The parent constructor calls `\Composer\Repository\ArrayRepository::addPackage()`, which, on a brand new repo object, further calls `\Composer\Repository\PlatformRepository::initialize()` and finally this iterates over a `NULL` `$this->overrides`, triggering the error.

Fix "Invalid argument supplied for foreach()" on a new PlaformRepository obj

---

src/Composer/Command/ShowCommand.php

gracefully remove the option and continue, after informing the user

disable path if no composer available, fixes #4101

---

src/Composer/Util/Filesystem.php
tests/Composer/Test/Util/FilesystemTest.php

Resolves #3024
Passing the third argument as `true` on `findShortestPath ` method, a dummy file is added to `$from`. 
If `$from` ends with `/` (e.g. C:/ , /foo/bar/ ), a second `/` is inserted resulting on a invalid path.

Remove extra '/' when findShortestPath $from is a directory

---

doc/articles/plugins.md
src/Composer/Package/Version/VersionParser.php
tests/Composer/Test/Package/Version/VersionParserTest.php
tests/Composer/Test/Plugin/PluginInstallerTest.php

This PR relates to https://github.com/composer/composer/pull/4089, which adds an unnecessary feature - converting a plugin's constraint from `1.0.0` to `^1.0`. That was a mistake on my part. I wrongly assumed that Composer has no support for multiple Plugin versions. Poor knowledge of the VersionParser class and some misinterpreted errors lead me to that conclusion.
The tests were kept, but changed accordingly. The exclusion of plugins which didn't match was kept. The text mentioning that a plugin was not registered was kept.
Thanks, @stof, for letting me know, albeit in a very obscure and then-hidden line comment. I saw it just now.

Revert the plugin versions converting from "1.0.0" to "^1.0" feature

---

doc/articles/troubleshooting.md

The [current implementation](https://github.com/composer/composer/blob/c471edc488f49f254c77ab97ecc14ea50bf3d2ab/bin/composer#L37) sets `1G`. Also, suggesting to set the `memory_limit` to `2G` would be more useful.

[docs] mention the `memory_limit` actually being set

---

src/Composer/Command/CreateProjectCommand.php

Realized feature in #2947. When press `Ctrl+C` in time processing `create-project` command target directory will be removed. Work on unix-like systems only.

Added Ctrl+C support to create-project command for unix-like systems

---

doc/04-schema.md
res/composer-schema.json
src/Composer/Command/ArchiveCommand.php
src/Composer/Config.php

Add some configuration values to be able to customize the archive command behaviour in `$COMPOSER_HOME/.composer/config.json`
Thus a content of 
```json
{
{
"type": "artifact",
"url": "/var/lib/composer/artifacts"
}
],
"config": {
"archive-format":"zip",
"archive-dir":"/var/lib/composer/artifacts",
}
}
```
would make  `composer archive` to build by default `zip` archives to be built into `/var/lib/composer/artifacts`
but `composer archive --dir=. --format=tar` would build archives locally in `tar` format

Add archive configuration

---

src/Composer/Command/CreateProjectCommand.php
src/Composer/DependencyResolver/Pool.php
src/Composer/DependencyResolver/Solver.php
src/Composer/Repository/ComposerRepository.php
tests/Composer/Test/Repository/ComposerRepositoryTest.php

This will significantly reduce the amount of loaded metadata for the solver. This should improve network time as well as solver complexity.

Load only explicitly named package data

---

src/Composer/Util/ConfigValidator.php

Since invalid names will prevent publishing to packagist, they should
be considered publish errors. If people do not plan on submitting their
package to packagist, they can use the --no-check-publish flag to turn
it into a normal warning again.

Make an invalid package name a publish error, not warning

---

src/Composer/Downloader/ArchiveDownloader.php
tests/Composer/Test/Downloader/ArchiveDownloaderTest.php

The issue mentioned on http://benramsey.com/blog/2015/06/composer-missing-distributions/ should be fixed by this PR.
BTW I removed the throw here because the parent::processUrl call already does that check.

download correct Bitbucket archive reference when using --prefer-dist

---

doc/02-libraries.md
doc/03-cli.md
doc/04-schema.md
doc/05-repositories.md
doc/06-config.md
doc/07-community.md
doc/articles/troubleshooting.md

Work in progress, feedback please.
I feel like it doesn't really make sense to put config **after** community. However, because of the numbering of the filenames and this actually being reflected in the urls generated, this PR might break some external links. Should I revert that change and move config to the last page (07)?

splitting up some docs, closes #4155

---

src/Composer/Package/Archiver/BaseExcludeFilter.php
tests/Composer/Test/Package/Archiver/ArchivableFilesFinderTest.php
tests/Composer/Test/Package/Archiver/GitExcludeFilterTest.php

Added test to reproduce #4183
Not sure on what the best way to fix it would be..
* Escape any delimiter characters used in the pattern?
* Use a different delimiter?
/cc @Seldaek @stof

Fix #4183 - exclude pattern containing delimiter used throws error

---

doc/01-basic-usage.md
src/Composer/Package/Version/VersionParser.php
tests/Composer/Test/Package/Version/VersionParserTest.php

On the 4080 ticket we concluded that the feature works correctly but could use documentation.
However, I also noticed that >=2.3.0 was inconsistent with the general rule "when stabilities aren't specified, treat all pre-releases the same way as you treat the stable release". So I've made a functional change as well.

>=2.3.0 now includes pre-releases, added docs for this and -stable suffix Fixes #4080.

---

src/Composer/DependencyResolver/RuleWatchNode.php

Fix: Add missing argument name to method-level docblock

---

src/Composer/Package/Archiver/ArchivableFilesFinder.php

Fix: Import Symfony\Component\Finder\Finder

---

doc/articles/handling-private-packages-with-satis.md

Updating docs to use `satis.json` instead of `config.json`

Changing config.json to satis.json

---

bin/update-spdx-licenses
res/spdx-exceptions.json
res/spdx-licenses.json
src/Composer/Util/SpdxLicense.php
src/Composer/Util/SpdxLicensesUpdater.php
tests/Composer/Test/Util/SpdxLicenseTest.php

Not sure if desired or not, but figured it was time for an update.

Updated SPDX related files in light of 2.0 release of SPDX specification

---

src/Composer/Util/RemoteFilesystem.php

The conditional a few lines above already checks for `bytesMax > 0`

Dropped obsolete condition

---

src/Composer/Command/CreateProjectCommand.php
src/Composer/Command/LicensesCommand.php
src/Composer/Command/ShowCommand.php
src/Composer/DependencyResolver/Operation/SolverOperation.php
src/Composer/Downloader/FileDownloader.php
src/Composer/Downloader/VcsDownloader.php
src/Composer/Package/BasePackage.php
src/Composer/Package/PackageInterface.php
src/Composer/Package/Version/VersionParser.php
tests/Composer/Test/Package/BasePackageTest.php
tests/Composer/Test/Package/Version/VersionParserTest.php

Working towards #3545.
formatVersion() does not belong in VersionParser since it depends upon a
Package object, and is creating a more complete pretty formatted
version, not parsing anything.
The new getFullPrettyVersion() method can be seen as an extension to
getPrettyVersion(), and is located in BasePackage as a result.
I'm also not very good at naming things, and `getFullPrettyVersion` was the best I could come up with. Better suggestions welcome :)

Move VersionParser::formatVersion() to BasePackage::getFullPrettyVersion()

---

doc/00-intro.md
doc/01-basic-usage.md
doc/02-libraries.md
doc/06-config.md
doc/articles/versions.md

(more) documentation changes

---

src/Composer/EventDispatcher/EventDispatcher.php
tests/Composer/Test/EventDispatcher/EventDispatcherTest.php

Follow up on #4120
Not sure if we should only show it in verbose mode, or show by default and hide in quiet mode. Feedback/thoughts?
/cc @Seldaek @theofidry

Output script command in verbose mode

---

src/Composer/Package/Version/VersionParser.php

Working towards #3545.
This adds VersionParser::$stabilities, which is an array of the
supported stability levels. This adds a little bit of duplication,
however we were already hardcoding the various stabilities in regular
expressions and functions like parseStability().

Don't use BasePackage::$stabilities in VersionParser

---

src/Composer/DependencyResolver/Pool.php
src/Composer/Installer.php

Useful to compare pool size changes to the new pool in https://github.com/composer/composer/pull/4163

Output the size of the pool after dependency resolution for users (verbose)

---

doc/03-cli.md

Fix: Update docs for require command

---

doc/03-cli.md

Fix: Streamline options in documentation

---

doc/03-cli.md

This PR
Related to #4219, where I spotted that it's not up to date.

Fix: Update docs for validate command

---

src/Composer/Package/Loader/ArrayLoader.php

Using a possessive quantifier avoids useless backtracking.

Optimize the regex detecting timestamps

---

src/Composer/Package/Version/VersionParser.php

This reduces array_merge calls on larger projects by thousands and saves a few hundred kilobytes through fewer more efficient memory allocations: So mostly a small time saver.
Packagist before/after:
```
[148.3MB/7.25s] Memory usage: 148.25MB (peak: 328.81MB), time: 7.25s
[148.2MB/7.01s] Memory usage: 148.24MB (peak: 328.72MB), time: 7.01s
```

VersionParser: remove a few hundred/thousand array_merge calls

---

src/Composer/DependencyResolver/Rule.php
tests/Composer/Test/DependencyResolver/RuleTest.php

The old hash calculation function goes back to a commit 40b3391 from 2012: `substr(md5(implode(',', $this->literals)), 0, 5)` - it uses only 20bit and inefficiently stores them in a 5 byte string. This PR changes this to a 4byte integer, and does not store the hash outside of the rule set.
Before/after comparisons for a few projects:
Composer:
```
[95.5MB/5.78s] Analyzed 15693 rules to resolve dependencies
[67.0MB/1.88s] Memory usage: 67.01MB (peak: 95.75MB), time: 1.88s
[95.5MB/1.67s] Analyzed 15693 rules to resolve dependencies
[67.0MB/1.90s] Memory usage: 67.05MB (peak: 94.3MB), time: 1.9s
```
Packagist:
```
[429.1MB/9.34s] Analyzed 144469 rules to resolve dependencies
[157.0MB/10.96s] Memory usage: 157MB (peak: 429.72MB), time: 10.96s
[417.4MB/13.39s] Analyzed 144469 rules to resolve …
```

Reduce rule hash size

---

doc/03-cli.md
src/Composer/Command/ValidateCommand.php

This PR
:information_desk_person: Useful if you want to break the build because someone modified `composer.json` without updating `composer.lock`.
Fiddle with `composer.json` in this repository, for example, change
```json
{
"autoload": {
"psr-0": { "Composer": "src/" }
}
}
```
to 
```json
{
"autoload": {
"psr-0": { "Composer": "src" }
}
}
```
```
$ ./bin/composer validate
./composer.json is valid
$ echo $?
0
```
```
$  ./bin/composer validate
./composer.json is valid
The lock file is not up to date with the latest changes in composer.json.
$ echo $?
1
```
```
$  ./bin/composer validate
./composer.json is valid
The lock file is not up to date with the latest changes in composer.json.
$ echo $?
0
```

Enhancement: Also validate if lock file is up to date

---

src/Composer/DependencyResolver/Problem.php
src/Composer/DependencyResolver/Rule.php
src/Composer/DependencyResolver/RuleSet.php
src/Composer/DependencyResolver/Solver.php
tests/Composer/Test/DependencyResolver/RuleTest.php

Storing the Rule data in a bitfield and getting rid of their id values saves up to 10% of memory.
This PR includes the commits from the rule hash changes in https://github.com/composer/composer/pull/4234
Comparison before/after: 
- Composer:
```
[96.2MB/1.63s] Analyzed 15693 rules to resolve dependencies
[67.7MB/1.80s] Memory usage: 67.7MB (peak: 96.48MB), time: 1.8s
[90.9MB/1.72s] Analyzed 15693 rules to resolve dependencies
[67.1MB/1.87s] Memory usage: 67.09MB (peak: 91.17MB), time: 1.87s
```
- Packagist:
```
[429.2MB/9.40s] Analyzed 144469 rules to resolve dependencies
[157.1MB/9.97s] Memory usage: 157.1MB (peak: 429.89MB), time: 9.97s
[386.0MB/10.05s] Analyzed 144469 rules to resolve dependencies
[157.1MB/10.52s] Memory usage: 157.09MB (peak: 386.64MB), time: 10.52s
```
- Symfony …

Reduce memory usage of Rule objects

---

src/Composer/Package/LinkConstraint/VersionConstraint.php

We construct a huge amount of VersionConstraint objects, storing the operator as an int can make a difference of multiple MB of memory usage. The comparison of version constraints is very fast, while the memory used for the static function cache can use a significant amount of the peak, so it makes no sense to cache these values. Accessing that much memory may be slower than the actual computation.
Sample projects with composer cache filled `update -v --dry-run --profile` (line 1 before, line 2 after):
Composer:
```
[67.0MB/2.71s] Memory usage: 67.03MB (peak: 95.82MB), time: 2.71s
[65.6MB/1.81s] Memory usage: 65.6MB (peak: 94.33MB), time: 1.81s
```
Packagist:
```
[157.0MB/10.02s] Memory usage: 156.99MB (peak: 429.76MB), time: 10.02s
[150.2MB/10.26s] Memory usage: 150.24MB (peak: …
```

Remove unnecessary version comparison cache variable and store operator as int

---

tests/Composer/Test/Util/RemoteFilesystemTest.php

This test requires internet connectivity.
I notice other test are set as "slow" (the pear ones).
Perhaps a group "online" will be better.
This will allow to run test suite from computer without network.
Reproducer:
echo "# nothing" > /etc/resolv.conf
phpunit -v
1) Composer\Test\Util\RemoteFilesystemTest::testCaptureAuthenticationParamsFromUrl
Failed asserting that 0 matches expected 404.

Set this test as slow

---

src/Composer/Autoload/ClassLoader.php
tests/Composer/Test/Autoload/ClassLoaderTest.php
tests/Composer/Test/Autoload/Fixtures/DirDotPhp/Dir.php
tests/Composer/Test/Autoload/Fixtures/DirDotPhp/psr4/Dir.php/File.php

This reverts commit bdb6ecb29e9624fb767aa690d09c780249050fc6, reversing
changes made to 8a12e50a16dbc4ddf808b752ad64b412dba272d5.
While working on the [perf of the DebugClassLoader](https://github.com/symfony/symfony/pull/15443), I noticed the change.
`is_file()` makes a stat syscall, which makes it MUCH slower that `file_exists`. Given that the autoloader is already one of the most perf hungry component of the PHP stack, this slows down everyone for almost no reason (but a very rare edge case that does not deserve it).

Revert "Merge pull request #3975 from marc-mabe/hotfix/3974"

---

src/Composer/Command/ConfigCommand.php

I chose to make the env variable override the parameter, which seems logical ?

Fixes #4302 allow COMPOSER env with config statements (if --file not used)

---

doc/articles/scripts.md

Add a line and example to the documentation covering the need to require the autoloader file in order to use autoloaded files.
Addresses #4184

Mention need to require autoloader in hooks using functions

---

src/Composer/Autoload/AutoloadGenerator.php

copy LICENSE file during autoload dumping ( refs #4288 )

---

src/Composer/Cache.php

Warn if cache directory cannot be created, refs #1161

---

.travis.yml

``apt_packages`` was the syntax for the initial beta previews of the feature.

Update the config of the apt addon to the new syntax

---

doc/articles/troubleshooting.md

occurred for my when I wanted to update a meta package, where nearly **ALL** dependencies changed their version.

add another case when package is not found

---

composer.json
composer.lock
src/Composer/Downloader/PathDownloader.php
src/Composer/Factory.php
src/Composer/Package/Loader/RootPackageLoader.php
src/Composer/Package/Version/VersionGuesser.php
src/Composer/Repository/PathRepository.php
src/Composer/Util/Filesystem.php
tests/Composer/Test/Package/Loader/RootPackageLoaderTest.php
tests/Composer/Test/Package/Version/VersionGuesserTest.php
tests/Composer/Test/Repository/Fixtures/path/with-version/composer.json
tests/Composer/Test/Repository/Fixtures/path/without-version/composer.json
tests/Composer/Test/Repository/PathRepositoryTest.php

This PR aims to replace #3904 because it's getting slow.
In addition, I've extracted everything related to version guessing from `RootPackageLoader` to a version `VersionGuesser` class. This class is used in the `PathRepository` to guess the version of the target dependency.
If the symlink fail, then we use the mirror method of Symfony Filesystem component.

Add a path repository and downloader

---

src/Composer/Factory.php
src/Composer/Package/Locker.php
tests/Composer/Test/InstallerTest.php
tests/Composer/Test/Package/LockerTest.php

Changing the formatting of the composer.json (ie. if there is a convention of vertically aligning the versions of the dependencies), the hash in the lock file will not match that of the JSON file. Instead if we use the hash of the parsed content, this is not going to be an issue.
This change adds a content-hash key to the lock file with the hash, which is the MD5 of the parsed and sorted content (decode to an associative array, sort it then re-encode and hash). 
This change should be backwards compatible.
Example use case. Given this composer.json:
```javascript
{
"name": "composer/composer",
// SNIP
"require": {
"php":                       ">=5.3.2",
"justinrainbow/json-schema": "~1.4",
"seld/jsonlint":             "~1.0",
"symfony/console":           "~2.5",
"symfony/finder": …
```

Add the hash of the parsed content of the composer.json to the lock file, and use it to verify the json is not changed

---

doc/05-repositories.md

This is a simple documentation about the `path` repository.

Add documentation about the `path` repository

---

src/Composer/Downloader/PathDownloader.php
src/Composer/Repository/PathRepository.php

This PR introduce two BC changes:

Path repository store relative path

---

src/Composer/Downloader/PathDownloader.php

Depending on the user configuration, the symlinked path may not be the good one, using `realpath` fixes the problem.

Uses `realpath` to fix relative path issues

---

src/Composer/Downloader/PathDownloader.php

When dealing with environment using VMs or Docker containers, the same filesystem will be shared between different environments and absolute paths won't work anymore.
This PR uses the `findShortestPath` method to find the shortest relative path to create the symlink. That will allow to have valid symlinks on all the different systems that share the project file system.

Use shortest relative paths for symlinks with `path` repository

---

src/Composer/Config.php

Just a minor fix in the flag check as "1" is the hardcoded value of RELATIVE_PATHS. Alternative the check could be ``$flags & self::RELATIVE_PATHS > 0``

Fix check for flag in case RELATIVE_PATHS should be changed somehow

---

src/Composer/Installer.php
tests/Composer/Test/Fixtures/installer/update-picks-up-change-of-vcs-type.test

In #3985, the source URL for all repos is updated during the `update` task. However, the change did not include take the source type and reference.
So, when moving a repo from `hg` to `git`, only the new git URL was written to the .lock file but the repository type and commit ID were not updated.

Update source type and reference along with URLs

---

src/Composer/Repository/ArtifactRepository.php

Follow symlinks when searching for artifacts.
When working locally, we have a maven project that creates an artifact containing a generated api client library. Obviously we could set the artifact directory directly to the other project like this:
```json
{"type": "artifact", "url": "../my-other-project/target"}
```
However, doing this means if we don't have my-other-project cloned down under the same relative path, in other environments, then doing a composer update will blow up because the directory doesn't exist...even though we may not be trying to get an artifact from that directory (ie we might be trying to pull it from the production released artifacts...which are in satis).
I see 2 ways to resolve this:
1. Silently (or print a warning) ignore artifact directories that don't exist …

Follow symlinks when searching for artifacts

---

doc/articles/scripts.md

The fix here being more "occurs before a package has been uninstalled", which is incorrect.

fix typo + better express order of events

---

doc/05-repositories.md
src/Composer/Repository/PathRepository.php
tests/Composer/Test/Repository/Fixtures/path/with-version/composer.json
tests/Composer/Test/Repository/Fixtures/path/without-version/composer.json
tests/Composer/Test/Repository/PathRepositoryTest.php

I extended the path repositories feature to use glob to resolve wildcards. It would be nice if you consider it for inclusion.

Enable wildcards in path names for path repositories

---

src/Composer/Command/ArchiveCommand.php

Using archive command for package your project would be useful to know the path of created file, because of there are a lot of factors that affects to the file name (package name, version property, COMPOSER_ROOT_VERSION environment variable, branch alias configuration, etc.).
I propose this PR to improve this thing.

Archive command shows created package path

---

src/Composer/Installer/LibraryInstaller.php

Line 130 has similar logic so avoided doing the check withiin `isDirEmpty()`
This prevents an InvalidArgumentException from the Symfony component when the directory doesn't exist
Relates to this https://github.com/composer/composer/commit/80f1e4372a10427aaf06d5cda87a9bf74db200ab

Ensure the bin directory exists before checking empty

---

src/Composer/Command/ConfigCommand.php

Fixes #4459
Not sure why this if/else construct was in there. The code is not documented nor is it very self-explaining. Removing these lines seems to fix the issue. It still displays any other info correctly. However, since I don't know what it was for in the first place, I can't specifically test it.
With a `auth.json` file as follows:
```javascript
{
"http-basic": {
"a.b.c": {
"username": "username",
"password": "password"
},
"d.e.f": {
"username": "username",
"password": "password"
}
}
}
```
Before:
```
[repositories.packagist.type] composer
[repositories.packagist.url] https?://packagist.org
[repositories.packagist.allow_ssl_downgrade] true
[process-timeout] 300
[use-include-path] false
[preferred-install] auto
[notify-on-install] true
[github-protocols] [git, https, ssh] …
```

config -l output breaks on listing keys with several colons [fixes #4459]

---

doc/06-config.md
src/Composer/Command/ConfigCommand.php

Those 2 parameters could be defined inside the config.json but were not accepted by the command 'composer config'.
So, just adding them to the known uniqueConfigValues
The doc on archive-dir is also improved with an example of configuration;

Enable command line configuration for archive-dir and archive-format

---

composer.json

Test suite pass with PHPUnit >= 5.0.5
(fails with < 5.0.5, see https://github.com/sebastianbergmann/phpunit-mock-objects/pull/262).
Of course, 4.x will still be used with php < 5.6  (in fact no, because of composer.lock, 4.8.6 used everywhere)

allow to use PHPUnit 5

---

src/Composer/Command/ConfigCommand.php

Now allows 'prefer-stable' and 'minimum-stability' to be set via composer config command

Issue #2384 allow 'prefer-stable' and 'minimum-stability' to be set 

---

src/Composer/Command/CreateProjectCommand.php
src/Composer/Installer.php
src/Composer/Installer/InstallationManager.php

Notify installs should use repository auth info if it's set, otherwise request will be denied (unauthorized).
I'm not sure this is the most elegant way of doing it as I haven't checked much of composer internals. I'd be more than happy to rework it if there are any suggestions.
Thanks!

InstallationManager: notifyInstalls: append authorization header

---

src/Composer/Installer/LibraryInstaller.php

Based on Composer's proxy: https://github.com/composer/windows-setup/blob/master/src/shims/composer
Previous `generateUnixyProxyCode()`'s version was generating unixy-proxy file which was causing problems:
```
$ phpunit
Could not open input file: /cygdrive/c/Users/<user>/AppData/Roaming/Composer/vendor/phpunit/phpunit/phpunit
```

generateUnixyProxyCode() properly supporting Cygwin & Git Bash

---

src/Composer/Package/AliasPackage.php
src/Composer/Package/RootAliasPackage.php
src/Composer/Package/RootPackageInterface.php
tests/Composer/Test/Package/RootAliasPackageTest.php

While implementing https://github.com/wikimedia/composer-merge-plugin/commit/f706e5ce863ee7f3cf61f165e120d547c64b1a78 I discovered that there was no way to modify the "conflict", "provide" and "replace" collections of a RootAliasPackage after construction. Since the "require" and "require-dev" collections already have support for post-construction changes I decided to propose this patch in the hope that the lack of setters for other cached collections was just a matter of them not having been needed before.
I also boldly added a commit to the pull request that extends RootPackageInterface and RootAliasPackage to expose methods of RootPackage that [composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin) uses internally. The Package interfaces generally stick to getters …

Allow easier manipulation of RootAliasPackage

---

src/Composer/Downloader/VcsDownloader.php

Q | A
------------ | -------------
Bug fix? | yes
New feature? | no
BC breaks? | no
Deprecations? | no
Tests pass? | yes
Fixed tickets | #4558 
See https://github.com/symfony/symfony/pull/4832 for the PR where the escaping is described.

Escape angle brackets for commit message output

---

tests/Composer/Test/Json/JsonFileTest.php

Upstream issue is fixed in 1.3.9.

skip no more needed with jsonc 1.3.9

---

src/Composer/Util/Filesystem.php

During a `composer install` on Windows, I had warning that xcopy was timing out. It ended up being because a file already existed in the target directory (non-composer issue, was a permissions issue on my end) and `xcopy` was waiting for a response to:
```
Overwrite [filename] (Yes/No/All)?
```
Adding the `/Y` switch will have `xcopy` overwrite without prompting, just to avoid this particular timeout error.

Have xcopy overwrite existing files

---

src/Composer/Autoload/AutoloadGenerator.php

Fixes #4562
Instead of failing on a `RuntimeException`, we can just skip the bad definition and proceed with the operation. I don't advocate this kind of configuration as it indicates an underlying problem in my opinion, but we can at least "fail" gracefully.
```
rob@macbookpro /tmp $ cat composer.json
{
"require": { "alcohol/iso3166": "@stable" },
"autoload": { "classmap": [ "yolo.php" ] },
"scripts": {
"pre-install-cmd": "touch yolo.php"
}
}
rob@macbookpro /tmp $ /srv/git/github/composer/bin/composer install
Could not scan for classes inside "yolo.php" which does not appear to be a file nor a folder
> touch yolo.php
Installing dependencies (including require-dev)
- Installing alcohol/iso3166 (3.0.0)
Loading from cache
Writing lock …
```

fixes #4562

---

src/Composer/Util/RemoteFilesystem.php

Before 400 errors were silently dropped. This caused composer to store
the returned body (usually some html) in cache. This resulted in later
errors when composer tried to extract this error response as zip.
With this exceptions thrown it handles the error gracefully and falls
back to the next URL provided by the package configuration.

Fix handling of http 400 errors

---

src/Composer/Repository/PathRepository.php

If there is no git folder, no reference is generated for the package, then subsequent update will never happen as for composer this will be the same version / reference as previous so it will be skipped.
In this case when the composer.json of the package is modified it is reinstalled.

Issue #4512 Set reference in path repository

---

doc/articles/scripts.md
src/Composer/EventDispatcher/EventDispatcher.php
tests/Composer/Test/EventDispatcher/EventDispatcherTest.php

Since I got positive feedback in Issue #4578 here's a first implementation of scripts "group".
Script prefixed by `@` are now considered alias of other script group. I've also implemented an infinite recursion detection (in a separate commit), to avoid simple configuration errors.
I'm not aware of all composer internals, so this code will need an expert review. Here's my consideration:
* prefixing by `@` can cause BC? I can't think of any real situation...
* all command (including `post-install-cmd` and the like) are callable. Is this correct?
* is the minimal documentation I've added enough?
I've made some phpunit tests, and manually tested the following configurations:
```yml
{
"scripts": {
"root": "@group2",
"group2": [
"@group1",
"echo 2",
"@group3"
],
"group1": [
"echo 1"
], …
```

Allow composer script call within other script group

---

doc/articles/troubleshooting.md

Most of the "out of memory" errors that users encounter may come from XDebug being loaded/enabled.

Add "out of memory" tip

---

src/Composer/Console/Application.php

As discussed in https://github.com/composer/composer/pull/4554#issuecomment-157028649 this adds a link to `getcomposer.org` troubleshooting section in case a out-of-memory error occurs.

added a troubleshooting link in case of out-of-memory errors

---

doc/articles/troubleshooting.md
src/Composer/Console/Application.php

As discussed in https://github.com/composer/composer/pull/4554#issuecomment-157357335
this adds a warning when xdebug is loaded, while composer cli commands run.

add a warning when xdebug is loaded while running composer commands

---

src/Composer/Autoload/AutoloadGenerator.php
src/Composer/Command/DumpAutoloadCommand.php
tests/Composer/Test/Autoload/AutoloadGeneratorTest.php

Script is executed, if post-autoload-dump specified and ````composer install --no-scripts```` is executed.
````
"scripts": {
"post-autoload-dump": "echo 1"
},
````
This PR do not execute scripts.

Add --no-scripts argument for dump-autoload command

---

src/Composer/Autoload/AutoloadGenerator.php
tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
tests/Composer/Test/Autoload/Fixtures/autoload_files.php
tests/Composer/Test/Autoload/Fixtures/autoload_files2.php
tests/Composer/Test/Autoload/Fixtures/autoload_files_functions.php
tests/Composer/Test/Autoload/Fixtures/autoload_files_target_dir.php
tests/Composer/Test/Autoload/Fixtures/autoload_real_files_by_dependency.php
tests/Composer/Test/Autoload/Fixtures/autoload_real_functions.php
tests/Composer/Test/Autoload/Fixtures/autoload_real_include_path.php
tests/Composer/Test/Autoload/Fixtures/autoload_real_target_dir.php

This would address #3003 by assigning an identifier to each included file during `AutoloadGenerator::dump`. Currently, this identifier is the value returned by `md5_file` (to address the concern raised in https://github.com/guzzle/guzzle/issues/676#issuecomment-43651280), but it could also be a logical file address such as `$packageName::$relativePath`, e.g. `guzzlehttp/guzzle::src/functions.php`. 
This is preferable to simple changing `require` to `require_once` because it prevents two copies of the same file from being loaded, as would happen if a globally installed package loads project's autoloader and both rely on the same package. A known example of this is using a globally installed copy of CodeCeption on a project requiring Guzzle.
Would also address: …

Explicitly check if a file has already been required before requiring it

---

doc/04-schema.md

Describe that package links can reference specific PHP versions and/ord PHP extensions.

Doc schema package links php extensions

---

src/Composer/Installer.php

Bypass `runScripts` parameter to autoload dumper in `Installer:run()`

---

src/Composer/Repository/ArtifactRepository.php
src/Composer/Repository/ComposerRepository.php
src/Composer/Repository/ConfigurableRepositoryInterface.php
src/Composer/Repository/PathRepository.php
src/Composer/Repository/PearRepository.php
src/Composer/Repository/VcsRepository.php

This PR attempts to solve an issue described here - https://github.com/composer/satis/pull/266#discussion_r45597333 by providing a new interface for all repository classes that use `$repoConfig` to implement. Which affects:
- `VcsRepository`
- `PearRepository`
- `ComposerRepository`
- `ArtifactRepository`
- `PathRepository`

Allows repositories to implement ConfigurableRepositoryInterface

---

doc/03-cli.md
src/Composer/Command/ShowCommand.php

I've added a new option for the `show` command.
```bash
$ composer show -t
```
will display something like:
```
justinrainbow/json-schema    1.1.0
└── php >= 5.3.0.0
phpunit/php-code-coverage    1.2.13 Library that provides collection, processing, and rendering functionality for PHP code coverage information.
├── php >= 5.3.3.0
├── phpunit/php-file-iterator >= 1.3.0.0
├── phpunit/php-text-template >= 1.1.1.0
└── phpunit/php-token-stream >= 1.1.3.0
phpunit/php-file-iterator    1.3.4  FilterIterator implementation that filters files based on a list of suffixes.
└── php >= 5.3.3.0
phpunit/php-text-template    1.1.4  Simple template engine.
└── php >= 5.3.3.0
phpunit/php-timer            1.0.5  Utility class for timing
└── php >= 5.3.3.0
phpunit/php-token-stream     1.2.1  Wrapper around …
```

Added a tree view of required packages

---

src/Composer/Repository/Vcs/GitLabDriver.php
tests/Composer/Test/Repository/Vcs/GitLabDriverTest.php

Since gitlab can be hosted on any url also subdirectories should be
supported. (e.g https://mycompany.com/gitlab).
This supports only http and https protocols since the gitlab api url
is derived from the package repository url. And the ssh protocol doesn't
support folders this way.

Adds support for gitlab installed in subfolder

---

tests/Composer/Test/Repository/Vcs/GitLabDriverTest.php

it looks like php 5.3.3 might not have openssl extension?

fix a 5.3.3 unit test

---

res/composer-schema.json
src/Composer/Command/ConfigCommand.php
src/Composer/Config.php
src/Composer/Config/JsonConfigSource.php

First apologies are in order for not testing the previous pull #4659.
I have scanned configuration code for github occurences and added gitlab where it was necessary.
Since this is "copy paste" kind of pull please check diffs for typos I have checked it but might be suffering from authors blindness. :smiley:
This one I have tested and works ie.: it is now possible to do `composer configure -g gitlab-oauth.<domain> <token>`.

Configuration of gitlab-oauth via CLI followup

---

src/Composer/Autoload/ClassLoader.php

str_replace is faster than strtr for this use-case. See symfony/symfony#15614
And we can even skip the str_replace on Windows completely.

[ClassLoader] performance improvement: use str_replace instead of strtr

---

src/Composer/DependencyResolver/Rule.php

When seeing the error message, I though "config.platform.php" was some file/value configured for platform.sh instead of a setting value in composer.json. I propose to make it a bit more clear that this value is set in composer.json

Improve error message about platform php version

---

doc/06-config.md
src/Composer/Command/ConfigCommand.php
src/Composer/Command/RequireCommand.php
src/Composer/Config.php

#4715 Added sort-packages into config

Added sort-packages into config

---

doc/03-cli.md
src/Composer/Command/DependsCommand.php

Closes #4657.
Output sample:
```bash
$ composer depends --with-replaces symfony/symfony
a2lix/translation-form-bundle requires symfony/symfony (>=2.3)
behat/behat requires (dev) symfony/process (~2.1)
behat/behat requires symfony/class-loader (~2.1)
behat/behat requires symfony/config (~2.3)
behat/behat requires symfony/console (~2.1)
behat/behat requires symfony/dependency-injection (~2.1)
behat/behat requires symfony/event-dispatcher (~2.1)
behat/behat requires symfony/translation (~2.3)
behat/behat requires symfony/yaml (~2.1)
behat/gherkin requires (dev) symfony/yaml (~2.1)
behat/mink-browserkit-driver requires symfony/browser-kit (~2.3)
behat/mink-browserkit-driver requires symfony/dom-crawler (~2.3)
behat/mink-extension requires symfony/config (~2.2)
behat/mink requires …
```

Add --with-replaces option on depends command

---

src/Composer/Autoload/AutoloadGenerator.php

When classMapAuthoritative is enabled autoload_real, will still look at and load the PSR0, PSR4, and include paths.  This is not necessary as in ClassLoader::findFile() if it's not in the classMap and we're authority, it will return false.  Only when classmap is not authority will it call findFileWithExtension, which goes and looks at PSR4/0 and IncludePaths.

Stop fileloads on classMapAuthoritative 

---

src/Composer/Plugin/PluginManager.php

This reverts commit 21f5933e0170b9673108f05df262dbc7f98cce69.
Commit 21f5933e breaks fresh installations of cakephp applications, or
any project where a dependency uses a different composer plugin
installer than the upstream project.
Closes auraphp/Aura.Intl#20

Revert "Avoid loading plugins that do not match the current plugin api even during installation"

---

src/Composer/Plugin/Capability/Capability.php
src/Composer/Plugin/Capable.php
src/Composer/Plugin/PluginInterface.php
src/Composer/Plugin/PluginManager.php
tests/Composer/Test/Plugin/Fixtures/plugin-v1/composer.json
tests/Composer/Test/Plugin/Fixtures/plugin-v2/composer.json
tests/Composer/Test/Plugin/Fixtures/plugin-v3/composer.json
tests/Composer/Test/Plugin/Fixtures/plugin-v4/composer.json
tests/Composer/Test/Plugin/Mock/Capability.php
tests/Composer/Test/Plugin/Mock/CapablePluginInterface.php
tests/Composer/Test/Plugin/PluginInstallerTest.php

Plugins can now present their capabilities to the PluginManager, through which it can act accordingly, thus making Plugin API more flexible, BC-friendly and decoupled.
**The Plugin API was bumped to version `1.1.0`.** :boom: 
**a) Plugin API evolution**
Every time Composer decides that a new extension should be added, it will extend its Plugin API to support that extension point - through an interface, an abstract class or a concrete one.  
Some example of extension points would be: allowing users to add their own Composer commands, allowing users to add their own validation steps in the `validate` command, offloading certain operations to userland implementations, otherwise falling back to default etc.
Because the PluginManager and the plugins communicate via strings and arrays, the …

Added Capable plugins for a more future-proof Plugin API

---

src/Composer/Util/RemoteFilesystem.php
src/Composer/Util/TlsHelper.php
tests/Composer/Test/Util/TlsHelperTest.php

This is an experimental (read crazy) PR to provide support for certificates using the [subjectAltName](https://en.wikipedia.org/wiki/SubjectAltName) (sAN) extension when Composer is being run on PHP < 5.6.
When running PHP < 5.6 and a CN error is thrown the following steps kick in:
1. Open socket to remote server and fetch certificate (disabling peer validation because PHP errors without giving up the certificate.)
2. Verifying the domain in the URL against the names in the sAN field. If there is a match record the authority [host/port], certificate common name, and certificate fingerprint.
3. Retry the original request but changing the CN_match parameter to the common name extracted from the certificate in step 2.
4. To prevent any attempt at being hoodwinked by switching the certificate …

Provide support for subjectAltName on PHP < 5.6

---

doc/03-cli.md
src/Composer/Command/ConfigCommand.php
tests/Composer/Test/Config/Fixtures/config/config-with-exampletld-repository-and-options.json
tests/Composer/Test/Config/JsonConfigSourceTest.php

It could help to allow an extra argument to the config command for repos, in my case it's to automate the creation of a satis repo, what do you think?
Related to #2920, also another alternative to #2604.

[Config command] allow to pass options when adding a repo

---

src/Composer/DependencyResolver/SolverProblemsException.php

Implements feature described in #2756 (no opinions there, so I chose 4th option - one information at the end).

Composer gives .ini hints about missing extensions

---

src/Composer/Repository/PathRepository.php
tests/Composer/Test/Repository/PathRepositoryTest.php

For predictable cross-platform behaviour, specifically on Windows with its backslashes. Fixes #4726

Globbing while resolving path repositories now normalizes to slashes

---

tests/Composer/Test/AllFunctionalTest.php
tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
tests/Composer/Test/Autoload/ClassMapGeneratorTest.php
tests/Composer/Test/CacheTest.php
tests/Composer/Test/Config/JsonConfigSourceTest.php
tests/Composer/Test/Downloader/FileDownloaderTest.php
tests/Composer/Test/Downloader/GitDownloaderTest.php
tests/Composer/Test/Downloader/HgDownloaderTest.php
tests/Composer/Test/Downloader/PearPackageExtractorTest.php
tests/Composer/Test/Downloader/PerforceDownloaderTest.php
tests/Composer/Test/Downloader/XzDownloaderTest.php
tests/Composer/Test/Downloader/ZipDownloaderTest.php
tests/Composer/Test/Installer/LibraryInstallerTest.php
tests/Composer/Test/Package/Archiver/ArchivableFilesFinderTest.php
tests/Composer/Test/Package/Archiver/ArchiverTest.php
tests/Composer/Test/Package/Archiver/PharArchiverTest.php
tests/Composer/Test/Plugin/PluginInstallerTest.php
tests/Composer/Test/Repository/FilesystemRepositoryTest.php
tests/Composer/Test/Repository/Vcs/GitHubDriverTest.php
tests/Composer/Test/Repository/Vcs/GitLabDriverTest.php
tests/Composer/Test/Repository/Vcs/PerforceDriverTest.php
tests/Composer/Test/Repository/Vcs/SvnDriverTest.php
tests/Composer/Test/Repository/VcsRepositoryTest.php
tests/Composer/Test/Util/FilesystemTest.php
tests/Composer/TestCase.php

Any tests that use the filesystem should have their own unique directory, as we run our test suite in parallel and cleanup of tests (removing directories) should not interfere with currently running tests.
Right now, this PR breaks testing locally on OSX due to the incredibly convoluted way the temporary directory is setup there. Need to find out why it breaks so many of our tests, cause I need to be able to run the test suite locally (have a hunch that it might be related to not enough use of `realpath()`).

try to use unique test directories

---

src/Composer/Config.php

Priority of "==" operation is higher then priority of "&" operation.
Possible defect was found by AppChecker static analyzer (http://cnpo.ru/en/solutions/appchecker.php).

fix: missing parentheses

---

src/Composer/IO/BaseIO.php
src/Composer/Util/RemoteFilesystem.php

When an environmental variable named "COMPOSER_AUTH" is set
as $USERNAME:$PASSWORD, it is automatically used for authentication
e.g. when fetching packages from Satis.
The envvar credentials are of lower priority than URL credentials.
Fixes #4285

Allow fetching auth credentials from an envvar

---

doc/05-repositories.md

A valid version specifier is required in the `composer.json` file of the package as it cannot be gleaned otherwise (as with a VCS repository). This was not immediately apparent to me.

Clarify "path" repository type version requirement

---

doc/00-intro.md
doc/03-cli.md

cf. #4866, otherwise it causes issues since the latest security improvements and changes about XDG support.

[doc] add -H flag to sudo commands

---

src/Composer/Repository/PlatformRepository.php

OpenSSL 0.9.8 reached a crazy `zh` patch level but Composer didn't handle this, previously it would have been detected as `0.9.8.26` now it is detected as `0.9.8.34`.
Also changed the package description to use `OPENSSL_VERSION_TEXT` so the original version number is available.

Handle OpenSSL's many patch releases

---

src/Composer/Autoload/ClassMapGenerator.php
tests/Composer/Test/Autoload/ClassMapGeneratorTest.php

As indicated by #4885 the handling was incorrect for PHP files with invalid content.
The `Silencer` call was removed and replaced by `@` as this issue causes an `E_COMPILE_WARNING` level warning which cannot be silenced and actually points at the wrong location.

Ensure exception is thrown when classmaps are requested for corrupted files

---

src/Composer/Command/ConfigCommand.php

On Linux systems that support [alternatives](http://linux.about.com/library/cmd/blcmdl8_alternatives.htm), which would be pretty much all of them, the `editor` symlink refers to the preferred editor by the current user, so if it exists it should be preferred over all other editors.
Wouldn't want to start an [editor war](https://en.wikipedia.org/wiki/Editor_war) ;)

Prefer 'editor' on a system that supports alternatives

---

src/Composer/Repository/PathRepository.php

An empty repository should be just that - empty. #4903

Ignore empty path repositories

---

src/Composer/Command/ValidateCommand.php

This allows plugins to run additional validations.

Trigger event in validate command

---

src/Composer/Repository/ComposerRepository.php

I believe `getProviderNames()` always returns an array of unique names, in which case the iteration of these names can break as soon as the first match is found, because, by definition, it would be impossible to get another match.
I am not familiar with the BC format of `providers-includes`, so I can't say with certainty that after applying `substr($provider, 2, -5)` on each item in the provider listing this would yield a completely unique set, but I'm guessing that it would. In that case, breaking early would offer a slight performance improvement. :)

Break early when a provider name is matched

---

src/Composer/Cache.php

Permission issues in `touch` throw an E_WARNING error. Worst consequence I can see of ignoring it is extra cache misses from early GC, which is better than current 'immediate death', so wrapped it with Silencer.
Should fix #4070

Wrap final attempt to touch a cache file in Silencer.

---

doc/03-cli.md
src/Composer/Command/RunScriptCommand.php

Add a --timeout parameter to run-script to override default timeout

---

src/Composer/Downloader/VcsDownloader.php
tests/Composer/Test/Downloader/GitDownloaderTest.php

Fixed (and added a test for) a regression introduced in a77e2fb, which causes package Git package updates to fail when the package has two or more URLs and the last URL is the only one that actually works.
Currently, this causes a RuntimeException to be thrown, even if, when trying the last URL, the update was successful.
Also, please look closely at the test. It passes, but as I am not familiar enough with which git commands composer *should* be executing, I'd like a second pair of eyeballs on it.

Regression when Git package has two or more URLs and only the last one works.

---

src/Composer/Config/JsonConfigSource.php

Without this change if user runs, i.e.: `composer update` but global Composer was installed by other user, he can't store new token for Github authorization due too fact that he can't access this config file, which leads to "infinity loop" with generating new tokens.

Be sure that configuration file can be manipulated by actual user

---

src/Composer/Repository/RepositoryManager.php
tests/Composer/Test/Repository/RepositoryManagerTest.php

This method is useful for dynamically adding repositories with higher priority than Packagist, e.g. from a Composer plugin.
Use case:
This would allow me to finally finish the new version of my [Studio plugin](https://github.com/franzliedke/studio) for Composer. It essentially allows installing project dependencies from a local path repository, without editing the composer.json file (as that is checked into Git, and only project maintainers may want such a setup). We have found this to be very useful over at Flarum: In our working copy, the flarum/flarum project requires the flarum/core project as well as several bundled extensions (all installed with Composer), and developing them from within the vendor folder is no fun. Thus, this solution was born.
@alcohol You may remember me asking …

RepositoryManager::prependRepository()

---

src/Composer/Installer/LibraryInstaller.php

Without the quotes cygpath will interpret the filename (containing spaces) as two or more different files. This results in the value of $dir being incorrect, which in turn causes the command to fail.

Fix for the unix bin proxy on cygwin if the directory contains spaces

---

doc/05-repositories.md
src/Composer/Downloader/PathDownloader.php
src/Composer/Repository/PathRepository.php

This pull request implements the ability to force PathDownloader to use copy instead of symlink, refs:  #4636
New config option:
```json
{
{
"type": "path",
"url": "../../packages/my-package",
"options": {
"symlink": false
}
}
]
}
```

Introduce option to force copy instead of symlinking in PathDownloader

---

src/Composer/Command/ExecCommand.php
src/Composer/Console/Application.php

This PR adds initial support for a `composer exec <script>` command. Passing in no arguments, or `--list|l` will show you the available scripts.
It allows you to pass additional arguments to the script by separating them with a `--`:
```sh
$ composer exec phpunit -- --filter ClassLoaderTest
```
**However**, if you try to pass in an argument that exists in composer (e.g. `--help` or `-V`) then it simply calls that — this is obviously sub-optimal. Preferably, anything after the `<script>` should be available as a string or an array of strings in the script, but I don't know how to make that happen.

Add `composer exec` command

---

src/Composer/Command/DiagnoseCommand.php

Version can be updated using "self-update" which is only available in phar mode
Pubkeys can be updated using "self-update --update-keys" which is also only available in phar mode
if ('phar:' === substr(__FILE__, 0, 5)) {
$commands[] = new Command\SelfUpdateCommand();
}
So, this simple patch skip those diag when not in phar mode.

skip diag. which are only for phar mode

---

doc/03-cli.md
src/Composer/Command/SuggestsCommand.php

I rewrote the `SuggestsCommand.php` as it had multiple flaws:
- Default output wasn't sorted by anything visible, making it nearly unusable in projects of any size
- It did not take `provide` and `replace` sections into account, so for example in a Symfony project it would keep suggesting `symfony/console` even though that's provided by `symfony/symfony` through a `replace`.
- There were some potential exponential performance issues because of nested loops on the list of installed packages - new implementation should be a ton faster on large projects
New version introduces 2 new flags:
--by-package               Groups output by suggesting package
--by-suggestion            Groups output by suggested package
These show a grouped minitree of the suggested packages, grouped both ways. …

Rewrote SuggestsCommand

---

src/Composer/Command/StatusCommand.php
src/Composer/Downloader/DvcsDownloaderInterface.php
src/Composer/Downloader/GitDownloader.php
tests/Composer/Test/Downloader/GitDownloaderTest.php

This is a cleaned up, rebased, resurrection of #2085

Improve status for unpushed branches

---

src/Composer/Downloader/PathDownloader.php
src/Composer/Util/Filesystem.php

See #4955, added both extra detection reliability and lessened chances of unknown errors causing unwanted recursive deletions.

Improve handling of removing junctions in Windows path repositories

---

src/Composer/Autoload/ClassMapGenerator.php
src/Composer/Command/ShowCommand.php
src/Composer/Command/StatusCommand.php
src/Composer/Config/JsonConfigSource.php
src/Composer/DependencyResolver/PolicyInterface.php
src/Composer/DependencyResolver/Solver.php
src/Composer/Downloader/FileDownloader.php
src/Composer/Downloader/PerforceDownloader.php
src/Composer/Package/AliasPackage.php
src/Composer/Package/Loader/RootPackageLoader.php
src/Composer/Package/Version/VersionSelector.php
src/Composer/Repository/ArtifactRepository.php
src/Composer/Repository/ComposerRepository.php
src/Composer/Repository/FilesystemRepository.php
src/Composer/Repository/PackageRepository.php
src/Composer/Repository/Pear/BaseChannelReader.php
src/Composer/Repository/PearRepository.php
src/Composer/Repository/VcsRepository.php
src/Composer/Util/Perforce.php
src/Composer/Util/RemoteFilesystem.php
src/Composer/Util/TlsHelper.php
tests/Composer/Test/Downloader/PerforceDownloaderTest.php

Commits are separated into repaired groups, summarized:
- Fixed some config manipulation commands not working on PHP 5.3 as it didn't support use of `$this` in closures
- Added all missing parent constructor calls (bugs waiting to happen when base functionality does become meaningful)
- Stripped a lot of unused variables and imports
- Repaired some functions being called with more parameters than used
- Fixed a bunch of implicit member variable declarations

Code quality

---

src/Composer/Repository/ComposerRepository.php

`createPackage()` accepts an argument for `$class` but doesn't actually use it. I added a default value of `'Composer\Package\CompletePackage'` which seems to be the preferred class to use, at least within `ComposerRepository`. Additionally, `'Composer\Package\Package'` was swapped for `'Composer\Package\CompletePackage'` on #L373, as this is the effective value that was being used having ignored the argument.

createPackage() method should use the $class argument it accepts

---

src/Composer/IO/ConsoleIO.php
src/Composer/IO/IOInterface.php
src/Composer/IO/NullIO.php
tests/Composer/Test/IO/ConsoleIOTest.php
tests/Composer/Test/IO/NullIOTest.php

Sometimes it is useful in scripts (script handlers, plugins) to have ability to choose values from list of predefined options during console interactions. This pull request makes it possible due to support of 'select' method in IOInterface

Add support of 'select' from option list in ConsoleIO and NullIO

---

src/Composer/Command/ShowCommand.php

This might be just me, but I always feel that `--installed` is actually what I'm looking for, instead of the huge list from all the packages. This was probably more useful in the beginning with lesser packages, or with just custom repositories.
This removes the `--installed` flag and makes that the default behavior. A `--all` flag is added to show all packages (which was the old behavior).
I couldn't use the `-a` shortcut, as that is used by `--available`. Do you want to switch that, or have a better name?

Change default behavior of show/list to --installed by default

---

src/Composer/DependencyResolver/Transaction.php
tests/Composer/Test/Fixtures/installer/circular-dependency2.test

When creating a transaction we try to identify all requirements that are
not themselves required by any other package. If a package references
itself this should not mark it as being required by another package.
Includes test from https://github.com/composer/composer/pull/4977
Addresses the bug in https://github.com/composer/composer/issues/3990

Ignore self references when anlaysing independent root requirements

---

src/Composer/Command/RemoveCommand.php

Fixes #4895
As discussed in #4895, the old behaviour was not intuitive. I deprecated the old option (`--update-with-dependencies`) and made that the default. Also added `--no-update-with-dependencies` if anyone would want to use the old behaviour.

Make remove with dependencies default

---

src/Composer/Command/ShowCommand.php

Fixes #4999 - for self.version the constraint comes preparsed into `getPackage`.

Show -t incorrectly expanded self.version constraints. Fixes #4999

---

src/Composer/Command/CreateProjectCommand.php

During `create-project`, the installed PHP version was used to determine
the best root package install candidate, but failed to take into account
the `--ignore-platform-reqs` flag.
Closes #5005

Check for --ignore-platform-reqs flag during create-project

---

src/Composer/Command/SelfUpdateCommand.php

Follow-up to #5020.
I also moved the `unlink` instruction. Only change in behavior is that if an unexpected exception were to occur (unrelated to test of phar validity) the file wouldn't be deleted. 1) that's in fact better 2) such an exception just can't happen.

Adjustments in self-update command in case of corrupted file

---

res/composer-schema.json

Recently introduced "secure-http" configuration property is available in documentation [https://getcomposer.org/doc/06-config.md#secure-http](https://getcomposer.org/doc/06-config.md#secure-http) is missing in the schema.

Add missing "secure-http" config property

---

src/Composer/Util/Filesystem.php

In certain complex situations where the same folder is created and removed during the same run intermediate data may be cached misrepresenting a junction as an actual folder.
Should fix #5053

Ensure stat cache is cleared for junctions

---

src/Composer/Repository/PathRepository.php

Force reinstall of packages if the repository options are changed. Practically speaking for path repositories this ensures symlink/junction/mirror preferences are correctly applied.
Fixes #5048

Make path repository options part of the dist reference hash

---

src/Composer/Installer.php
tests/Composer/Test/Fixtures/functional/create-project-command.test
tests/Composer/Test/Fixtures/installer/abandoned-listed.test
tests/Composer/Test/Fixtures/installer/broken-deps-do-not-replace.test
tests/Composer/Test/Fixtures/installer/github-issues-4319.test
tests/Composer/Test/Fixtures/installer/suggest-installed.test
tests/Composer/Test/Fixtures/installer/suggest-prod.test
tests/Composer/Test/Fixtures/installer/suggest-replaced.test
tests/Composer/Test/Fixtures/installer/suggest-uninstalled.test

Ping @naderman
I tried to reproduce https://twitter.com/RomainMonceau/status/707992176517640192 (update and install have different results, no lock file in any case) and indeed the [composer.json](http://pastebin.com/7EifAtSb) installs correctly when using `composer update`, but it fails when doing `composer install` with the following:
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
- akeneo/pim-community-dev v1.5.1 requires doctrine/doctrine-bundle 1.2.0 -> satisfiable by doctrine/doctrine-bundle[v1.2.0].
- akeneo/pim-community-dev v1.5.0 requires doctrine/doctrine-bundle 1.2.0 -> satisfiable by doctrine/doctrine-bundle[v1.2.0].
- Conclusion: don't install doctrine/doctrine-bundle v1.2.0
- Installation request for akeneo/pim-community-dev 1.5.* …
```

[RFC] Add an update-all request when there is no lock file

---

src/Composer/Repository/Pear/ChannelReader.php

Prefer the first https:// PEAR mirror; avoid http://.

---

CHANGELOG.md

Not entirely useful because the changes are too big to show, but this follows the line set in #4010 and keeps consistency with existing links.

Add compare link to changelog for beta1

---

doc/articles/scripts.md

Since this commit https://github.com/composer/composer/commit/55b0ed8c8be74af348d9fec6702da3efd50feb46 the command events related to the `install` command are no longer tightened to the raw command `install`.
In my humple opinion this is a weird change, and I hope you will be able to merge https://github.com/composer/composer/issues/5034 needs to old doc behaviour.
But if you are not going to revert the expected behaviour, at least let's document it :smile:

Install / Update script event changed, now documented

---

src/Composer/Downloader/PathDownloader.php

The `PathDownloader` may be confronted to relative paths that have been set through a `repositories` entry in `composer.json`.
The symlinking code only works with absolute paths. So, to deal with these relative paths, we append them to the current working directory first, in order to transform them into an absolute path.
Resolves #4451

Make sure to use an absolute path for symlinking in PathDownloader.

---

src/Composer/DependencyResolver/Solver.php
src/Composer/Installer.php
tests/Composer/Test/DependencyResolver/SolverTest.php

As both #5084 and #5094 are confusing issue reports to both users and developers misinterpreting the last line of logging before it 'hangs'.

Add extra logging before and after SAT solving

---

src/Composer/Command/SelfUpdateCommand.php

I noticed `composer self-update --clean-backups` isn't removing the backups when no update is actually performed ("You are already using composer version...").
I had to do a little refactoring to implement the corrected behaviour. Split into several commits to make it easier to review.

Also clean backups if no Composer update actually performed

---

src/Composer/EventDispatcher/EventDispatcher.php

Fix #5045 
Windows a case-insensitive letter for system environment variables.
And, PHP sets environments on `$_SYSTEM`.
Any windows users use `Path` for PATH environment.  It is legal on Windows.
In this case, `$_SYSTEM['Path']` is enabled, but `$_SYSTEM['PATH']` is disabled...
So, `composer exec` cannot set `PATH` environment.
I fixed this problem.

fix Windows Path Info

---

src/Composer/Config.php
src/Composer/Downloader/HgDownloader.php
src/Composer/Repository/Vcs/HgDriver.php
src/Composer/Util/Git.php
src/Composer/Util/RemoteFilesystem.php
src/Composer/Util/Svn.php
tests/Composer/Test/ConfigTest.php

As discussed in #5008 this PR routes the `secure-http` check centrally, and checks whether the host is not on known private or reserved IP ranges.
Also reversed the protocol check - the previous implementations blacklisted `http://` hosts, while the new implementation whitelists `ssh:` and `https:` hosts. I'm not entirely sure this will work correctly with all Git use cases - review highly appreciated.

Centralize secure-http checking

---

tests/Composer/Test/DependencyResolver/RuleSetTest.php

It makes the test fail with recent (>= 3.1) phpunit-mock-objects
version.

Fix method name

---

src/Composer/DependencyResolver/Pool.php
src/Composer/DependencyResolver/Problem.php
src/Composer/DependencyResolver/Rule.php
src/Composer/Repository/ComposerRepository.php
tests/Composer/Test/Fixtures/installer/solver-problems.test

Fixes #5086, #2575 and #2661
Using this:
```json
{
"require": {
"react/socket-client": "^0.4",
"react/http": "dev-master",
"seld/jsonlint": "dev-nope",
"foo/madeup": "dev-master",
"relution-developments/carbon-php": "*",
"php-pm/php-pm": "dev-master"
}
}
```
We currently get:
```
Problem 1
- The requested package seld/jsonlint could not be found in any version, there may be a typo in the package name.
Problem 2
- The requested package foo/madeup could not be found in any version, there may be a typo in the package name.
Problem 3
- The requested package relution-developments/carbon-php could not be found in any version, there may be a typo in the package name.
Problem 4
- Installation request for php-pm/php-pm dev-master -> satisfiable by php-pm/php-pm[dev-master].
- php-pm/php-pm …
```

Improve solver error reporting

---

src/Composer/Package/Archiver/ArchivableFilesFinder.php
src/Composer/Package/Archiver/ZipArchiver.php

Empty dirs get archived (leafs).
Previously it seemed ok to skip all directories in zip generation.
References:
- Ref: 6066359944642e47d03c2dd367c9e43af787a9f7
- Issue: #4865 Keep empty folders after re-zip a module

Skip non-empty directories in zip generation

---

src/Composer/Plugin/PluginManager.php

I need access to global composer from my plugin and didn't find other way to get it.

Added getter for global composer

---

src/Composer/Installer/PluginInstaller.php

Fixes #5130, sample output:
```
[64.8MB/4.70s] Analyzed 54 packages to resolve dependencies
[64.8MB/4.70s] Analyzed 55 rules to resolve dependencies
[64.9MB/4.71s]   - Installing slbmeh/gh-5130-bad-dependency (dev-master)
[64.9MB/4.73s]     Junctioned from ../libs/bad-dependency/
[64.9MB/4.73s] 
[64.9MB/4.73s] Plugin installation failed, rolling back
[64.9MB/4.73s]   - Removing junction for slbmeh/gh-5130-bad-dependency (dev-master)
[UnexpectedValueException]                                                                 
Plugin slbmeh/gh-5130-bad-dependency could not be initialized, class not found: SomeClass  
```

Rollback installation of plugins if corrupted, fixes #5130

---

src/Composer/Downloader/PathDownloader.php

symlink names are not allowed to contain
a trailing slash, so trim it.

trim trailing slash from symlink names

---

src/Composer/Command/ConfigCommand.php
src/Composer/Config.php
src/Composer/Config/JsonConfigSource.php
src/Composer/IO/BaseIO.php

Not sure why the code to handle `bitbucket-oauth` was in its own section, but it prevented `--unset` from working for that key. Moved it where it belongs.

Fix config add/remove/unset/merge for Bitbucket OAuth

---

src/Composer/Util/RemoteFilesystem.php

I host packages on S3, which has a nasty habit of just closing connections in the middle of a transfer. Later in the process, this will then cause a failure to unpack the tarball.
This change checks the length of the loaded content against the size determined by the stream wrapper, if known. As the exception bubbles up, `FileDownloader::doDownload()` will retry two more times before giving up.
I initially wanted to implement this in `RemoteFilesystem::callbackGet()` using `STREAM_NOTIFY_COMPLETE`, but it turns out that that event is plainly not implemented in any PHP version.

Fail download on content-length mismatch

---

src/Composer/Command/SelfUpdateCommand.php

At the moment using composer self-update you just get the message that you are on the current version:
````
$ composer self-update
You are already using composer version 1.0.0.
````
This PR adds the channel information so that a user can decide if he wants to select another channel.

Show channel even if there is no new version on the current channel

---

src/Composer/Console/Application.php

Extra startup check as #4797 and #5186 show this can cause exotic hard to find errors otherwise.

Check temp folder usability before runtime

---

doc/00-intro.md

Switch the dependency management documentation
to an ordered list from a pseudo-ordered list. This
has the benefit of using more structured markdown,
and the added benefit of matching the "Suppose"
list items with corresponding "Composer" list items.

Convert documentation to ordered list

---

src/Composer/Installer.php
tests/Composer/Test/Fixtures/installer/partial-update-downgrades-non-whitelisted-unstable.test
tests/Composer/Test/Fixtures/installer/partial-update-from-lock.test

Need a sanity check here (looking at the test files). I think it's better like this. The removed packages come back if they are still in the lock, which is maybe a bit WTF but is actually correct and I doubt it'll be much of an issue in practice. Other side-effects updates or packages that were in lock but not currently installed should not happen anymore.
Fixes #3468

Fix partial updates from a dirty state and apply exactly the locked state

---

src/Composer/Json/JsonManipulator.php
tests/Composer/Test/Json/JsonManipulatorTest.php

This will allow a dollar sign followed by a digit to be used in the password stored in auth.json file.
If the content variable contains a dollar sign followed by a digit ("$n", where n consists of digits) it will match as a replacement reference for preg_replace and thus it will be replaced by the text captured by the n'th paranthesized pattern or blank if there's no such paranthesized pattern. A replacement reference can also be in the form of "\\\n", but "$n" is preferred (and also mentioned in the PHP documentation), being made available since PHP 4.0.4.

Fix addMainKey method of JsonManipulator with content having $n

---

doc/05-repositories.md
src/Composer/Config.php
src/Composer/Repository/PathRepository.php
src/Composer/Util/Platform.php
tests/Composer/Test/ConfigTest.php
tests/Composer/Test/Util/PlatformTest.php

Allows using tildes in path repositories for easier sharing of path repositories between multiple team members. For example a path repository to `~/git/mysubproject/*` will automatically load all those packages from the developer's home folder.

Tilde and environment variable expansion for paths

---

src/Composer/Console/Application.php
src/Composer/Factory.php
src/Composer/Plugin/CommandsProviderInterface.php
tests/Composer/Test/Plugin/Fixtures/plugin-v5/Installer/Plugin.php
tests/Composer/Test/Plugin/Fixtures/plugin-v5/composer.json
tests/Composer/Test/Plugin/PluginInstallerTest.php

This PR will move plugins to a next level by exposing the application to the plugins (and also loads the plugins BEFORE the application starts).
It might be a start to solve few tickets like #3312 or https://twitter.com/lsmith/status/526053583834603520
ping @lsmith77
It should also fixes #1234, #2761
Sample of use
```
composer global require FriendsOfPHP/security-advisories
cd my/project
composer security-check
```
Want to simply test  it see a sample plugin (https://github.com/jeremy-derusse/composer-plugin)
```
composer global require jderuse/plugin
composer demo:greet
```
Todo

WIP - Allow plugins to register commands

---

src/Composer/Command/ShowCommand.php

In `outdated` command, when checking for the latest packages, it will fail in case it is unable to find the latest version.
In [Composer\Command\ShowCommand.php#L280](https://github.com/composer/composer/blob/master/src/Composer/Command/ShowCommand.php#L280), the method call `$latestPackage->getFullPrettyVersion()` will throw an exception as `$latestPackage` might be `false` when there is no "bestCandidate". See [VersionSelector.php#L64](https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionSelector.php#L64).

Ignore it for unfound packages

---

src/Composer/Util/Git.php

This change provides a fallback to SSH when using https URLs for bitbucket.org.
A typical situations where this is needed include having a non-interactive install of dependencies in a location where oauth authentication (if it actually works) is not configured.
This also includes a fix for the problem with double .git extension metioned in #5160.

Bitbucket https fallback to ssh

---

doc/06-config.md

The JSON example for the `http-basic` option was missing the closing curly brace.

fix `http-basic` json example

---

src/Composer/Repository/PlatformRepository.php

I decided to add two additional PHP interpreter packages instead of an additional extension key. IPv6 support is part of PHP core (if enabled) and is not part of any optional extension.
Would close #5304.

IPv6 Platform Requirement

---

src/Composer/Package/Loader/ValidatingArrayLoader.php
tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php

This PR
Fixes https://github.com/composer/composer/issues/5339.

Fix: Do not suggest to avoid exact version constraints for unstable package

---

doc/02-libraries.md

Typo: hit the "Submit" -> hit the "Submit" button

Fix typo in 02-libraries.md

---

src/Composer/Plugin/PluginManager.php
tests/Composer/Test/Plugin/Fixtures/plugin-v9/Installer/Plugin.php
tests/Composer/Test/Plugin/Fixtures/plugin-v9/composer.json

If a plugin file starts with `declare(strict_types=1);`, Composer fails with this error:
```
Fatal error: strict_types declaration must be the very first statement in the script
in src/Composer/Plugin/PluginManager.php(194) : eval()'d code on line 3
```
So, let's strip out the strict types declaration before evaluating the file contents.

Strip out declare strict_types from plugins

---

doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md

Because the caret is closer to semver than the tilde.

Use caret operator for unbound version constraints doc

---

doc/03-cli.md
src/Composer/Command/RemoveCommand.php
src/Composer/Command/RequireCommand.php

`--no-scripts` option wasn't available for require and remove command. 
Background: 
I'm working with a lot of small vagrant boxes (small in terms of low available memory). The memory consumption of composer sometimes makes uncomfortable to use composer within the vagrant boxes. Because of this, I tend to use composer outside of the vagrant boxes. This leads to thrown exceptions, if the scripts defined in composer.json try to access resources that are not accessible from outside of the boxes.

--no-scripts option for remove and require command

---

src/Composer/Command/InstallCommand.php
src/Composer/Command/UpdateCommand.php
src/Composer/Installer.php

This allows suggestions to be disabled by the new flag `--no-suggest` 
I requested this in #5379 - it was declined, but I'm hoping as I did the footwork it might be more palatable. 
There is no reason to show suggested packages in an automated CI environment the same as the progress bar. This goes nicely with `--no-progress`.

Adds --no-suggest to install and update commands

---

src/Composer/Util/Bitbucket.php

I had similar issues described in #5166 and after investigation, I found out that Bitbucket needs you to set **Callback URL** in the **OAuth consumer** configuration to be able to generate access tokens.
If you leave this field blank the api `https://bitbucket.org/site/oauth2/access_token` will give the following error:
```
{
"error_description": "No callback uri defined for the OAuth client.",
"error": "invalid_request"
}
```
The grant type `client_credentials` will not actually use this callback URL, but it seems Bitbucket is enforcing that it is configured anyway.
This PR updates the log messages to inform the user that the `Callback URL` needs to be set to something. *Ensure you enter a "Callback URL" or it will not be possible to create an Access Token (this callback url will not be …

Update bitbucket oauth instructions

---

src/Composer/Command/SearchCommand.php
src/Composer/Repository/ArrayRepository.php
src/Composer/Repository/ComposerRepository.php
src/Composer/Repository/CompositeRepository.php
src/Composer/Repository/RepositoryInterface.php
tests/Composer/Test/Repository/ArrayRepositoryTest.php
tests/Composer/Test/Repository/ComposerRepositoryTest.php

Fixes #4317
Add a `--type` parameter to the `search` function, in order to search for specific package types.
E.G
```bash
$ composer search foo --type=composer-plugin
```
Depends on composer/packagist#692

Added type option to search

---

src/Composer/Repository/RepositoryInterface.php

Fixes #5458
Remove the `$type` parameter from `RepositoryInterface` to alleviate the BC break for plugins.

Remove type parameter from RepositoryInterface

---

doc/00-intro.md
doc/02-libraries.md
doc/04-schema.md
doc/05-repositories.md
doc/06-config.md
src/Composer/Command/CreateProjectCommand.php
src/Composer/Downloader/FossilDownloader.php
src/Composer/Factory.php
src/Composer/Package/Version/VersionGuesser.php
src/Composer/Repository/RepositoryFactory.php
src/Composer/Repository/Vcs/FossilDriver.php
src/Composer/Repository/VcsRepository.php
tests/Composer/Test/Downloader/FossilDownloaderTest.php
tests/Composer/Test/Repository/Vcs/FossilDriverTest.php

This adds support for local and remote Fossil repositories as Composer packages.
Fossil is a popular DVCS that includes issues management, a wiki and more: https://www.fossil-scm.org/

Fossil VCS support for Composer

---

doc/faqs/how-to-install-composer-programmatically.md

The double equal (==) with single quote condition for string comparison gives a unexpected operator error.

error in string comparison

---

src/Composer/Factory.php
src/Composer/Installer.php
src/Composer/Installer/InstallationManager.php
src/Composer/Installer/InstallerBinaryInterface.php
src/Composer/Installer/LibraryInstaller.php
tests/Composer/Test/Fixtures/functional/create-project-command.test
tests/Composer/Test/Fixtures/installer/abandoned-listed.test
tests/Composer/Test/Fixtures/installer/github-issues-4795-2.test
tests/Composer/Test/Fixtures/installer/github-issues-4795.test
tests/Composer/Test/Fixtures/installer/suggest-installed.test
tests/Composer/Test/Fixtures/installer/suggest-prod.test
tests/Composer/Test/Fixtures/installer/suggest-replaced.test
tests/Composer/Test/Fixtures/installer/suggest-uninstalled.test
tests/Composer/Test/Installer/InstallationManagerTest.php
tests/Composer/Test/Installer/LibraryInstallerTest.php

Binaries are re-installed after an update/install (ie: removed and then installed).
This is a working draft that fix https://github.com/composer/composer/issues/1209.
For the moment it removes all binaries links and re-create them on every update/install.
I have few questions:
1. Re-installing binaries are performed every time on an update or installation. Should I run it only when user re-define the bin dir? If yes, how can I detect that the config is overridden in the `composer.json` with `"bin-dir": "bin"` ?
2. In `InstallationManager` I retrieve the installer but since I only updated the `LibraryInstaller`, I try/catch to avoid other installer to throw exception. Is there a better way?
3. I also display a message when installing binaries: _Installing binaries files_ Is that necessary? …

Re-install binaries on update/install

---

src/Composer/Config.php
src/Composer/Downloader/GitDownloader.php
src/Composer/Util/Git.php
tests/Composer/Test/Downloader/GitDownloaderTest.php

I tried #4685 but it seems to not being creating the git mirror, so I extended it a little, on top of @luisfaceira changes; I have also added a version check for git, given that the `--dissociate` option is only available since 2.3.0-rc0, which is not yet the default on some *nix distributions.
PS: Please notice that this is my first attempt to read/modify composer, so I would be happy to rework this if needed.

Faster git clones using cache

---

src/Composer/Util/Git.php

Fixes #5543 
Using git with fcgiwraps/nginx behind basic authentication Composer currently receives the following error output from Git, which Composer does not detect as an authentication error:
```
error: The requested URL returned error: 401 Unauthorized while accessing http://git.robbast.nl/repo/test.git/info/refs
fatal: HTTP request failed
```

check for additional possible authentication failure strings in gitutil

---

src/Composer/Autoload/ClassLoader.php

Caching missing classes in `$this->classMap` breaks the benefit of #5174 by triggering a copy-on-write.
Let's track them in a dedicated array.

Add ClassLoader::$missingClasses to not trigger a COW

---

tests/Composer/Test/AllFunctionalTest.php

The `$sectionData` was being overwritten (type mismatch), causing its assertion (`$this->assertSame()`) to fail.

Fix support for testing exit code

---

doc/03-cli.md

At the moment, the ``--no-suggest`` flag (implemented in https://github.com/composer/composer/pull/5392) is not being documented anywhere and in my opinion this is such an awesome feature that should be know everyone as soon as possible.
Ping @aeony @donatj @Seldaek

Adds --no-suggestion flag to the docummentation

---

src/Composer/Package/Loader/ArrayLoader.php
tests/Composer/Test/Package/Loader/ArrayLoaderTest.php

commit 3994b556dcffcde7b1801c8bc712f3127e8f8e7c
Author: John Whitley 
Date:   Tue Aug 16 09:02:53 2016 +0100
https://github.com/composer/composer/issues/5600
This alters the default flag for loadOptions in \Composer\Package\Loader\ArrayLoader to true; and alters the assumption of the test to reflect this change.
**Rationale**
The `\Composer\Package\Loader\ArrayLoader` test (defined in tests/Composer/Test/Package/Loader/ArrayLoaderTest.php) assumed that a new `\Composer\Package\Loader\ArrayLoader` instance would be always created with the optional flag loadOptions set to true.
```php
$this->loader = new \Composer\Package\Loader\ArrayLoader(null, true);
```
This change alters the general case to reflect the default assumption as defined in the test.
commit …

require-dev package repository options get copied into composer.lock (fix for #5600)

---

doc/03-cli.md
src/Composer/Command/RequireCommand.php

`--no-suggest` was added on UpdateCommand and InstallCommand.  
This adds it to RequireCommand which can be seen quite visibly by running the following (which our CI system runs):
```bash
composer require phing/phing
```
vs
```bash
composer require phing/phing --no-suggest
```

Adds --no-suggest to RequireCommand

---

doc/03-cli.md
src/Composer/Command/ShowCommand.php

This adds a new option to the show command: --minor-only.
When used in combination with --outdated, it will only show packages that have minor semver-compatible updates.
The use case for this is that we want to use composer to check if our project has any direct dependencies with minor semver-compatible updates, and fail our CI build if that's the case. The alternative would've been either trying to parse the original output checking for minor versions, or write a separate tool that hooks into composer to do the check.
This seemed like the simplest option.
Looking forward to your feedback.

Added minor-only option to show command to only show packages with minor updates

---

doc/articles/scripts.md

remove trailing comma from JSON.

JSON standard do not allow trailing comma

---

src/Composer/Downloader/RarDownloader.php
src/Composer/Downloader/ZipDownloader.php

I was playing with a blackfire profile done on a composer install and figured out that `fread` was called 90k times. After investigating, it turns out that `unzip`'s output is ignored by composer, but it's not by the underlying Symfony Process object.
Let's pipe it's output to `/dev/null` (not on windows of course).
Meanwhile, some code needed a related cleanup, here it is :)

Cleanup processes output handling

---

src/Composer/Repository/Vcs/GitLabDriver.php
tests/Composer/Test/Repository/Vcs/GitLabDriverTest.php

With this change the `GitLabDriver` follows the same behavior as the `GitHubDriver` when the repository url is retrieved: if the project is public it returns the HTTPS url, otherwise it returns the SSH url.
Fixes #4744

Use https url of the repository instead of ssh given gitlab project is public

---

bin/composer
src/Composer/Console/Application.php
src/Composer/Factory.php
src/Composer/XdebugHandler.php
tests/Composer/Test/Mock/XdebugHandlerMock.php
tests/Composer/Test/XdebugHandlerTest.php

I was asked about implementing a solution regarding xdebug performance ([Windows-Setup: issue#58](https://github.com/composer/windows-setup/issues/58)) and wondered whether this functionality would be more useful inside Composer - if it can be made to work reliably. This PR is an initial stab at that.
To make testing easier, here is the compiled [composer.phar](https://github.com/johnstevenson/composer/releases/tag/v1.2-dev.0256f62)  (updated to 0256f62)
I have assumed that the preferred use-case is running Composer without `xdebug`, so this is the default behaviour. It can be controlled by setting an environment variable beforehand:
* `COMPOSER_ALLOW_XDEBUG=0` Composer will restart without xdebug if it has been enabled. This is the default behaviour and does not require any variable to …

Restart with xdebug disabled

---

doc/06-config.md
res/composer-schema.json
src/Composer/Command/ConfigCommand.php
src/Composer/Config.php
src/Composer/Config/JsonConfigSource.php
src/Composer/IO/BaseIO.php
src/Composer/Util/GitLab.php
src/Composer/Util/RemoteFilesystem.php

Support gitlab private-token (or personal-access-token) for easier access via Gitlab API
Config example:
$HOME/.composer/auth.json
```json
{
"gitlab-token": {
"gitlab.com": "YOUR-TOKEN-HERE"
}
}
```
Gitlab API authentication doc: http://doc.gitlab.com/ce/api/README.html

Support gitlab private-token for easier access via Gitlab API

---

src/Composer/Command/GlobalCommand.php

default installation directory for global packages
has changed since adding support for freedesktop.org standards
per confusion from http://stackoverflow.com/q/38703915/4233593
Now if your system uses freedesktop.org standards, then it will first check
`XDG_CONFIG_HOME` or default to `/home/<user>/.config/composer`

update help page on global for COMPOSER_HOME info

---

src/Composer/Command/ExecCommand.php
src/Composer/EventDispatcher/EventDispatcher.php
tests/Composer/Test/EventDispatcher/EventDispatcherTest.php

Projects that add binaries to `vendor-bin` can now execute those via the same command as projects that consume them without installing them first.
In list overview local commands have a `(local)` tag to distinguish them from commands installed in `vendor-bin`.
Local binaries take precedence over `vendor-bin` which takes precedence over binaries in path.

Add support for seamless execution of local binaries

---

src/Composer/Config.php
tests/Composer/Test/ConfigTest.php

This is used in silex/silex-skeleton for instance to run the PHP embed server (https://github.com/silexphp/Silex-Skeleton/blob/master/composer.json#L37).

Fix process timeout when set to 0

---

src/Composer/XdebugHandler.php
tests/Composer/Test/XdebugHandlerTest.php

To make testing easier, here is the compiled [composer.phar](https://github.com/johnstevenson/composer/releases/download/413a516/composer.phar) updated to 413a516
<hr>
There is no need to point `PHP_INI_SCAN_DIR` to an empty directory in order to bypass the compiled-in scan directory, because it can be overridden by providing an empty value.
The documentation is not entirely clear about this, but this was how it was designed. From [https://bugs.php.net/bug.php?id=45114](https://bugs.php.net/bug.php?id=45114):
> Now you can either use both -n and -c in command line options (-n disables every ini loading, -c enables loading the specified file / from specified path) or set PHP_INI_SCAN_DIR environment variable to empty (disables scanning) or to point to some other directory.
which references …

Simplify XDebugHandler restart process

---

doc/03-cli.md
src/Composer/Downloader/PathDownloader.php

This change allows setting COMPOSER_DEFAULT_TRANSPORT_STRATEGY
in the environment to set the default strategy to 'mirror' if you like.
This allows using 'mirror' during deployments while still symlinking
on a development machine. The default is still overwritten by the
options on the repository configuration.

Allow setting default transport strategy for path repositories

---

res/composer-repository-schema.json

A stab at writing a more formal specification that covers the various metadata files that packagist hosts.
Ideally it would include refs to the composer-schema.json definitions for the package schemas contained in each version.

[wip] composer repository json schema

---

src/Composer/Plugin/PluginManager.php

Happens when the class is not namespaced.

added missing var declaration

---

src/Composer/Autoload/ClassLoader.php
tests/Composer/Test/Autoload/ClassLoaderTest.php

Composer requires PHP 5.3.2 as a minimum.
The code I've removed in this PR is for a bug that was fixed in 5.3.2, so it should be safe (https://github.com/php/php-src/blob/PHP-5.3.29/NEWS#L2080).

removed obsolete code

---

doc/04-schema.md

Using JSON object should be discouraged as there is no explicit order
of keys in JSON object. Even though it's deterministic in current PHP
version, it may change any time. As stated on http://json.org/:
"An object is an unordered set of name/value pairs. An object begins
with { (left brace) and ends with } (right brace). Each name is
followed by : (colon) and the name/value pairs are separated
by , (comma)."
Fixes #2802.

Clarify allowed format for repositories key

---

src/Composer/DependencyResolver/Solver.php

Thanks to [blackfire.io](https://blackfire.io), I spotted that `count()` is hurting performance for no reason here. It was called 730023965 times in the case I was working on, not unusual.
Using `time` to "profile" the patch, `composer up` dropped from 290s to 140s (PHP7.1)!

Enhance performance by removing count() from Solver's main loop

---

src/Composer/Command/ShowCommand.php

When using certain parameters together in 'composer show', specifically '-s --outdated', the root package itself is inspected for its latest version. If the git repository it belongs to does not have any tags yet this would return FALSE, while the next call to printMeta requires a PackageInterface or NULL, causing a crash.
Refs #5808

Fix crash when listing root package without versions

---

src/Composer/EventDispatcher/EventDispatcher.php
src/Composer/Installer/PackageEvents.php
src/Composer/Script/ScriptEvents.php

This PR mostly updates phpdoc to reference the non-deprecated event classes. It also fixes the event dispatcher which stills uses a deprecated event class.

fixed deprecated class usages

---

doc/04-schema.md

Following the discussion in #5823 it has become clear that this feature is supplied at-your-own-risk, this should be more explicitly reflected in its documentation.

Clarify documentation that commit refs are unsupported

---

src/Composer/Downloader/GitDownloader.php
tests/Composer/Test/Downloader/GitDownloaderTest.php

When composer needs to update a library which is installed as a git repository, it currently performs a fetch to make sure that the git repository is up to date and then issues the checkout. On slow networks this fetch can take 10-20 seconds to complete, slowing down the install of the new commit. This fetch, however, is not always needed, as the new reference commit may already be known by git. By checking if the reference commit exists before issuing the fetch, we can skip the fetch entirely when not needed, resulting in checkouts taking less than a second where the commit is know.
Testing with a simple project, switching between `composer/semver` version 1.4.1 and 1.4.2, has checkouts going from an average of 1.92s over 5 passes to 0.48s.

Speed up git checkout by skipping fetch

---

src/Composer/Util/ProcessExecutor.php
tests/Composer/Test/EventDispatcher/EventDispatcherTest.php
tests/Composer/Test/Util/ProcessExecutorTest.php

All output go through the IO object, except the output of the script executions, which is output directly via `echo`. This PR fixes this bug.

Remove usage of echo when executing Composer script

---

doc/articles/scripts.md
src/Composer/Installer.php

**Issue addressed**
https://github.com/composer/composer/issues/5769
**Summary**
Sets a php environment variable during the composer install/update, to expose to any post-install/update scripts which mode the install/update was run in.
**Example Usage (In post install/update script)**
```
if (getenv("COMPOSER_DEV_MODE") ==1) {
// do something
}
```

Issue 5769 dev mode varaible

---

res/composer-schema.json
tests/Composer/Test/Json/ComposerSchemaTest.php

``additionalProperties`` does not only accept a boolean, but also a schema object, in which case the value of the additional property must validate this schema (``true`` is equivalent to adding a catch-all schema).
I added this extra validation for all places using ``additionalProperties`` except 2 of them:
- ``extra`` because the content is really free-form
- ``repositories`` because the inner content is very complex, and I prefer keeping this in a separate PR (looking at a way to avoid duplicating things in Satis, where we already worked on adding validation for it, and probably submitted to master as it would make bigger changes to the schema)
Refs #5807

Enhance the json schema with validation for map objects

---

src/Composer/Installer.php
tests/Composer/Test/Fixtures/installer/abandoned-listed.test
tests/Composer/Test/Fixtures/installer/github-issues-4795-2.test
tests/Composer/Test/Fixtures/installer/suggest-installed.test
tests/Composer/Test/Fixtures/installer/suggest-prod.test
tests/Composer/Test/Fixtures/installer/suggest-replaced.test
tests/Composer/Test/Fixtures/installer/suggest-uninstalled.test

This PR adds two pieces of output:
- One line of summary about what Composer is about to install, remove, update (always displayed, not on quiet mode of course);
- Up to 3 lines, in verbose mode only, to list the operations that are going to occur.
The goal is to give some more information upfront about what's going to happen next. A lot of package managers do that and I find it extremely useful for both informational purpose and debugging purpose as well.

added more information in the output

---

src/Composer/Downloader/VcsDownloader.php

realpath() returns FALSE for paths with URL encoding like %20, and decoded path needs file:/// reapplied.
(this was originally pull request #5845)

Fixing local file VCS URLs with encoded characters 

---

src/Composer/Util/Filesystem.php

To fix #5870
AFAIK, '//' -- means '/' at Linux, and there is no reason to use // at Linux systems.

windows remote path treats as remote now

---

src/Composer/Command/DiagnoseCommand.php
src/Composer/DependencyResolver/SolverProblemsException.php
src/Composer/Downloader/RarDownloader.php
src/Composer/Downloader/ZipDownloader.php
src/Composer/Util/IniHelper.php
src/Composer/XdebugHandler.php
tests/Composer/Test/Util/IniHelperTest.php
tests/Composer/Test/XdebugHandlerTest.php

Question: Should `php_ini_scanned_files()` use a `function_exists` guard, since it was only introduced in HHVM in September 2014? I have left this out at the moment.

Use random name for tmp ini and delete after use

---

doc/05-repositories.md

While testing i found that 
"packagist.org": false 
didn't work to disable packagist.
I have read following issue 
https://github.com/composer/composer/issues/3713
afterwards i've testet 
"composer config repositories.packagist false"
did the review on the composer.json and found that 
"packagist": false 
actually disabled packagist.

disabling packagist.org did not work

---

src/Composer/Package/BasePackage.php
src/Composer/Package/Dumper/ArrayDumper.php
tests/Composer/Test/Package/Dumper/ArrayDumperTest.php
tests/Composer/Test/Package/LockerTest.php
tests/Composer/Test/Package/Version/VersionSelectorTest.php

Rather than assigning empty array in constructor, simply default to an array on the class attribute. Also add a guard clause in the dumper. This resolves failing tests on php 7.2.0 which no longer accepts non-countable arguments for `count()`.

use array as default value

---

doc/05-repositories.md

A merge conflict slipped through recently, corrupting the page a bit.

Clean up a merge conflict in repositories doc

---

doc/articles/versions.md

http://semver.mwl.be/ produce a 404, it moved to https://semver.mwl.be/

semver.mwl.be moved to HTTPS

---

doc/04-schema.md

Details: https://wiki.typo3.org/Composer#TYPO3_Composer_installers

Fix wrong Composer package "type" example

---

doc/03-cli.md
doc/06-config.md
res/composer-schema.json
src/Composer/Autoload/AutoloadGenerator.php
src/Composer/Autoload/ClassLoader.php
src/Composer/Command/ConfigCommand.php
src/Composer/Command/DumpAutoloadCommand.php
src/Composer/Command/InstallCommand.php
src/Composer/Command/RemoveCommand.php
src/Composer/Command/RequireCommand.php
src/Composer/Command/UpdateCommand.php
src/Composer/Config.php
src/Composer/Installer.php
tests/Composer/Test/Autoload/AutoloadGeneratorTest.php

APCu is near perfect for caching classes: it is really fast.
Even when using static arrays on PHP 7 (see #5174), `findFile` can be slow in non authoritative mode because of not-found classes. And when the class map is not dumped (esp. on PHP 5.5 where dumped classes don't scale with the number of classes), using e.g. Symfony's ApcClassLoader in front of composer provides a significant speed boost. Let's inline this knowledge into composer, the only loader that should rule them all :)
This PR isn't the same as #5172: instead of decorating the loader, we hook apcu between the class map lookup and the filesystem lookup.
As advised by @lisachenko in https://twitter.com/lisachenko/status/719105126439497728, some use case of APCu can lead to slowness because of memory fragmentation. Yet, not …

Add --apcu-autoloader option to enable APCu caching of found/not-found classes

---

src/Composer/Downloader/ArchiveDownloader.php
src/Composer/Downloader/FileDownloader.php
src/Composer/Downloader/FossilDownloader.php
src/Composer/Downloader/GitDownloader.php
src/Composer/Downloader/HgDownloader.php
src/Composer/Downloader/PathDownloader.php
src/Composer/Downloader/PerforceDownloader.php
src/Composer/Downloader/SvnDownloader.php
src/Composer/Downloader/VcsDownloader.php
src/Composer/Downloader/ZipDownloader.php
src/Composer/Installer.php
src/Composer/Util/RemoteFilesystem.php
tests/Composer/Test/Fixtures/functional/create-project-command.test

As you can see below, this reformats the output slightly to save vertical space at a little horizontal space cost.
Less blank lines, and dist updates are shown as updates and not remove+install.
I'd be happy to get feedback here, from users perspective but also from people that may be doing wonky things with the output (/cc @dzuelke @fabpot ;) and might see breakage.
> Note that you should click the images to see them full size for a fair comparison..
Before:
After:

Simplify composer output to take less lines

---

src/Composer/Repository/PlatformRepository.php
src/Composer/XdebugHandler.php
tests/Composer/Test/Mock/XdebugHandlerMock.php
tests/Composer/Test/XdebugHandlerTest.php

Adds the internal `COMPOSER_XDEBUG_VERSION` environment variable for the restarted process.

Set xdebug version in environment, fixes #5967

---

src/Composer/Downloader/PathDownloader.php

I'm working on my composer plugin, and I want to be able to test the plugin with actual composer.json files. In order to do this, I want to use a composer.json like this: https://github.com/cweagans/composer-patches/blob/acceptance-tests/tests/acceptance/fixtures/_fixture-template/composer.json
Currently, `composer install` in that directory yields
```
[RuntimeException]                                                                                                   
Package cweagans/composer-patches cannot install to "/home/cweagans/Code/composer-patches/tests/acceptance/fixtures  
/_fixture-template/vendor/cweagans/composer-patches" inside its source at "/home/cweagans/Code/composer-patches"     
```
I think this PR should do what I need. If you have a different way you want to handle …

Allow use of parent directories in PathDownloader when not mirroring the path

---

tests/Composer/Test/Repository/PathRepositoryTest.php

This fixes the case, where `__DIR__` expands to a value different than `getcwd()` in length.
PHP bug https://bugs.php.net/bug.php?id=73797

Fix __DIR__/getcwd() inconsistency.

---

doc/03-cli.md
doc/articles/troubleshooting.md

* remove the xdebug section, since it will be irrelevant from v1.3
* add cPanel shell fork bomb protection as an other possible root cause of memory errors
This should solve #5869

[Documentation] Update troubleshooting article

---

tests/Composer/Test/Downloader/GitDownloaderTest.php

Mindless copy-paste never gets old. Sorry. This is fixed proper this time.

Properly skip GitDownloaderTest if git is not available

---

src/Composer/XdebugHandler.php
tests/Composer/Test/XdebugHandlerTest.php

This clears the `COMPOSER_XDEBUG_VERSION` environment variable if the restart fails and xdebug is still loaded.
Here is the compiled [composer.phar](https://github.com/johnstevenson/composer/releases/download/2b8ad7d/composer.phar)
I had to mock the failure to test this, so it would be appreciated if those affected by this issue could confirm if this now works for them.

Clear xdebug version if restart fails, fixes #5995

---

src/Composer/Util/RemoteFilesystem.php

URL https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
results in the following $pathParts:
```
array(5) {
[0]=>
string(0) ""
[1]=>
string(5) "ariya"
[2]=>
string(9) "phantomjs"
[3]=>
string(9) "downloads"
[4]=>
string(36) "phantomjs-2.1.1-linux-x86_64.tar.bz2"
}
```
A dist download URL like https://bitbucket.org/user/repo/get/[git-hash].zip results in the following $pathParts:
```
array(5) {
[0]=>
string(0) ""
[1]=>
string(4) "user"
[2]=>
string(4) "repo"
[3]=>
string(3) "get"
[4]=>
string(14) "[git-hash].zip"
}
```

Fix dist downloads from bitbucket private repos

---

src/Composer/Repository/RepositoryFactory.php

Fossil is a VCS driver. It does not have its own Repository class

Fix the class name for fossil repositories

---

composer.json
composer.lock
res/composer-schema.json
src/Composer/Json/JsonFile.php

This is the next step of the schema improvements, validating repositories. This should give a avoid mistakes putting the ``autoload`` config outside the ``package`` configuration for package repositories for instance.
For inline packages, I kept things simple by referencing the schema for the full composer.json, even though root-only properties are actually useless here as they would not be used.
The second commit changes the way we load the schema when validating so that references are resolved properly (otherwise they don't work). The previous code was working only because the schema did not have any references in it. To keep things simple, I dropped support for ``justinrainbow/json-schema`` 1.x and 2.x, as support for references was much harder for them (and maybe not working). These …

Implement schema validation for repositories

---

res/composer-schema.json

Closes #6021 
This replaces the list of required properties of the root schema instead of adding a second list of required properties, because the ``description`` property should not be required for inline packages (it is necessary only when publishing).

Fix the validation of required properties for inline packages

---

res/composer-schema.json

The URL of the VCS repository may not match the uri pattern of the JSON schema spec, for instance when using a SSH URL of the repository.
Closes #6026

Loosen the validation for the URL field of VCS repositories

---

res/composer-schema.json
tests/Composer/Test/Json/ComposerSchemaTest.php

Reusing the root schema was a mistake, because the root schema does not have the dist and source properties (which are populated by repository objects).
And adding new properties in a referenced schema using ``additionalProperties: false`` is not possible in json-schema draft 4.
closes #6028 (tested with the files given by @skors and @Rudloff)

Refactor the validation of inline package definitions

---

src/Composer/Console/Application.php

Composer incorrectly shows Xdebug warning, even if extension is not loaded, but COMPOSER_ALLOW_XDEBUG is present.

Fix Xdebug warning

---

src/Composer/Command/AboutCommand.php
src/Composer/Command/ArchiveCommand.php
src/Composer/Command/ConfigCommand.php
src/Composer/Command/DependsCommand.php
src/Composer/Command/DumpAutoloadCommand.php
src/Composer/Command/ExecCommand.php
src/Composer/Command/LicensesCommand.php
src/Composer/Command/ProhibitsCommand.php
src/Composer/Command/RemoveCommand.php
src/Composer/Command/RequireCommand.php
src/Composer/Command/SearchCommand.php
src/Composer/Command/ShowCommand.php
src/Composer/Command/StatusCommand.php
src/Composer/Command/SuggestsCommand.php
src/Composer/Command/ValidateCommand.php

Simple but effective, I simply added a full stop to each command's description if it was not already there.

Add full stop to all command descriptions

---

src/Composer/Command/ArchiveCommand.php
src/Composer/Package/Archiver/ArchivableFilesFinder.php
src/Composer/Package/Archiver/ArchiveManager.php
src/Composer/Package/Archiver/ArchiverInterface.php
src/Composer/Package/Archiver/PharArchiver.php
src/Composer/Package/Archiver/ZipArchiver.php
tests/Composer/Test/Package/Archiver/ArchivableFilesFinderTest.php

Fixes https://github.com/composer/composer/issues/3733.
Gives the user an option to ignore the `HgExcludeFilter`, `GitExcludeFilter` and `ComposerExcludeFilter` filters by using the option `--ignore-filters`.
Example: 
`composer archive --ignore-filters package/package 1.0`

Add ignore filters option to archive command

---

src/Composer/XdebugHandler.php

The segfault occurs on PHP for Windows (5.5, 5.6, 7.0 and 7.1), but not on Ubuntu or Centos.
I'll submit a bug report later.

Work-around for Windows opcache bug, fixes #6052

---

src/Composer/DependencyResolver/GenericRule.php
src/Composer/DependencyResolver/Rule.php
src/Composer/DependencyResolver/Rule2Literals.php
src/Composer/DependencyResolver/RuleSet.php
src/Composer/DependencyResolver/RuleSetGenerator.php
src/Composer/DependencyResolver/RuleWatchGraph.php
src/Composer/DependencyResolver/RuleWatchNode.php
src/Composer/DependencyResolver/Solver.php
tests/Composer/Test/DependencyResolver/RuleSetIteratorTest.php
tests/Composer/Test/DependencyResolver/RuleSetTest.php
tests/Composer/Test/DependencyResolver/RuleTest.php

It is known that composer update takes a lot of memory: #5915, #5902, #5847, #5879
I am playing with a profiler (@blackfireio) to make a demo in my local PHP meetup (@phpvigo) and I found out a way to use less memory. These are my first tests:
* Private project using PHP 5.6: 
* Memory: from 1.31GB to 1.07GB 
* Wall Time: from 2min 8s to 1min 33s
* symfony-demo using PHP 7.1 in my old mac book:
* Memory: from 667MB to 523MB 
* Wall Time: from  5min 29s to 5min 28s
Not use an array inside conflict rules is this improvement main idea:
```php
<?php
//Memory 38MB
gc_collect_cycles();
gc_disable();
class Rule
{
public $literals;
public function __construct(array $literals)
{
$this->literals = $literals;
}
}
$rules = array();
$i = 0;
while ($i<80000){ //
$i++;
$array = array(-$i, $i);
$rule = …
```

Improve memory usage resolving dependencies 

---

src/Composer/Downloader/FileDownloader.php
src/Composer/Downloader/FossilDownloader.php
src/Composer/Downloader/GitDownloader.php
src/Composer/Downloader/HgDownloader.php
src/Composer/Downloader/PathDownloader.php
src/Composer/Downloader/PerforceDownloader.php
src/Composer/Downloader/VcsDownloader.php
src/Composer/Util/RemoteFilesystem.php
tests/Composer/Test/Fixtures/functional/create-project-command.test

This PR streamlines the messages printed during package installs. It cleans up several small discrepancies and issues:
1. ensure output is the same with and without `--no-progress`;
1. ensure the message doesn't say just "Downloading" after completion with `--no-progress` by appending "(100%)" when done;
1. proper-ish grammar (there should be some kind of separator before "Downloading");
1. print all progress indicators before the operation (e.g. for symlink/mirroring), which is useful in particular if the operation fails with an exception
Current, no cache:
```ShellSession
$ COMPOSER_CACHE_DIR=/dev/null composer install
Installing dependencies (including require-dev) from lock file
Package operations: 11 installs, 0 updates, 0 …
```

Streamline install progress messages

---

src/Composer/Command/ShowCommand.php

This PR adds JSON representation of package lists dumped by the show command, to simplify integration in quality assurance tools.
As an example (`composer show -f json --outdated`):
```json
{
"installed": [
{
"name": "guzzle/guzzle",
"version": "v3.9.3",
"latest": "v3.9.3",
"status": "up-to-date",
"description": "PHP HTTP client. This library is deprecated in favor of https://packagist.org/packages/guzzlehttp/guzzle",
"warning": "Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead."
},
{
"name": "paragonie/random_compat",
"version": "v2.0.4",
"latest": "v2.0.9",
"status": "update-recommended",
"description": "PHP 5.x polyfill for random_bytes() and random_int() from PHP 7"
},
{
"name": "zendframework/zend-code",
"version": "2.6.3",
"latest": …
```

Add json output for show command

---

doc/01-basic-usage.md
doc/02-libraries.md
doc/04-schema.md
doc/articles/versions.md

This is a first attempt at clarifying these points. I added a lot of information about the internals of Composer's process for resolving packages. I tried not to flood the user with unnecessary information, but the details I added were those that I myself found to be lacking and that, had they been present before, would have helped me better understand how to publish libraries and use Composer to manage them.
Having taken this foray into the docs, I remain convinced that they're very good, but could be better. I'd like to have a go at maybe a total rewrite of the Composer "book". There are just a few details that were hard to place in the current set of files, and I think this is because they're not structured in the best possible way.
Anyway, I know this pull request is a lot to read …

Updated documentation to clarify versions and package resolution (refs #6088)

---

src/Composer/Command/InitCommand.php
tests/Composer/Test/Command/InitCommandTest.php

The Init command was not accepting my author name. I have my default git `user.name` formed in a way that **Pérez** was not using the latin small "e" with acute (U+00E9), but instead using the combining diacritic mark for acute accent (U+0301).

Fix Init command to accept author names with Unicode combining marks

---

src/Composer/Package/Loader/ValidatingArrayLoader.php

Complete #6098
Now run `composer validate` will notice:
```
./composer.json is invalid, the following errors/warnings were found:
config.platform.php : invalid value (^7.0): Invalid version string "^7.0"
```

Add config>platform checking

---

src/Composer/Util/ConfigValidator.php

I was one of this stupid users, so I would like to help future ones.

Add a specific message for stupid users that put useless spaces in license

---

src/Composer/Package/Version/VersionGuesser.php
tests/Composer/Test/Package/Version/VersionGuesserTest.php

Current versions of Git output the commit hash as detached HEAD instead
of FETCH_HEAD. The VersionGuesser should be able to handle commit hashes
as well as FETCH_HEAD to detect the correct branch of a commit.
Resolves: #6311

Fix Git branch parsing for detached HEAD on a commit

---

src/Composer/Command/AboutCommand.php
src/Composer/Command/ArchiveCommand.php
src/Composer/Command/ConfigCommand.php
src/Composer/Command/CreateProjectCommand.php
src/Composer/Command/ExecCommand.php
src/Composer/Command/LicensesCommand.php
src/Composer/Command/RunScriptCommand.php
src/Composer/Command/ScriptAliasCommand.php
src/Composer/Command/SearchCommand.php
src/Composer/Command/ShowCommand.php
src/Composer/Command/StatusCommand.php
src/Composer/Command/SuggestsCommand.php

Right now, the verb form in descriptions of commands is confused base form with third-person singular form. So I want to aligh this to the latter because Symfony's general commands are so.

Aligns the verb form of commands' description

---

src/Composer/Installer/SuggestedPackagesReporter.php
tests/Composer/Test/Installer/SuggestedPackagesReporterTest.php

With this PR, common control characters are removed from the output of suggest fields, with the exception of new line characters. This fixes the problem described in #6334.

Remove ANSI control characters from suggested packages output

---

src/Composer/Command/InitCommand.php

Currently when running `composer init --require=symfony/console`, you will still get the yes/no question to define your dependencies interactively. If you answer no to this question, the `composer.json` will be initialised without the requirement passed to the command initially. I feel like this is not desired behaviour.
This PR skips the 'Would you like to define your dependencies (require) interactively?' and 'Would you like to define your dev dependencies (require-dev) interactively?' questions if the `--require` or `--require-dev` option(s) were set already.

Auto-skip interactive require when set by option.

---

src/Composer/Repository/Vcs/VcsDriver.php
tests/Composer/Test/Repository/Vcs/GitLabDriverTest.php

Fix for: https://github.com/composer/composer/commit/876f14341814d427e87dd358ed91ccc855678a5c#commitcomment-21901159
When using GitLab driver in a non-public network (e.g. company) and the GitLab server instance is using SSL with a self-signed certificate, it is not possible to retrieve repository information because SSL certificate verification errors (encountered in the context of Satis).
This could be solved by explicitly disabling SSL verification check via `options` but unfortunately composer isn't forwarding the options to the remote filesystem.
This patch fixed the issue for VCS based drivers by always forwarding `options` if available. The same has been done for the `composer` repository type as seen in the commit above.

Forward GitLab driver options to remote filesystem

---

src/Composer/Installer.php
tests/Composer/Test/Fixtures/installer/plugins-are-installed-first.test

Currently plugins are only moved to the front to be installed first when they don't have dependencies beyond platform requirements and `composer-plugin-api`. This causes an issue for our plugin [`oomphinc/composer-installers-extender`](https://github.com/oomphinc/composer-installers-extender) which is built atop `composer/composer-installers` and thus requires it. Users are seeing the same issue as https://github.com/composer/composer/issues/1147, see: https://github.com/oomphinc/composer-installers-extender/issues/6.
What this does is instead of skipping plugins that have additional dependencies, it moves the plugin and those dependencies to the front as well. This works on the assumption that install/update operations for a package's dependencies come before the package that required …

Move all plugins and their dependencies to the front

---

doc/04-schema.md

These licenses are deprecated in spdx spec v2 (https://spdx.org/licenses/).

Remove Deprecated Licenses

---

.travis.yml

Since PHP 5.3 is not supported on Trusty, this PR moves tests for PHP 5.3 over to Ubuntu Precise.

Test PHP 5.3 on Precise

---

doc/05-repositories.md

Obviously this is not a common use case, but it is good for isolated networks. As far as I could tell, this was not documented, but I figured it out by looking through the code.

Example of disabling packagist.org globally

---

src/Composer/Package/Locker.php
src/Composer/Repository/Vcs/VcsDriver.php
tests/Composer/Test/Repository/Vcs/GitBitbucketDriverTest.php

Dev packages which are installed from source  will produce time in `Y:m:d H:i:s` format according to lines 373-375, 435 in file `composer/src/Composer/Package/Locker.php`.
Other packages will have time formatted by `ArrayDumper` class and will have DATE_RFC3339 format as per line 86.

Lock file package time inconsistency

---

doc/04-schema.md
res/composer-schema.json
src/Composer/Package/Version/VersionGuesser.php
tests/Composer/Test/Package/Version/VersionGuesserTest.php

A negative list of non-feature-branches names
is already supported - this patch adds a list of
branches names which *will* be considered as
feature branches.
Allows changing the currently hardcoded set of
expected feature branch names, from:
* master|trunk|default|develop
To any set of names or patterns that you desire.

Add support for feature-branches setting

---

src/Composer/Cache.php
src/Composer/Command/ClearCacheCommand.php
tests/Composer/Test/CacheTest.php

fixes: #6362
cc/ @barbazul @Seldaek @stof 
Hello! This is my first PR. As directed in issue #6362 I introduced a separate function for clearing the cache and just used `removeDirectory` directly instead of the `gc` command. 
_*Note*_: If `cache-dir` is the root directory of `cache-files-dir`, `cache-repo-dir` and `cache-vcs-dir` than it tries to remove something that is not there -- possible to optimize more?
Let me know if any questions or concerns. thanks.

Cache: clear cache using removeDirectory

---

doc/03-cli.md
doc/06-config.md
res/composer-schema.json
src/Composer/Command/ConfigCommand.php
src/Composer/Config.php
src/Composer/Factory.php
tests/Composer/Test/ConfigTest.php

Fixes Issue #6480.
This pull request adds a `htaccess-protect` option to composer, which makes it possible to disable the creation of `.htaccess` files in the Composer home, data, and cache directories.
The option defaults to `true` in order to preserve the previous behavior for users who do nothing, in case anyone was relying on it (knowingly or unknowingly).
This option can also be overridden by the environment variable `COMPOSER_HTACCESS_PROTECT`.

Add htaccess-protect option for disabling the creation of .htaccess files

---

src/Composer/Downloader/ZipDownloader.php

Warn about identical names with different capitalization on unzip archive
extract failure (Not a directory)
Issue #5938

Warn identical names w/ different capitalization for unzip

---

src/Composer/Repository/Vcs/HgDriver.php

getFileContent generated command like hg cat -r hg cat -r CHANGESET FILE that caused errors "Skipping missing sub" while fetching composer.json files in repositories containing subrepositories.
This fixes that error.

Fix hg command to retrieve file content

---

src/Composer/DependencyResolver/Rule.php

According to type 2nd constructor-argument `$reasonData` can either be a Link or a PackageInterface. IDEs like PhpStorm won't be able to provide autocompletion since both classes are from a different namespace.
In order to provide better autocompletion for `$reasonData` and by extension `$this->reasonData` the use statements should be included or the type hint should use the fully qualified class name.
For the same reason I added the docblock on the protected method `formatePackagesUnique()`.

Improve IDE autocompletion

---

src/Composer/Json/JsonManipulator.php
tests/Composer/Test/Json/JsonManipulatorTest.php

When currently executing the `require` command for a package that is already listed in `require(-dev)`, one must use the exact same, case matching package name as written in `composer.json`. That is, if one changes the case of a character in the package name, the `require` command will add a new entry to `require(-dev)`, instead of updating the existing one:
```json
// Initial composer.json
{
"require": {
"foo/bar": "^1"
}
}
// composer.json after running `composer require fOo/BaR:^2`
{
"require": {
"foo/bar": "^1",
"fOo/BaR": "^2"
}
}
```
This commit fixes the described behaviour to make it consistent with other commands like `update` that are already case insensitive:
```json
// composer.json after running `composer require fOo/BaR:^2` with this PR
{
"require": {
"foo/bar": "^2"
}
}
```

Fix case insensitivity of ‘require’ command

---

doc/05-repositories.md

Clarified and expanded the documentation for private repositories using the BitBucket driver. Emphasized the use of the COMPOSER_AUTH variable to encourage people not to save their credentials in composer.json. Pointed out that git endpoints don't seem to work.

Improve BitBucket driver usage documentation

---

src/Composer/Installer/BinaryInstaller.php

in the sh script, the first cd command did output the directory it cd'ed
into did output the path itself.
fix for me is to redirect it's standard output to /dev/null
using git bash on a windows 10 box.
w/o this fix, the workaround is to invoke the .bat file which is created
as well (but this is not so handy as a non windows user for me).

mute first cd in win proxy stub for sh shell, fixes #6567

---

src/Composer/Repository/Vcs/GitLabDriver.php
tests/Composer/Test/Repository/Vcs/GitLabDriverTest.php

this commit introduced V4 gitlab api -
https://github.com/composer/composer/commit/6832eacb0161ecec4666a7d2456a474e3f8e903d
however the branches/tags endpoints: `http://gitlab.krone.at/api/v4/projects/XXX%2FYYY/repository/branches`
in V4 require to be paginated, where as in v3 it was not, resulting in composer only downloading the first couple of branches -> resulting in wrong version picks.
which was kind a nuklear 💣  on our ci machines deploying stone age  old code to different systems.
(one could say - do not use `--snapshot` in production 😆 )
this PR adds support for pagination!

GitlabDriver V4 Paging

---

src/Composer/Repository/Vcs/FossilDriver.php

Fossil driver was unable to work with urls pointing to a my-repo.fossil files. It only allowed urls to point to local checkout directories. This meant that user had to create checkout directories for all repos referenced in composer.json, even if origin repo fossil file is accessible via local filesystem. This patch attempts to fix this.
The old functionality is still there. Users can still point the fossil url to an open checkout directory. But now, users can also specify local (or network, UNC) file paths in the url.
The logic is as follows:
1. if the url points to a local directory, assume it's a local checkout directory
2. otherwise, the url has to be something that fossil can clone from

Teach FossilDriver to work with local fossil repository files

---

doc/03-cli.md

When you run Composer without args it prints all commands.
However documentation says nothing about some of them.
And note for short names.

Note for aliases

---

src/Composer/Util/Filesystem.php
tests/Composer/Test/Util/FilesystemTest.php

Some packages, e. g. `tm/tooly-composer-script`, are using the composer classes to e. g. create symlinks or perform other file operations. While there's only a `copyThenRemove()` method this commit introduces a new `copy()` method. `copy()` behaves the same as the copy part of `copyThenRemove()` did with one exception: it returns `true` on success and `false` on failure. Copying a directory may lead to a `false`, while the whole directory or some of its files couldn't been copied. To ensure backwards compatibility `copyThenRemove()` calls `copy()` now. This commit also adds the necessary tests.

Introduces a new method `copy()`.

---

.travis.yml

previous code introduced in 4d8b371908 used subshell capture which would be executed, but intended is just to set exit code to 1. probably never noticed because empty command is not executed by current shell.

fix parallel test exit scenario shell syntax

---

doc/articles/scripts.md
src/Composer/Command/ScriptAliasCommand.php
src/Composer/Console/Application.php

Allows you to add custom descriptions for custom scripts which is useful for providing some basic inline documentation.
```json
"extra": {
"scripts-description": {
"test": "Run all tests!"
}
}
```
Each script can have it's own description set in `extra.scripts-description` and it will still show the default if nothing is set.

Allow custom script descriptions.

---

doc/03-cli.md
src/Composer/Util/StreamContextFactory.php
tests/Composer/Test/Util/StreamContextFactoryTest.php

since WINDOWS can only have one case and that is usually upperase
I rely on the all-uppercase settings to get packages from the internet but also get some from our Satis server in the local network. You can have lowercase environment variables on Windows but not both. You can only flip them by unsetting one case before setting the case again (assuming satis.local in global config.json):
```
SET no_proxy=
SET NO_PROXY=satis.local
composer update
SET NO_PROXY=
SET no_proxy=satis.local
composer update
```

also support NO_PROXY

---

src/Composer/Command/DiagnoseCommand.php

For those that manage multiple PHP binaries (and multiple Composer binaries), sometimes we aren't sure which PHP nor Composer is running... specially when running it behind a tool, such an IDE or CI server.
This commit expose some informations that can help us to find and fix errors.

add php version and binary to the dignose command

---

src/Composer/Command/InitCommand.php

Make it clearer that the issue is not necessarily about stability. It simply did not find a matching version, there are different types of reasons this could happen.

Improve the error on init/require if a package could not be found

---

src/Composer/Command/ValidateCommand.php

using
```
COMPOSER=composer_dev.json composer validate
```
you get
```
./composer.json is valid for simple usage with composer but has...
```
but expect
```
./composer_dev.json is valid for simple usage with composer but has...
```

support COMPOSER env var in validate command

---

src/Composer/Autoload/ClassLoader.php

the `foreach` over the `prefixDirsPsr4[$search]` won't affect `$length`. 
It's used for the offset of `$logicalPathPsr4`.

Improve findFileWithExtension PSR-4 code

---

.travis.yml

Add the PHAR file to GitHub releases. Amon other things, it will allow to use the GitHub API to download current and old versions.
Before merging this PR, a maintainer will have to add a `GITHUB_TOKEN` secret environment variable using the Travis UI. This GitHub token must have the `repo` scope.

Deploy PHAR to GitHub releases

---

src/Composer/Repository/FilesystemRepository.php

Just like composer.lock, sort installed.json in order of the package
names. This makes it easier to review diffs when this file is changed.
See discussion on #4410.

Sort vendor/composer/installed.json deterministically

---

tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
tests/Composer/Test/Autoload/ClassMapGeneratorTest.php
tests/Composer/Test/Repository/ArtifactRepositoryTest.php
tests/Composer/Test/Repository/PathRepositoryTest.php
tests/Composer/Test/Util/ConfigValidatorTest.php
tests/Composer/Test/XdebugHandlerTest.php

Continuing to refactored tests, like #6849, using:
- `assertNotEmpty` instead of `empty` method;
- `assertFalse` instead of strict comparisons with `false` keyword;
- `assertSame` instead of strict comparisons;
- `assertContains` instead of `in_array` method;
- `assertStringEqualsFile` when comparing `string` and files.

Refactoring tests

---

doc/05-repositories.md

The current language here implies that the branch name on your remote repo should be named according to a certain pattern (`dev-*`), which isn't accurate. You can name the branch whatever you want, but in composer.json you should _reference_ it as `dev-*`.

Clarified language on branch naming for forks

---

.gitattributes

[Exclude non-essential files in .gitattributes](https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/). This way users of this package don't have to download non-essential files such as the `tests` directory, which is a whopping 4MB.

Exclude non-essential files from dist package

---

doc/articles/scripts.md

Custom commands support the same pattern to pass arbitrary arguments like the "run-script" Composer command.

Document arguments for custom commands

---

doc/articles/troubleshooting.md

There was an extra space lurking that prevented a link from rendering. The space is now removed.

Corrects troubleshooting.md documentation link by removing space

---

src/Composer/Installer/BinaryInstaller.php

Recently fixed in Composer-Setup: https://github.com/composer/windows-setup/blob/master/CHANGELOG.md#v480

Fix shell proxy to allow user-defined cygdrive

---

appveyor.yml

This will at least get PHP installed where we want it, so the tests can run.
Planet Chocolatey is still a wild and random place, so there is no guarantee that this will continue to work. However, their latest PHP package (7.2.0) has made some major improvements in not depending on operating system updates and VC redistributables (that are not needed on appveyor anway and break the install). Prior to this, it had already started to provide a php.ini file (copying php.ini-production and setting the extension_dir). So the evolution has been good.
I've removed setting `date.timezone` as it defaults to UTC anyway. Questions:
-  What is the purpose of installing OpenSSL.Light when php_openssl.dll is enabled?
-  What is the reason for enabling `php_fileinfo.dll`?
If these are not needed, then we …

Fix chocolatey php

---

tests/Composer/Test/Downloader/ZipDownloaderTest.php

This could be done more elegantly using `@requires extension zip`, but perhaps there is a reason for using
`if (!class_exists('ZipArchive'))` ?
It is not used consistently though, because ArtifactRepositoryTest uses `if (!extension_loaded('zip'))`.

Skip MockedZipDownloader tests if zip is missing

---

.php_cs
src/Composer/Util/Perforce.php

Should we add `no_useless_else` based on #6903?

Add no_useless_else in phpcs

---

src/Composer/Downloader/GitDownloader.php
src/Composer/Util/Git.php
tests/Composer/Test/Downloader/GitDownloaderTest.php

when run `composer install`,
required ref already exist at cachePath, we don't need fetch new commit.

Don't fetch when ref already on local

---

src/Composer/Command/CheckPlatformReqsCommand.php

The command must validate that the current package matches the constraint, not that any newer package matches it.
Closes #6925

Fix the platform requirement check command

---

doc/01-basic-usage.md
doc/03-cli.md
doc/04-schema.md

I was reading the documentation and I found a few places where the `code` formatting was missing or superfluous.

[docs] Few typographical fixes

---

src/Composer/Json/JsonManipulator.php
tests/Composer/Test/Json/JsonManipulatorTest.php

Fix: Remove key when value is null

---

res/composer-schema.json

Fix: Add 'sort-packages' to composer-schema.json

---

res/composer-schema.json
src/Composer/Package/Loader/ArrayLoader.php
src/Composer/Package/Loader/ValidatingArrayLoader.php
tests/Composer/Test/Json/Fixtures/composer.json
tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php

Something that I always see in packages, including `Composer`, is an `array` wrapper in a single bin file:
```json
"bin": ["bin/composer"],
```
So, the way we do with our `licenses` key, why not support `array` and `string` in the `bin` key? :nerd_face:

Allow bin key to receive string

---

CHANGELOG.md

ps: don't forget to fix the same typo in [1.5.6](https://github.com/composer/composer/releases/tag/1.5.6) github release.

changelog: fix typo in 1.5.6 entry

---

src/Composer/Autoload/AutoloadGenerator.php
src/Composer/Autoload/ClassLoader.php

This needs an emergency release, as it breaks using legacy class-loader, like the one bundled into phpunit.
ping @Seldaek

Fix BC of generated static map

---

src/Composer/Command/CreateProjectCommand.php

Since I'm doing a lot of "create-project" these days, I noticed that CTRL+C just doesn't work while that command runs.
The culprit is this logic, which is totally broken:
1. ticks apply to the current file/script only, which means they are useless here and signals are just put on a process queue for the full command execution. The correct fix on PHP <7.1 would be to call explicitly `pcntl_signal_dispatch()` at key points everywhere in the code base. No-go, isn't it? So let's restrict this feature to PHP >=7.1, where we can leverage `pcntl_async_signals()`.
2. the `$directory` variable holds a folder that might be relative. But since composer does `chdir()` at other places, this "relative" aspect means `$fs->removeDirectory($directory);` is basically random...
Here is something that works …

Fix CTRL+C handling during create-project

---

src/Composer/Util/RemoteFilesystem.php

Using this new extension point, I'm able to use a shared cURL connection and speed up downloads by a significant margin (depends on round-trip latency).
This is not as efficient as prefetching as done by prestissimo, but on the other side, this plays well with the existing life cycle.

Add RemoteFilesystem::getRemoteContents() extension point

---

src/Composer/Command/DiagnoseCommand.php
src/Composer/Command/InitCommand.php
src/Composer/DependencyResolver/Rule.php
src/Composer/DependencyResolver/Solver.php
src/Composer/Factory.php
src/Composer/Installer/PluginInstaller.php
src/Composer/Json/JsonManipulator.php
src/Composer/Package/Archiver/BaseExcludeFilter.php
src/Composer/Repository/RepositoryInterface.php
tests/Composer/Test/DependencyResolver/RuleSetIteratorTest.php
tests/Composer/Test/Installer/InstallationManagerTest.php
tests/Composer/Test/Mock/RemoteFilesystemMock.php
tests/Composer/Test/Util/PerforceTest.php

Some, not all, fixes found by running [`PHPStan`](https://github.com/phpstan/phpstan) at level 0:
File | Problem
---- | ----
src/Composer/DependencyResolver/Rule.php:56 | Access to an undefined property Composer\DependencyResolver\Rule::$job.
src/Composer/Factory.php:549 | Class Composer\Installer\MetapackageInstaller does not have a constructor and must be instantiated without any parameters.
src/Composer/Command/DiagnoseCommand.php:38 | Property Composer\Command\DiagnoseCommand::$rfs has unknown class Composer\Command\RemoteFileSystem as its type.
src/Composer/Command/InitCommand.php:282 | Anonymous function has an unused use $self.
src/Composer/Repository/RepositoryInterface.php:73 | Return typehint of method Composer\Repository\RepositoryInterface::search() has invalid type array. …

Fixes from PHPStan level 0

---

src/Composer/Command/SelfUpdateCommand.php

Raising a warning if the current user doesn't match the initial ownership of the $home directory. 
Not sure how this works on let's say Windows, might have to add some extra checks for that.
Would love some feedback on how I can improve this PR in order to merge into master.

Fix for issue 6602 - warning when running composer as another user

---

doc/articles/vendor-binaries.md

`project b's` should be `project a's` in the example given

Correct a tiny typo

---

doc/00-intro.md
doc/01-basic-usage.md
doc/03-cli.md
doc/04-schema.md
doc/05-repositories.md
doc/articles/aliases.md
doc/articles/handling-private-packages-with-satis.md
doc/articles/troubleshooting.md
doc/articles/versions.md
doc/faqs/why-are-version-constraints-combining-comparisons-and-wildcards-a-bad-idea.md

The word "just" can often be dropped in writing. 
- https://dev.to/marcuscreo/the-4-letter-word-word-that-makes-my-blood-boil
- https://www.glamour.com/story/why-i-quit-using-the-word-just-in-my-emails
**Edit:** I'd've edited the "Just fork it" at the bottom of the pages as well but it looks like that's part of the website, and isn't in the markdown files here.

Avoid using 'just' in documentation

---

src/Composer/Console/Application.php

For [Humbug Box](https://github.com/humbug/box/blob/master/src/Composer/ComposerOrchestrator.php#L30) we are using Composer to dump the autoload. To do so I'm using the `Composer` class from the application:
```php
$composer = (new ComposerApplication())->getComposer();
```
If you do so however this is going to fail because `Application#io` is `null` instead of being a `IOInterface` instance. Indeed it is initialised only when the application is run. So one solution
is to initialised it with a dummy IO and the right IO object will be set when the application is run
as usual.

Allow Composer to be used without running the application

---

doc/faqs/how-to-install-composer-programmatically.md

Not using quotes could end badly, because shell does not forgive when it comes to quotes.
If https://composer.github.io/installer.sig contains a shell command... well oops.
```bash
EXPECTED_SIGNATURE=foobar ; rm -rf /* # Catastrophic
EXPECTED_SIGNATURE="foobar ; rm -rf /*" # No harm done
```

how-to-install-composer-programmatically.md: quotes are seatbelts

---

src/Composer/Util/RemoteFilesystem.php

Instead of "Undefined variable $http_response_header" when network is off.

Fix RemoteFilesystem::getRemoteContents() on-failure behavior

---

doc/04-schema.md

This change is related to https://github.com/composer/packagist/pull/750
It should also be added to the schema.json but I don't know where it is. Is it stored in this repo or generated? And where is the definition of it?

add readme to support fields in the schema docs

---

.php_cs

This PR
💁‍♂️ Makes it easier to find, and to determine where to add a new rule.

Fix: Keep rules sorted

---

res/composer-schema.json

Fix: Add type field to schema for inline-package

---

src/Composer/Command/StatusCommand.php
src/Composer/Downloader/ArchiveDownloader.php
src/Composer/Downloader/DownloaderInterface.php
src/Composer/Downloader/FileDownloader.php
src/Composer/Package/Comparer/Comparer.php

Added LocalChanges detector for ArchiveFiles, it is necesary for the command "composer status" for when you need to check if you have changed any dependency. 
Currently only checks Git, so the status says that they have not changed packages that have done so. With this we complete that process of truth with zip packages.
This PR comes from https://github.com/composer/composer/pull/7095 without CS fixes

LocalChanges for ArchiveFiles

---

src/Composer/Command/ShowCommand.php

The ShowCommand was taking all packages into account when determining the max lengths used to display the width of each column. This was causing unnecessary hiding of columns in case of using a longer name or a longer version in a different package.
This was especially visible when using the outdated command, as it applies filtering by default.
Closes #7153

Take only displayed packages into account to determine column width

---

src/Composer/Downloader/FileDownloader.php
src/Composer/Downloader/VcsDownloader.php
tests/Composer/Test/Downloader/FileDownloaderTest.php
tests/Composer/Test/Downloader/GitDownloaderTest.php

Add logic for choosing correct word for the action performed on a package (update/downgrade). 
Related to #7085.
Should work with both packages that use tags and those which does not

Wording:Use Downgrading instead of Updating

---

doc/faqs/how-to-install-composer-programmatically.md

This improves grammar and uses official casing for UNIX and GitHub.

Improve grammar in the programmatic Composer installation page

---

bin/composer

Fixes https://github.com/symfony/flex/issues/362
Forces case insensitive operations and lowercasing to consider `I` <=> `i`, ignoring the dot-less Turkish "i".

Force "C" locale to prevent issue with Turkish "I"

---

src/Composer/Autoload/AutoloadGenerator.php
tests/Composer/Test/Autoload/AutoloadGeneratorTest.php

Strips entries from packageMap that are not included by recursion of Package->getRequires()
Testcases have been adjusted to prevent false positives

Filter dev-dependencies from "dump-autoload --no-dev" , fixes #4343

---

README.md
composer.json
composer.lock
src/Composer/Compiler.php
src/Composer/IO/ConsoleIO.php

Instead of using a custom package, use symfony/console
functionality, which is already a requirement to composer
Composer command: `composer remove seld/cli-prompt`
Fixes: #7337

Use symfony/console for hidden questions

---

src/Composer/Util/Git.php

Hi,
I am trying to run composer (well, satis to be precise) from a process that has no tty attached. Obviously, the underlying git process fails to get user input for username & password, but the error message was not taken into account by composer in the `isAuthenticationFailure` method of `Composer\Util\Git` class.
You can get this Git error message when trying the following command:
`setsid sh -c 'git clone http://private/repo/url' < /dev/null`
You will get something like the following:
`fatal: could not read Username for 'http://private/repo/url': No such device or address`
Setting `GIT_ASKPASS=echo` or `true` has no impact on this behavior.
Such error did not trigger the authentication mechanism, with this PR it does.
Thank you for your awesome work on composer! Best regards.

Fix Git detection of authentication failure when no tty is attached to the process

---

src/Composer/DependencyResolver/Solver.php

Currently, when you debug using `-vvv`, with rather complex dependencies, your CLI output is stuck at `Resolving dependencies through SAT` for 20+ seconds and you don't know if Composer is still doing anything or it crashed, so I tried to improve this.
Before it just prompts after 22 seconds:
After:

Improve SAT resolving developer debug information

---

.php_cs

This option had been removed in v2.0, linter is enabled and can't be disabled. Don't worry - under PHP 7 it has no performance impact

DX: .php_cs - drop commented option of v1

---

doc/05-repositories.md

In the current context (the paragraph above relating to auth.json), the sample given would be incorrect as it references a `config` node which is for [root only](https://getcomposer.org/doc/04-schema.md#config).

Update example for auth.json in BitBucket config

---

README.md

This PR
Follows #4019.
💁‍♂️ It's been shut down a while ago. For reference, also see https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/.

Fix: Remove VersionEye badges

---

src/Composer/DependencyResolver/RuleSetGenerator.php

this reduces number of unnecessary function calls in the hot path of "composer update".
in my case this reduces "composer update" walltime (~45s) by 750ms .

Temporary save the package-name into a variable

---

src/Composer/DependencyResolver/Solver.php

`runSat` is at the hot path, every fn call saved counts.
https://github.com/composer/composer/blob/master/src/Composer/DependencyResolver/Decisions.php Calls abs() on the given arguments again, so no need to call it before calling methods on Decisions objects.

Remove unnecessary abs() calls

---

src/Composer/DependencyResolver/Rule2Literals.php

optimize Rule2Literal for a common case of the hot-path.
Reduces walltime by ~1.1 seconds on our typical workload:
https://blackfire.io/profiles/compare/5e2c1260-9186-4ad6-aef9-fd524ce46094/graph
the actual speedup seems to happen because we need 23% less calls to `$rule->getLiterals()`
(+ the calling overhead + saving ~100.000 calls to `count`)

Specialize Rule2Literal->equals(Rule2Literal) for speedup

---

src/Composer/DependencyResolver/Rule2Literals.php

this speeds up "composer update" by a second.
as discussed in https://github.com/composer/composer/issues/7449 lets use a simpler hashing to speedup the hot path.

Use a simpler hashing for the Rule2Literal case

---

src/Composer/DependencyResolver/RuleWatchNode.php

`count()` is called hundred thousands of times. using a single variable in this single spot (most calling code-site) reduced it by ~130.000x even in a small project.

Use variable to call count() less often

---

src/Composer/Repository/PathRepository.php

In the Composer document, it is stated that glob can be used, but only some functions can be used.
All functions are unnecessary, but I would like to use ``GLOB_BRACE``.
- [Repositories - Composer](https://getcomposer.org/doc/05-repositories.md#path "Repositories - Composer")
- [PHP: glob - Manual](http://php.net/manual/ja/function.glob.php "PHP: glob - Manual")
Since now ``GLOB_BRACE`` can not be used, it will be written as follows.
```
{
"repositories": [{
"type": "path",
"url": "$HOME/Scripts/composer",
} {,
"type": "path",
"url": "$HOME/Scripts/php-test",
}, {
"type": "path",
"url": "$HOME/Scripts/php-unit",
}]
}
```
If you can use ``GLOB_BRACE`` you can write more easily
```
{
"repositories": [{
"type": "path",
"url": "$HOME/Scripts/{composer,php-*}"
}]
}
```

Add repositories path glob

---

src/Composer/Downloader/HgDownloader.php
src/Composer/Repository/Vcs/HgDriver.php
src/Composer/Util/Hg.php

This PR aim to resolve the issue #7463.
I've added a `Composer\Util\Hg` class similar to the `Composer\Util\Git` class. The purpose of this class is to add the credentials (username and password) at the beginning of the mercurial's URL to allow authentication with the `auth.json` file.
An URL like `https://my-domain.com/my-repo` will be transformed to `https://my-username:my-password@my-domain.com/my-repo` if authentication is required.
The `Composer\Util\Hg` class works in the same way as the `Composer\Util\Git`, providing a `runCommand` method that handle the potential URL modification.

Add support for authentication with mercurial repositories.

---

doc/03-cli.md
src/Composer/Command/InstallCommand.php
src/Composer/Command/UpdateCommand.php

In npm I really like this shorthand `npm i`
So thought it may also be convenient in composer

Add `composer i` shorthand for `composer install`

---

src/Composer/Cache.php

before this change the whitelist-replacement was invoked, even when the variable wasn't used.

prevent preg_replace() calls when cache is not enabled

---

doc/01-basic-usage.md

I'm aware this just an example, but it [leads readers to see it a best practise](https://github.com/Automattic/phpcs-neutron-standard/commit/40642df5ec9ea39871f1b99ada7fa34976169788#r29802440).
Having code with `"php": ">=5.4.0"` is pretty dangerous and will probably break with next major version. Such usage is nowhere to be seen apart docs and just a handful of php packages.
On the other hand: 
```json
{
"require": {
"php": "^5.4"
}
}
```
or
```json
{
"require": {
"php": "^7.1"
}
}
```
is much more safer. Promoting best and proven practise should from *Basic usage* helps people to use composer the best way they can.
What do you think?

[docs] basic usage - promote safe version range

---

src/Composer/Package/Dumper/ArrayDumper.php
tests/Composer/Test/Package/Dumper/ArrayDumperTest.php

I stumbled upon composer/satis#439, did some tests and it looks like nothing breaks when removing `source` and `dist`. Anything else that this could go wrong?

Do not dump source and dist for metapackages

---

src/Composer/Repository/Vcs/GitHubDriver.php

Returning null inside the catch doesn't have a meaning since it makes not found retry thing useless. Either not found retry or return null should be removed.

Remove github API request retries as it is not needed anymore

---

appveyor.yml

Fixes command options to be able to use the latest Chocolately PHP versions, and use separate folders in the cache:
```
C:\tools
- phpci       (the cache folder)
- php
- composer
- cache
- home

Improve Appveyor caching and update PHP

---

src/Composer/Command/AboutCommand.php

Such as the concept that is showed on the page [introduction](https://getcomposer.org/doc/00-intro.md).
>Composer is not a package manager in the same sense as Yum or Apt are. Yes, it deals with "packages" or libraries, but it manages them on a per-project basis, installing them in a directory (e.g. vendor) inside your project. By default it does not install anything globally. Thus, it is a dependency manager. It does however support a "global" project for convenience via the global command
I think it's better to unify the Composer concept.
"Composer is a dependency manager or dependency management".

Unify Composer concept

---

src/Composer/Repository/RepositoryInterface.php

This seems to be implemented by all repositories, but not part of any interface. Since both the `Installer` and `CompositeRepository` depend on it, it should probably be a part of the interface.

add removePackage() to RepositoryInterface

---

src/Composer/Command/CheckPlatformReqsCommand.php

This pull request covers https://github.com/composer/composer/issues/7314 issue.
It adds "--no-dev" option to "check-platform-reqs" command.
To do this it changes "check-platform-reqs" logic. Previous logic considered `installed.json` file to check platform reqs. Current logic considers `composer.lock` to perform such check.
Logic has been changed, because currently there is no easy way to check whether requirement is `required-dev` or not with `installed.json` file. On other hand, it's really easy to do with `composer.lock`.
`installed.json` file should be related to `composer.lock`, so there is no big deal at that point.
On dev machines, both of files (`installed.json` and `composer.lock`) exist.
On prod (which may not contain `composer.lock`) such commands should not be executed (like …

Add --no-dev option to check-platform-reqs command (#7314)

---

src/Composer/DependencyResolver/Pool.php
src/Composer/DependencyResolver/PoolBuilder.php
src/Composer/Repository/ComposerRepository.php
tests/Composer/Test/DependencyResolver/RuleSetTest.php
tests/Composer/Test/DependencyResolver/RuleTest.php

Ids all get set in one place only and at a specific time when nothing else will possibly change them anymore.
Improves https://github.com/composer/composer/pull/7625

Generate Package Ids in pool only once all packages are defined

---

src/Composer/Repository/Vcs/BitbucketDriver.php

Calling the `getChangeDate` method in the `BitbucketDriver` with an identifier containing a slash always throws an error
See: https://api.bitbucket.org/2.0/repositories/pcomtest/a1/commit/t/test?fields=date
This works fine for branches without slash or if you directly use the commit hash, see:
https://api.bitbucket.org/2.0/repositories/pcomtest/a1/commit/test?fields=date
https://api.bitbucket.org/2.0/repositories/pcomtest/a1/commit/a55e5e623678907fbd63f63ce37b873f57eec7b1?fields=date
Encoding the identifier doesn't help.
Note: this is only an issue while using the VcsRepositories directly outside of a regular composer install or update. For instance to check if a vcs repository contains a composer file.

Fix: Bitbucket getChangeDate throws exception for branches containing a slash

---

src/Composer/DependencyResolver/Pool.php
src/Composer/DependencyResolver/RuleSetGenerator.php

Part of https://github.com/composer/composer/issues/7630

Remove pool whitelist

---

src/Composer/Command/SelfUpdateCommand.php

This pull request ports the fix from the installer script, see here https://github.com/composer/getcomposer.org/pull/128, to the composer self-update command, where the same bug is present.

Use a case insenstive method to check that SHA384 is a supported openssl algorithm

---

.travis.yml

Actually not 100% sure this is correct, but I feel the php version used for deployment should be the latest stable

Updated deploy php version to 7.2

---

src/Composer/Repository/VcsRepository.php

Requiring a VcsRepository that has tags where the composer.json is missing the name attribute in certain tags results in PHP notices.
This is the error message if I force throwing exceptions on notices
`Notice: Undefined index: name {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: name at /path/to/vendor/composer/composer/src/Composer/Repository/VcsRepository.php:201)

Fix: undefined index name in VcsRepository

---

src/Composer/Repository/VcsRepository.php

Requiring a VcsRepository that doesn't have a composer.json in the rootIdentifier branch and that has tags and/or branches where the composer.json is missing the name attribute results in PHP notices.
`$this->packageName` is `null` if there is no composer.json in the rootIdentifier branch.
`Notice: Undefined index: name {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: name at /path/to/vendor/composer/composer/src/Composer/Repository/VcsRepository.php:298`

VcsRepository: fix undefined index notice in preProcess

---

src/Composer/Factory.php
tests/Composer/Test/FactoryTest.php

There's a similar PR #7750 which I overlook, but it has no test coverage.

Ensure that a missing SSL/TLS protection warning does not pollute STDOUT

---

src/Composer/Repository/Vcs/BitbucketDriver.php
tests/Composer/Test/Repository/Vcs/GitBitbucketDriverTest.php

Bitbucket 1.0 API is deprecated and will be removed on Dec 31 this year. 
See: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/
Here are response samples of the new API endpoints:
To fetch the main branch data (note the change in the response structure): https://api.bitbucket.org/2.0/repositories/gentlero/bitbucket-api?fields=mainbranch
vs https://api.bitbucket.org/1.0/repositories/gentlero/bitbucket-api/main-branch
To fetch a file: https://api.bitbucket.org/2.0/repositories/gentlero/bitbucket-api/src/master/composer.json

Bitbucket: switch to v2 API

---

src/Composer/Repository/VcsRepository.php
src/Composer/Repository/VersionCacheInterface.php

Having such a mechanism would allow us to reuse existing/available data to run updates. For instance on packagist.org we can use the existing version data from the database and skip processing versions which are already stored. This should improve the time for a full update especially for repositories with lots of tags and branches.

Vcs Repository: add option to cache/reuse entire versions

---

src/Composer/Console/Application.php

Core commands can be run from child directories and will look for the first composer.json in the parent folders. However, plugin commands get kicked with a `Symfony\Component\Console\Exception\CommandNotFoundException` before that/before plugins are actually known.
This changes it so that that does work.

Allow plugin commands to be run from child folders like core commands

---

doc/03-cli.md

In `*nix`, the star needs to be part of the content, not of the markdown markup, and so it requires escaping.

Fix the doc markup

---

src/Composer/Autoload/ClassLoader.php
src/Composer/Command/DiagnoseCommand.php
src/Composer/Compiler.php
src/Composer/Util/ErrorHandler.php
src/Composer/Util/RemoteFilesystem.php

Currently setting `false` or `off`, ... value to configure some PHP ini directives will make this evaluated to true as this is equal to a non empty string.

Fix ini_get() for boolean values

---

src/Composer/Command/OutdatedCommand.php
src/Composer/Command/ShowCommand.php

This PR adds `--ignore` / `-i` option to the `outdated` command so when invoking with `--strict` mode user can provide array of packages that should be ignored.
Fixes #7656 (automatic checks in GitLab pipelines with `allow_failure` flag).

Support for ignoring packages in `outdated` command

---

bin/composer
src/Composer/EventDispatcher/EventDispatcher.php
src/Composer/Util/StreamContextFactory.php

In order to run PHPUnit, it's very handy to add a section like this in composer.json:
```json
{
"require-dev": {
"phpunit/phpunit": "whatever"
},
"scripts": {
"test": "phpunit"
}
}
```
so that we can invoke PHPUnit simply by running
```sh
composer run-script test
```
This is currently working great.
We have one problem though: when we want to collect code coverage (`composer run-script test -- --coverage-clover=coverage.xml`), we can use xdebug or phpdbg.
Using xdebug works fine.
BTW using phpdbg doesn't work, since `PhpExecutableFinder::find()` returns `'/usr/bin/phpdbg -rrq'` (note the extra argument), and composer calls `ProcessExecutor::escape()` on it, so we'll try to execute the command `/usr/bin/phpdbg -qrr`, which does not exist (what exists is `/usr/bin/phpdbg`).
So, let's just …

Add support for running composer with phpdbg

---

doc/articles/scripts.md
src/Composer/EventDispatcher/EventDispatcher.php
tests/Composer/Test/EventDispatcher/EventDispatcherTest.php

This PR adds a way to call Composer scripts with params, as described in #7562. Thus, it allows to do this:
```json
{
"scripts": {
"test": "phpunit",
"testVerbose": "@test -vvv"
}
}
```
Calling `testVerbose` will resolve as `phpunit -vvv`.
This PR also adds some docs about this new feature.

Call a script recursively with extra parameters

---

src/Composer/Repository/PlatformRepository.php

Most of the imagick pecl extension functionality cames from underlying ImageMagick library version: http://php.net/manual/en/imagick.constants.php (see descriptions like `This constant is available if Imagick has been compiled against ImageMagick version 6.4.0 or higher.`)
```
$ composer.phar show -p|grep -i imagick
ext-imagick          3.4.3     The imagick PHP extension
```
```
$ ./bin/composer show -p|grep imagick
ext-imagick          3.4.3     The imagick PHP extension
lib-imagick          7.0.8.14  The imagick PHP library
```
Sadly there's no constant in the extension, so the version information is extracted from extension info, like `intl` extension.
There's two versions available, version from compile time and from runtime. Wasn't sure which one to pick, so I choose runtime …

add lib-imagick to composer show -p output

---

src/Composer/Command/InitCommand.php

When the `init` command is run in interactive mode, the dev will be asked if they wish to install dependencies straightaway (only if they specified any dependencies). It's a minor improvement that makes life a tad easier. 😀

Add interactive option to install dependencies after running init command

---

doc/04-schema.md
src/Composer/Package/Loader/ValidatingArrayLoader.php
tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php

- update schema documents to note that chat is allowed,
- validate that chat must be a string and a url similar to forum options
Is there anything else that should be changed? As far as I can see most chat options like slack and discord take a url to register users.

composer/composer#7384: add chat to support options

---

src/Composer/Command/RemoveCommand.php

Make the remove command do a lookup for package name
- if you have multiple vendor modules installed you should be able to do composer remove vendor/* to remove all
- update remove and also remove from alternative type to also do a preg_grep for what the user has inputed
Fixes #7159

composer/composer#7159: make the remove command do a lookup

---

src/Composer/Repository/PlatformRepository.php

This PR is an alternative to https://github.com/composer/composer/commit/489e0d4b124905a26310c9026d83eb82eb0e57ce (which introduced another bug).
See #7762:
> This regex is not correct and breaks Composer with PHP Imagick < `3.3.0`:
> * Before `3.3.0`:
> ```C
> php_info_print_table_row(2, "ImageMagick version", MagickGetVersion(&version_number));
> ```
> * Since `3.3.0`:
> ```C
> php_info_print_table_row(2, "Imagick using ImageMagick library version", MagickGetVersion(&version_number));
> ```

Fix support for imagemagick <3.3

---

src/Composer/DependencyResolver/Pool.php
src/Composer/DependencyResolver/PoolBuilder.php

This still loads all package metadata by name but it collects all constraints for all names as it loads data. It then tries to prune all versions away which do not match a single constraint used for that package name, before the pool is created and before the solver creates rules.
Results:
Composer: 8MB peak saved, 14% rule reduction, 12% package object count reduction
Sylius: 22MB peak saved, 2.4% rule reduction, 14% package object count reduction
Applying this pruning to aliased packages seems unnecessarily complex for hardly any benefit that I could measure, so I may want to remove that part from this PR.
Alternatively we could still try to prune versions as part of data loading already. The only downside is that it's possible that a versions already pruned for a package may be needed …

PoolBuilder:  prune impossible versions before pool creation

---

src/Composer/Json/JsonFile.php

Normally, there should be no side effects.
Unit tests work identically.
The goal is to allow the JsonFile class to be more easily used by any composer plugin.

Allows the JsonFile class to be used for other json files than composer.json

---

src/Composer/Config.php
src/Composer/Factory.php

htaccess-protect doesn't work in global config because the option is checked before the config is read.
This also fixes the parsing for htaccess-protect. It's parsed as a string but should be parsed as a bool.

Fix htaccess-protect problems

---

doc/03-cli.md

This PR
💁‍♂️ Probably not so nice to review, but unless there are reasons for the environment variables *not* to be sorted I am unaware of, I think there are no reasons not to sort them.

Fix: Keep environment variables sorted by name

---

.travis.yml

Fix: Consistently indent with 2 spaces

---

.travis.yml

This PR
See https://travis-ci.org/composer/composer/builds/474430201:
See https://travis-ci.org/composer/composer/builds/474433629:

Enhancement: Explicitly configure build matrix to maintain order

---

src/Composer/Package/Archiver/ArchiveManager.php

Composer will not cleanup the temporary directory created in case the archive manager throws an exception while downloading a version from a git repository e.g.
```
Failed to execute git checkout '18313f04cea0e078412a028c5361bd4e' -- && git reset --hard '18313f04cea0e078412a028c5361bd4e' --
fatal: invalid reference: 18313f04cea0e078412a028c5361bd4e
```
This starts consuming quite a lot of disk space if this happens while trying to install a 200MB repo like wordpress several times.

Archive: cleanup temp dir on download error

---

src/Composer/Command/RunScriptCommand.php

The `run` command looks like more pretty than `run-script` but it's still meaningful. Let me add an alias for the "run-script" command.
```bash
composer run post-root-package-install # instead of "composer run-script post-root-package-install"
composer run test # instead of "composer run-script test"
```

Add alias of run-script command

---

src/Composer/Console/Application.php

Currently, the Composer console Application relies on the default helper set of the Symfony Console Component. However, only one is used internally (the Question one).
I think it would be better to require it directly like this.
It is also better for the `BuffferIO` class (cf my next PR https://github.com/composer/composer/pull/7868)

fix(application): use precise helper set

---

src/Composer/IO/BufferIO.php

Without the `QuestionHelper`, it is impossible to use the `BufferIO` class when your Composer command has an interactive question.
```
Symfony\Component\Console\Exception\InvalidArgumentException: The helper "question" is not defined.
```

feat(buffer-io): add question helper to helper set

---

src/Composer/IO/BufferIO.php
tests/Composer/Test/IO/BufferIOTest.php

This feature makes it possible to easily use the `BufferIO` class to test a Composer command that have interactions.
I did it in a non BC way but I would to work on a new version of this class for the v2.
Inspired by the Symfony `CommandTester` class.
Needs https://github.com/composer/composer/pull/7868.

feat(buffer-io): add the possibility to set user inputs for interactive questions

---

src/Composer/Config/JsonConfigSource.php

Fix: Remove empty node

---

doc/faqs/how-to-install-composer-programmatically.md

Installer that is listed in the documentation is affected by #7776.
The newest copy is no longer affected but have updated the link in the docs to prevent people trying to install a broken version.

Update installer commit to fix SHA384 bug

---

src/Composer/Repository/RepositoryFactory.php

When a full 'composer' cannot be constructed (because there is no local composer.json and no global composer.json), some commands (e.g. `show -a`) fall back to the default repositories from the `$COMPOSER_HOME/config.json` file. Without this fix, any auth configuration from `$COMPOSER_HOME/auth.json` is not used for these repositories in such a fallback scenario.
Steps to reproduce:
* Configure a password-protected composer repository in `$COMPOSER_HOME/config.json`.
* Configure valid credentials for that repository in `$COMPOSER_HOME/auth.json`.
* Make sure there is no file `$COMPOSER_HOME/composer.json`.
* Ensure the current working directory has no `composer.json`.
* Run `composer show -a some/package`.
Expected: Information about `some/package` is shown without needing to enter …

Fix defaultRepos fallback does not use auth config

---

src/Composer/DependencyResolver/Decisions.php
src/Composer/DependencyResolver/Solver.php
tests/Composer/Test/DependencyResolver/SolverTest.php
tests/Composer/Test/Fixtures/installer/update-requiring-decision-reverts-and-learning-positive-literals.test

This 5 character fix comes with a solver test as well as a functional installer test essentially verifying the same thing. The solver test is more useful when working on the solver. But the functional test is less
likely to be accidentally modified incorrectly during refactoring, as every single package, version and link in the rather complex test scenario is essential, and a modified version of the test may very well still result in a successful installation but no longer verify the bug described below.
In commit https://github.com/composer/composer/commit/451bab1c2cd58e05af6e21639b829408ad023463#diff-57acde011ed9b5a18bb373af9d616bf1L554 from May 19, 2012 I refactored literals from complex objects into pure integers to reduce memory consumption. The absolute value of an integer literal …

Fix solver problem exceptions with unexpected contradictory "Conclusions"

---

src/Composer/DependencyResolver/Problem.php
src/Composer/DependencyResolver/Rule.php
src/Composer/Repository/PlatformRepository.php
tests/Composer/Test/Repository/PlatformRepositoryTest.php

hhvm-nightly (and the next release) are no longer able to execute
Composer. Support executing Composer with PHP to install dependencies
for hack projects.
The goal is for this to be temporary, until Hack identifies a new
package manager, given that Composer does not aim to be a multi-language
package manager.
fixes #7734

Support identifying the HHVM version when not running with HHVM

---

src/Composer/Installer/BinaryInstaller.php

The `[[` keyword is not compatible with all shells that `/bin/sh` can represent. This non-portablity is a problem when calling Composer, or stuff installed by Composer, from Ubuntu on WSL. 
See: https://github.com/composer/windows-setup/pull/90

Make unixy proxy code POSIX compatible

---

src/Composer/Util/Filesystem.php

This implements the POSIX `S_ISDIR` macro to determine if the `st_mode` value (returned by the stat functions) is a directory.
Unfortunately it doesn't always fix failing junction tests on PHP 7.3 (and some versions of PHP 7.2), but at least we've got one source of error out of the picture.
@curry684 Could do with your blessing here! Or at least a quick look.

Fix mode bitmask when detecting a Windows junction

---

src/Composer/Util/Filesystem.php

PHP will happily remove junctions using its `rmdir` function (tested on versions back to 5.2.17). This saves invoking system `rmdir` through cmd.exe.
Note this is just a tweak (it is not crucial and is separate from the previous buggy junction issue).

Remove junctions with PHP rather than system rmdir

---

src/Composer/Downloader/PathDownloader.php
src/Composer/Util/Filesystem.php

I'm probably jumping the gun a bit here since the PHP bug fixes haven't been released yet (they are merged now), but otherwise I'll have forgotten all about this in a month.

Only use junctions if they can be safely removed

---

doc/05-repositories.md

Adds an explanation of junctions and their edge-case limitations.

Explain Windows junctions in 05-repositories.md

---

src/Composer/Downloader/PathDownloader.php

Please check this logic. To recap:
- we need `proc_open` to call mklink to create a junction.
- we need `proc_open` available so the system rmdir is used on a package removal (rather than the fallback `Filesystem::removeDirectoryPhp`) in case a junction is not recognized due to the PHP bug.
- we need to be running on Windows 7 or up, so the system rmdir doesn't delete target content if given a junction.
- the PHP versions with the bug fix use the `Visual C++ Redistributable for Visual Studio 2017` which require a minimum of Windows 7 Sp1.

Improve safe junction logic

---

src/Composer/Cache.php

Using composer with docker it can be useful to put the cache in its own data volume.
Doing this will result in problems clearing the cache because composer relies on removing the cache-root directory.
Therefore I want to suggest using emptyDirectory instead of removeDirectory here.

using emptyDirectory instead of remove for clearing the cache

---

src/Composer/Util/Filesystem.php

Made isAbsolutePath recognize Windows UNC-style absolute paths starting with \\

Fix for UNC Windows paths

---

doc/articles/versions.md

I assume the original author meant to type `another-feature` after `my-feature`.  This PR updates that.

Updates typo: nother-feature to another-feature

---

src/Composer/Package/Loader/ValidatingArrayLoader.php
tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php

As reported in #8004 the validate command should return a non zero exit code when using `--strict` mode.
Fixes #8004
#OpenSourceFriday

Return non zero exit code on deprecation

---

src/Composer/Config.php

This came about because Sculpin's blog skeleton was recently changed to use Composer to manage long running processes like `yarn encore --watch` and `sculpin generate --watch`. Shortly thereafter, it was observed that this triggered the 5 minute default Composer timeout.
It seemed unwise to set the entire Composer configuration to unlimited timeouts, and I felt that this narrower approach was potentially worthy of being included in Composer itself.
The helper can be included in custom script definitions by calling
`"Composer\\Config::disableProcessTimeout"`.
Example:
```json
{
"scripts": {
"watch": [
"Composer\\Config::disableProcessTimeout",
"vendor/bin/sculpin generate --watch --server"
]
}
}
```

Add a helper to disable process timeouts

---

doc/06-config.md
doc/articles/scripts.md

This change modifies the `06-config.md` section and the `scripts` article to provide information about the new `Composer\\Config::disableProcessTimeout` helper added in #8088.
It also adds some extra information about process timeouts in general, and is careful to preface the disable-timeout helper documentation with a note that Composer isn't exactly intended for that use case.

Add documentation for Composer\\Config::disableProcessTimeout

---

doc/articles/scripts.md

Mentioning and giving an example of the usage of the 4 options to disable the default script timeout of 300 seconds:
1. Static helper (already exists and kept).
2. Config key "process-timeout".
3. Environment variable "COMPOSER_PROCESS_TIMEOUT".
4. The "--timeout" parameter.

Document the alternatives to disable the default script timeout

---

composer.lock

The only update is to add environment changes to `$_ENV`, but only if it is being used.

Update xdebug-handler to 1.3.3

---

src/Composer/Repository/ComposerRepository.php
tests/Composer/Test/Repository/ComposerRepositoryTest.php

Continuation of #8115 which i messed up with a force push.
Changes since then:
- fix the pattern reference issue by ditching `preg_replace()` for `preg_match()`
- add relevant tests (remove an irrelevant one)
Sorry for the inconvenience :blush:

Fix URL resolution for Composer repositories

---

src/Composer/Command/SelfUpdateCommand.php

This is useful if Composer is provided on a read-only filesystems, to allow self-update to work with a different destination. This assumes composer is available on the PATH and running composer self-update then results with correct use of the environment variable in the updated version written to a preferred directory on the PATH, so that subsequent invocations of composer on the PATH will now use the newer version.
You can see here how this is supposed to work. The PATH includes a writable and a read-only directory. The self-update fails if you execute it from the read-only directory, but it works with the target environment variable. Afterwards the composer.phat on the PATH has been updated, but the file in the read-only directory remains unchanged.
```
naderman@saumur:~/read-only$ echo …
```

Allow overriding self-update target file with env var COMPOSER_SELF_UPDATE_TARGET

---

doc/articles/plugins.md
doc/articles/scripts.md

By trial, I figured out that also plugins can be run manually. Would be nice if documentation would show that as well.

Add documentation how to run plugins manually

---

src/Composer/Autoload/AutoloadGenerator.php
src/Composer/Plugin/PluginManager.php
src/Composer/Util/PackageSorter.php

A second shot at fixing #8065, and follow-up to #8070
Should be pretty self-explanatory. `$packages` was previously sorted non-deterministically depending on the context in which Composer was run (sometimes alphabetically, sometimes according to dependency weight). This ensures that plugins are always loaded according to dependency weight.

Fixes #8065: Sort plugins deterministically before loading.

---

src/Composer/Installer.php

The `$solver` variable in the `Installer::doInstall()` method holds a pretty big object.
Keeping this object around is not needed once dependencies are solved.
In my use case, this reduces the peak memory from 1.3GB to 1.0GB.
Not bad :)
Discovered while working on https://github.com/symfony/flex/pull/520

Free $solver asap

---

src/Composer/Util/ProcessExecutor.php
tests/Composer/Test/Util/ProcessExecutorTest.php

Using composer with svn repositories with debug mode enabled will output the full credentials like shown in the example below:
```
Executing command (CWD): svn info --non-interactive 'https://svn.example.org/svn/glaubinix' []
Executing command (CWD): svn ls --verbose --non-interactive  --username 'glaubinix' --password 'my-actual-password'  'https://svn.example.org/svn/glaubinix/trunk' []
Executing command (CWD): svn ls --verbose --non-interactive  --username 'glaubinix' --password 'my-actual-password'  'https://svn.example.org/svn/glaubinix/branches' []
...
```

SVN: hide passwords for debug output

---

src/Composer/Util/ErrorHandler.php
src/Composer/Util/RemoteFilesystem.php

Hi, 
Small patch to fix error handler function return type. 
From php.net documentation, the error_handler should return a bool and not a void (https://www.php.net/manual/en/function.set-error-handler.php).

Fix error_handler return type declaration

---

.travis.yml
src/Composer/Installer.php
src/Composer/Repository/FilesystemRepository.php
src/Composer/Repository/WritableArrayRepository.php
src/Composer/Repository/WritableRepositoryInterface.php
tests/Composer/Test/Mock/InstalledFilesystemRepositoryMock.php
tests/Composer/Test/Repository/FilesystemRepositoryTest.php

This introduces a BC break in installed.json as the packages are now nested in a "packages" key, but it also brings it in line with the composer.lock format which isn't bad, and opens up for further improvements later. Any thoughts @gossi as you requested the feature?
Fixed #3008

Store dev mode in installed.json, fixes #3008

---

src/Composer/Util/RemoteFilesystem.php

If you rename a private repository on GitHub which has been added as VCS repository the redirect url will contain the access token as GET parameter which will then be displayed in the log output.
```
Downloading https://api.github.com/repos/pcom-test-group/test-repo [] 
[]
Following redirect (2) https://api.github.com/repositories/82816341?access_token=my-github-token []
Downloading https://api.github.com/repositories/82816341?access_token=my-github-token []
```
Note: this is not an issue for GitLab because GitLab keeps the url the same even if you rename a project.

GitHub: don't display access token in debug log on redirect

---

src/Composer/Console/Application.php

As described in GH-8289, if no `composer.json` file is found in the current
directory, the user is prompted if she wants to use another `composer.json` file
from a parent directory even if the `COMPOSER_NO_INTERACTION` environment
variable is set.  This is fixed here by just moving the check of the environment
variable up in the code so that it is evaluated before the user is prompted.

Respect COMPOSER_NO_INTERATION for search prompt.

---

src/Composer/Repository/PathRepository.php

Fixes a problem with path based repositories such as:
```
{
"type": "path",
"url": "../otherproject/"
}
],
"require": {
"vendorname/otherproject": "dev-master"
},
```
on PHP7.4beta4 (at least on Windows) where an attempt is made to access null as an array causing an error exception to be raised:
```
[ErrorException]
Trying to access array offset on value of type null
Exception trace:
() at E:\Projects\composer\src\Composer\Repository\PathRepository.php:158
Composer\Util\ErrorHandler::handle() at E:\Projects\composer\src\Composer\Repository\PathRepository.php:158
Composer\Repository\PathRepository->initialize() at E:\Projects\composer\src\Composer\Repository\ArrayRepository.php:185
Composer\Repository\ArrayRepository->getPackages() at …
```

Fixes a problem with path based repositories on PHP7.4 

---

src/Composer/Repository/Vcs/GitHubDriver.php

Fixes https://github.com/composer/composer/issues/8309.
Credit to @stof for pointing me to the regexes that needed tweaking.

Allow for leading slash in path part of GitHub URLs

---

src/Composer/Command/InitCommand.php
src/Composer/Command/RequireCommand.php

See #8303.
Unfortunately, I didn't find tests for `require` command.
```bash
$ php bin/composer require symfony/http-client-contracts --ignore-platform-reqs 
Using version ^1.1 for symfony/http-client-contracts
```
... with `--fixed`:
```bash
$ php bin/composer require symfony/http-client-contracts --ignore-platform-reqs --fixed
Using version v1.1.6 for symfony/http-client-contracts
```

Provide `--fixed` option for the `require` command, fixes #8303

---

src/Composer/Command/AboutCommand.php
src/Composer/Command/BaseDependencyCommand.php
src/Composer/Command/ClearCacheCommand.php
src/Composer/Command/ConfigCommand.php
src/Composer/Command/DependsCommand.php
src/Composer/Command/DumpAutoloadCommand.php
src/Composer/Command/InitCommand.php
src/Composer/Command/LicensesCommand.php
src/Composer/Command/ProhibitsCommand.php
src/Composer/Command/SearchCommand.php
src/Composer/Command/SelfUpdateCommand.php
src/Composer/Command/StatusCommand.php
src/Composer/Command/SuggestsCommand.php

In Symfony 4.4, a deprecation error is triggered if `Command::execute()` does not return an integer, see symfony/symfony#33747. This PR adds the necessary `return` statements.

Command::execute() should always return an integer

---

tests/Composer/Test/Util/FilesystemTest.php

I'm trying to track down the seemingly random failures on Appveyor. This first step is to see if there is a single failing condition (which I doubt).

Add messages to junction tests to see failures

---

src/Composer/Repository/Vcs/HgDriver.php

This PR follows https://github.com/composer/composer/pull/8358 and is now addressing the issue instead of blindly creating directories.
In the HgDriver implementation the initial clone for a repository is executed in the directory which is created by the clone command -> the dir does not exist when running the command. This results in a deprecation warning using symfony/process:3.4 and an exception using symfony/process:^4.

HgDriver: don't run command in non-existing directory

---

src/Composer/Repository/BaseRepository.php

I discovered that Composer does not check replaced packages when checking for dependents. Here are two example what this change does in a [Contao Managed Edition](https://contao.org).
I needed to figure out if a package was manually removed from the `composer.json` in the [Contao Manager](https://github.com/contao/contao-manager). I used the same code as `composer why` to compare installed packages against each other, but it also showed locally installed packages that were never in my `composer.json` 😆 
**Before:**
```
$ composer why symfony/contracts
There is no installed package depending on "symfony/contracts"
```
**After:**
```
$ composer why symfony/contracts
symfony/contracts             v1.1.5  replaces  symfony/cache-contracts (self.version)             
symfony/contracts …
```

Consider replaces when checking package dependents

---

doc/06-config.md
res/composer-schema.json
src/Composer/Command/ConfigCommand.php
src/Composer/Config.php
src/Composer/Installer.php
tests/Composer/Test/Fixtures/installer/install-without-lock.test
tests/Composer/Test/Fixtures/installer/update-without-lock.test
tests/Composer/Test/InstallerTest.php

This implements the feature proposed in #8354 to make workflows without a versioned lockfile less error-prone.

Config option to disable lockfile generation

---

src/Composer/Repository/PathRepository.php
tests/Composer/Test/Repository/PathRepositoryTest.php

When using a repository with a path, if the path didn't exist there was no error reporting and the remote dependency was installed.
This change checks for an empty array being returned from the `getUrlMatches` methods and throws a RuntimeException with details about the missing path for debugging.

Improve error reporting for missing path in Repository Path

---

src/Composer/Autoload/AutoloadGenerator.php
tests/Composer/Test/Autoload/Fixtures/autoload_real_files_by_dependency.php
tests/Composer/Test/Autoload/Fixtures/autoload_real_functions.php
tests/Composer/Test/Autoload/Fixtures/autoload_real_functions_with_include_paths.php
tests/Composer/Test/Autoload/Fixtures/autoload_real_functions_with_removed_include_paths_and_autolad_files.php
tests/Composer/Test/Autoload/Fixtures/autoload_real_include_path.php
tests/Composer/Test/Autoload/Fixtures/autoload_real_target_dir.php

to ease working with a loader after requiring 'vendor/autoload.php', as it can now provide autocompletion in an IDE

Added phpdoc for ComposerAutoloaderInit$SHA1::getLoader()

---

.travis.yml
CHANGELOG.md
bin/composer
doc/articles/troubleshooting.md
src/Composer/Console/Application.php
src/Composer/Repository/PlatformRepository.php
tests/Composer/Test/ApplicationTest.php

This PR
💁‍♂ For reference, also see 
- https://twitter.com/derickr/status/1184465999971700736
- https://github.com/composer/xdebug-handler/pull/99

Fix: Xdebug vs xdebug

---

doc/03-cli.md

This PR
💁‍♂ Both are currently only mentioned in [`doc/articles/troubleshooting.md`](https://github.com/composer/composer/blob/4e4c38795a0814db2b9222871a63714f674fd1d9/doc/articles/troubleshooting.md).

Fix: Add environment variables related to Xdebug to documentation

---

src/Composer/DependencyResolver/MultiConflictRule.php
src/Composer/DependencyResolver/RuleSetGenerator.php
src/Composer/DependencyResolver/RuleWatchGraph.php
src/Composer/DependencyResolver/RuleWatchNode.php

A large part of rule memory is used up with rules representing transitive conflicts, or mutual exclusion. This PR implements a new type of rule representing a combination of all these individual rules into a single object, greatly reducing memory usage and consequently also improving performance.
This PR is an alternative approach to https://github.com/composer/composer/pull/8053 - the upside is that its approach is more generic than just different versions of one package name. At the same time the alternative approach in #8053 may reduce memory more effectively by getting rid of parts of the watch graph entirely. So will need to do some benchmarking and explore whether these two approaches can maybe even be combined.
Sylius example before (on 1.9 branch):
```
[492.1MiB/75.38s] Memory …
```

New Multi Conflict Rule for transitive conflicts, to reduce memory use by rules

---

src/Composer/Util/ProcessExecutor.php
tests/Composer/Test/Downloader/GitDownloaderTest.php

Commit: 149250ab92feadd9fe045b54d6e42f33d185a595
ProcessExecutor::escape handled a false value inconsistently across
platforms, returning an emtpy string on Windows, otherwise `''`. This
is fixed to return `""` on Windows.
The GitDownloaderTest code has been appropriately updated.
See https://ci.appveyor.com/project/Seldaek/composer/builds/28664380 
@Seldaek This was caused by introducing a `preg_replace` value to escape the url, at: https://github.com/composer/composer/commit/149250ab92feadd9fe045b54d6e42f33d185a595#diff-c730819db325e3e10b8a4ef1be25373fR130
So the url was escaped twice:
1. from a `false` value, resulting in an empty string
2. from an empty string value (via `preg_replace` called with the `false` value), resulting in `""`
I guess the best behaviour would be not to use …

Fix Windows test regression from commit 149250a

---

doc/06-config.md

Right one paragrah above the correct language for technical docs (en US) is used
> will define the global behavior ...
This here should also be in that case.

Fix language.

---

src/Composer/Repository/ArrayRepository.php

Hi,
I've been profiling performance issues on a Magento2 install and noticed that 20% of each request was attributed to composer. Composer manages around 500 packages for that install. 
The problem is specifically with `ArrayRepository:hasPackage()`.
During bootstrapping this function is called once for each repository. Due to the loop used for name matching the complexity for n packages (executed once for each package) would be n*(n-1)/2. The proposed fix would reduce this to n. 
In practical terms this fix shaved off 200ms of each request. 
Please have a look at the profiles below. Specifically the profile "composer filtered without fix". Highlights the issue. getUniqeName is called 121k times during each request.
Overview without fix:
Overview with fix:
Composer filtered without fix: …

Improve hasPackage() performance

---

src/Composer/Downloader/ZipDownloader.php
tests/Composer/Test/Downloader/ZipDownloaderTest.php

https://github.com/composer/composer/issues/8461

#8461: [ZipDownloader] Print `unzip` exit code when the command is failed

---

src/Composer/Command/CreateProjectCommand.php

On slow connections, `create-project` may not output anything for over a minute when run, implying something may be wrong that is preventing Composer from working.
This is due to the 2nd line of [`getBestCandidate()`](https://github.com/composer/composer/blob/837ad7c14e8ce364296e0d0600d04c415b6e359d/src/Composer/Package/Version/VersionSelector.php#L52) doing some network download(for me it was ~13.6MB), and only after that would any output be produced with common usage of the command(no verbosity), as a new user to Composer is likely to try from following instructions online.
The validity of the install location is also not checked until after this network activity, which if it fails, has wasted time and can take a few more MB of network traffic for repeating the same command(unclear …

Fix: Improve the create-project UX

---

composer.lock

Changes:
* Added: support for `NO_COLOR` environment variable: https://no-color.org
* Added: color support for Hyper terminal: https://github.com/zeit/hyper
* Fixed: correct capitalization of Xdebug (apparently).
* Fixed: improved handling for uopz extension.

Update xdebug-handler to 1.4.0

---

src/Composer/Util/NoProxyPattern.php
tests/Composer/Test/Util/NoProxyPatternTest.php

This includes two breaking changes:
- the hostname is not resolved in the case of an IP address.
- a hostname with a trailing period (FQDN) is not matched.
This brings the basic implementation in line with curl behaviour, with 
the addition of full IP address and range matching (curl does not
differentiate between IP addresses host names).
The NO_PROXY environment variable can be set to either a comma-separated
list of host names that should not use a proxy, or single asterisk `*`
to match all hosts.
- Port numbers can be included by prefixing the port with a colon `:`
- IP addresses can be used, but must be enclosed in square brackets
`[...]` if they include a port number
- IP address ranges can specified in CIDR notation, separating the IP
address and prefix-length with a forward slash …

Rewrite NoProxyPattern to include IPv6

---

src/Composer/EventDispatcher/EventDispatcher.php
tests/Composer/Test/EventDispatcher/EventDispatcherTest.php

`@putenv` supports setting environment variables in a x-OS compatible way
closes https://github.com/composer/composer/issues/8489 https://github.com/composer/composer/issues/8488
after this change one can write a composer.json script like
```
{
"scripts": {
"myscript": [
"@putenv COMPOSER=phpstan-composer.json",
"composer install --prefer-dist"
]
}
}
```
before this change one could only write e.g.
`"COMPOSER=phpstan-composer.json composer install --prefer-dist"`
which is not compatible with windows (see also related issues, linked above).
one could also write things like
`"SET COMPOSER=phpstan-composer.json"`
but this works only on windows.

implemented `@putenv` composer script

---

src/Composer/DependencyResolver/Pool.php
src/Composer/DependencyResolver/PoolBuilder.php
src/Composer/DependencyResolver/Problem.php
src/Composer/DependencyResolver/Rule.php
src/Composer/Installer.php
src/Composer/Repository/RepositorySet.php
tests/Composer/Test/DependencyResolver/PoolTest.php
tests/Composer/Test/DependencyResolver/RuleSetIteratorTest.php
tests/Composer/Test/DependencyResolver/RuleSetTest.php
tests/Composer/Test/DependencyResolver/RuleTest.php
tests/Composer/Test/Fixtures/installer/solver-problems.test

After discussions with @naderman at #SymfonyHackday, here's the removal of the `$filterRequires` on the `Pool`. I've also renamed it to `$rootRequires` because that's what it's really is. It was only ever used for `Problem` as well as `Rule`, so it had no influence on the resolving process but it was there to display information only. This information, however, should be provided by the new `RepositorySet` and not the `Pool` itself.

Removed the filters from the pool

---

src/Composer/Repository/Vcs/GitHubDriver.php
src/Composer/Repository/Vcs/GitLabDriver.php
tests/Composer/Test/Repository/Vcs/GitHubDriverTest.php

This implements: https://github.com/composer/packagist/issues/1055
Note:
* Bitbucket does not have an archive functionality
* GitLab only provides the properties if the project data is accessed with authentication

VcsRepositories: mark archived repositories as abandoned

---

src/Composer/Command/ConfigCommand.php
src/Composer/Json/JsonManipulator.php
tests/Composer/Test/Json/JsonManipulatorTest.php

Reported in https://github.com/composer/composer/issues/6301
Currently, preferred-install accepts the hash of patterns as the value in the composer.json. I've followed the same approach as used in extra and platform for letting the user define install preferences through CLI in the format:
```
composer config preferred-install my-organization/stable-package.dist
composer config preferred-install my-other-organization/stable-package.source
composer config preferred-install my-other-organization/stable-package.auto
```

Implemented way to use preferred-install for defining granular preferences through CLI

---

src/Composer/DependencyResolver/DefaultPolicy.php
src/Composer/DependencyResolver/Pool.php
src/Composer/DependencyResolver/PoolBuilder.php
src/Composer/Repository/ArrayRepository.php
src/Composer/Repository/BaseRepository.php
src/Composer/Repository/ComposerRepository.php
src/Composer/Repository/CompositeRepository.php
src/Composer/Repository/RepositoryInterface.php
src/Composer/Repository/RepositorySet.php
tests/Composer/Test/DependencyResolver/DefaultPolicyTest.php
tests/Composer/Test/Fixtures/installer/repositories-priorities.test
tests/Composer/Test/Fixtures/installer/repositories-priorities2.test

@naderman Question: the way I understand things, this makes the concept of priorities in PoolBuilder/Pool/DefaultPolicy entirely irrelevant. If that's correct I can also delete all that. 
Fixes #5076

Avoid loading packages found in a higher prio repo entirely from lower prio repos

---

src/Composer/DependencyResolver/PoolBuilder.php
src/Composer/DependencyResolver/Request.php
src/Composer/Installer.php
src/Composer/Repository/RepositorySet.php
src/Composer/Repository/RootPackageRepository.php
tests/Composer/Test/Fixtures/installer/solver-problems.test

Avoids loading fixed packages from remote repos entirely, which is good, but it breaks a test as the problem reporting doesn't work anymore since the package is missing.
Fixes https://github.com/composer/composer/issues/3672

Pool builder cleanups

---

src/Composer/DependencyResolver/Pool.php
src/Composer/DependencyResolver/PoolBuilder.php
src/Composer/DependencyResolver/Problem.php
src/Composer/DependencyResolver/Request.php
src/Composer/DependencyResolver/RuleSetGenerator.php
src/Composer/Installer.php
src/Composer/Package/Version/StabilityFilter.php
src/Composer/Repository/ArrayRepository.php
src/Composer/Repository/ComposerRepository.php
src/Composer/Repository/CompositeRepository.php
src/Composer/Repository/RepositoryInterface.php
src/Composer/Repository/RepositorySet.php
tests/Composer/Test/DependencyResolver/PoolTest.php
tests/Composer/Test/DependencyResolver/RequestTest.php
tests/Composer/Test/DependencyResolver/RuleSetTest.php
tests/Composer/Test/DependencyResolver/RuleTest.php
tests/Composer/Test/DependencyResolver/SolverTest.php
tests/Composer/Test/Fixtures/installer/partial-update-downgrades-non-whitelisted-unstable.test

This allows optimizing the loading of ~dev files, and cleans up a few things

Remove callback and pass stabilities all the way instead

---

src/Composer/Command/InitCommand.php

A `minimum-stability` of `rc` is valid according to `composer-schema.json` and works fine with install and update and generally in version comparisons, because it's normalized to `RC`.
This change makes it work in `InitCommand` and `RequireCommand` too.
I know that only RC is documented, but considering that install and update work, it should not hurt to make it work in require too.
Example composer.json:
```json
{
"name": "pweyck/rc-test",
"description": "This works with composer install, but not composer require",
"type": "library",
"require": {
"shopware/core": "v6.1.0"
},
"license": "MIT",
"authors": [
{
"name": "Patrick Weyck",
"email": "p.weyck@shopware.com"
}
],
"minimum-stability": "rc"
}
```
Install works but require produces an error:
```
Reading ./composer.json
Loading config …
```

Normalize minimum-stability `rc` to `RC` in `InitCommand`

---

src/Composer/EventDispatcher/EventDispatcher.php
tests/Composer/Test/EventDispatcher/EventDispatcherTest.php

Issue https://github.com/composer/composer/issues/5522
The "composer install" can create the vendor/dir folders and be used as a script item on composer.json. Having another script running after it that relies on vendor/bir binaries (such as phpunit) will cause it to not find the binary. This fix addresses the issue by trying to append the path on each script iteration.

Append the bin dir on each listener iteration

---

src/Composer/Autoload/AutoloadGenerator.php
src/Composer/Installer.php
src/Composer/Json/JsonFile.php

Hello!
We use CI process, which includes a  `composer install` command.
Every `composer install` execution modifies the dates for the vendor folder and some files.
It blocks docker layer caching system and increase CI JOB time.
This PR allows composer install and docker cache system to run along.

Change only modified files for docker caching

---

src/Composer/DependencyResolver/Pool.php
tests/Composer/Test/Fixtures/installer/provider-packages-can-be-installed-if-selected.test
tests/Composer/Test/Fixtures/installer/provider-packages-can-be-installed-together-with-provided-if-both-installable.json
tests/Composer/Test/Fixtures/installer/provider-packages-can-not-be-installed-unless-selected.test

Fixes #6753
I think it's fine really as per the 3 new tests, as they only get installed if selected, this isn't risky.

Allow providers which are selected to be installed in place of existing packages which do not satisfy requirements

---

src/Composer/Installer.php

From what I see, this option was not working since 2012, when notification logic was moved from `ComposerRepository` to `InstallationManager`:
https://github.com/composer/composer/commit/a8f74a0983306306bfaac6c2d853bed15a3703f1#diff-faebd9b86332c29e1458dc470019a9eaL85-L87
https://github.com/composer/composer/commit/a8f74a0983306306bfaac6c2d853bed15a3703f1#diff-fd5a4cc2db7062747cf9410deb222310L222-R235

respect `notify-on-install` option

---

doc/03-cli.md

Some shells like ZSH require wrapping * with quotes, otherwise, it shows an error like:
> zsh: no matches found: 2.2.*

Wrap version constaints that contain * with quotes

---

.php_cs
src/Composer/Command/ArchiveCommand.php
tests/Composer/Test/Command/ArchiveCommandTest.php

It was previously blindly getting a new instance from the factory thus ignoring what is on Composer object config data.

Uses config data from Composer object whenever possible on ArchiveCommand

---

doc/faqs/how-to-install-composer-programmatically.md

Sha-384 is a hash algorithm which can be used as checksum, but it's no digital signature.

rename signature to checksum

---

phpunit.xml.dist
tests/Composer/Test/Command/ArchiveCommandTest.php

#8562 introduced a risky test `ArchiveCommandTest::testUsesConfigFromFactoryWhenComposerIsNotDefined()` which did not make sure that the method is really called and contained some unused test code. 
PHPUnit config has been updated to prevent such tests to pass but it will only fail on v5.7 and up because PHPUnit 4.8 does not support `failOnRisky` directive.

Fix risky test

---

src/Composer/DependencyResolver/Operation/UpdateOperation.php
tests/Composer/Test/Fixtures/installer/partial-update-downgrades-non-whitelisted-unstable.test
tests/Composer/Test/Fixtures/installer/partial-update-from-lock.test
tests/Composer/Test/Fixtures/installer/partial-update-without-lock.test
tests/Composer/Test/Fixtures/installer/update-downgrades-unstable-packages.test
tests/Composer/Test/Fixtures/installer/update-prefer-lowest-stable.test

Currently, running `composer install --dry-run` produces different output than `composer install` when some of packages will be downgraded:
```
$ composer u --dry-run                           
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
- Updating composer/ca-bundle (1.2.6) to composer/ca-bundle (1.0.0)
$ composer u
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
- Downgrading composer/ca-bundle (1.2.6 => 1.0.0): Loading from cache
Writing lock file
Generating autoload files
```
I usually use `--dry-run` switch to see which operations will be executed on a feature branch I am …

Distinguish between updates and downgrades in dry-run

---

doc/03-cli.md
src/Composer/Command/CreateProjectCommand.php
src/Composer/Repository/RepositoryFactory.php
tests/Composer/Test/Repository/RepositoryFactoryTest.php

This PR adds an option to the create-project command to also add the repository option to the composer.json of the project.
It prevents doing so if the project already contains a composer.lock file because this will lead to an outdated composer.lock file.

Create project: add option to add the repository to the composer.json

---

doc/articles/scripts.md
src/Composer/DependencyResolver/PoolBuilder.php
src/Composer/EventDispatcher/EventDispatcher.php
src/Composer/Installer.php
src/Composer/Installer/InstallerEvent.php
src/Composer/Installer/InstallerEvents.php
src/Composer/Plugin/PluginEvents.php
src/Composer/Plugin/PrePoolCreateEvent.php
src/Composer/Repository/RepositorySet.php
tests/Composer/Test/EventDispatcher/EventDispatcherTest.php
tests/Composer/Test/Installer/InstallerEventTest.php

Fixes #8348 - possibly. 
@stof I am not sure what you meant there with: 
> To keep these optimization safe, the hook allowing to add or remove packages from the pool should run before them rather than after them.
I would tend to say the opposite, that our optimizations should run first then the plugins can filter what is left. That's what I implemented here but it's definitely up for discussion where the hook should happen.
Also looping in @nicolas-grekas

Restore installer events and add a PRE_POOL_CREATE hook for plugins

---

src/Composer/Util/Git.php

In case sync mirror fails if there already is a local copy available this will now output the reason why the sync fails:
Before
```
Failed to update git@github.com:glaubinix/test-repo-rename.git, package information from this repository may be outdated
```
After
```
Sync mirror failed: Failed to execute git remote set-url origin 'git@github.com:glaubinix/test-repo-rename.git' && git remote update --prune origin && git remote set-url origin 'git@github.com:glaubinix/test-repo-rename.git'
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
Failed to update git@github.com:glaubinix/test-repo-rename.git, package information from this repository …
```

Git: log error for sync mirror with existing local copy

---

src/Composer/Command/ValidateCommand.php

- The first commit fixes a regression in #7637
- The second commit fixes #8602
- Extra commits are to improve maintainability

Fix validate strict warnings

---

doc/03-cli.md
doc/04-schema.md
res/composer-schema.json
src/Composer/Command/FundCommand.php
src/Composer/Console/Application.php
src/Composer/Installer.php
src/Composer/Package/AliasPackage.php
src/Composer/Package/CompletePackage.php
src/Composer/Package/CompletePackageInterface.php
src/Composer/Package/Dumper/ArrayDumper.php
src/Composer/Package/Loader/ArrayLoader.php
src/Composer/Package/Loader/ValidatingArrayLoader.php
src/Composer/Repository/Vcs/GitHubDriver.php
tests/Composer/Test/Fixtures/installer/install-funding-notice.test
tests/Composer/Test/Json/Fixtures/composer.json
tests/Composer/Test/Package/Dumper/ArrayDumperTest.php
tests/Composer/Test/Package/Loader/ArrayLoaderTest.php
tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php

Packages can specify a list of funding options each with a type and URL. The type is used to specify the kind of funding or the platform through which funding is possible.
Thanks to the symfony/thanks implementation which uses GitHub funding files https://github.com/symfony/thanks/pull/73/files we decided to add a general funding feature to Composer. This PR is based on the implementation in npm: https://github.com/npm/rfcs/blob/latest/accepted/0017-add-funding-support.md and https://github.com/npm/cli/pull/273 which has its roots in various previous projects/ideas/experiments: https://github.com/npm/rfcs/blob/latest/accepted/0017-add-funding-support.md#prior-art
Still missing, now that the field is supported and loaded and saved everywhere:

Add funding field to composer.json and composer fund command

---

src/Composer/Util/Filesystem.php

I thought that ’copyThenRemove’ did not return anything, so I removed 'return'.
Also, extra trimmed spaces.

delete 'return' and 'spaces' in Filesystem.php

---

src/Composer/Command/DiagnoseCommand.php
src/Composer/SelfUpdate/Versions.php

Use http to get the latest version when disable-tls is true and error-
trap DiagnoseCommand::checkVersion so that all checks can complete.
Fixes #8657.

Respect disable-tls in Versions::getLatest

---

composer.lock

Changes:
* Fixed: restart fails if an ini file is empty.

Update xdebug-handler to 1.4.1

---

doc/articles/versions.md

The wikipedia section `Version_control#Common_vocabulary` has moved to `Version_control#Common_terminology`.
You know, scrolling along is harassing :-)

Update link to wikipedia VC -> Common terminology

---

src/Composer/Autoload/AutoloadGenerator.php

when composer builds classmaps those are either build from the `classmap` key in `composer.json` or in `classMapAuthoritative`-mode for psr-0/4 classes.
see https://github.com/composer/composer/blob/f154d5c09d69a6338d6a955bf51cc264d0448b3d/src/Composer/Autoload/AutoloadGenerator.php#L237-L267
before this PR composer did only check whether the classes are ambiguous within either the defined classmap or the psr-0/4 namespaces.
It did not check whether classes defined via classmap are ambiguous with class from the psr-0/4 autoloading or vice versa.
with this PR we collect all `ambigiousClasses` across `addClassMapCode` call-sites and report the classes afterwards.
with this change classes will also be detected which happen more then 2 times, therefore the error message was adjusted.
without …

report ambiguous classes across all classmaps

---

src/Composer/Repository/Vcs/GitLabDriver.php

This causes `Notice: Undefined index: default_branch at GitLabDriver.php:22` and never tries to fallback to the git driver.

GitLab: properly handle token which has Guest only access

---

src/Composer/Autoload/AutoloadGenerator.php

The PR fixes this PHP 8 deprecated warning:
PHP Deprecated:  Required parameter $ambiguousClasses follows optional parameter $blacklist in phar://.../composer.phar/src/Composer/Autoload/AutoloadGenerator.php on line 339

Fix PHP 8 deprecated warnings

---

src/Composer/Installer.php
tests/Composer/Test/Fixtures/installer/install-funding-notice.test

I think adding some backticks would make this more discernible within the sentence, thus promoting the use of the command :)

Adds backticks around `composer fund` to improve readability.

---

src/Composer/DependencyResolver/Pool.php
src/Composer/DependencyResolver/Rule.php
src/Composer/DependencyResolver/RuleSetGenerator.php
src/Composer/Package/BasePackage.php
src/Composer/Package/PackageInterface.php
tests/Composer/Test/Fixtures/installer/provider-conflicts.test
tests/Composer/Test/Fixtures/installer/provider-conflicts2.test
tests/Composer/Test/Fixtures/installer/update-allow-list-require-new-replace.test

Started out by implementing that a package providing a name should not conflict with a package replacing it. This PR does correct this behavior but it expanded in scope due to the way this was accomplished:
The only implicit conflict (not using the conflict keyword) we have now results from packages using the same name, either by literally having the same name and being different versions, or they replace the same name, so:
- removed all types of obsolete rules
- simplified rule generation significantly, since there are now only explicit conflicts or same name conflicts which use a single multi conflict rule per name
- removed match types from Pool as these are no longer used
- matching by name only is no longer available in whatsProvide because mustMatchName was unused
- fixed some …

Remove obsolete rules

---

src/Composer/Package/Archiver/ArchiveManager.php
src/Composer/Package/PackageInterface.php
src/Composer/Repository/RepositoryInterface.php

used `@psalm-return` in places where types are more advanced and my IDE (phpstorm) would not understand the type.
using regular `@return` in places where "regular IDEs" support the notation

use more precise phpstan/psam return-types

---

src/Composer/Util/RemoteFilesystem.php

TLDR: We shouldn't be adding authentication on anything but the api.github.com url
Following the discussion about github deprecating auth via query string https://github.com/composer/composer/issues/8454
(Original blog post here https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters )
A fix was created see: https://github.com/composer/composer/commit/4b6c25d4bc33d49097320e29e6e5705b12e9d6ef
The problem is that this broke hardcoded URLs to tag archives. This works:
```
% curl -sv https://github.com/components/codemirror/archive/5.48.2.zip |& grep HTTP
> GET /components/codemirror/archive/5.48.2.zip HTTP/1.1
< HTTP/1.1 302 Found
```
Add a scopeless token, and it doesn't redirect anymore:
```
% curl -sv -H …
```

Making a fallback for broken auth on github

---

src/Composer/Installer/PackageEvent.php
src/Composer/Repository/ComposerRepository.php

Related to #8686
I linted the current master branch, with PHP master builds, and found two more deprecation notices:
1. `Deprecated: Required parameter $name follows optional parameter $constraint in src\Composer\Repository\ComposerRepository.php on line 745`
2.  `Deprecated: Required parameter $operation follows optional parameter $operations in src\Composer\Installer\PackageEvent.php on line 73`
…ository\ComposerRepository::isVersionAcceptable() required arguments used after optional, which is deprecated in PHP 8.0
Optional parameters with a type declared, and a default value of `null` is excepted from this deprecation. See https://php.watch/versions/8.0/deprecate-required-param-after-optional. This is the case in `ComposerRepository::isVersionAcceptable`, which still has two optional …

PHP 8 fixes for functional optional parameters before required parameters

---

.gitattributes
.github/CONTRIBUTING.md
CHANGELOG.md
README.md
composer.json
doc/01-basic-usage.md
doc/04-schema.md
doc/05-repositories.md
doc/07-community.md
res/composer-repository-schema.json
res/composer-schema.json
src/Composer/Autoload/ClassLoader.php
src/Composer/Util/TlsHelper.php
tests/Composer/Test/Fixtures/functional/packages.json
tests/Composer/Test/Json/Fixtures/composer.json

A low-effort PR 🙊. 
Some of the old URLs used in composer still use plain HTTP. I have scanned through, and updated them where appropriate and after checking if they automatically redirect to HTTPS. It does _not_ include HTTP URLs that refer to namespaces, schema, etc, nor change examples (that use `example.com` as the domain name). 
Thank you.
*The following domains automatically redirect HTTPS*
- php.net
- php-fig.org
- getcomposer.org
- git-scm.com
- naderman.de
- seld.be
- tools.ietf.org
*URL below support both HTTP and HTTPS, and are updated to their HTTPS variants*
- json-schema.org
*URL below redirects to a new URL, but with same contents*
- `http://contributor-covenant.org/version/1/4/` -> `https://www.contributor-covenant.org/version/1/4/code-of-conduct/` (301 to HTTPs -> 301 to …

Update HTTP URLs to their HTTPS if they already redirect automatically

---

src/Composer/Package/Loader/ValidatingArrayLoader.php
tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php

This is #8750 but for the 1.10 branch and including tests.
fixes #8749

Allow duplicate dashes in package names (1.10)

---

doc/articles/scripts.md

This line was removed (by mistake I guess) with this commit: https://github.com/composer/composer/commit/4d1416050dcf3493d2fb2d411dc1490d47fd3001#diff-d34ee8b7fff0f721fe2321f9c22e34f0

Add missing pre-status-cmd event in doc

---

src/Composer/Downloader/FileDownloader.php
src/Composer/Plugin/PluginEvents.php
src/Composer/Plugin/PostFileDownloadEvent.php

Start the conversation on resolving #8654

Provides a post download event

---

res/composer-schema.json
tests/Composer/Test/Json/ComposerSchemaTest.php

as discussed in #8749
```
$ ../bin/composer validate
[Composer\Json\JsonValidationException]                                                                     
"./composer.json" does not match the expected JSON schema:                                                  
- name : Does not match the regex pattern ^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$  
```

Add package naming pattern to the composer.json JSON schema

---

src/Composer/DependencyResolver/Problem.php
src/Composer/DependencyResolver/Rule.php
src/Composer/DependencyResolver/RuleSet.php
src/Composer/DependencyResolver/SolverProblemsException.php
src/Composer/Installer.php
tests/Composer/Test/DependencyResolver/RuleTest.php
tests/Composer/Test/DependencyResolver/SolverTest.php
tests/Composer/Test/Fixtures/installer/problems-reduce-versions.test

Fixes #8743
Not super happy about the $isVerbose-propagation-fest, but otherwise seems to do the job pretty well.
We could also just always do this without the -v option to get a full list, which then cleans up the implementation a lot.. Or we could add an env var or so when run with -vvv to at least get a chance to get full output for debugging?

Shorten long lists of similar versions in problem output

---

src/Composer/Command/ValidateCommand.php
src/Composer/Util/ConfigValidator.php

Field `version` can be a useful source of truth for packages that are not published on Packagist.

Add "no-check-version" option to ValidateCommand

---

src/Composer/Autoload/AutoloadGenerator.php
tests/Composer/Test/Autoload/Fixtures/platform/no_extensions_required.php
tests/Composer/Test/Autoload/Fixtures/platform/no_php_lower_bound.php
tests/Composer/Test/Autoload/Fixtures/platform/no_php_required.php
tests/Composer/Test/Autoload/Fixtures/platform/no_php_upper_bound.php
tests/Composer/Test/Autoload/Fixtures/platform/specific_php_release.php
tests/Composer/Test/Autoload/Fixtures/platform/typical.php

Small optimization of the code generated after #8546
`extension_loaded()` can be optimized out by opcache so better use it.

Optimize extension checks

---

doc/03-cli.md
src/Composer/Command/ConfigCommand.php

This is a PR for https://github.com/composer/composer/issues/8353#issuecomment-599117797.
The goal is to enable using composer config for setting deeper than the current limit of 3 by allowing the value to be specified as a JSON array or object. For example:
`composer config --json extra.patches.vendor/project '{"Patch title": "http://example.com/url/to/patch.patch"}'`

Added --json and --merge options to ConfigCommand

---

doc/03-cli.md
src/Composer/Command/ShowCommand.php

Hey, In this pull request I added `--locked` option to `composer show`. I also added displaying locked packages when using `composer show --all`

close #8784, Added --locked option to composer show command. Displaying locked packages with --all option

---

.github/workflows/phpstan.yml

Utilizing https://github.com/staabm/annotate-pull-request-from-checkstyle
phpstan errors get promoted into the „Files-changed“ Tab
Example:

Annotate phpstan errors in pull requests

---

src/Composer/Composer.php
src/Composer/Repository/PlatformRepository.php

Fixes #8846 
I tried a partial cherry pick of 0ab48a1773e55ee1706d43e739fa5719811a87c8, so surely this is incomplete... at the very least it would need tests, but I couldn't find any on master.

Add composer-runtime-api version constant
