src/Composer/Command/RequireCommand.php
It did not mention that it is possible to leave out the version constraint.
=> Updated the documentation of the require command

src/Composer/Util/RemoteFilesystem.php
=> fix-token-retrying-itself

src/Composer/Factory.php
See comments in https://github.com/composer/composer/pull/3655
=> Improve error message for case with incorrect "repositories"

src/Composer/Command/ConfigCommand.php
Minor fix for https://github.com/composer/composer/issues/3663
=> #3663 fix error message for config command

src/Composer/IO/ConsoleIO.php, tests/Composer/Test/IO/ConsoleIOTest.php
ConsoleIO writing a message which contains end of lines characters
#3647 
Edited: wrong issue number, changed it
=> fix for issue #3647

doc/00-intro.md
=> Add note about /usr not existing in OSX Yosemite by default.

src/Composer/Command/DiagnoseCommand.php
- added some docblocks
- added rate limit check for users that have no oauth token configured
- made it 'scream' less (yellow text instead of yellow background)
- reformatted the php ini checks slightly to be more condensed
=> Altered output of diagnose

tests/Composer/Test/Json/JsonManipulatorTest.php
Initial test delivered, needs a fix.
Closes #3716.
=> solve edge case for `composer remove vendor/pkg`, fixes #3716

res/composer-schema.json, tests/Composer/Test/Json/ComposerSchemaTest.php
Not sure if the testcase is in the right place, but it seemed fitting when I wrote it.
Closes #3723
=> composer-schema strict check for minimum-stability, closes #3723

tests/Composer/Test/Package/Archiver/ArchivableFilesFinderTest.php, tests/Composer/Test/Package/Archiver/ArchiveManagerTest.php
One can’t assume a Git user is already setup for the tests.
=> Config Git repository user

src/Composer/Command/ConfigCommand.php, tests/Composer/Test/Config/Fixtures/composer-repositories.json, tests/Composer/Test/Config/Fixtures/config/config-with-exampletld-repository.json, tests/Composer/Test/Config/Fixtures/config/config-with-packagist-false.json, tests/Composer/Test/Config/JsonConfigSourceTest.php
closes #3728, closes #3713, closes #3290, not sure about #3025
I specifically left the original exception message as-is in order to not expose this behaviour deliberately.
=> composer config repositories.packagist false

composer.json, composer.lock, src/Composer/Command/LicensesCommand.php
Refs #3760, pulled out of #3715
=> Update tablehelper to table

src/Composer/Command/LicensesCommand.php
=> [Commande licenses] Remove deprecated TableHelper and minor update of the table style

src/Composer/Command/ValidateCommand.php
This is useful when you want to use composer to manage dependencies, but
don't actually want your project to be installable as a composer package.
Any issues that would prevent publishing are still shown, but as a warning
instead of an error.
=> Add --no-check-publish option to "composer validate"

src/Composer/Util/RemoteFilesystem.php
When package has been downloaded, composer duplicate progress message.
https://drive.google.com/file/d/0B9XRnt4GsyJrZV9MTmZoSFc0OFk/
=> Duplicate download progress

doc/articles/handling-private-packages-with-satis.md
This details are more or less copied directly from [Authentication management in Composer](http://seld.be/notes/authentication-management-in-composer).
I don't want to take credits for this at all, I just needed it again and again, so I added it to the documentation. Hope the location is correct.
=> Added some details about authentication handling.

src/Composer/Json/JsonFile.php
Related https://github.com/composer/composer/pull/3816#issuecomment-77207670
* Fixed $json parameter type from parseJson() and validateSyntax()
* Added docBlock to throwEncodeError()
=> Add/Fix DocBlock

src/Composer/Util/RemoteFilesystem.php
All other verbs are in the form of "doing something", ie Installing, Downloading. "connection" is the odd one out.
=> Improved wording

src/Composer/Util/Git.php, src/Composer/Util/ProcessExecutor.php
=> Fix #3813,  #3830

src/Composer/Package/Version/VersionSelector.php
Also refs beberlei/DoctrineExtensions#145
=> Fixes #3900

doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md
In accordance with http://git-scm.com/docs/gitignore
=> Ignore all .git dirs in the vendor dir recursively

src/Composer/Command/DiagnoseCommand.php
Updated ```DiagnoseCommand::execute()``` and ```DiagnoseCommand::getGithubRateLimit()```
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3859
| Doc PR        | none
Fixes #3859.
=> [bugfix] Fix for #3859

src/Composer/Command/DiagnoseCommand.php, src/Composer/Package/Loader/ArrayLoader.php
=> fixes #3976: drop ext/ctype dependency

src/Composer/Installer.php, tests/Composer/Test/Fixtures/installer/update-dev-packages-updates-repo-url.test
=> Check if package URLs are up to date after composer update is done

src/Composer/Installer.php, tests/Composer/Test/Fixtures/installer/partial-update-downgrades-non-whitelisted-unstable.test, tests/Composer/Test/Fixtures/installer/partial-update-forces-dev-reference-from-lock-for-non-updated-packages.test, tests/Composer/Test/Fixtures/installer/partial-update-from-lock.test, tests/Composer/Test/Fixtures/installer/partial-update-installs-from-lock-even-missing.test, tests/Composer/Test/Fixtures/installer/update-alias-lock.test, tests/Composer/Test/Fixtures/installer/update-whitelist-reads-lock.test
=> Partial updates should not corrupt the lock if the installed repo is not up to date with it

src/Composer/Autoload/ClassLoader.php, tests/Composer/Test/Autoload/ClassLoaderTest.php, tests/Composer/Test/Autoload/Fixtures/DirDotPhp/Dir.php, tests/Composer/Test/Autoload/Fixtures/DirDotPhp/psr4/Dir.php/File.php
=> fixes #3974: Autoloader have to distinguish between files and directories

tests/Composer/Test/Util/FilesystemTest.php
See https://phpunit.de/manual/current/en/incomplete-and-skipped-tests.html#incomplete-and-skipped-tests.requires.tables.api
=> Use PHPUnit pre-conditions

CHANGELOG.md
Compare links added to CHANGELOG.md, a la [keepachangelog.com](http://keepachangelog.com).
This is just an idea, and it only took a couple minutes, so feel free to reject it.
=> Add GitHub compare links to CHANGELOG.md

README.md
All dependencies are up-to-date and ~400 other packages are referencing composer. Keep up the good work.
=> Adding dependency badge and reference badge

doc/04-schema.md, res/composer-schema.json, src/Composer/Package/Loader/ValidatingArrayLoader.php
Note that this does not yet add this attribute @ packagist though
/cc @Seldaek any parts that I missed where this is relevant? Does .lock file generation and such take new fields into account automatically?
=> Add docs to composer schema in support section - closes #4055

.gitattributes
=> Make sure the .test files always have LF eol in the working directory

.gitattributes
/cc @Seldaek I wasn't done yet, please don't merge so quickly :-(.
=> force eol LF style, php diff, and some whitespace flags

src/Composer/Package/Loader/ValidatingArrayLoader.php, tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php
=> Allow unicode keywords, fixes #4087

doc/00-intro.md
=> Windows Installation Details this closes #3186

CONTRIBUTING.md, README.md
Speaks for itself, minor change.
=> code of conduct: 1.0.0 -> 1.1.0

src/Composer/Command/HomeCommand.php, src/Composer/Config.php, src/Composer/Downloader/GitDownloader.php, src/Composer/IO/ConsoleIO.php, src/Composer/Installer/PackageEvent.php, src/Composer/Installer/PluginInstaller.php, src/Composer/Repository/ComposerRepository.php, src/Composer/Util/GitHub.php
=> Fix: Remove unused imports

src/Composer/Installer/PluginInstaller.php
=> Fix: Remove unused private property

src/Composer/DependencyResolver/Operation/MarkAliasInstalledOperation.php, src/Composer/DependencyResolver/Operation/MarkAliasUninstalledOperation.php, src/Composer/EventDispatcher/EventDispatcher.php, src/Composer/Installer/InstallerInterface.php, src/Composer/Repository/ArtifactRepository.php, src/Composer/Repository/RepositoryManager.php
=> Fix: Add missing imports

src/Composer/Util/RemoteFilesystem.php
=> Dropped unnecessary break statements

doc/03-cli.md, src/Composer/Command/SuggestsCommand.php, src/Composer/Console/Application.php
=> Add suggests command

src/Composer/DependencyResolver/Solver.php, src/Composer/Installer.php
Similar to https://github.com/composer/composer/pull/4221
=> Output the number of rules used in the solver for profiling purposes

src/Composer/DependencyResolver/Problem.php, src/Composer/DependencyResolver/Rule.php
* determine conflicting version in problem using pool package
* more verbose message in rule
fixes #4319
=> make sure php version errors are less misleading

doc/05-repositories.md
I spent all day trying to figure out why I couldn't install my own fork... figured I'd add a note to save someone else the trouble.
=> Clarified instructions

src/Composer/Downloader/GitDownloader.php
When a vendor package has been modified locally, this PR allows to view the modifications (the result of `git diff HEAD`).
That's helpful when you don't remember what was the modifications.
Before this PR, it was only possible to see file names.
=> Add a new option to view local modifications (git diff)

CONTRIBUTING.md, README.md
/cc @Seldaek I know it's only docs, but since the content of the CoC changed someone should approve it first :-)
=> updated code of conduct and minor addition in contrib

src/Composer/Command/ConfigCommand.php, src/Composer/Command/CreateProjectCommand.php, src/Composer/Command/DependsCommand.php, src/Composer/Command/DiagnoseCommand.php, src/Composer/Command/HomeCommand.php, src/Composer/Command/InitCommand.php, src/Composer/Command/InstallCommand.php, src/Composer/Command/LicensesCommand.php, src/Composer/Command/RemoveCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Command/RunScriptCommand.php, src/Composer/Command/SearchCommand.php, src/Composer/Command/SelfUpdateCommand.php, src/Composer/Command/ShowCommand.php, src/Composer/Command/StatusCommand.php, src/Composer/Command/UpdateCommand.php, src/Composer/Command/ValidateCommand.php, src/Composer/Console/Application.php
Optimized the code by replacing a lot of `$this->getIO()` by `$io`.
=> Optimized this->getIO()

src/Composer/Repository/ComposerRepository.php
=> only urlencode $ if filename is not local

src/Composer/Command/ConfigCommand.php
=> itteratively expand key and attempt to match

src/Composer/Repository/RepositoryInterface.php
This permits a better auto-completion on IDE's
=> PackageInterface[] on RepositoryInterface php doc

.php_cs, src/Composer/Autoload/ClassMapGenerator.php, src/Composer/DependencyResolver/PolicyInterface.php, src/Composer/DependencyResolver/Solver.php, src/Composer/Package/AliasPackage.php, src/Composer/Util/ProcessExecutor.php, tests/Composer/Test/Autoload/ClassLoaderTest.php, tests/Composer/Test/Autoload/ClassMapGeneratorTest.php, tests/Composer/Test/DependencyResolver/SolverTest.php, tests/Composer/Test/Util/GitHubTest.php, tests/Composer/Test/Util/SvnTest.php
Added some rules we already follow but don't check for yet. Ran fixers.
=> php-cs-fixer

src/Composer/Command/ArchiveCommand.php, src/Composer/Package/Archiver/ArchiveManager.php, tests/Composer/Test/Package/Archiver/ArchiveManagerTest.php
Add --file option to the archive command, as per issue #4397 . Added 2 tests for this in the Composer\Test\Package\Archiver\ArchiveManagerTest class: ::testArchiveCustomFileName, and ::testNonStringFileName.
=> Added --file flag: Feature#4397

README.md
Update the README.md to include the php only command to install
composer incase curl is not available
=> Update readme.md to include php fall back

src/Composer/Util/ConfigValidator.php, tests/Composer/Test/Util/ConfigValidatorTest.php, tests/Composer/Test/Util/Fixtures/composer_commit-ref.json
=> Generate a warning when a commit reference is used

src/Composer/Autoload/AutoloadGenerator.php, tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
=> Up-level relative paths in exclude-from-classmap

doc/05-repositories.md
- Mentions symlinking
- Mentions absolute paths also being supported
=> Adds more details about Path Repository to the Documentation - #4412

src/Composer/Downloader/XzDownloader.php, src/Composer/Factory.php, tests/Composer/Test/Downloader/XzDownloaderTest.php
Hello,
As stated in https://github.com/composer/composer/issues/2804, it can be useful to be able to install from XZ tarballs. So here is an XzDownloader class based on GzipDownloader.
Regards,
=> .tar.xz downloader

doc/articles/troubleshooting.md
Related @Seldaek comment: https://github.com/composer/composer/commit/7a06615bf06c5a391ab2d360907012529508e695#commitcomment-14599053
=> Add alias trick on xdebug documentation part

src/Composer/Autoload/ClassLoader.php
=> Update the autoloader PHPDoc: PSR-4 instead of PSR-0

src/Composer/Command/ShowCommand.php
=> Fixed typo in the ShowCommand

doc/07-community.md
=> Fix broken link on Community docs page

doc/articles/handling-private-packages-with-satis.md
This PR adds informations on missing or new properties of the satis configuration file.
=> Satis documentation updates

src/Composer/Config/JsonConfigSource.php
=> Could not configure gitlab-oauth via CLI #3765

doc/articles/handling-private-packages-with-satis.md
satis now supports `notify-batch` configuration key
=> add notify-batch in schema

src/Composer/Package/AliasPackage.php, src/Composer/Package/Package.php, src/Composer/Package/RootPackageInterface.php
=> Improve PHPDoc for package requires

src/Composer/Autoload/ClassLoader.php
Reverts #4672 as per https://github.com/composer/composer/pull/4672#issuecomment-162845602
=> Revert "[ClassLoader] performance improvement: use str_replace instead of strtr"

src/Composer/Command/DependsCommand.php
Closes #4661.
Output sample:
```bash
$ composer depends symfony/dependency-injection --match-constraint='~3.0'
sensio/distribution-bundle requires symfony/dependency-injection (~2.3|~3.0)
sllh/iso-codes-validator requires (dev) symfony/dependency-injection (^2.3|^3.0)
symfony/assetic-bundle requires symfony/dependency-injection (~2.3|~3.0)
symfony/monolog-bundle requires symfony/dependency-injection (~2.3|~3.0)
symfony/swiftmailer-bundle requires symfony/dependency-injection (~2.3|~3.0)
$ composer depends symfony/dependency-injection --match-constraint='~3.0' --match-constraint-invert
behat/behat requires symfony/dependency-injection (~2.1)
cocur/slugify requires (dev) symfony/dependency-injection (~2.4)
doctrine/mongodb-odm-bundle requires symfony/dependency-injection (~2.2) …
```
=> Add match-constraint options to depends command

src/Composer/Command/UpdateCommand.php
=> Interactive interface with autocompletion that can help to select the packages to update

doc/03-cli.md
After discussions on this PR : https://github.com/composer/composer/pull/657
=> [doc] add a link about composer auto-completion

doc/03-cli.md
As requested on https://github.com/composer/composer/pull/4660#issuecomment-170267292.
=> Add Symfony 3 special case on depends command doc

doc/06-config.md, res/composer-schema.json, src/Composer/Command/ConfigCommand.php, src/Composer/Config.php, src/Composer/Factory.php, src/Composer/Util/RemoteFilesystem.php, tests/Composer/Test/Downloader/ZipDownloaderTest.php
Adds capath configuration capability.
Minor refactor of how cafile is resolved also (when not specified).
Closes #4804 #4812
=> Add capath configuration capability and refactor cafile resolving

src/Composer/Util/RemoteFilesystem.php
A general fix for #4782 rather than hard coded workaround for GitHub.
=> Follow redirects to properly validate certificates

src/Composer/Command/DiagnoseCommand.php, src/Composer/Command/SelfUpdateCommand.php, src/Composer/Util/Keys.php
Happy to get any feedback on this as it's quite sensitive.
=> Add verification of signatures when running self-update

doc/articles/plugins.md
As discussed in #4830
Hopefully this better explains how plugins register handlers for events
=> Improved Event Handlers for Plugins section 

src/Composer/Autoload/ClassMapGenerator.php, src/Composer/Cache.php, src/Composer/Command/ConfigCommand.php, src/Composer/Command/CreateProjectCommand.php, src/Composer/Config/JsonConfigSource.php, src/Composer/Console/Application.php, src/Composer/Factory.php, src/Composer/Installer/LibraryInstaller.php, src/Composer/Util/RemoteFilesystem.php, src/Composer/Util/Silencer.php, tests/Composer/Test/Util/SilencerTest.php
Implementation without external dependencies of #4820
=> Added more graceful warning suppression utility

src/Composer/Command/RemoveCommand.php, src/Composer/Command/RequireCommand.php
=> Add --no-plugins option to remove/require

src/Composer/DependencyResolver/SolverProblemsException.php, tests/Composer/Test/DependencyResolver/SolverTest.php, tests/Composer/Test/Fixtures/installer/broken-deps-do-not-replace.test
The link might as well take you straight to the documentation, IMO.
=> Update Error Message In SolverProblemsException.php

src/Composer/Package/Loader/RootPackageLoader.php, tests/Composer/Test/Fixtures/installer/install-self-from-root.test, tests/Composer/Test/InstallerTest.php
=> Bail out if root package attempts to include itself

src/Composer/Command/ConfigCommand.php, src/Composer/Command/HomeCommand.php, src/Composer/Command/ShowCommand.php, src/Composer/Console/Application.php, src/Composer/Downloader/GitDownloader.php, src/Composer/Downloader/GzipDownloader.php, src/Composer/Downloader/RarDownloader.php, src/Composer/Downloader/ZipDownloader.php, src/Composer/Factory.php, src/Composer/Installer/LibraryInstaller.php, src/Composer/Installer/PearInstaller.php, src/Composer/Util/Filesystem.php, src/Composer/Util/Perforce.php, src/Composer/Util/Platform.php, src/Composer/Util/ProcessExecutor.php, src/Composer/Util/TlsHelper.php, tests/Composer/Test/Downloader/GitDownloaderTest.php, tests/Composer/Test/Downloader/HgDownloaderTest.php, tests/Composer/Test/Downloader/XzDownloaderTest.php, tests/Composer/Test/Repository/Vcs/SvnDriverTest.php, tests/Composer/Test/Util/PlatformTest.php, tests/Composer/Test/Util/SvnTest.php
Scattered throughout the code there were 4 different ways of testing whether the code is running on Windows, each being used several to tens of times. Now there is one unified unit tested approach.
=> Windows platform tests unified

composer.json, composer.lock, src/Composer/Downloader/GzipDownloader.php
* Added a suggest for `ext-zlib` which had got mangled in with `ext-zip`
* Fallback to zlib extension if available to extract gzip files
=> zlib suggest and fallback on non Windows

src/Composer/Command/DiagnoseCommand.php
https://github.com/composer/getcomposer.org/pull/91
=> Warning if OpenSSL does not support TLSv1.2

src/Composer/Factory.php, src/Composer/Package/Archiver/ZipArchiver.php, tests/Composer/Test/Package/Archiver/ZipArchiverTest.php
the PharArchiver used to create zip files does not compress anything currently. 
when using satis with an archive directory, this new ZipArchiver saves a ton of hard disk space when the zip extension is enabled. 
fallback is the current behaviour using PharArchiver.
=> added ZipArchiver to actually compress zip files

src/Composer/Package/Archiver/PharArchiver.php
Sometimes someone need tar.gz package to deploy the project or host the package.
=> Support tar.gz and tar.bz2 compressed archiver

doc/04-schema.md
As stated here: https://getcomposer.org/doc/articles/versions.md#range
A logical OR is done using a double pipe "||".
=> fix documentation which use a single pipe for a "logical OR"

src/Composer/Downloader/PathDownloader.php
If a path repository contained a package that was first successfully installed, and then something broke its source, the package would be removed before the issue was detected, leaving the dependency broken.
Along the way added a fatal check on installing a path download to (a subfolder of) its source. #4431  suggested this should be a no-op but it's so dangerous I consider it better to rely on the symlinking/junctioning behaviour instead for development scenarios.
=> Fixes in path repository handling of removed or nested sources

src/Composer/Downloader/PathDownloader.php, src/Composer/Util/Filesystem.php, tests/Composer/Test/Util/FilesystemTest.php
Following up on #4690. Please note that this code was tested with a very limited test case, and you'll need to reboot if it corrupts the path repositories. Some test feedback is welcome before merging.
=> Implement junctioning on Windows for path repositories

src/Composer/Command/CreateProjectCommand.php, src/Composer/DependencyResolver/DefaultPolicy.php, src/Composer/DependencyResolver/Rule.php, src/Composer/Installer.php, src/Composer/Installer/LibraryInstaller.php, src/Composer/Repository/ComposerRepository.php, src/Composer/Repository/RepositoryManager.php, tests/Composer/Test/Repository/ComposerRepositoryTest.php
- Checked code marked as 'backwards compatible' and removed any that were from early 2013 or even before.
- Corrected a missing deprecation warning.
- Fixed a unit test depending on deprecated implementation
- Removed long deprecated methods that were no longer referenced (2+ years old)
=> BC cleanup

src/Composer/Command/ConfigCommand.php, src/Composer/Config.php, src/Composer/Util/RemoteFilesystem.php
@Seldaek Something like this for issue #4777?
It seems somewhere there's still http://packagist.org links generated, so I added a little fix for those specifically. I guess that shouldn't be necessary, so maybe you can point me to the right spot to fix?
=> Added secure-http flag, defaults to true

src/Composer/Command/UpdateCommand.php
This issue resolves #4729. I didn't see any tests for the update command, but if you'd like a test for this, let me know where to put it.
=> Add the --root-require option to the update command

doc/articles/troubleshooting.md
=> Troubleshoot info about SSH ControlMaster

doc/04-schema.md, res/composer-schema.json, src/Composer/Config.php, src/Composer/Downloader/DownloadManager.php, src/Composer/Factory.php, tests/Composer/Test/ConfigTest.php, tests/Composer/Test/Downloader/DownloadManagerTest.php
=> add support for package based install type preferences

doc/articles/troubleshooting.md, src/Composer/Downloader/ZipDownloader.php
Replaces #4964, fixes #2565 
(new PR since git crashed my other branch and I had to rebuild from master)
=> Troubleshooting and warning in code related to issues with native ZipArchiver

tests/Composer/Test/Downloader/GitDownloaderTest.php
=> Disabled unit test breaking on some platforms. Ref #4973

CHANGELOG.md
=> Add changelog entry for #4970

src/Composer/Command/CreateProjectCommand.php, src/Composer/Installer.php, src/Composer/Installer/SuggestedPackagesReporter.php, tests/Composer/Test/Installer/SuggestedPackagesReporterTest.php
Resolves https://github.com/composer/composer/issues/2752
=> List project suggestions in create-project command

src/Composer/Command/InitCommand.php
=> Improved error message when adding a package disallowed by PHP version

src/Composer/Command/SearchCommand.php
`SearchCommand` uses same `getComposer(false)` call as many other commands, but does not load any config obviously at all, including `auth.json`, when no `composer.json` is found. This PR injects a dummy `Composer` with empty config instead, thus including all global config.
Should fix #4392
=> Simulate dummy Composer when searching in uninitialized folder

src/Composer/Installer.php, tests/Composer/Test/Fixtures/installer/github-issues-4795-2.test
Reproduces (and solves) an issue reported by @teohhanhui on the initial "fix" (#4817) for #4795.
=> simplified existing test, added a new test - related to #4795

src/Composer/Installer/LibraryBinariesHandler.php, src/Composer/Installer/LibraryInstaller.php, tests/Composer/Test/Installer/LibraryInstallerTest.php
The functionality to install binaries might be useful
for other installers.
Create API for that by extracting this functionality from
the LibraryInstaller class.
=> Extract binary installation and removal to own class

src/Composer/Command/SelfUpdateCommand.php
Follow-up to #4995 which has been recently merged.
Hotfix for an error in code. My apologizes for the inconvenience.
ping @Seldaek
=> Fix missing argument for getLastBackupVersion()

src/Composer/Command/DiagnoseCommand.php, src/Composer/Command/SelfUpdateCommand.php, src/Composer/SelfUpdate/Keys.php, src/Composer/SelfUpdate/Versions.php
Implementation of #4960, also fixes #3707
=> Add update channels support to self-update and diagnose

src/Composer/Console/Application.php
=> Warn if running as root, and clobber sudo credentials

doc/04-schema.md, res/composer-schema.json
=> Add RSS channel to support section in composer schema

src/Composer/Autoload/AutoloadGenerator.php
Static arrays are limited to 32767 values on PHP 5.6
See https://bugs.php.net/68057
=> Workaround https://bugs.php.net/68057

src/Composer/Package/Archiver/ArchivableFilesFilter.php, src/Composer/Package/Archiver/PharArchiver.php
Compared with buildFromIterator this is much slower.
- Report: #5206
- Ref: 8389b4b
=> Support empty directories with tar-files, closes #5206

src/Composer/Installer.php, tests/Composer/Test/Fixtures/installer/update-no-dev-still-resolves-dev.test
Fixes #5016
Again, quite big changes in core code so could use a review. It's pretty well tested though so I don't expect major issues.
=> Always resolve dev packages even when doing an update with --no-dev

src/Composer/Command/ShowCommand.php
This is a partial fix for #3771
Shows the recommend version, same as used in the require command. When used with the `--recommended` or `-r` flag, it shows an extra column in the table layout, or extra row for 1 package.
Multiple packages:
Single package:
Possible improvements (which I'm not really sure how to do easy):
- Show the exact latest versions (eg. `3.1.2` instead of `^3.2`)
- Show the current constraint? (`eg `3.x` instead of `3.1.2`)
- Take PHP version into account?
- Add coloring to see of the current constraint allows the latest version?
Update: Now using `--latest` / `-l` and showing the latest version, instead of best constraint.
=> Add latest version to show command (option)

src/Composer/Command/ShowCommand.php
As request, a separate PR, following up on https://github.com/composer/composer/pull/5028 with the addition of a deprecation notice.
Screenshot:
=> Add latest version to show + Deprecated message

src/Composer/Repository/Vcs/GitLabDriver.php
Fixed a bug that prevented interactive authentication to work properly
=> Gitlab driver bugfix

src/Composer/Console/Application.php
=> fix command injection from the environment when run as root, issue #5244

doc/03-cli.md
This is a follow up from https://github.com/bamarni/symfony-console-autocomplete/pull/16. I also added a command snippet to help locating that folder.
Should I submit this to `1.0` or master? I'm confused by all this stablility 😄
=> doc - some rephrasing for global cli install

src/Composer/Package/Loader/ValidatingArrayLoader.php, tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php
As addition to my previous pull request #5125.
=> Validate RSS channel in composer schema

src/Composer/Repository/Vcs/GitBitbucketDriver.php, src/Composer/Util/Bitbucket.php, src/Composer/Util/Git.php, src/Composer/Util/ProcessExecutor.php, src/Composer/Util/RemoteFilesystem.php, tests/Composer/Test/Repository/Vcs/GitBitbucketDriverTest.php, tests/Composer/Test/Util/BitbucketTest.php
Currently downloading the source with https bitbucket urls configured works as intended.
However, downloading a zip file with the source is not.
This PR implements the OAuth way for all dist downloads.
=> All bitbucket (https) communication with OAuth

src/Composer/Repository/Vcs/GitHubDriver.php
This patch stops the GitHub VCS driver prompting for a new access token when a repository is deleted/hidden.
Specifically, it checks the X-OAuth-Scopes and X-Accepted-OAuth-Scopes response headers to see if the scopes on the current request match those needed by the API call. If they do, the 404 means that the repo is deleted/hidden, and there's no point asking for a new OAuth token.
=> Check headers for missing scopes before asking for new OAuth token

src/Composer/Util/Bitbucket.php, src/Composer/Util/RemoteFilesystem.php, tests/Composer/Test/Util/BitbucketTest.php
If authentication is required and composer downloads a zip from bitbucket, it's redirected to a login page asking for credentials.
With this fix, the code with apply existing (or ask for new oauth) credentials automatically.
=> Fix minor bitbucket oauth issues

src/Composer/Repository/PlatformRepository.php
Please see #5317 (this is the original proposal again) and #5304.
=> IPv6 Platform Requirement

src/Composer/Console/Application.php
=> Modify the message for memory errors

appveyor.yml
2 spaces as in `travis.yml` and in the beginning of this file:
```
platform:
- x86
- x64
```
To make this united.
=> appveyor.yml: use one type of indentation

src/Composer/XdebugHandler.php
Brought the restart logic closer 👫 for the early exit and to make it easy on the eyes.
=> Minor refactoring to `XdebugHandler@check`

composer.json
This is correct right compared to https://github.com/composer/composer/blob/1.2/composer.json#L62?
=> Set branch alias for 1.3-dev

src/Composer/Util/ProcessExecutor.php, tests/Composer/Test/Util/ProcessExecutorTest.php
Minor annoyance I ran into while debugging something
=> User password masking patch

src/Composer/Package/Version/VersionSelector.php, tests/Composer/Test/Package/Version/VersionSelectorTest.php
=> What provides stability ordering issue

doc/04-schema.md
@Seldaek: As discussed yesterday here addition to the docs re PHP extensions. I have put it as a note as it appears emphasized for users to notice easily.
=> Elaborated on importance of PHP extension dependencies

tests/Composer/Test/Repository/ArtifactRepositoryTest.php, tests/Composer/Test/Repository/FilesystemRepositoryTest.php, tests/Composer/Test/Repository/PathRepositoryTest.php, tests/Composer/Test/Repository/Pear/ChannelReaderTest.php, tests/Composer/Test/Repository/Pear/ChannelRest10ReaderTest.php, tests/Composer/Test/Repository/Pear/ChannelRest11ReaderTest.php, tests/Composer/Test/Repository/Pear/PackageDependencyParserTest.php, tests/Composer/Test/Repository/PearRepositoryTest.php, tests/Composer/Test/Repository/RepositoryManagerTest.php, tests/Composer/Test/Repository/Vcs/GitBitbucketDriverTest.php
All other tests are in the ``Composer\Test`` namespace (matching PSR-0 btw)
=> Fix namespace for tests for consistency

src/Composer/Util/RemoteFilesystem.php, tests/Composer/Test/Util/RemoteFilesystemTest.php
=> prevent (prompt for) bitbucket auth when it redirected

src/Composer/Package/Dumper/ArrayDumper.php, tests/Composer/Test/Package/Dumper/ArrayDumperTest.php
=> bring arraydumper in line with json schema spec and packagist

src/Composer/Installer.php
When listening for `POST_DEPENDENCIES_SOLVING`, I was expecting to get all operations that will be executed by Composer, but that's not always the case.
Under some conditions, `processDevPackages` might add some `UpdateOperation` operations, which are not available during the event dispatching as it is dispatched too early.
This PR moves the event dispatch to after the call to `processDevPackages`. It means that it is not part of the `try/catch` block anymore, but throwing a `SolverProblemsException` from the event is not documented and I did not find any such usage on the "Internet".
=> Fix POST_DEPENDENCIES_SOLVING trigger

src/Composer/Command/RequireCommand.php
Nothing fancy, but this avoids reading the JSON file twice and simplifies code when possible.
=> Code simplification

src/Composer/Repository/Vcs/HgDriver.php, tests/Composer/Test/Repository/Vcs/HgDriverTest.php
=> HgDriver does not identify bitbucket mercurial repos correctly

doc/faqs/how-to-install-composer-programmatically.md
=> Make download shell script PSR-2 compatible

doc/articles/handling-private-packages-with-satis.md
With composer/satis#295 an option for dumping provider includes was added which is missing here in the docs
=> Add documentation for providers option

src/Composer/Repository/Vcs/BitbucketDriver.php, src/Composer/Repository/Vcs/FossilDriver.php, src/Composer/Repository/Vcs/GitBitbucketDriver.php, src/Composer/Repository/Vcs/GitDriver.php, src/Composer/Repository/Vcs/GitHubDriver.php, src/Composer/Repository/Vcs/GitLabDriver.php, src/Composer/Repository/Vcs/HgBitbucketDriver.php, src/Composer/Repository/Vcs/HgDriver.php, src/Composer/Repository/Vcs/PerforceDriver.php, src/Composer/Repository/Vcs/SvnDriver.php, src/Composer/Repository/Vcs/VcsDriver.php, src/Composer/Repository/Vcs/VcsDriverInterface.php, src/Composer/Util/Perforce.php
To solve https://github.com/composer/packagist/issues/556 we need a function to get the content of a file. This function can also be used for getComposerInformation. And because this is the main difference between drivers (how to get the file) we can than create a common function `getComposerInformation()` to the absract class.
=> Feature: get file content

doc/articles/handling-private-packages-with-satis.md
=> mardown issue + move urls to footnotes

src/Composer/Repository/PlatformRepository.php
=> support libressl

src/Composer/Downloader/PathDownloader.php
Reverts composer/composer#5974
=> Revert "Allow use of parent directories in PathDownloader when not mirroring the path"

src/Composer/XdebugHandler.php
@Seldaek I haven't implemented any further command-line ini handling here. It is a bit of a struggle trying to understand PHP's string quoting rules at the moment.
=> Ignore xdebug.ini and process all files, #5995

doc/articles/troubleshooting.md
As per 0bc75c3fb6920798ec5410b912a7fe15d220e24a
=> Update memory limit in docs

src/Composer/XdebugHandler.php
It would need a very weird setup for this to cause problems, but it might as well be right.
=> Fix scanned ini files logic

doc/05-repositories.md
https://www.mercurial-scm.org/ <-- new one
=> Dead link to Mercurial

tests/Composer/Test/Package/Version/VersionGuesserTest.php
```
~/tmp/tc$ ./composer.phar --version
Composer version 1.3.3 2017-03-08 11:06:43
~/tmp/tc$ hg --version
Mercurial SCM Distribuito (versione 3.8.2)
[...]
~/tmp/tc$ hg init
~/tmp/tc default $ ./composer.phar require -vvv psr/log
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/mnt/home/user/tmp/tc): git branch --no-color --no-abbrev -v
Executing command (/mnt/home/user/tmp/tc): git describe --exact-match --tags
Executing command (/mnt/home/user/tmp/tc): git log --pretty="%H" -n1 HEAD
Executing command (/mnt/home/user/tmp/tc): hg branch
[ErrorException]
Illegal string offset 'version'
Exception trace:
() at phar:///mnt/home/user/tmp/tc/composer.phar/src/Composer/Package/Version/VersionGuesser.php:73 …
```
=> 1.3.3 incompatible with HG

src/Composer/Downloader/ZipDownloader.php, tests/Composer/Test/Downloader/ZipDownloaderTest.php
Refactoring of unzip ZipArchive fallback.
* a solution to #604
* cleaner fallback mecanism between ZipArchive and SystemUnZip
* tests
=> Fix unzip on win php56

doc/03-cli.md
This update the CLI documentation which looked out of sync with the `composer --help output`.
Thanks to proofreaders :)
=> update cli documentation

doc/04-schema.md
In the JSON schema it says that this property is of type "string" ... but maybe we can explain this a bit more and recommend to use good package names.
=> [Doc] Explained a bit more about the possible contents of the "name" property

src/Composer/IO/ConsoleIO.php, src/Composer/Question/StrictConfirmationQuestion.php, tests/Composer/Test/IO/ConsoleIOTest.php, tests/Composer/Test/Question/StrictConfirmationQuestionTest.php
This adds makes the init command enforce yes/no answers for boolean questions as requested in issue #5989
=> Fix for https://github.com/composer/composer/issues/5989

src/Composer/IO/IOInterface.php
Change `callback` typehint to `callable` in order to satisfy phpstan.
=> Fix callable typehint

tests/Composer/Test/IO/ConsoleIOTest.php, tests/Composer/Test/Json/ComposerSchemaTest.php
=> Issue deps

doc/05-repositories.md
=> Fix typo in docs

doc/05-repositories.md
Update bitbucket repo driver documentation...
=> Teolaz1990 doc patch

src/Composer/Command/InitCommand.php
Added $_SERVER['USER'] as possible value for <vendor> name in init command.
=> Added $_SERVER['USER'] as possible value for <vendor>

doc/01-basic-usage.md
Should be repository instead of respository.
=> Typo correction

doc/05-repositories.md
This PR is to Fix #6627.
I'm open to any suggestions on this. 
Do I need to provide a full working example ? or leaving @naderman example as is is fine ?
=> Document how to define multiple versions in a package repository

src/Composer/Command/ShowCommand.php
Add default sort feature for #6646
=> Add default sort for show --tree option

doc/articles/versions.md
Fixed link to Caret version range paragraph
=> fixed caret sub title link in the article

src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Command/RunScriptCommand.php, src/Composer/Command/SuggestsCommand.php, src/Composer/Command/UpdateCommand.php, src/Composer/DependencyResolver/RuleSetGenerator.php, src/Composer/DependencyResolver/RuleSetIterator.php, src/Composer/DependencyResolver/Transaction.php, src/Composer/Downloader/PerforceDownloader.php, src/Composer/Factory.php, src/Composer/Json/JsonFile.php, src/Composer/Repository/BaseRepository.php, src/Composer/Repository/Pear/ChannelRest10Reader.php, src/Composer/Repository/Vcs/GitDriver.php, src/Composer/Repository/Vcs/PerforceDriver.php, src/Composer/Util/Perforce.php, src/Composer/Util/RemoteFilesystem.php, src/Composer/Util/Silencer.php, src/Composer/Util/StreamContextFactory.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_functions_with_include_paths.php, tests/Composer/Test/Package/Archiver/ArchiveManagerTest.php, tests/Composer/Test/Package/Loader/ArrayLoaderTest.php, tests/Composer/Test/Util/GitHubTest.php, tests/Composer/Test/Util/GitLabTest.php
Minor code tweaks:
- alias functions usage fixes
- is_null -> null ===
- one-time use variables
- array_push -> []=
- more minor stuff
PS: `break; // orcontinue 2?` - I'm not following the intention there
=> SCA with PHP Inspections (EA Extended)

.travis.yml
I think It's time to add PHP 7.2.
=> add PHP 7.2 in travis

doc/03-cli.md
Common and useful enough to be explicitly stated in docs
=> Add 'remove' to example global commands

tests/Composer/Test/AllFunctionalTest.php, tests/Composer/Test/Autoload/AutoloadGeneratorTest.php, tests/Composer/Test/DependencyResolver/SolverTest.php, tests/Composer/Test/Installer/SuggestedPackagesReporterTest.php, tests/Composer/Test/Package/Dumper/ArrayDumperTest.php, tests/Composer/Test/Repository/ArrayRepositoryTest.php, tests/Composer/Test/Repository/FilesystemRepositoryTest.php, tests/Composer/Test/Repository/Pear/ChannelReaderTest.php, tests/Composer/Test/Util/FilesystemTest.php
I've refactored some tests with [`assertFileExists`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertFileExists) and `assertFileNotExists`, [`assertFalse`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertFalse), [`assertTrue`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertTrue), [`assertCount`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertCount)  and [`assertEmpty`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertEmpty) methods.
=> Refactoring Tests

src/Composer/Command/CheckPlatformReqsCommand.php, src/Composer/Console/Application.php
=> Add command `check-platform-reqs`

src/Composer/DependencyResolver/RuleWatchNode.php, src/Composer/Package/Archiver/HgExcludeFilter.php, src/Composer/Util/Perforce.php
Small one: cleaned up the `else`s when we have already returned something :put_litter_in_its_place:
=> Clean elses

src/Composer/Command/DumpAutoloadCommand.php
I was a little bit confused, that the output is the same, regarding `-o` or `-a` option.
=> output used strategy

doc/03-cli.md, src/Composer/Command/RequireCommand.php
This is a behavior I was unaware of and I didn't feel it was clearly identified in the docs
=> clarify optionality of package in require command

doc/articles/scripts.md, res/composer-schema.json, src/Composer/Console/Application.php
=> Move "scripts-description" to toplevel

CHANGELOG.md, doc/00-intro.md, doc/01-basic-usage.md, doc/03-cli.md, doc/04-schema.md, doc/05-repositories.md, doc/07-community.md, doc/articles/handling-private-packages-with-satis.md, doc/articles/plugins.md, doc/articles/troubleshooting.md, doc/articles/versions.md, doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md
Some of the links were either not using https or linking to a redirecting page, so I fixed them.
=> [docs] Fix links

src/Composer/Package/Locker.php, src/Composer/Plugin/Capability/CommandProvider.php
=> Fix: Typo / wording

doc/03-cli.md, doc/04-schema.md, doc/05-repositories.md, doc/articles/aliases.md, doc/articles/autoloader-optimization.md, doc/articles/handling-private-packages-with-satis.md, doc/articles/plugins.md, doc/articles/scripts.md, doc/articles/troubleshooting.md, doc/articles/vendor-binaries.md, doc/articles/versions.md, doc/faqs/how-to-install-untrusted-packages-safely.md, doc/fixtures/fixtures.md
I removed all white spaces and extra lines from our documentation :smile: 
Also, ensure that all block of codes has their "type" declared.
=> Clean up documentation

src/Composer/Command/InitCommand.php, src/Composer/Package/Version/VersionParser.php
=> Add feature for issue #6892

src/Composer/Util/ConfigValidator.php, tests/Composer/Test/Util/ConfigValidatorTest.php, tests/Composer/Test/Util/Fixtures/composer_scripts-descriptions.json
=> Validation warns if script description for nonexistent script is present

doc/03-cli.md
Refers to #5121, commit f13e0f975f3b513b5bbe5f04f5eef05923b39843
=> Add option "no-secure-http" for create-project

src/Composer/Autoload/ClassLoader.php
Fix a missed space for string concatenation
=> Added space to concatenation

doc/articles/troubleshooting.md
as implemented in 882b82d542b45435bae1d95b33e225427950c59c
=> document the COMPOSER_MEMORY_LIMIT env var

doc/04-schema.md
Refers to #6635
English is not my primary language, I did my best but any feedback is very welcome.
=> Add abandoned property in composer schema documentation

res/composer-schema.json
=> add readme node to composer.json schema

doc/04-schema.md
=> move readme description one level up

src/Composer/Command/ConfigCommand.php
=> Update scripts for config command

res/composer-schema.json
=> Fix the JSON schema for package repositories

src/Composer/Repository/RepositoryManager.php
Some minor tweaks to help with IDE typehinting.
=> FIX Update PHPDocs to indicate more specific return types

doc/faqs/which-version-numbering-system-does-composer-itself-use.md
=> Document the versioning system used by Composer.

src/Composer/Repository/ArtifactRepository.php
=> Closing the ZipArchive in ArtifactRepository::getComposerInformation()

src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Command/ShowCommand.php, src/Composer/Command/StatusCommand.php, src/Composer/DependencyResolver/GenericRule.php, src/Composer/DependencyResolver/Problem.php, src/Composer/DependencyResolver/Rule2Literals.php, src/Composer/DependencyResolver/RuleSetGenerator.php, src/Composer/DependencyResolver/Transaction.php, src/Composer/Installer.php, src/Composer/Installer/BinaryInstaller.php, src/Composer/Json/JsonFile.php, src/Composer/Json/JsonFormatter.php, src/Composer/Package/Loader/RootPackageLoader.php, src/Composer/Package/Loader/ValidatingArrayLoader.php, src/Composer/Plugin/PluginManager.php, src/Composer/Util/Filesystem.php, src/Composer/Util/TlsHelper.php, src/Composer/Util/Url.php
Together with PHPStorm and https://github.com/kalessil/phpinspectionsea, here are some improvements that we can make to Composer :smile:
=> Improvements

src/Composer/Installer.php, src/Composer/Package/Archiver/ArchiveManager.php, src/Composer/Util/Git.php
A couple of micro-optimizations and tweaks around hardening security
=> [minor] SCA

src/Composer/Repository/PathRepository.php
Should address https://github.com/composer/composer/pull/7444#issuecomment-405940095
=> GLOB_BRACE is not defined on all platforms

src/Composer/Command/ShowCommand.php
I would like to resolve #7244.
I separated generation of tree from writing a tree to stdout
=> Support json format for 'show tree'

src/Composer/Command/RequireCommand.php
When you run `require some/package` and the process stops, the `composer.json` file doesn't get reverted. This PR adds a signal handler that captures when a process stops unexpectedly (E.G pressing ^C) and reverts the `composer.json` file
=> Revert composer.json changes when require process stops

src/Composer/Repository/Vcs/GitHubDriver.php
=> Fix typo in variable name in GitHubDriver

src/Composer/DependencyResolver/PoolBuilder.php, src/Composer/Repository/BaseRepository.php, src/Composer/Repository/ComposerRepository.php, tests/Composer/Test/Fixtures/installer/solver-problems.test
Part of https://github.com/composer/composer/issues/7630
=> Only load package versions which fit the root composer.json constraints

doc/00-intro.md, doc/03-cli.md
=> Replace OSX with macOS

src/Composer/Command/DiagnoseCommand.php
Change the warnings in diagnose to a friendly messages when allow_url_fopen is disabled.
If you have any suggestions please let me know.
Issue: #7622
=> Skip all network-based checks

src/Composer/Installer.php
=> Dispatch "post-package-update" event after writing lock

src/Composer/Console/Application.php
Following #7795 suggestion, 
I added a confirmation question before continue running Composer as root/super user.
=> Ask confirmation when is run as admin

composer.lock
while working on #7857 i found this little fellow.
might be caused by https://github.com/composer/composer/commit/4301c19ce3b2468ad841ca9f5f35ca5558fb005f#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780
=> Updating lock file hash

.travis.yml
This PR
Follows https://github.com/composer/composer/pull/7858.
=> Enhancement: Validate composer.json on Travis

src/Composer/EventDispatcher/EventDispatcher.php
Quite simple solution to solve #7850
=> Adding PHP_BINARY as env var to script execution

src/Composer/Autoload/AutoloadGenerator.php, tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
=> Fix: Keep replaced packages for autoload dumping with --no-dev

src/Composer/Package/Loader/ArrayLoader.php, src/Composer/Repository/ComposerRepository.php
Follow-up to https://github.com/composer/composer/pull/7904 - needs all packages to have been re-dumped though before it can be merged.
=> Cleanup of old compression algo

src/Composer/Command/ArchiveCommand.php, src/Composer/Command/ClearCacheCommand.php, src/Composer/Command/ConfigCommand.php, src/Composer/Command/CreateProjectCommand.php, src/Composer/Command/DependsCommand.php, src/Composer/Command/DiagnoseCommand.php, src/Composer/Command/DumpAutoloadCommand.php, src/Composer/Command/ExecCommand.php, src/Composer/Command/GlobalCommand.php, src/Composer/Command/HomeCommand.php, src/Composer/Command/InitCommand.php, src/Composer/Command/InstallCommand.php, src/Composer/Command/LicensesCommand.php, src/Composer/Command/OutdatedCommand.php, src/Composer/Command/ProhibitsCommand.php, src/Composer/Command/RemoveCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Command/RunScriptCommand.php, src/Composer/Command/ScriptAliasCommand.php, src/Composer/Command/SearchCommand.php, src/Composer/Command/SelfUpdateCommand.php, src/Composer/Command/ShowCommand.php, src/Composer/Command/StatusCommand.php, src/Composer/Command/SuggestsCommand.php, src/Composer/Command/UpdateCommand.php, src/Composer/Command/ValidateCommand.php
as initially suggested in #8005 with this PR we add "Read more at" links to all cli commands.
Replaces #8018
closes #8005
Example:
=> Added "Read more at" links to all commands

composer.json
I am not an English native speaker but I think the `ensure` verb is used for the `Composer` subject. So, it have to be `ensures`.
The current sentence is too long. Let's separate it into 2 smaller pieces for readable reason.
=> Correct description grammar

composer.json, composer.lock
Composer.json related side-note: will composer 2.0 raise the bar for the min php-version?
=> Fixed 2.0 branch alias

src/Composer/Repository/VcsRepository.php
=> Display branches and tags if verbose is specified

src/Composer/Util/Http/CurlDownloader.php
Lesson learned from https://github.com/symfony/flex/pull/486 and https://github.com/symfony/flex/pull/489
=> Let curl handle proxy and cipher list itself

src/Composer/Package/AliasPackage.php, src/Composer/Package/PackageInterface.php
expand interface and add missing methods to aliaspackage
=> fixes #8159

src/Composer/EventDispatcher/EventDispatcher.php, src/Composer/Script/Event.php, tests/Composer/Test/Script/EventTest.php
This PR implements the feature discussed in issue #8183.
=> allow Composer\Script\Event to reference originating event

tests/Composer/Test/AllFunctionalTest.php
Instead of count and comparing, we can simple use a foreach.
=> Make usage of foreach to improve readability

src/Composer/DependencyResolver/RuleSetGenerator.php
=> Ignore platform reqs now handle conflict rules

doc/articles/handling-private-packages-with-satis.md
This PR come with https://github.com/composer/satis/pull/509
=> Update only one package

src/Composer/Installer/PluginInstaller.php, src/Composer/Plugin/PluginInterface.php, src/Composer/Plugin/PluginManager.php, tests/Composer/Test/Plugin/Fixtures/plugin-v1/Installer/Plugin.php, tests/Composer/Test/Plugin/Fixtures/plugin-v2/Installer/Plugin2.php, tests/Composer/Test/Plugin/Fixtures/plugin-v3/Installer/Plugin2.php, tests/Composer/Test/Plugin/Fixtures/plugin-v4/Installer/Plugin1.php, tests/Composer/Test/Plugin/Fixtures/plugin-v4/Installer/Plugin2.php, tests/Composer/Test/Plugin/Fixtures/plugin-v5/Installer/Plugin5.php, tests/Composer/Test/Plugin/Fixtures/plugin-v6/Installer/Plugin6.php, tests/Composer/Test/Plugin/Fixtures/plugin-v7/Installer/Plugin7.php, tests/Composer/Test/Plugin/Fixtures/plugin-v8/Installer/Plugin8.php, tests/Composer/Test/Plugin/Fixtures/plugin-v9/Installer/Plugin.php, tests/Composer/Test/Plugin/PluginInstallerTest.php
Fixes #3000 and relies on https://github.com/composer/composer/commit/1b7e957cc1b62ad815dfdd4fab912bd8916e428f which was recently added without PR.
=> Plugin deactivation/uninstall support

doc/00-intro.md
There's other search engines as well.
=> Don't necessarily mention Google

doc/articles/troubleshooting.md
As per these issues:
https://github.com/composer/composer/issues/7186
https://github.com/composer/composer/issues/8152
=> Add Windows proc-open errors to troubleshooting.md

src/Composer/Util/RemoteFilesystem.php
Implements https://github.com/composer/composer/issues/8316
This currently output the used authentication for every http call even if the same origin gets called multiple times. If preferred I can also limit the output to once per origin.
=> Debug: display used authentication for http calls

src/Composer/Command/ShowCommand.php
=> Validate composer show with --tree and --path options set

src/Composer/Util/Git.php, tests/Composer/Test/Util/GitTest.php
Addresses: https://github.com/composer/composer/issues/8414
=> Git: fix authentication handling for private GitHub repositories

doc/03-cli.md, src/Composer/Command/ClearCacheCommand.php
Same as command update with up and install with i. 
I think it's a good idea to use cc for clear-cache, like npm command.
=> Added new Alias For Clear cache + Documentation

doc/01-basic-usage.md
Hello,
I add the `php composer.phar dump-autoload` command explicity because i didn't find it on the doc like this.
Cheers 😉
=> Update 01-basic-usage.md - add dump-autoload

.travis.yml, phpstan/config.neon
This PR
Perhaps slightly related to #8471.
=> Enhancement: Configure paths and autoload files via phpstan/config.neon

src/Composer/Repository/VcsRepository.php
While initializing a VCS repository via GitHub/GitLab/Bitbucket API composer catches every TransportException and treats the version as if there is no composer.json file. However in cases where the TransportException has a HTTP status code like 429 or 5XX we do not know whether there is a composer.json file or not. Tools like packagist.org should not treat such exceptions as "no composer.json file" as it will lead to the deletion of that version (it will then reappear with the next successful run).
Unfortunately without being able to load the composer.json we do not know what version a tag/branch refers to. I grouped the exceptions with `versionTransportExceptions` into branches and tags but I am not sure there is a more useful way.
This will also display the HTTP status code as part of …
=> VcsRepository: make transport exceptions during initialize run accessible

src/Composer/Command/DiagnoseCommand.php
This matches the platform checks in https://github.com/composer/getcomposer.org/blob/master/web/installer
=> Add Windows OneDrive to platform warnings

doc/01-basic-usage.md, src/Composer/Downloader/SvnDownloader.php, src/Composer/Util/Hg.php
https://english.stackexchange.com/questions/117552/why-does-information-not-have-a-plural-form
=> Fix nits on typos

src/Composer/Command/ExecCommand.php, src/Composer/Console/Application.php
=> Make `composer global exec` execute commands in working directory

doc/04-schema.md
This PR only updates the documentation.
=> Documentation: Explain the syntax of stability flags

src/Composer/Command/ConfigCommand.php, src/Composer/Json/JsonManipulator.php, tests/Composer/Test/Json/JsonManipulatorTest.php
Issue https://github.com/composer/composer/issues/5460
=> Implemented way to add packages into suggest through CLI

src/Composer/Command/ShowCommand.php
Resolves #8544, luckily most of the front work was already done in #7416
=> Add support for "composer show --format=json <package>" #8544

tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
=> Added test for exclude-from-classmap (see issue #8563)

src/Composer/Command/CreateProjectCommand.php
Fixing #8609 by reverting commit 43e0321ee74aa5efb9b720f8576145c351d7f3e3.
=> Create project with absolute path(fixes #8609)

src/Composer/Config/ConfigSourceInterface.php
I modified the document a bit in ConfigSourceInterface.php
=> add 'array' to document in ConfigSourceInterface.php

src/Composer/IO/BaseIO.php, src/Composer/Util/RemoteFilesystem.php
No documentation updates or additional tests yet. Would appreciate direction on tests.
=> Bearer support.

src/Composer/DependencyResolver/Problem.php, src/Composer/DependencyResolver/SolverProblemsException.php, src/Composer/Installer.php, src/Composer/Repository/ComposerRepository.php, src/Composer/Repository/RepositorySet.php, tests/Composer/Test/Fixtures/installer/provider-dev-require-can-satisfy-require.test, tests/Composer/Test/Fixtures/installer/provider-dev-require-cannot-satisfy-require.test
Addresses https://github.com/composer/composer/issues/8570
=> Handle dev extraction exit codes instead of completing broken lock with errors

src/Composer/DependencyResolver/PoolBuilder.php, tests/Composer/Test/Fixtures/installer/solver-problems.test
Replaces https://github.com/composer/composer/pull/8535
=> Optimize loading of deps from fixed packages

src/Composer/Command/RequireCommand.php
=> Add --dry-run to composer require

src/Composer/Package/Version/VersionGuesser.php
=> Fix: Return early

src/Composer/Command/RequireCommand.php, src/Composer/DependencyResolver/PoolBuilder.php, src/Composer/DependencyResolver/Problem.php, src/Composer/DependencyResolver/Rule.php, src/Composer/DependencyResolver/SolverProblemsException.php, tests/Composer/Test/Fixtures/installer/update-allow-list-require-new-replace.test
Follow up to https://github.com/composer/composer/pull/8717 addresses https://github.com/composer/composer/issues/8355 if require is used without --with-dependencies.
=> Give a clearer error message explaining how to update a conflicting locked dependency

src/Composer/DependencyResolver/Problem.php, src/Composer/DependencyResolver/Rule.php, src/Composer/DependencyResolver/SolverProblemsException.php, src/Composer/Package/AliasPackage.php, src/Composer/Package/Loader/ArrayLoader.php, tests/Composer/Test/Fixtures/installer/alias-solver-problems.test, tests/Composer/Test/Fixtures/installer/alias-solver-problems2.test
Fixes the dev-master alias issue as well as the other lock-related problem we found yesterday.
=> Error reporting improvements

src/Composer/DependencyResolver/Problem.php, src/Composer/DependencyResolver/Rule.php, src/Composer/Package/AliasPackage.php, src/Composer/Package/Loader/ArrayLoader.php, src/Composer/Package/Version/VersionGuesser.php, src/Composer/Package/Version/VersionParser.php, src/Composer/Repository/ComposerRepository.php, src/Composer/Repository/VcsRepository.php, tests/Composer/Test/Package/Version/VersionParserTest.php
as suggested in https://github.com/composer/composer/pull/8690/files#r404786378
=> extracted `VersionParser::DEV_MASTER_ALIAS`

res/composer-schema.json
=> Add the new repository options in the JSON schema

src/Composer/Command/StatusCommand.php
=> Dispatch POST_STATUS_CMD even when there is no changes

src/Composer/Command/RemoveCommand.php
=> Add --unused flag to remove command

res/composer-schema.json
This was missed in the removal.
=> Remove the pear repository type from the JSON schema

res/composer-schema.json
Reverts composer/composer#8792
=> Revert "Remove the pear repository type from the JSON schema"

src/Composer/Downloader/DownloadManager.php
Found it while working on https://github.com/composer/satis/pull/595
=> Remove unused property $httpDownloader

src/Composer/DependencyResolver/Transaction.php, tests/Composer/Test/DependencyResolver/TransactionTest.php, tests/Composer/Test/Fixtures/installer/partial-update-installs-from-lock-even-missing.test, tests/Composer/Test/Fixtures/installer/update-alias-lock2.test, tests/Composer/Test/Fixtures/installer/update-alias.test, tests/Composer/Test/Fixtures/installer/update-allow-list-with-dependencies-alias.test, tests/Composer/Test/Fixtures/installer/update-downgrades-unstable-packages.test, tests/Composer/Test/Fixtures/installer/update-no-dev-still-resolves-dev.test, tests/Composer/Test/Fixtures/installer/updating-dev-from-lock-removes-old-deps.test, tests/Composer/Test/InstallerTest.php, tests/Composer/Test/Mock/InstallationManagerMock.php
See individual commits for details, I tried to split it all up nicely to make sure travis shows failure etc.
=> Fix transaction order

.travis.yml
This check detects syntax errors like this one: #8759
=> Check syntax of PHP files in src

.github/workflows/continuous-integration.yml
This PR
Related to https://github.com/shivammathur/setup-php/issues/215.
=> Fix: Install ext-intl

README.md
Update the `Continuous Integration` status badge image URI in `README.md`.
=> fix: workflow status badge

doc/articles/scripts.md
I've heard about the field but was not aware of how to see the descriptions.
=> scripts: indicate how to see scripts-descriptions

src/Composer/DependencyResolver/Operation/SolverOperation.php
Fixes https://github.com/composer/composer/issues/8833
=> Provide default implementation for abstract method in interface for PHP < 5.3.9

tests/Composer/Test/Util/BitbucketTest.php
Adding unit tests for uncovered source-code in `Util\Bitbucket` class.
=> Additional Util\Bitbucket class test coverage

src/Composer/Repository/PlatformRepository.php, tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php
=> Do not throw deprecation on validation for composer-runtime-api

doc/03-cli.md
Addresses https://github.com/composer/composer/issues/7459 by listing these special arguments in the documentation.
=> Documentation: Clarify composer update mirrors/nothing/lock

src/Composer/DependencyResolver/PoolBuilder.php
to get better type coverage in this class, as we are in the process of changing it
=> Added phpdoc types for PoolBuilder

src/Composer/Package/Version/VersionSelector.php
Fixes getsentry/sentry-php#1008
=> Make the VersionSelector take Composer API/Runtime versions into account

src/Composer/Repository/ComposerRepository.php
Should make #8850 more efficient even though getting 304s back in async HTTP/2 persistent connections is quite fast.
=> Cache successful requests to make sure subsequent loadPackages calls do not do the same requests for nothing

UPGRADE-2.0.md, src/Composer/Command/CreateProjectCommand.php, src/Composer/Command/InitCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Command/ShowCommand.php, src/Composer/Package/Version/VersionSelector.php, tests/Composer/Test/Package/Version/VersionSelectorTest.php
Follow-up to https://github.com/composer/composer/pull/8871
=> Use all PlatformRepo packages in VersionSelector checks

.github/workflows/continuous-integration.yml
Refs: https://github.com/reactphp/promise/pull/161#issuecomment-624581608
=> Test PHP 8.0 with lowest dependencies

src/Composer/Util/Http/CurlDownloader.php
Closes https://github.com/composer/composer/issues/8939.
=> Fix for HHVM 3

doc/04-schema.md
added docs for the glob pattern feature added with https://github.com/composer/composer/pull/8923
=> Added docs for glob pattern support in classmaps

src/Composer/Util/RemoteFilesystem.php, tests/Composer/Test/Util/RemoteFilesystemTest.php
Additional test cases:
- copy() failure without retry case
- copy() success on retry case
=> Additional Util\RemoteFileSystem tests

src/Composer/DependencyResolver/PoolBuilder.php, src/Composer/Repository/RepositorySet.php, tests/Composer/Test/Fixtures/installer/aliases-with-require-dev.test
=> Fix inline aliases not being loaded when extracting dev requirements

.github/workflows/release.yml
@Seldaek can you create the necessary secret ?
Based on documentation: https://octokit.github.io/rest.js/v18#issues-create
https://github.com/settings/tokens/new?description=Token%20for%20composer/docker%20repository&scopes=public_repo
=> Create an issue @ Docker repository on tag

UPGRADE-2.0.md, doc/00-intro.md, doc/01-basic-usage.md, doc/02-libraries.md, doc/03-cli.md, doc/04-schema.md, doc/05-repositories.md, doc/06-config.md, doc/articles/aliases.md, doc/articles/autoloader-optimization.md, doc/articles/custom-installers.md, doc/articles/versions.md, doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md, doc/faqs/why-can't-composer-load-repositories-recursively.md
Contains multiple grammar fixes, including a few slightly opinionated ones backed by ngram statistics and university text recommendations :)
- `By default` changed to `By default,` (with comma)
- `can not` changed to `cannot` [[WSU](https://brians.wsu.edu/2016/05/31/cannot/)]
- `case insensitive` to `case-insensitive` [[ngram](https://books.google.com/ngrams/graph?content=case-insensitive%2Ccase+insensitive&year_start=1800&year_end=2008&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Ccase%20-%20insensitive%3B%2Cc0%3B.t1%3B%2Ccase%20insensitive%3B%2Cc0#t1%3B%2Ccase%20-%20insensitive%3B%2Cc0%3B.t1%3B%2Ccase%20insensitive%3B%2Cc0)]
- `machine readable` to `machine-readable` [[ngram](https://books.google.com/ngrams/graph?content=machine-readable%2C+machine+readable&year_start=1800&year_end=200 …
=> Multiple grammar fixes in markdown files

src/Composer/Util/GitLab.php
This PR is trying to improve the OAuth token prompt which appears if a user tries to install a VCS repository from GitLab without having any auth setup:
```
Installing acme-company/gitlab-test (dev-master jfdjhfdjhd): Cloning failed, enter your GitLab credentials to access private repos
A token will be created and stored in "/path/to/composer/project/auth.json", your password will never be stored
To revoke access to this token you can visit gitlab.com/profile/applications
Username: my-gitlab-user
Password:
Bad credentials.
You can also manually create a personal token at https://gitlab.com/profile/personal_access_tokens
```
Changes:
* The prompt now shows a message if the authentication failed because of 2FA which prevents OAuth tokens creation with the password grant
* GitLab has now …
=> GitLab: clarify interactive auth prompt

src/Composer/Command/SelfUpdateCommand.php
When called from a native shell and using cygwin PHP, cygpath translates
`/tmp` to `User\AppData\Local\Temp`, rather than `/cygdrive/.../tmp`.
This change does not affect using windows PHP from a Cygwin shell.
As before, using this compiled composer.phar: [composer-1.10-dev+8ddbae3.zip](https://github.com/composer/composer/files/4933043/composer-1.10-dev%2B8ddbae3.zip) (incidentally, it is still not possible to compile on Windows as seld/phar-utils needs to be at 1.1.1)
On Windows, create a test folder in C:\Program Files and copy this composer.phar here:
```cmd
mkdir "C:\Program Files\test"
copy /B <path to>\composer.phar "C:\Program Files\test\composer.phar"
```
To test:
```cmd
cd "C:\Program Files\test"
php composer.phar self-update
php composer.phar self-update --rollback
```
=> Remove cygwin php handling in UAC elevation

src/Composer/Command/CreateProjectCommand.php
Apologies for the previous (bungled) PR.
This is a patch to allow plugins which hook into the [pre-file-download plugin event](https://getcomposer.org/doc/articles/scripts.md#plugin-events) to interact with the create-project command. I created the patch as a result of an issue I found while using @naderman 's [composer-aws plugin](https://github.com/naderman/composer-aws) in combination with composer's create-project command ([issue here](https://github.com/naderman/composer-aws/issues/19)).
=> Supply event dispatcher in Create Project Command

src/Composer/Util/StreamContextFactory.php
=> added phpdocs in StreamContextFactory

doc/06-config.md, res/composer-schema.json, src/Composer/Cache.php, src/Composer/Command/ClearCacheCommand.php, src/Composer/Config.php, src/Composer/Downloader/FileDownloader.php, src/Composer/Factory.php, src/Composer/Repository/ComposerRepository.php, src/Composer/Repository/Vcs/BitbucketDriver.php, src/Composer/Repository/Vcs/GitDriver.php, src/Composer/Repository/Vcs/GitHubDriver.php, src/Composer/Repository/Vcs/GitLabDriver.php, src/Composer/Repository/Vcs/SvnDriver.php
=> Add a readonly mode to the cache

doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md
Just capitalised the word "But".
=> Capitalised the word "But" in point 3.

src/Composer/Command/CheckPlatformReqsCommand.php, src/Composer/Command/ConfigCommand.php, src/Composer/Command/ShowCommand.php, src/Composer/Command/StatusCommand.php, src/Composer/Command/SuggestsCommand.php, src/Composer/Command/ValidateCommand.php
Hey, this is some stuff I came across while debugging something.
- Removed unnecessary method calls
- Sorted conditions by cost
- Improved code readability
=> Performance improvements

src/Composer/Autoload/ClassMapGenerator.php, src/Composer/Command/ConfigCommand.php, src/Composer/Command/DiagnoseCommand.php, src/Composer/Command/InitCommand.php, src/Composer/Command/SelfUpdateCommand.php, src/Composer/Config/JsonConfigSource.php, src/Composer/Console/Application.php, src/Composer/DependencyResolver/DefaultPolicy.php, src/Composer/EventDispatcher/EventDispatcher.php, src/Composer/Factory.php, src/Composer/Installer/LibraryInstaller.php, src/Composer/Json/JsonManipulator.php, src/Composer/Package/Loader/ArrayLoader.php, src/Composer/Package/Loader/ValidatingArrayLoader.php, src/Composer/Package/Version/VersionGuesser.php, src/Composer/Package/Version/VersionParser.php, src/Composer/Repository/ComposerRepository.php, src/Composer/Repository/RepositoryFactory.php, src/Composer/Repository/VcsRepository.php, src/Composer/Util/Filesystem.php, src/Composer/Util/RemoteFilesystem.php, src/Composer/Util/StreamContextFactory.php, src/Composer/Util/Svn.php
Some additional code cleanups in those classes
I tried to only change code smells which shouldn't raise up discussions.
=> Micro optimization: Changed all substr calls used to compare fragments of text to strpos

src/Composer/Repository/ComposerRepository.php
This supplements the available-packages list so that repositories may
rule themselves out of a given name (and thus not be probed with lazy
load requests) by regex, as well as by exact name match.
The use case is sizeable and varying supplemental Composer repositories
such as packages.drupal.org, which otherwise must either maintain a list
of over 10k package names in their root packages.json or accept lots of
lazy-load requests for unrelated packages that will 404.
With this, we can just do `"available-package-regexes": ["drupal/*"]`, shrinking
the root repo file considerably and keeping its contents static.
=> Specify covered names with regexes in 2.x repos

src/Composer/DependencyResolver/SolverProblemsException.php
It feels like there is to much „them“ in there :-)
=> Improve error message further

src/Composer/Command/ShowCommand.php, src/Composer/Package/AliasPackage.php, src/Composer/Package/BasePackage.php, src/Composer/Package/Link.php, src/Composer/Package/Loader/ArrayLoader.php, src/Composer/Package/Locker.php, src/Composer/Package/RootAliasPackage.php, src/Composer/Repository/InstalledRepository.php, src/Composer/Repository/PlatformRepository.php, tests/Composer/Test/Autoload/AutoloadGeneratorTest.php, tests/Composer/Test/DependencyResolver/DefaultPolicyTest.php, tests/Composer/Test/DependencyResolver/SolverTest.php, tests/Composer/Test/DependencyResolver/TransactionTest.php, tests/Composer/Test/InstallerTest.php, tests/Composer/Test/Package/Dumper/ArrayDumperTest.php, tests/Composer/Test/Package/Version/VersionSelectorTest.php
Fix for #9210 
the PlatformRepository now sets the pretty constraint to Links.
I also introduced constants for the different Link types
=> Add pretty constraint

doc/05-repositories.md, src/Composer/Package/Loader/RootPackageLoader.php, src/Composer/Repository/PathRepository.php, tests/Composer/Test/Package/Loader/RootPackageLoaderTest.php, tests/Composer/Test/Repository/Fixtures/path/with-branch-version/composer.json, tests/Composer/Test/Repository/PathRepositoryTest.php
As discussed in https://github.com/composer/packagist/issues/1125 and in https://github.com/symfony/symfony/pull/38460
=> Add support for "extra.branch-version"

doc/04-schema.md
Refs https://github.com/composer/composer/issues/9311#issuecomment-714461855
=> Enhance the doc about provide to reduce mistakes

src/Composer/DependencyResolver/Transaction.php, src/Composer/Installer/InstallationManager.php, tests/Composer/Test/DependencyResolver/TransactionTest.php
Fixes #9333
Still needs documentation.
=> Fix plugin install order for plugins modifying downloads

src/Composer/Command/DiagnoseCommand.php
There is now no need for `checkHttpProxyFullUriRequestParam()` and `checkHttpsProxyFullUriRequestParam()` because we don't use the corresponding environment variables any more.
I've removed the lines below since I can't see how the condition can exist, because `Factory::createHttpDownloader()` will have already thrown a terminating NoSslException in this situation. Likewise it also throws a TransportError if a CA file cannot be found. 
https://github.com/composer/composer/blob/ec5f02018643ccd8a1d7f8ae41f3c6d8e01dab78/src/Composer/Command/DiagnoseCommand.php#L229-L231
I've reordered the tls warning, otherwise it "hides" an exception by reporting it as a WARNING rather than a FAIL.
=> Remove fulluri checks and tidy diagnose output

src/Composer/Autoload/AutoloadGenerator.php, tests/Composer/Test/Autoload/Fixtures/platform/no_extensions_required.php, tests/Composer/Test/Autoload/Fixtures/platform/no_php_required.php, tests/Composer/Test/Autoload/Fixtures/platform/no_php_upper_bound.php, tests/Composer/Test/Autoload/Fixtures/platform/replaced_provided_exts.php, tests/Composer/Test/Autoload/Fixtures/platform/specific_php_release.php, tests/Composer/Test/Autoload/Fixtures/platform/typical.php
=> Add new lines to platform reqs issues

src/Composer/Downloader/FileDownloader.php
=> Simplify code in FileDownloader.php

src/Composer/Package/Archiver/ZipArchiver.php, tests/Composer/Test/Package/Archiver/ZipArchiverTest.php
Fixes https://github.com/composer/composer/issues/9403
=> Remove CWD from only the beginning of a path in ZipArchiver

src/Composer/Installer.php, tests/Composer/Test/Fixtures/installer/partial-update-without-lock.test, tests/Composer/Test/Fixtures/installer/update-mirrors-fails-with-new-req.test
=> Fix mirror updates when adding new reqs and dev-reqs are present

src/Composer/Util/Filesystem.php
see https://3v4l.org/FJZNm
`@` operator in PHP 8.0 does NOT suppress fatal error thrown when a disabled function is called, thus we need to check explicitly if disabled first. `@` operator continues to hide php warnings thus the operator before the file function should stay.
This fix is fully BC.
```
Fatal error: Uncaught Error: Call to undefined function Composer\Util\symlink() in phar:///usr/local/bin/composer/src/Composer/Util/Filesystem.php:604
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Installer/BinaryInstaller.php(160): Composer\Util\Filesystem->relativeSymlink('/builds/mvorise...', '/builds/mvorise...')
#1 phar:///usr/local/bin/composer/src/Composer/Installer/BinaryInstaller.php(88): Composer\Installer\BinaryInstaller->installSymlinkBinaries('/builds/mvorise...', …
```
=> Fix for PHP 8.0 when symlink function is disabled

src/Composer/Util/Http/CurlDownloader.php
This is a follow up to https://github.com/composer/composer/pull/9592 that makes sure to add the response info to 3xx/4xx/5xx HTTP requests.
=> Add response info for 3xx/4xx/5xx HTTP responses

src/Composer/Util/Filesystem.php
drive-by micro-optimization while analyzing other things
=> Filesystem: use fast operation first in emptyDirectory()

src/Composer/Package/Archiver/BaseExcludeFilter.php, tests/Composer/Test/Package/Archiver/ZipArchiverTest.php
Fixes https://github.com/composer/composer/issues/9464, fixes https://github.com/composer/composer/issues/9600
=> #9464: ZipArchiver incorrectly treats `.gitignore` directory inclusions

src/Composer/Console/Application.php
=> Suppress error when chdir($oldWorkingDir); unsuccessful

.github/workflows/phpstan.yml, src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Autoload/ClassLoader.php, src/Composer/InstalledVersions.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_files_by_dependency.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_functions.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_functions_with_include_paths.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_functions_with_removed_include_paths_and_autolad_files.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_include_path.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_target_dir.php
Fixes issues like https://github.com/getsentry/sentry-symfony/issues/383
(the phpstan failure is a false-positive)
=> Ensure InstalledVersions reports info about all currently registered class loaders

doc/05-repositories.md, src/Composer/Package/Loader/RootPackageLoader.php, src/Composer/Repository/PathRepository.php, tests/Composer/Test/Package/Loader/RootPackageLoaderTest.php, tests/Composer/Test/Repository/Fixtures/path/with-branch-version/composer.json, tests/Composer/Test/Repository/PathRepositoryTest.php
Allows easily creating versioned package repositories out of collections of directories.
=> Handle "versions" option in PathRepository, remove support for "branch-version"

doc/articles/authentication-for-private-packages.md
=> docs: fix bad URL

src/Composer/Package/Loader/ArrayLoader.php, tests/Composer/Test/Fixtures/installer/unbounded-conflict-does-not-match-default-branch-with-numeric-branch.test
=> Remove default branch alias from versions which are numeric

src/Composer/Command/RequireCommand.php
I added a check and warning if the require (`require` vs `require-dev`) for a dependency which is already installed changes. I'm a bit unsure about the implementation and the messages, thus I created a draft before making it a proper pull request.
- #9516
=> Show a warning if require key changes for dependency

src/Composer/Util/Http/CurlDownloader.php, src/Composer/Util/Http/ProxyHelper.php, src/Composer/Util/RemoteFilesystem.php
Nothing major here: the only thing of note is actually using `$this->proxyManager` in RemoteFilesystem.php.
https://github.com/composer/composer/blob/dfc69140fe720b169b978b18b7863611cc0d8077/src/Composer/Util/RemoteFilesystem.php#L77
=> Proxy handling docs and tweaks

src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Autoload/ClassMapGenerator.php, src/Composer/Command/ConfigCommand.php, src/Composer/Command/InitCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Command/SelfUpdateCommand.php, src/Composer/Command/ValidateCommand.php, src/Composer/Config/JsonConfigSource.php, src/Composer/Console/Application.php, src/Composer/Installer/LibraryInstaller.php, src/Composer/Util/Filesystem.php, src/Composer/Util/StreamContextFactory.php
=> Introduce a cross-platform safe version of is_readable to support UNC / wsl$ paths on Windows

src/Composer/DependencyResolver/Problem.php, tests/Composer/Test/Fixtures/installer/hint-main-rename.test
=>  Hint at a branch rename if we detect dev-master can not be found and condense dev-* versions in problem output

doc/articles/authentication-for-private-packages.md
Love the docs! I thought it would be helpful to link to GitLab's documentation about how to create an access token.
=> Link to GitLab documentation for auth

composer.json, composer.lock
Similar to #8432 this would unlock the CI
=> Allows Symfony 6.0

doc/articles/troubleshooting.md, src/Composer/DependencyResolver/Problem.php, tests/Composer/Test/Fixtures/installer/circular-dependency-errors.test
=> Detect and output a better hint for cyclic dependencies

src/Composer/Command/ValidateCommand.php
Implements #9842 
I tried writing contained code that works in 5.3. I'm not sure if this should live in it's own class and if there is a way to UT this, please let me know if you want anything changed!
=> Detect missing packages that are a requirement or dev-requirement but not locked

src/Composer/Package/Package.php, src/Composer/Util/ComposerMirror.php
=> Add support for mirror-style placeholders for the dist url

src/Composer/Command/DiagnoseCommand.php, src/Composer/Downloader/ArchiveDownloader.php, src/Composer/Downloader/FileDownloader.php, src/Composer/Downloader/ZipDownloader.php, src/Composer/Util/Filesystem.php, tests/Composer/Test/Downloader/ZipDownloaderTest.php, tests/Composer/Test/Fixtures/functional/installed-versions.test, tests/Composer/Test/Fixtures/functional/installed-versions2.test
This is a quick and dirty PRto share an experiment I've been doing on Windows to speedup extracting ZIP files.
=> Speedup extracting on Windows

src/Composer/Autoload/AutoloadGenerator.php
=> Fix autoload generation for dev dependencies when --no-scripts is used

src/Composer/Command/AboutCommand.php
Hi,
I found relevant to add this info in the `composer about` output
Even if it is already present in the `composer -V` as well
Feel free to close :)
=> Add Composer version in about command

src/Composer/Repository/ComposerRepository.php
`if ($cacheKey)` is always true because it's concatenated with literal parts a few lines above :)
=> Simplify code

.github/workflows/phpstan.yml, src/Composer/Util/Perforce.php
The latest PHPStan fixes the ignored error :)
=> Update PHPStan and remove ignore

src/Composer/InstalledVersions.php, src/Composer/Repository/RepositoryManager.php, src/Composer/Util/Filesystem.php, tests/Composer/Test/Fixtures/functional/installed-versions2/vendor/composer/InstalledVersions.php, tests/Composer/Test/Fixtures/installer/update-reference.test
Just scratching a grammatical itch.
Sorry if this is the wrong branch to merge with, It's not a critical fix, so I didn't choose 1.10
=> Just some comments with 'it's' that should have been 'its'

tests/Composer/Test/DependencyResolver/SolverTest.php
Not a case with regular Packagist packages, but some custom installers with custom repos do this, and the current behavior should not randomly change at some point, as that would cause downstream breakage.
As discussed with / requested by @naderman
=> tests for solver handling multiple packages with same name and version

tests/Composer/Test/Package/Archiver/ArchivableFilesFinderTest.php, tests/Composer/Test/Package/Archiver/ArchiveManagerTest.php, tests/Composer/Test/Package/Archiver/GitExcludeFilterTest.php, tests/Composer/Test/Package/Archiver/HgExcludeFilterTest.php, tests/Composer/Test/Package/Archiver/PharArchiverTest.php, tests/Composer/Test/Package/Archiver/ZipArchiverTest.php, tests/Composer/Test/Package/BasePackageTest.php, tests/Composer/Test/Package/CompletePackageTest.php, tests/Composer/Test/Package/Dumper/ArrayDumperTest.php, tests/Composer/Test/Package/Loader/ArrayLoaderTest.php, tests/Composer/Test/Package/Loader/RootPackageLoaderTest.php, tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php, tests/Composer/Test/Package/LockerTest.php, tests/Composer/Test/Package/RootAliasPackageTest.php, tests/Composer/Test/Package/Version/VersionParserTest.php, tests/Composer/Test/Package/Version/VersionSelectorTest.php
=> Add types to `Package` tests

src/Composer/Console/GithubActionError.php
refs https://github.com/composer/composer/pull/10243/files#r741054182
=> Fix GithubActionError on php 8.1

src/Composer/Cache.php, src/Composer/Command/ConfigCommand.php, src/Composer/Command/GlobalCommand.php, src/Composer/Config.php, src/Composer/Console/Application.php, src/Composer/Console/GithubActionError.php, src/Composer/Downloader/GitDownloader.php, src/Composer/Downloader/PathDownloader.php, src/Composer/EventDispatcher/EventDispatcher.php, src/Composer/Factory.php, src/Composer/Installer/InstallationManager.php, src/Composer/Package/Loader/RootPackageLoader.php, src/Composer/Repository/PathRepository.php, src/Composer/Util/Git.php, src/Composer/Util/HttpDownloader.php, src/Composer/Util/Platform.php, src/Composer/Util/StreamContextFactory.php, tests/Composer/Test/EventDispatcher/EventDispatcherTest.php
=> Read first from $_SERVER and $_ENV before using getenv

src/Composer/Autoload/AutoloadGenerator.php
Trying to help move #10024 forward.
=> Fix loading files section for plugins

src/Composer/Repository/ComposerRepository.php, src/Composer/Util/Http/CurlDownloader.php
=> Add retry behavior on certain http status and curl error codes

doc/03-cli.md, src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php, src/Composer/Package/BasePackage.php, src/Composer/Repository/FilterRepository.php, tests/Composer/Test/Autoload/AutoloadGeneratorTest.php, tests/Composer/Test/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilterTest.php, tests/Composer/Test/Fixtures/installer/install-ignore-platform-package-requirement-list.test, tests/Composer/Test/Fixtures/installer/install-ignore-platform-package-requirement-wildcard.test, tests/Composer/Test/Fixtures/installer/update-ignore-platform-package-requirement-list.test, tests/Composer/Test/Fixtures/installer/update-ignore-platform-package-requirement-wildcard.test, tests/Composer/Test/Package/BasePackageTest.php
This is the implementation of what is described in #10045 and the follow-up of #10079.
=> Add wildcard support to ignore platform req

src/Composer/Autoload/AutoloadGenerator.php, src/Composer/EventDispatcher/EventDispatcher.php, src/Composer/Plugin/PluginManager.php
Fix #10277
Files should be included only after the autoloader has been registered.
=> Fix loading files for plugins/scripts

doc/05-repositories.md
super minor thing that I noticed
=> Fix spelling of Bitbucket

doc/06-config.md, res/composer-schema.json, src/Composer/Command/ConfigCommand.php, src/Composer/Command/InitCommand.php, src/Composer/Command/ShowCommand.php, src/Composer/DependencyResolver/Problem.php, src/Composer/Package/Loader/ValidatingArrayLoader.php, src/Composer/Repository/PlatformRepository.php, tests/Composer/Test/Fixtures/installer/solver-problems-with-disabled-platform.test, tests/deprecations-8.1.json
=> Add support for setting platform packages to false to disable them

src/Composer/Autoload/AutoloadGenerator.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_files_by_dependency.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_functions.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_functions_with_include_paths.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_target_dir.php, tests/Composer/Test/Fixtures/functional/installed-versions2/vendor/composer/autoload_real.php
=> Allow recursively call composerRequire

doc/06-config.md, res/composer-schema.json, src/Composer/Command/ConfigCommand.php, src/Composer/Config.php, src/Composer/Console/Application.php
Resolves: #10299 
I'm far off being done, since I haven't got any tests for this new feature (and don't even know if you'd want to have it), so it'll stay at WIP state for now.
=> [FEATURE] Configure automatic yes for composer.json in upper directory

doc/00-intro.md
=> docs: Highlight sudo

src/Composer/Repository/PathRepository.php
Also adds dev-master alias for BC, fixes #10360
=> Switch the default version in path repo packages to dev-main

src/Composer/Plugin/PluginManager.php, tests/Composer/Test/Plugin/Fixtures/files_autoload_which_should_not_run.php, tests/Composer/Test/Plugin/PluginInstallerTest.php
=> Fix plugin autoloading including files autoload rules from the root package

src/Composer/Console/Application.php, src/Composer/IO/BaseIO.php
Fixed the described warnings in #10397
=> Fix symfony error handler warnings, fixes #10397

src/Composer/IO/ConsoleIO.php, src/Composer/Util/ProcessExecutor.php, tests/Composer/Test/Package/Archiver/ArchivableFilesFinderTest.php, tests/Composer/Test/Question/StrictConfirmationQuestionTest.php
Congratulations for getting rid of PHP 5 and ancient Symfony packages. 🎉
=> Remove obsolete Symfony feature detections

composer.json, composer.lock, phpstan/baseline-8.1.neon, phpstan/baseline.neon
=> Update to PHPStan 1.4

composer.json, composer.lock, phpstan/baseline.neon
=> Update to PHPStan 1.4.1

doc/03-cli.md
=> Improve documentation

composer.lock, src/Composer/Autoload/PhpFileCleaner.php, src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php, src/Composer/Package/Archiver/BaseExcludeFilter.php, src/Composer/Package/BasePackage.php, src/Composer/Plugin/PluginManager.php, src/Composer/Question/StrictConfirmationQuestion.php, src/Composer/Repository/ComposerRepository.php, src/Composer/Repository/FilterRepository.php, tests/Composer/Test/Package/BasePackageTest.php
=> update composer/pcre to 1.0.1

src/Composer/Installer/InstallerInterface.php
refs https://github.com/composer/composer/discussions/10523#discussioncomment-2132413
=> InstallerInterface: describe `getInstallPath()` to return a absolute path

src/Composer/Repository/Vcs/GitBitbucketDriver.php, src/Composer/Repository/Vcs/GitHubDriver.php, src/Composer/Repository/Vcs/GitLabDriver.php, tests/Composer/Test/Repository/Vcs/GitBitbucketDriverTest.php, tests/Composer/Test/Repository/Vcs/GitHubDriverTest.php
```
{
{"type": "github", "url": "https://github.com/acme"}
],
"require": {
"smarty/smarty": "*"
}
}
```
```
composer update                                                                  
[ErrorException]
Undefined array key 3
update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] …
```
=> VcsRepositories: handle initialize with invalid repository URL

src/Composer/Command/StatusCommand.php, src/Composer/Downloader/FileDownloader.php, src/Composer/Downloader/FossilDownloader.php, src/Composer/Downloader/GitDownloader.php, src/Composer/Downloader/HgDownloader.php, src/Composer/Downloader/SvnDownloader.php, src/Composer/Package/Comparer/Comparer.php
=> Fix #10575

src/Composer/Command/ArchiveCommand.php
just a tiny drive-by PR. not sure if this counts as "fix" for 2.2, just let me know :)
=> Add file agument to archive help

.github/workflows/close-stale-support.yml
This pull request
💁‍♂️ For reference, see https://github.com/actions/stale/compare/v3...v5.
=> Enhancement: Update `actions/stale`

.github/workflows/release.yml
This pull request
💁‍♂️ For reference, see https://github.com/actions/github-script/compare/v2...v6.
=> Enhancement: Update `actions/github-script`

src/Composer/Command/RemoveCommand.php
Fixing #10599. No idea if this approach is too lazy
=> Remove allow-plugin config on remove of plugin

src/Composer/Installer/InstallationManager.php
To make it easier to grep the source for those.
=> Inline PackageEvents constants

src/Composer/Util/Http/CurlDownloader.php
`size_download` of the `$progress` array  for gzipped responses refers to the gzipped size making it possible to download larger files than specified via the `max_file_size` if no `Content-Length` header is defined in the response.
=> CurlDownloader: detect max file size for gzipped responses with missing content-length header

src/Composer/Repository/Vcs/GitHubDriver.php
See GitHub documentation https://docs.github.com/en/rest/repos/contents#size-limits
=> GitHub: add support for files >1MB to getFileContent

src/Composer/Json/JsonFormatter.php
=> replace 'for' loop with 'str_repeat' function

doc/00-intro.md
Basic docker information added.  Given Docker is one of the key development environments I think it is worth adding some basic information.
I know this isn't officially supported, so I have added the details on where issues should be posted.
I hope this is agreeable.
=> Add Docker information

composer.json, doc/articles/plugins.md
refs https://github.com/composer/composer/pull/10635
=> plugins: mention static analysis support

doc/03-cli.md, src/Composer/Command/BumpCommand.php, src/Composer/Command/CompletionTrait.php, src/Composer/Command/RequireCommand.php, src/Composer/Console/Application.php, src/Composer/Package/Version/VersionBumper.php, tests/Composer/Test/Command/BumpCommandTest.php, tests/Composer/Test/Mock/FactoryMock.php, tests/Composer/Test/Mock/InstallationManagerMock.php, tests/Composer/Test/Package/Version/VersionBumperTest.php, tests/Composer/Test/TestCase.php
=> Add bump 👊🏻 command to bump requirements to the currently installed version

doc/articles/resolving-merge-conflicts.md
=> Hint at improved merge conflict resolving

doc/03-cli.md
Hello :wave: 
I tried the new autocompletion feature and thought I was doing something wrong, until I accidentally discovered the `completion.bash` file in the directory I was working in. Yes, I didn't remember what `>` is doing :sweat_smile: 
To make it more clear, what happens, I slightly adjusted the docs. Hope that helps other people, too :slightly_smiling_face:
=> Improve documentation about the new bash completion feature

src/Composer/Repository/Vcs/GitDriver.php, tests/Composer/Test/Repository/Vcs/GitDriverTest.php
refs https://github.com/composer/composer/discussions/10949#discussioncomment-3206578
=> Only fetch remote default branch for mirrored git repos, not local ones

doc/articles/handling-private-packages.md
In issue composer/satis#656 somebody mentioned the docs still show an example with invalid json.
The PR fixes the docs, not the original problem.
=> Fix docs for issue composer/satis#656

tests/Composer/Test/Command/AboutCommandTest.php
=> Test for About command

doc/05-repositories.md
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Docs update
**What is the current behavior?** (You can also link to an open issue here)
Typo in word "wordpress"
**What is the new behavior (if this is a feature change)?**
Fixed typo to "WordPress"
**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No
**Other information**:
Other occurrences of the word were already spelled correctly.
=> Fix typo in "WordPress"

tests/Composer/Test/Command/ClearCacheCommandTest.php
Hello! I saw this **Good First Issue** https://github.com/composer/composer/issues/10796
I created this PR that adds some tests for the **Clear Cache Command**.
Code coverage improves for this command class from 20% to 82% (approximate).
=> Added tests for Clear Cache Command.

tests/Composer/Test/Command/LicensesCommandTest.php, tests/Composer/Test/LicenseCommandTest.php
Added a new LicensesCommandTest which gives 100% coverage on `Composer\Command\LicensesCommand`.
=> Added new `LicensesCommandTest` class

tests/Composer/Test/Command/InitCommandTest.php
This commit adds tests for all the different input options.
=> Added lots of new tests for `InitCommand`

tests/Composer/Test/Command/BumpCommandTest.php
I've added tests for the BumpCommand to increase the test coverage.
See #10796
Signed-off-by: Jesper Skytte <jesper@skytte.it>
=> Add tests for BumpCommand

tests/Composer/Test/Command/CheckPlatformReqsCommandTest.php
Created a test for the CheckPlatformReqsCommand which increases coverage from 8% to 76%.
=> test: Create test for CheckPlatformReqsCommand

tests/Composer/Test/Command/FundCommandTest.php
This PR adds test coverage to the fund command bringing coverage from 7% to 82%.
=> Adds test coverage to the Fund Command

src/Composer/Command/ShowCommand.php, tests/Composer/Test/Command/ShowCommandTest.php
=> Add message when doing composer outdated --direct and there is nothing to show

src/Composer/Installer.php
When running `composer install` in a state where all packages are already installed, the following output will be shown:
```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating autoload files
61 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```
When there is any dependency that relies on an alias, a different output will be shown however:
```diff
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
- Nothing to install, update or remove
+ Package operations: 0 installs, 0 updates, 0 removals
Generating autoload files
61 packages you are …
```
=> Fix output inconsistencies when aliases are being used when running 'composer install'

src/Composer/Command/ExecCommand.php, src/Composer/Command/RunScriptCommand.php, src/Composer/IO/ConsoleIO.php
=> Add interactive prompt for which script/binary to run if run-script/exec is called without arg

CODE_OF_CONDUCT.md
=> Update Code of Conduct to Contributor Covenant v2.1

src/Composer/IO/IOInterface.php
I am not into all the details, so I am not 100% confident the phpdoc matches the implementation.
=> Conditional return type for `IOInterface::select()`

phpstan/baseline-8.1.neon, phpstan/baseline.neon, src/Composer/Command/ArchiveCommand.php
=> Improve version selection in archive command

src/Composer/Repository/ComposerRepository.php
=> Allow v2 metadata target to provide security advisories without releases

src/Composer/Command/RequireCommand.php, src/Composer/Console/Application.php, tests/Composer/Test/Command/RequireCommandTest.php
=> Warn when require ends up auto-selecting a feature branch

.github/workflows/autoloader.yml, src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Autoload/ClassLoader.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_files_by_dependency.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_functions.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_functions_with_include_paths.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_target_dir.php, tests/Composer/Test/Autoload/MinimumVersionSupport/Foo.php, tests/Composer/Test/Autoload/MinimumVersionSupport/composer.json, tests/Composer/Test/Autoload/MinimumVersionSupport/main.php, tests/Composer/Test/Autoload/MinimumVersionSupport/test.php
=> Fix autoloading on PHP 5.6

src/Composer/Package/Archiver/ArchiveManager.php, tests/Composer/Test/Package/Archiver/ArchiveManagerTest.php
Issue #11235
Adds default exclude patterns for the "archive" command based on the target file name.
=> Default exclude patterns for the "archive" command

src/Composer/DependencyResolver/SolverProblemsException.php
I do not exactly know the minimum reproduction, but I had this notice when executing composer. This fix the notice without altering the behaviour.
=> Fix strpos deprecation notice

src/Composer/DependencyResolver/Solver.php
=> Removed unused private `Solver::enableDisableLearnedRules` method

doc/articles/plugins.md, src/Composer/Plugin/PluginManager.php
=> Add extra.plugin-optional to auto-disable plugins in non-interactive mode

src/Composer/Installer/PluginInstaller.php
Same as https://github.com/composer/composer/pull/11318 for 2.2
=> Added optional plugin check in PluginInstaller

composer.json, doc/04-schema.md, res/composer-schema.json, src/Composer/Package/CompletePackage.php, src/Composer/Package/CompletePackageInterface.php, src/Composer/Package/Loader/ValidatingArrayLoader.php, tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php
This support option allows projects to specify a URL to the project's vulnerability disclosure policy (VDP).
=> Add security to support options

src/Composer/Util/Http/CurlDownloader.php
=> Fix basic auth infinite loop

src/Composer/DependencyResolver/PoolBuilder.php
Instead we just directly check if any currently loaded package requires the package to be loaded optionally.
=> Remove optional package loading to simplify pool builder

src/Composer/Installer/BinaryInstaller.php
=> Fixed binary proxies to return whatever the original binary returns as well

src/Composer/Repository/ArtifactRepository.php, src/Composer/Repository/VcsRepository.php
=> Add support for env vars and ~ (for HOME) in repo paths for vcs/artifact repos

src/Composer/Repository/RepositorySet.php
=> Support advisories from multiple repositories for the same package

tests/Composer/Test/Command/InstallCommandTest.php
re: #10796 
Adds some initial tests for the Install command. I think there is some more work to do here in improving tests on the happy path but this gets us started at least.
Would appreciate some guidance/feedback on other test cases that could improve this.
Thanks
=> Test install command

composer.json, composer.lock
=> Allow Symfony7 package installs

src/Composer/Json/JsonFile.php
=> Handle better nullable file parameter

phpstan/baseline.neon, tests/Composer/Test/Autoload/AutoloadGeneratorTest.php, tests/Composer/Test/ConfigTest.php, tests/Composer/Test/Downloader/DownloadManagerTest.php, tests/Composer/Test/Downloader/FileDownloaderTest.php, tests/Composer/Test/Downloader/GitDownloaderTest.php, tests/Composer/Test/EventDispatcher/EventDispatcherTest.php, tests/Composer/Test/IO/ConsoleIOTest.php, tests/Composer/Test/Installer/SuggestedPackagesReporterTest.php, tests/Composer/Test/Mock/IOMock.php, tests/Composer/Test/Repository/Vcs/GitDriverTest.php, tests/Composer/Test/TestCase.php, tests/Composer/Test/Util/BitbucketTest.php, tests/Composer/Test/Util/GitHubTest.php, tests/Composer/Test/Util/GitLabTest.php
Refs https://github.com/sebastianbergmann/phpunit/issues/4564 - this gets us ready for an upgrade eventually, and adding an IOMock is anyway a good thing to be able to assert input/output more easily there.
=> Add IOMock and get rid of all withConsecutive calls in tests

.gitattributes
Fixes https://github.com/composer/composer/issues/11507
=> Ensure phpstan/rules.neon is exported

tests/Composer/Test/Command/ReinstallCommandTest.php
Adds tests for the `ReinstallCommand` as mentioned in #10796
=> Re install command test

.gitignore
Just adding .vscode dir to the gitignore file
=> Adds .vscode dir to gitignore file

composer.json, composer.lock, phpstan/baseline.neon, src/Composer/Downloader/ArchiveDownloader.php, src/Composer/Downloader/DownloadManager.php, src/Composer/Downloader/DownloaderInterface.php, src/Composer/Downloader/GitDownloader.php, src/Composer/Downloader/SvnDownloader.php, src/Composer/Downloader/VcsDownloader.php, src/Composer/Downloader/ZipDownloader.php, src/Composer/Installer/InstallationManager.php, src/Composer/Installer/InstallerInterface.php, src/Composer/Installer/LibraryInstaller.php, src/Composer/Package/Version/VersionGuesser.php, src/Composer/Repository/ComposerRepository.php, src/Composer/Util/Filesystem.php, src/Composer/Util/HttpDownloader.php, src/Composer/Util/Loop.php, src/Composer/Util/ProcessExecutor.php, src/Composer/Util/SyncHelper.php, tests/Composer/Test/Downloader/ZipDownloaderTest.php, tests/Composer/Test/Util/ProcessExecutorTest.php
Needs a react/promise 3.x release to happen first, then this can be finalized
=> Use Promise::done where possible, upgrade react/promise to allow v3

doc/04-schema.md
Just updating the casing here; as Silverstripe have changed their casing.
You can see more here
https://www.silverstripe.com/about-us/our-brand/
=> Update Silverstripe casing

doc/04-schema.md
=> Changed psr/logger to psr/log

src/Composer/Advisory/Auditor.php, tests/Composer/Test/Advisory/AuditorTest.php
=> Fix abandoned package list JSON serialization

src/Composer/DependencyResolver/PoolBuilder.php, src/Composer/DependencyResolver/Request.php, src/Composer/Installer.php, src/Composer/Repository/RepositorySet.php, tests/Composer/Test/DependencyResolver/PoolBuilderTest.php
=> Optimize show -a by loading only the requested package

src/Composer/Util/Filesystem.php
=> Fix error when vendor dir contains broken symlinks

tests/Composer/Test/Command/ShowCommandTest.php
I've added more tests for the `Composer\Command\ShowCommand` command to increase the test coverage.
Please add suggestions for changes :)
=> 10796 Increase coverage of ShowCommand

src/Composer/Command/BaseDependencyCommand.php, tests/Composer/Test/Command/BaseDependencyCommandTest.php
This was inspired by and might fix https://github.com/composer/composer/issues/11690
=> Suggest running 'require' not 'update' if package is a root requirement

doc/articles/scripts.md, res/composer-schema.json, src/Composer/Command/ScriptAliasCommand.php, src/Composer/Config/JsonConfigSource.php, src/Composer/Console/Application.php, src/Composer/Util/ConfigValidator.php, tests/Composer/Test/Command/RunScriptCommandTest.php, tests/Composer/Test/Util/ConfigValidatorTest.php, tests/Composer/Test/Util/Fixtures/composer_scripts-aliases.json
Closes: https://github.com/composer/composer/issues/11420
I added the functionality and tests and updated relevant documentation I found.
=> Add support for "scripts-aliases" in composer.json

src/Composer/Downloader/DvcsDownloaderInterface.php, src/Composer/Downloader/FileDownloader.php, src/Composer/Downloader/VcsCapableDownloaderInterface.php
I noticed these comments are not consistent with other instances so I fixed them.
=> Fix PackageInterface parameter comments

doc/articles/plugins.md
This PR adds some clarity for the plugin documentation
=> Update plugin documentation

src/Composer/Package/Loader/ValidatingArrayLoader.php, tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php
=> Add detection of constraints which do not match anything in validate command

src/Composer/Util/Bitbucket.php, src/Composer/Util/GitHub.php, src/Composer/Util/GitLab.php
links now display on their own line
=> issue #11811 auth token links on separate lines

doc/03-cli.md, doc/06-config.md, src/Composer/Advisory/Auditor.php, src/Composer/Config.php, tests/Composer/Test/Advisory/AuditorTest.php, tests/Composer/Test/ConfigTest.php
=> Introduce COMPOSER_AUDIT_ABANDONED env var

.gitignore, tests/Composer/Test/AllFunctionalTest.php, tests/Composer/Test/Command/SelfUpdateCommandTest.php
https://github.com/composer/composer/issues/10796
Hello!
I added some tests for ```SelfUpdateCommand```.
Coverage increased from 0% to an approximate 40%.
=> Add tests for SelfUpdateCommand

CHANGELOG.md, UPGRADE-2.0.md
=> chore: remove repetitive words

res/composer-schema.json, src/Composer/Package/Package.php, src/Composer/Package/PackageInterface.php
Updating the `php-ext` section shape in `composer.json` to support the newer properties we added ThePHPF/pie-design#12 and ThePHPF/pie-design#10
=> Updated array shape of php-ext options

src/Composer/Config/JsonConfigSource.php, src/Composer/Json/JsonManipulator.php, tests/Composer/Test/Command/ConfigCommandTest.php
=> Ability to remove autoload* keys with cli

src/Composer/Package/Version/VersionBumper.php, tests/Composer/Test/Package/Version/VersionBumperTest.php
=> Fix some edge cases of tilde constraints in bump command

res/composer-schema.json
Reference: https://github.com/ThePHPF/pie-design/pull/18
=> Update schema for php-ext section to add needs-value flag

composer.json, composer.lock, phpstan/baseline-8.3.neon, phpstan/baseline.neon, phpstan/config.neon, src/Composer/Command/ConfigCommand.php, src/Composer/Command/InitCommand.php, src/Composer/Compiler.php, src/Composer/Downloader/GitDownloader.php, src/Composer/Installer/BinaryInstaller.php, src/Composer/Platform/Runtime.php, src/Composer/Repository/PlatformRepository.php, src/Composer/Repository/Vcs/GitDriver.php, src/Composer/Repository/Vcs/GitHubDriver.php, src/Composer/Repository/Vcs/GitLabDriver.php, src/Composer/Repository/Vcs/SvnDriver.php, src/Composer/Util/ErrorHandler.php, src/Composer/Util/Git.php, src/Composer/Util/Hg.php, tests/Composer/Test/AllFunctionalTest.php
Requires these to be fixed for all remaining errors to go away:
Last blocker is to have a composer/pcre release and a phpstan release.
=> Update phpstan and add composer/pcre extensions

src/Composer/Downloader/GitDownloader.php, src/Composer/Repository/Vcs/GitDriver.php, src/Composer/Repository/Vcs/HgDriver.php
=> Sanitize VCS URLs when building cache keys

phpstan/baseline.neon, src/Composer/Command/ShowCommand.php
=> Provide release-date in composer outdated -A -f json

doc/faqs/how-to-install-untrusted-packages-safely.md, src/Composer/Console/Application.php, src/Composer/Util/Platform.php
=> Improvements to docker detection

tests/Composer/Test/Command/UpdateCommandTest.php
re: #10796
Added two cases for update command interactive mode.
=> Add Update Interactive tests

src/Composer/Repository/PlatformRepository.php
=> Fix duplicate libraries causing issues when conflicting extensions from core and pecl are installed concurrently

doc/03-cli.md, doc/06-config.md, src/Composer/Advisory/Auditor.php, src/Composer/Command/AuditCommand.php, src/Composer/Command/BaseCommand.php, src/Composer/Config.php
=> Add `--abandoned` option

src/Composer/DependencyResolver/Problem.php
Fixes #11669
Example output:
```
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Root composer.json requires PHP extension ext-mbstring * but the ext-mbstring package is disabled by your platform config. Enable it again with "composer config platform.ext-mbstring --unset".
Alternatively you can require one of these packages that provide the extension (or parts of it):
- symfony/polyfill-mbstring Symfony polyfill for the Mbstring extension
- protoqol/quo-php PHP - Quo package.
- lucifer/domain 域名和url解析器
- masteryoda101/database Symfony polyfill for the Mbstring extension
- symfony70/polyfill-mbstring PHP 7.0 support for: Symfony polyfill for the Mbstring extension
To enable …
```
=> Add suggestions of provider packages for ext- and lib- packages

doc/06-config.md, res/composer-schema.json, src/Composer/Config.php, src/Composer/Installer.php, tests/Composer/Test/Fixtures/installer/install-from-incomplete-lock-with-ignore.test
As discussed in #11417 introduce new `allow-missing-requirements` config setting.
=> Add allow-missing-requirements config setting to ignore missing requirements

doc/03-cli.md, src/Composer/Command/DumpAutoloadCommand.php
=> Add --strict-ambiguous to dump-autoload command

src/Composer/Command/CompletionTrait.php, src/Composer/Command/ReinstallCommand.php, tests/Composer/Test/Command/ReinstallCommandTest.php
=> Add ability to reinstall packages by type

res/composer-schema.json, src/Composer/Package/Package.php, src/Composer/Package/PackageInterface.php
=> Add support-nts flag for php-ext section

src/Composer/Package/Version/VersionGuesser.php
This caused issues for example https://github.com/phpstan/phpstan-src/actions/runs/10707505997/job/29687642092
Where a PR based on an 1.12 branch of PHPStan had an equal diff to the 2.0 branch:
```
$ 'git' 'rev-list' 'remotes/origin/2.0.x..37fe841588827442002752de801040744699aa3b'
37fe841588827442002752de801040744699aa3b
bdf9b1dc66709de86486a1ffbeca086cb589873e
$ 'git' 'rev-list' 'remotes/origin/1.12.x..37fe841588827442002752de801040744699aa3b'
37fe841588827442002752de801040744699aa3b
bdf9b1dc66709de86486a1ffbeca086cb589873e
```
Then due to the parallelism involved when running the rev-list commands, it would sometimes return 1.12.x-dev and sometimes 2.0.x-dev, failing builds at random.
This makes it more deterministic, and hopefully more often correct too.
Targetting for 2.8 because it's …
=> Make version guessing more deterministic if two branches appear to be the base of a feature branch

res/composer-lock-schema.json, res/composer-repository-schema.json, res/composer-schema.json, src/Composer/Command/DiagnoseCommand.php, src/Composer/Json/JsonFile.php, src/Composer/Package/Locker.php
- Added composer-lock-schema
- Updated composer-repository-schema with new properties
- Added lock file schema validation in `diagnose`
Fixes #7823
=> JSON schema updates

doc/articles/scripts.md
=> Add version information to Controlling additional arguments doc

src/Composer/Command/InitCommand.php
=> Allow init without license

composer.json, composer.lock, src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Command/DumpAutoloadCommand.php
Here the second bit @janedbal - thanks for the good repro case that actually made me find a bug in non-strict mode even.
fixes #12140
=> Fix --strict-ambiguous to really report all issues

src/Composer/Command/CreateProjectCommand.php, src/Composer/Config.php, src/Composer/Repository/RepositoryFactory.php
=> Fix create-project to reuse the target folders permissions for files created

phpstan/baseline.neon, src/Composer/DependencyResolver/Problem.php, src/Composer/Repository/RepositoryInterface.php, src/Composer/Repository/RepositorySet.php
=> do not stumble over missing descriptions

src/Composer/DependencyResolver/Problem.php
see https://github.com/composer/composer/pull/12152#discussion_r1800980110
=> don't return a single space for packages without descriptions

src/Composer/Installer/BinaryInstaller.php
=> Fix handling of signals in non-PHP binaries run via proxies

src/Composer/Autoload/AutoloadGenerator.php
@fredericgboutin-yapla I hope this would have helped you? :)
=> Add hint how ambiguous class issues can be resolved, refs #6221

src/Composer/Command/StatusCommand.php, src/Composer/Downloader/PathDownloader.php, src/Composer/Downloader/VcsDownloader.php, src/Composer/Factory.php, src/Composer/Package/Loader/RootPackageLoader.php, src/Composer/Package/Version/VersionGuesser.php, src/Composer/Repository/PathRepository.php, src/Composer/Repository/Vcs/GitDriver.php, src/Composer/Util/Git.php
=> Warn/throw when we detect git safe.directory errors

doc/03-cli.md
=> Update docs for `audit` command

bin/composer
fixes #12214
cc @dzuelke does this do what you expected?
=> Avoid duplicate errors in the output

src/Composer/InstalledVersions.php
=> Fixed InstalledVersions returning duplicates in some instances

doc/04-schema.md
for https://github.com/composer/composer/discussions/12252
=> explicitly state UTC

src/Composer/Repository/VcsRepository.php
=> Copy source ref to dist ref if a custom dist info is present in non-dist-supporting drivers

tests/Composer/Test/Package/Archiver/ZipArchiverTest.php
Hey 👋 
while working on a bug, I found some issues in the ZipArchiverTest and figured would be good to send those changes first.
To reproduce: Create a testcase that fails. Run a few times. Note that the zip archive written is not unlinked producing a bigger and bigger growing zipfile in $target file.
=> Fix issues and improve Output from ZipArchiverTest

src/Composer/DependencyResolver/PoolBuilder.php, src/Composer/DependencyResolver/Problem.php, tests/Composer/Test/Command/UpdateCommandTest.php
=> Fix handling of replace together with the --with temporary constraints

src/Composer/InstalledVersions.php, src/Composer/Repository/FilesystemRepository.php
=> Fix InstalledVersions showing duplicates at Composer runtime during installation

.github/workflows/continuous-integration.yml, .github/workflows/php32bit.yml
Refs https://github.com/composer/composer/issues/12365
=> Add a CI job running with a 32bits build of PHP

res/composer-schema.json, tests/Composer/Test/Json/ComposerSchemaTest.php
=> ensure that version suffixes are case-insensitive

src/Composer/Downloader/ZipDownloader.php
=> Check the whole archive if a file looks like a zipbomb

src/Composer/Package/Archiver/PharArchiver.php, src/Composer/Package/Archiver/ZipArchiver.php
=> Fix creation of empty archives

doc/03-cli.md, src/Composer/Command/UpdateCommand.php, src/Composer/Installer.php, tests/Composer/Test/Fixtures/installer/full-update-minimal-changes.test
=> Add support for --minimal-changes with full updates

doc/articles/authentication-for-private-packages.md, res/composer-schema.json, src/Composer/Command/ConfigCommand.php, src/Composer/Config.php, src/Composer/Config/JsonConfigSource.php, src/Composer/IO/BaseIO.php, src/Composer/Util/AuthHelper.php, tests/Composer/Test/Util/AuthHelperTest.php
Fixes #10165 
Thanks @pulzarraider for support.
=> Add support to authorize with Custom Headers in auth.json or COMPOSER_AUTH env

src/Composer/Util/Git.php
=> Fix git prompt breaking on some systems

src/Composer/Autoload/AutoloadGenerator.php, tests/Composer/Test/Autoload/Fixtures/platform/no_extensions_required.php, tests/Composer/Test/Autoload/Fixtures/platform/no_php_required.php, tests/Composer/Test/Autoload/Fixtures/platform/no_php_upper_bound.php, tests/Composer/Test/Autoload/Fixtures/platform/php_64bit_required.php, tests/Composer/Test/Autoload/Fixtures/platform/replaced_provided_exts.php, tests/Composer/Test/Autoload/Fixtures/platform/specific_php_64bit_required.php, tests/Composer/Test/Autoload/Fixtures/platform/specific_php_release.php, tests/Composer/Test/Autoload/Fixtures/platform/typical.php
=> Fix deprecation message on PHP 8.4 when platform check fails

doc/03-cli.md
Reference:
- https://github.com/composer/composer/issues/12469#issuecomment-3055684448
=> doc: add `SHELL_VERBOSITY` to CLI
