composer/composer

src/Composer/Downloader/SvnDownloader.php, src/Composer/Repository/ComposerRepository.php
A small micro-optimization in some of the regular expressions used in Composer. 
The `.*` pattern is often greedy, and sometimes doesn't provide any assertions because `*` matches **zero** or more of the given pattern. This, combined with the "any" (`"."`) used as a prefix, or worse, as a suffix, provides sub-optimal regular expressions. 
`{.*@(\d+)$}` currently in Composer, for example, is exactly the same as `{@(\d+)$}` because the `*` quantifier is _zero_ or more. However, the latter uses fewer steps. See [current](https://regex101.com/r/yRa4Oy/1/) vs [suggested](https://regex101.com/r/yRa4Oy/2).
Trailing `.*` are not necessarily a performance hit in most cases (because the engine can immediately return results), but it's an unnecessary one nonetheless. 
For all changes made here, the …
=> Regex improvements with unnecessary `.*` matchers

src/Composer/DependencyResolver/Problem.php, tests/Composer/Test/Fixtures/installer/alias-solver-problems.test, tests/Composer/Test/Fixtures/installer/deduplicate-solver-problems.test, tests/Composer/Test/Fixtures/installer/provider-conflicts3.test
Fixes #8851
For reference, the added test without the patch was outputting:
```
- package/a 2.6.0 requires missing/dep ^1.0 -> found missing/dep[2.0.0] but it does not match the constraint.
- package/a 2.5.0 requires missing/dep ^1.0 -> found missing/dep[2.0.0] but it does not match the constraint.
- package/a 2.4.0 requires missing/dep ^1.0 -> found missing/dep[2.0.0] but it does not match the constraint.
- package/a 2.3.5 requires missing/dep ^1.0 -> found missing/dep[2.0.0] but it does not match the constraint.
- package/a 2.3.4 requires missing/dep ^1.0 -> found missing/dep[2.0.0] but it does not match the constraint.
- package/a 2.3.3 requires missing/dep ^1.0 -> found missing/dep[2.0.0] but it does not match the constraint.
- package/a 2.3.2 requires missing/dep ^1.0 -> found …
```
=> Deduplicate require/conflict rules which are the same but for different versions of the same package

doc/03-cli.md, src/Composer/Command/BaseCommand.php, src/Composer/Command/InitCommand.php, src/Composer/Command/UpdateCommand.php
=> Add --with to update command to allow downgrading to a specific version / applying custom temporary constraints

src/Composer/Util/PackageSorter.php, tests/Composer/Test/Util/PackageSorterTest.php
PackageSorter weighs the importance of a package
by counting how many times it is required by other packages.
This works by calculating the weight for each package name.
However currently the package index of the package array
is currently passed the weigh function, which basically
disables package sorting.
The reason for that is, that a package repository previously
returned the package list as associative array with  package name as keys,
but currently just as an array with integer keys.
Therefore we must extract the package name from the package
before passing it to the weigh function.
Related to #2642, #8065, 9d8db4e14858537e440f1a9523b6ea952013c184
=> Fix package sorting

tests/Composer/Test/Fixtures/installer/replace-range-require-single-version.test
This will require a semver library update to be fixed.
=> Adding a test to verify replace version overlap with unbound constraints and single versions

doc/04-schema.md, res/composer-schema.json, src/Composer/Package/AliasPackage.php, src/Composer/Package/Archiver/ArchiveManager.php, src/Composer/Package/Dumper/ArrayDumper.php, src/Composer/Package/Loader/ArrayLoader.php, src/Composer/Package/Package.php, src/Composer/Package/PackageInterface.php
`--file` argument for `archive` command, introduced in #4397 and #4479, is great, but:
* Written by hands, it's just tedious
* Used from CI, command becomes non-reusable. You can't have a single command to build any package
I propose to add `name` property into `archive` section of `composer.json` and use it for base name for archive, if `--file` argument was not provided.
*Base* means that Composer still concatenates it with version (and this is not configurable).
I haven't write any tests yet. They are probably required, but I'm not sure on the test strategy.
Let's discuss.
=> Add (default) base name of archive into composer.json

composer.json
`2.8.52` was released on 13th November 2019, and the simultaneous 3.4.x release was `3.4.35`. I've removed the conflict line since it's no longer relevant due to the minimum version of symfony/console.
=> Tweaked symfony versions

src/Composer/EventDispatcher/EventDispatcher.php, src/Composer/Repository/RepositoryManager.php
Method `ReflectionParameter::getClass()` is deprecated in PHP 8, `ReflectionParameter::getType` is only available in PHP 7.0, `ReflectionType::__toString()` is deprecated in PHP 7.4, and `ReflectionNamedType` is only avilable in PHP 7.4+
I'm also working on a fix for the json-scheme package :)
=> fix deprecations in PHP 8

src/Composer/DependencyResolver/Rule.php, src/Composer/DependencyResolver/RuleSetGenerator.php, tests/Composer/Test/Fixtures/installer/github-issues-8902.test
Refs #8902
Also can reproduce using real world packages with:
```json
{
"require": {
"beyondcode/laravel-dump-server": "^1.3",
"laravel/framework": "^6.18"
},
"minimum-stability": "dev",
"prefer-stable": true
}
```
The first composer update locks:
```
- Locking symfony/var-dumper (dev-master 63629be)
- Locking symfony/var-dumper (v4.4.8)
```
And actually installs both (luckily the dev package installs after the stable one, so it succeeds as the dev install wipes the dir).
Subsequent updates switch between:
```
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
- Upgrading symfony/var-dumper (v4.4.8 => dev-master 63629be)
Installing dependencies from lock file (including require-dev)
Package operations: 0 …
```
=> Ensure loading aliased package rules loads all rules for original package too #8902

src/Composer/DependencyResolver/RuleSetGenerator.php
Found this while looking at https://github.com/composer/composer/issues/3508 and the original change in https://github.com/composer/composer/pull/3482 - IMO #3508 can be closed now as addConflictRules does a single pass on all packages, there shouldn't be duplicate conflicts created anymore.
=> Remove some dead code from RuleSetGenerator

src/Composer/DependencyResolver/PoolBuilder.php
Refs #8882 - see in particular https://github.com/composer/composer/issues/8882#issuecomment-626372513 for context.
The code is somewhat confusing and I think we were misled there into thinking it was a recursive call for the same name. IMO what happens is rather this:
- A replacing B gets fixed, so A and B get fixed
- A gets unfixed somehow, B remains fixed
- B gets unfixed too, so it tries to unfix A, but it's already unfixed so the array access fails there.
I added the isset to avoid doing that last step if A isn't fixed anymore. I believe that's correct, but proving it with a test is unfortunately pretty damn hard right now.
=> Fix unfixing of packages when a replacer gets unfixed before a replacee

src/Composer/Autoload/ClassMapGenerator.php
support `glob` expressions in classmaps
example composer.json
```json
{
"autoload": {
"classmap": [
"redaxo/src/addons/*/lib/",
"redaxo/src/addons/*/plugins/*/lib/",
]
}
}
```
=> Autoload-Generator: support glob patterns in classmaps

src/Composer/DependencyResolver/RuleSetGenerator.php, src/Composer/Package/AliasPackage.php, tests/Composer/Test/Fixtures/installer/alias-solver-problems.test, tests/Composer/Test/Fixtures/installer/alias-solver-problems2.test
From a couple tests, this can speed up the actual dependency resolution CPU time quite a bit (got ~50% reduction) but mainly when used with `minimum-stability: dev`, as that leads to having way more alias packages.
Would be good to have more people test this to check it does not have any bad side effects.
=> Optimize rule creation for alias packages

composer.lock
Changes:
* Fixed: ignore SIGINTs to let the restarted process handle them.
=> Update xdebug-handler to 1.4.2

src/Composer/Autoload/AutoloadGenerator.php
Ref #8946
The platform-check feature maps `ext-X` to `extension_loaded('X')` calls. While most of the extensions can be tested this way, the `zend-opcache` extension requires `zend opcache` to be probed instead of the `zend-opcache` name.
This commit adds a special case for `zend-opcache` to use the correct name in `extension_loaded()` calls in generated `platform_check.php` files.
=> Platform Check: Add a special case for `zend-opcache`

.github/workflows/continuous-integration.yml, .github/workflows/phpstan.yml, phpstan/config.neon
Includes a few improvements in PHPStan CI runs. 
- Require PHPStan `^0.12.26` (currently `^0.12`) because this version contains major improvements how files are autoloaded. 
- Remove `autoload_files` from PHPStan `config.neon` because PHPStan no longer needs to autoload files for it to analyze files. 
- Add `ignoreErrors` pattern for the use of `sapi_windows_set_ctrl_handler` function. The ignore pattern is specific about files, where we already have `function_exists()` calls to make sure this function is available. 
- Add `ignoreErrors` pattern for `ZipArchive::LIBZIP_VERSION` usage, which is checked before hand. This rule is specific to the single usage we have in Composer. 
With this PR, we bring down PHPStan report from **6 errors and 1 warning** to **1 error**.
The only remaining …
=> PHPStan fixes: `autoload_files`, and `ignoreErrors`

doc/03-cli.md, src/Composer/Command/LicensesCommand.php
This was inspired by https://www.npmjs.com/package/license-checker which has a `--summary` option to have a list of used licenses and the number of dependencies using each license.
Here's how it looks when executed:
=> Add new summary format for licenses

src/Composer/Downloader/GitDownloader.php
Problem:
A package which is installed using Git is not cleaned up completely during `composer install`.
How to reproduce:
1. Install a package as a Git repository (including `.git` folder)
1. Make some modifications to the package (incl. adding new files and folders)
1. Update the package + confirm discard notice. Composer warns about the modified files and asks if these changes should be discarded.
1. The result is that all files that were modified have been reverted (`git reset --hard`), but any files which are not part of the Git repository are still there.
Expected result:
Git project folders should be clean when choosing "discard changes".
Solution:
Run `git clean -df` when attempting to discard local changes.
=> Discard changes is incomplete if Git project has additional folders

src/Composer/Command/ArchiveCommand.php, src/Composer/Command/CreateProjectCommand.php, src/Composer/Command/InstallCommand.php, src/Composer/Command/RemoveCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Command/UpdateCommand.php, src/Composer/Downloader/ArchiveDownloader.php, src/Composer/Downloader/FileDownloader.php, src/Composer/Downloader/GzipDownloader.php, src/Composer/Downloader/PathDownloader.php, src/Composer/Downloader/RarDownloader.php, src/Composer/Downloader/XzDownloader.php, src/Composer/Downloader/ZipDownloader.php, src/Composer/Factory.php, src/Composer/IO/ConsoleIO.php, src/Composer/Installer.php, src/Composer/Installer/InstallationManager.php, src/Composer/Util/Http/CurlDownloader.php, src/Composer/Util/HttpDownloader.php, src/Composer/Util/Loop.php, src/Composer/Util/ProcessExecutor.php, src/Composer/Util/RemoteFilesystem.php, tests/Composer/Test/Downloader/FileDownloaderTest.php, tests/Composer/Test/Downloader/XzDownloaderTest.php, tests/Composer/Test/Downloader/ZipDownloaderTest.php, tests/Composer/Test/Repository/ComposerRepositoryTest.php
This adds support for async processes, and on linux/OSX if `unzip` is present it will be used to extract package archives in parallel.
This speeds up extraction time by 30-50% in a few tests I made. Curious to get feedback from others, especially HDD users as I am not sure how it'll behave there.
For example here is `time` output for an install of 197 packages:
parallel-installs:
```
real    0m47.391s
user    0m6.266s
sys     1m19.531s
```
master:
```
real    1m15.275s
user    0m5.297s
sys     1m3.094s
```
And a more reasonable one with 47 packages:
parallel-installs:
```
real    0m19.097s
user    0m1.844s
sys     0m30.109s
```
master:
```
real    0m30.592s
user    0m2.141s
sys     0m26.328s
```
=> Parallel zip installs

src/Composer/DependencyResolver/Pool.php, src/Composer/DependencyResolver/PoolBuilder.php, src/Composer/Repository/ComposerRepository.php
This is draft of integrating compiled constraint in Composer:
https://github.com/composer/semver/pull/86.
I Probably need help to find the right way to inject the `Compiledatcher` with the right cache dir configured.
Note: I did not replace ALL  occurrences of `->matches()` but just the one that are the most often called.
=> Use compiled constraint in Composer

src/Composer/Downloader/FileDownloader.php, src/Composer/Plugin/PreFileDownloadEvent.php, src/Composer/Repository/ComposerRepository.php
I am the maintainer of [private-composer-installer](https://github.com/ffraenz/private-composer-installer) offering users to inject environment values into the dist URLs of their repositories without leaking sensitive information into `composer.lock`. In the next major version ([pull request](https://github.com/ffraenz/private-composer-installer/pull/25)) I'd like to add support for Composer 2.
Currently the plugin replaces the remote file system to alter the dist URL before the download gets triggered. As explained in the [upgrade guide](https://github.com/composer/composer/blob/master/UPGRADE-2.0.md) this will no longer work in Composer 2.
As already suggested in https://github.com/composer/composer/pull/8807#issuecomment-617864883 I'd like to implement a way for plugins to alter the …
=> Composer 2: Allow plugins to override the URL before triggering the download

src/Composer/Repository/Vcs/GitDriver.php
The GitDriver wasn't using authentication when trying to determine whether a URL is a git repository. The `GitDriver::supports` methods therefore returned always false for private git repositories which for instance look like regular URLs.
=> GitDriver: use authentication for supports check

src/Composer/Command/LicensesCommand.php
- Used licenses in the summary overview are now correctly sorted, showing the most used license first
- Output of `composer help licenses` now shows the summary format option just like the regular docs.
---
I recently added the feature in https://github.com/composer/composer/pull/8973 and while playing around with the latest snapshot version of `2.x` I found these two small improvements.
=> Sort licenses summary

src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Plugin/PluginManager.php
Replaces cascading `str_replace()` calls with a single `strtr()` call that makes it more readable and provides a micro performance improvement.
Some instances of cascading `str_replace()` calls were not refactored due to the potential recurring replacement patterns.
Thank you.
=> Replace cascading str_replace() calls with strtr()

src/Composer/DependencyResolver/Pool.php, src/Composer/DependencyResolver/Solver.php, tests/Composer/Test/Fixtures/installer/github-issues-7051.test, tests/Composer/Test/Fixtures/installer/provider-conflicts3.test
First attempt at fixing https://github.com/composer/composer/issues/7051
This now appears to lead to the same problem description as composer v1 for the test case provided in https://github.com/composer/composer/issues/7051#issuecomment-637745282
However this definitely needs a bit more work, e.g. I don't think the increment of `$num` by exactly 1 necessarily always works. There may also be necessary changes to `$l1num` depending on the level the multi conflict rule is found at. There may be other problems with this workaround.
=> Fix solver bug exception 7051

src/Composer/Installer.php
=> Fix: Reference

src/Composer/DependencyResolver/DefaultPolicy.php
See https://wiki.php.net/rfc/named_params#internal_functions
(implemented but not yet merged)
An ArgumentCountError will be thrown when passing variadic arguments to
a function with call_user_func_array() if extra unknown named arguments
are encountered.
Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in phar:///path/to/composer.phar/src/Composer/DependencyResolver/DefaultPolicy.php:84
(e.g. for `...['phpunit/phpunit' => [72]]`)
------
I'm proposing fixing this in composer 1.10 because this is a relatively straightforward fix, and composer otherwise does not warn when being run in php 8.0-dev.
I'm sorry if I missed any notes about no longer accepting patches for php 8.0 - I didn't see any other notes the readme for this branch.
=> Properly support PHP 8.0 Named Arguments (Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters)

src/Composer/Repository/PlatformRepository.php, tests/Composer/Test/Repository/PlatformRepositoryTest.php
libicu ships with a version of CLDR (http://cldr.unicode.org/), which is basically the data version. It would be great if one could specify the CLDR version specifically using composer.
=> Allow specifying a version requirement for CLDR

src/Composer/Repository/Vcs/BitbucketDriver.php, src/Composer/Repository/Vcs/GitHubDriver.php, src/Composer/Repository/Vcs/GitLabDriver.php
For VCS repositories where the API can be used (GitHub/GitLab/Bitbucket) Composer currently caches the a modified composer.json file on disk which contains additional data from the API e.g. whether a repository was archived. This currently prevents Composer from detecting whether a package was archived if there was no new commit.
Steps to reproduce:
* create a GitHub/GitLab repository
* Have a local composer.json that requires the VCS repository like
```
{
"repositories": [{"type": "vcs", "url": "https://github.com/acme/package"}],
"require": {
"acme/package": "dev-master"
}
}
```
* Run `composer update` which will output something like
```
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 …
```
=> Driver: only cache composer.json file without API data to disk

src/Composer/Repository/PlatformRepository.php, tests/Composer/Test/Repository/PlatformRepositoryTest.php
Reverts composer/composer#9085 as features don't really belong in 1.10 anymore, @lstrojny will send another PR targetting 2.0.
=> Revert "Allow specifying a version requirement for CLDR"

UPGRADE-2.0.md
The autolinking from GFM does not include the `*` char in the link. Using an explicit link in the markdown fixes it.
=> Fix the example link for the list endpoint

doc/01-basic-usage.md
Move note about when it is not necessary to commit the lockfile from the "Updating dependencies to their latest version" section to the "Commit your composer.lock file to version control" section as that placements makes better sense.
=> Docs: Move note about not committing lock file to correct section.

.github/workflows/phpstan.yml
phpstan recently added native support, so no need to use cs2pr anymore
=> phpstan natively sends github action formatted errors

src/Composer/Platform/Runtime.php, src/Composer/Repository/PlatformRepository.php, tests/Composer/Test/Repository/PlatformRepositoryTest.php
varargs double indirection was incorrect, this fixes it + ads a regression test.
Adresses #9128
=> Fix regression when inet_pton() does not exist

src/Composer/Util/RemoteFilesystem.php
Follow up for https://github.com/composer/composer/pull/9130 prevents PHP warning `stream_context_create(): options should have the form ["wrappername"]["optionname"] = $value`
=> RemoteFilesystem: avoid warning when setting max file size

src/Composer/Util/Zip.php
`strpos()` first argument is a haystack, not a needle.
`strpos('x', $s)` is identical to `$s === 'x'` which is probably not what we want here.
=> Util/Zip: fix strpos args order

src/Composer/Util/AuthHelper.php, tests/Composer/Test/Util/AuthHelperTest.php
Previously, `AuthHelper` consumed the authentication credentials for GitLab domains and added access tokens as GitLab-specific headers.
[Composer repositories now supported in GitLab](https://php.watch/articles/composer-gitlab-repositories) require standard Authorization headers with a personal access to function, which failed to work due to out GitLab-specific headers.
With this commit, AuthHelper checks if the password is an access token, and falls through to HTTP basic authentication even if the domain name is a GitLab domain name.
=> AuthHelper: Allow fall-through GitLab-specific HTTP headers for auth

src/Composer/Repository/ComposerRepository.php
When a Composer repository is cached, a directory name is generated created stored package meta information fetched from that repository.
The cache directory can contain HTTP basic auth tokens, or access_token query parameters that end up in the directory name of the cache directory.
Discovered when trying out [GitLab composer repository feature](https://php.watch/articles/composer-gitlab-repositories), and the HTTP password was visible in a `composer update -vvv` command.
Using passwords/tokens in the URL is fundamentally a bad idea, but Composer already has `\Composer\Util\Url::sanitize()` that tries to mitigate such cases, and this same function is applied to the repo URL before deciding the name of the repo cache directory.
=> Sanitize repo URLs to mask HTTP auth passwords from cache directory

doc/06-config.md
I intuitively thought the requirement was `read_repository`, but this needs API access. Document as such.
=> Update config section to note required scope for GitLab tokens

src/Composer/Repository/ComposerRepository.php
Starting with PHP 7.4 Composer repositories that do not provide a sha1 hash for includes like the example listed below trigger a PHP notice
`Notice: Trying to access array offset on value of type null at vendor/composer/composer/src/Composer/Repository/ComposerRepository.php:640`
```
{
includes: {
path-to-include/include.json: null
}
}
```
=> ComposerRepository: avoid notice if includes do not provide a sha1

src/Composer/Autoload/ClassLoader.php
Same issue as #9076, different spot. 😃 
This piece of code currently causes the test suite of Symfony's debug component to fail on php 8.
=> Call call_user_func_array() with a numeric arguments array

src/Composer/Util/RemoteFilesystem.php
The response property of TransportExceptions thrown by the CurlDownloader are always decoded. The RemoteFileSystem however throws TransportExceptions which will contain a gzipped response for gzipped responses.
=> Composer2 RemoteFileSystem: response decode for TransportException

doc/03-cli.md, src/Composer/Command/CreateProjectCommand.php
The `create-project` command is used by a lot of projects as part of their installation documentation, for example [Symfony][symfony-install], [Laravel][laravel-install] and [Statamic][statamic-install]. The `create-project` command accepts a `directory` argument which authors of installation instructions must try to convey to readers as being a value the reader must replace with their desired directory. 
This Pull Request is for a change to add a new `ask` option which allows documentation authors to remove any reference to the `directory` argument and instead have Composer prompt the reader for their target directory. This does not change the default behaviour.
```console
dev:~$ composer create-project symfony/symfony --ask
New project directory [optional]:
```
Here are a couple of …
=> :sparkles: Ask for target directory when using `create-project`

src/Composer/Util/HttpDownloader.php, src/Composer/Util/ProcessExecutor.php, tests/Composer/Test/Util/ProcessExecutorTest.php
Added test to cancel ProcessExecutor::asyncExecute.
This failed for PHP 5.3.
=> Fix self usage in closures results in fatal error on PHP 5.3

.github/workflows/continuous-integration.yml, .github/workflows/phpstan.yml, phpstan/config.neon, tests/Composer/Test/Autoload/AutoloadGeneratorTest.php, tests/Composer/Test/CacheTest.php, tests/Composer/Test/Downloader/ArchiveDownloaderTest.php, tests/Composer/Test/Downloader/FileDownloaderTest.php, tests/Composer/Test/Downloader/XzDownloaderTest.php, tests/Composer/Test/Installer/LibraryInstallerTest.php, tests/Composer/Test/Package/Archiver/ArchiveManagerTest.php, tests/Composer/Test/Util/ErrorHandlerTest.php, tests/Composer/Test/Util/FilesystemTest.php, tests/Composer/Test/Util/RemoteFilesystemTest.php
We need PHPUnit 9.3@dev (and its @dev stability dependencies), which include PHP 8.0 support, including https://github.com/sebastianbergmann/phpunit/pull/4374 which fixes the issue with Match which is currently crashing composer's test suite on actions.
=> Fix tests on PHP 8.0

src/Composer/Repository/ComposerRepository.php
While testing some performance improvements I noticed disabling network does not work in projects I use lazy repositories in (discussed in https://github.com/composer/composer/pull/9171#issuecomment-690617374).
The problems are appearing if a lazy repository does not have this package and as a result of this no cache item can be found.
I added status code 499 beside 404 to not fail hard in this situation but still log the warning as it happens on regular repositories as well.
=> Do not hard fail on lazy repository when network is disabled and no package cache exists

src/Composer/Command/DiagnoseCommand.php
The diagnose command already warns when openssl is not available. But the command was failing later when displaying the Openssl version.
Discovered in #9235
=> Fix support for running diagnose without openssl

tests/Composer/Test/Repository/VcsRepositoryTest.php
`getUniqueTmpDirectory` already creates the directory, so that this mkdir is always false, preventing the tests from running.
=> Fix VcsRepositoryTest

src/Composer/Package/Link.php
This property is accessed from outside of the class, so it needs to be marked as internal, not private, to indicate that it should not be used by code that is not composer itself.
=> Fixed incorrect private annotation

src/Composer/Command/StatusCommand.php
I tested it, and even with "dist" packages, the status command is able to find modified vendor 
(And that's amazing, thanks)
=> Fixed description of StatusCommand: It do list all changes in vendor, not only for "source" ones

src/Composer/Package/Version/VersionGuesser.php, tests/Composer/Test/Package/Loader/RootPackageLoaderTest.php, tests/Composer/Test/Package/Version/VersionGuesserTest.php
Addresses https://github.com/composer/packagist/issues/1125 which previously only worked reliably when using a branch alias for git master.
=> Version Guesser: Look at branches on remotes origin & upstream to look for version numbers too

doc/articles/plugins.md
A colon has been wrapped to a next line due to a redundant space.
=> Fixed a white-space typo

src/Composer/Downloader/FileDownloader.php, src/Composer/Plugin/PreFileDownloadEvent.php
Following up the introduction of a `setProcessedUrl` method on the `PreFileDownloadEvent` in https://github.com/composer/composer/pull/8975 we found another issue that is blocking us from upgrading plugins to Composer 2. When altering the `processedUrl` for packages the file download `cacheKey` unexpectedly does not change with it, potentially reusing outdated files.
I am therefore suggesting that the cache key gets regenerated when the processed URL gets changed during `PreFileDownloadEvent` dispatching.
For [use cases](https://github.com/ffraenz/private-composer-installer/pull/25#issuecomment-692792485) that introduce temporary processed URLs (e.g. timestamps, session tokens, etc.) further optimization may be possible by allowing plugin authors to optionally provide a custom cache key …
=> Composer 2: Adapt file download cache keys to changed processed URLs

src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Command/DumpAutoloadCommand.php, src/Composer/Command/InstallCommand.php, src/Composer/Command/RemoveCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Command/UpdateCommand.php, src/Composer/Installer.php, tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
Closes #7049 
Introduces new option `--apcu-autoloader-prefix` to `install`, `require`, `update`, `remove` and `--apcu-prefix` in `dump-autoload`.
=> Specify APCu autoloader prefix

src/Composer/DependencyResolver/Transaction.php, tests/Composer/Test/DependencyResolver/TransactionTest.php, tests/Composer/Test/Fixtures/installer/install-aliased-alias.test
So far the ordering of alias packages with the same name was undefined
so the actual order was determined by implementation of the sorting
algorithm in PHP. As of PHP8 sort is stable by default which changes the
outcome in some of our test cases.
With the fully defined total order the order can longer change depending
on sorting algorithm used and remains the same across PHP versions.
=> Transaction: Define a total order on packages to keep behavior on PHP8

src/Composer/DependencyResolver/LockTransaction.php, src/Composer/DependencyResolver/Pool.php, src/Composer/DependencyResolver/PoolBuilder.php, src/Composer/DependencyResolver/Problem.php, src/Composer/DependencyResolver/Request.php, src/Composer/DependencyResolver/Rule.php, src/Composer/DependencyResolver/RuleSetGenerator.php, src/Composer/DependencyResolver/Solver.php, src/Composer/Installer.php, tests/Composer/Test/Fixtures/installer/alias-solver-problems2.test, tests/Composer/Test/Fixtures/installer/partial-update-from-lock.test, tests/Composer/Test/Fixtures/installer/remove-deletes-unused-deps.test, tests/Composer/Test/Fixtures/installer/remove-does-nothing-if-removal-requires-update-of-dep.test, tests/Composer/Test/Fixtures/installer/root-alias-change-with-circular-dep.test, tests/Composer/Test/Fixtures/installer/update-allow-list-require-new-replace.test, tests/Composer/Test/Fixtures/installer/update-allow-list-with-dependencies-require-new-replace-mutual.test
Instead of marking locked packages as fixed, we change the pool builder to load only the locked version and treat it like a fixed package for loading purposes. But removing the actual request fix, makes the solver treat it as a regular optional dependency. As a consequence locked packages may be removed on a partial update of another package, but they still cannot be updated. This keeps the performance improvements achieved by fixing packages (no loading of alternatives unless explicitly listed for update) but it removes the automatic decision to install locked packages.
Tests fail because this changes some other assumptions, but I believe in a way that we would actually prefer.
For example a locked dependency may now get removed in favour of another package which can satisfy the same …
=> Partial updates should remove all unused dependencies

doc/03-cli.md, doc/05-repositories.md, doc/06-config.md, doc/articles/authentication-for-private-packages.md, doc/articles/troubleshooting.md
In PR #9250 a first start was made on documenting authentication for private packages. The github and bitbucket authentication methods were not initially included as I was only thinking about composer registry options, but this PR documents those remaining authentication methods (as requested by @Seldaek) and clarifies that the documentation is about authentication in general, not only against composer registries.
=> Update authentication methods in documentation

src/Composer/Downloader/FileDownloader.php, tests/Composer/Test/Downloader/FileDownloaderTest.php
Fixes #9220, as per [comment](https://github.com/composer/composer/pull/9220#issuecomment-709510751):
> The `$urls` variable is passed by reference to each callback (`$download`, `$accept`, `$reject`) but the manipulations, in `$download`, made to `$url` are done on a copy:
> 
> ```php
> $download = function () use ($io, $output, $httpDownloader, $cache, $cacheKeyGenerator, $eventDispatcher, $package, $fileName, &$urls, &$accept, &$reject) {
>     $url = reset($urls);
> ```
> 
> Once `$accept` is called, it still has the original dataset:
> 
> ```php
> $accept = function ($response) use ($cache, $package, $fileName, $self, &$urls) {
>     $url = reset($urls);
> ```
This pull request ensures the manipulated `$url` is reassigned back to `$urls` to be available to `$accept` and `$reject`.
=> Fix availability of $urls in FileDownloader

src/Composer/DependencyResolver/Solver.php, tests/Composer/Test/Fixtures/installer/github-issues-7051.test, tests/Composer/Test/Fixtures/installer/github-issues-9012.test, tests/Composer/Test/Fixtures/installer/provider-conflicts3.test
In complex scenarios reasons for learned rules can themselves be learned
rules caused by other learned rules which had some of the same
reasons. In this situation iterating over all problem rules requires
keeping track of which rules have previously been analyzed to avoid an
endless loop.
Side effect is that the sorting of problems including learned rules
changes slightly.
Addresses https://github.com/composer/composer/issues/9012 which is item 6 on https://github.com/composer/composer/issues/9294
=> Solver: Prevent infinite recursion in analyzeUnsolvableRule

src/Composer/DependencyResolver/Solver.php, tests/Composer/Test/Fixtures/installer/github-issues-9290.test
Addresses https://github.com/composer/composer/issues/9290 which is also item 1 on https://github.com/composer/composer/issues/9294
After the fix in https://github.com/composer/composer/commit/851050e85c07f68ce0a0290fa53f6ed884751a6b it could now happen that $l1num gets incremented twice or $l1num and $num both got incremented for the same literal, which is not supposed to happen.
=> MultiConflictRule conflict analysis handling on level 1 decisions

tests/Composer/Test/Fixtures/installer/provider-satisfies-its-own-requirement.test, tests/Composer/Test/Fixtures/installer/replacer-satisfies-its-own-requirement.test
Asserts the behavior discussed in https://github.com/composer/composer/issues/9308 so it doesn't change in the future.
=> Test: Verify require for package provided or replaced by pkg itself is used

src/Composer/Command/SelfUpdateCommand.php
Instead of: 
> You are already using composer version 1.10.15 (1 channel).
it shows: 
> You are already using composer version 1.10.15 (1.x channel).
=> Improve readability of version info message

src/Composer/Package/Archiver/ArchivableFilesFinder.php
Given you have a symlink in one of your path repositories and mirroring-strategy enabled.
```bash
lrwxrwxrwx 1 inf inf    8 27. Aug 17:41 Create.html -> New.html
-rw-r--r-- 1 inf inf  750 27. Aug 17:24 Edit.html
-rw-r--r-- 1 inf inf    0 27. Aug 17:24 List.html
-rw-r--r-- 1 inf inf 5064 27. Aug 17:24 New.html
-rw-r--r-- 1 inf inf  716 27. Aug 17:24 Show.html
```
`$file->getLinkTarget()` just returns a relative path in this example. It does not return an absolute normalized path.
`$sources` is always a normalized path.
`strpos` can never be `0`.
Use `$file->getRealPath()` to fix the strpos-check.
=> Fix symlink check

doc/articles/troubleshooting.md
Warning text:
```
/sbin/swapon /var/swap.1
swapon: /var/swap.1: insecure permissions 0644, 0600 suggested.
```
Adding `/bin/chmod 0600 /var/swap.1` prevents the warning for me on Trisquel 9 (Ubuntu 18.04).
=> Setting permissions prevents a warning from swapon

doc/00-intro.md, doc/01-basic-usage.md, doc/02-libraries.md, doc/03-cli.md, doc/04-schema.md, doc/05-repositories.md, doc/06-config.md, doc/articles/autoloader-optimization.md, doc/articles/custom-installers.md, doc/articles/handling-private-packages-with-satis.md, doc/articles/scripts.md, doc/articles/versions.md, doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md, doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md, doc/faqs/why-are-version-constraints-combining-comparisons-and-wildcards-a-bad-idea.md, doc/fixtures/fixtures.md
They only serve to make anyone reading the docs who doesn't find something as simple or easy as stated feel bad about themselves, they don't add anything valuable to the docs in these cases.
=> Docs: Remove unnecessary uses of simple/easy

src/Composer/Repository/BaseRepository.php
The version provided by such a rule is defined by the constraint of the rule, not by the package version.
Closes #8415
=> Fix support of provided packages in the why-not command

src/Composer/Util/Http/CurlDownloader.php, src/Composer/Util/Http/ProxyHelper.php, src/Composer/Util/Http/ProxyManager.php, src/Composer/Util/Http/RequestProxy.php, src/Composer/Util/RemoteFilesystem.php, src/Composer/Util/StreamContextFactory.php, tests/Composer/Test/Util/Http/ProxyHelperTest.php, tests/Composer/Test/Util/Http/ProxyManagerTest.php, tests/Composer/Test/Util/Http/RequestProxyTest.php, tests/Composer/Test/Util/StreamContextFactoryTest.php
First attempt at fixing the issues highlighted in https://github.com/composer/composer/issues/9314
* ProxyHelper is a utility class that process the environment variables. I've split this out from StreamContextFactory so it can be more easily used by the installer.
* ProxyManager uses the ProxyHelper to provide the context options for streams, and the proxy url for curl. It's a singleton class but I couldn't find any other way of doing it.
In the rare cases of a secure proxy, PHP streams will fail in the case of an https request (in a similar way that a missing openssl extension does). The curl handling also takes a request based approach - however curl cannot handle http requests either so it could lead to a situation where using streams would have worked.
=> Refactor proxy handling for Composer2

CHANGELOG.md, UPGRADE-2.0.md, doc/03-cli.md, doc/05-repositories.md, doc/articles/authentication-for-private-packages.md, doc/articles/versions.md, doc/fixtures/fixtures.md
Some characters in Markdown have special meaning and should be escaped if used in text.
<details><summary>Example</summary>
This screen-shot was taken from https://getcomposer.org/changelog/2.0.0-RC1 at time of authorship. Note the second bullet has some unintentionally-emphasised text.
</details>
=> Escape special characters in Markdown files

src/Composer/Command/RequireCommand.php
The installer does not support partial updates, when
no lock file is present. The check in require command
to prevent a partial update however does not check whether
a lock file is present, but whether a lock file should be written,
which most likely always is true.
This check is now changed to check if a lock file is actually present.
=> Correctly avoid partial updates in require commands

doc/articles/plugins.md
Related to #3108. When developing an plugin it may be usefull to have a dev dependency to composer/composer to have autocompletion in IDEs.
Also Capitalized some "composer" occurences in the same article.
=> Add info about dev-dependency of composer/composer to plugin article

src/Composer/Exception/NoSslException.php, src/Composer/Util/StreamContextFactory.php, tests/Composer/Test/Util/StreamContextFactoryTest.php
I got my logic wrong, so this needs fixing. The exception messages have also been improved (hopefully).
Previously, this threw a RuntimeException but I changed it to a TransportException to match what I was using for secure-proxy >https not being supported natively.
However, there is also a NoSslException, which looks like it is only specifically used when the application first runs. So what should I be using for no openssl situations?
Also, I could add tests for this, but it seems a bit pointless unless the tests explicity run without openssl. What should I do.
=> Improve proxy error messages for streams

doc/03-cli.md
The self-update command is only available when running as a PHAR (see commit 761ad6d171); notably, it is not defined in the Ubuntu package.
=> Document availability of self-update command

tests/Composer/Test/Package/Archiver/ArchiveManagerTest.php, tests/Composer/Test/Repository/VcsRepositoryTest.php
When the global git config has `init.defaultbranch` set to something other than master the tests fail. This is because the tests assume that the default branch is called master but that may not be the case.
```
There were 3 errors:
1) Composer\Test\Package\Archiver\ArchiveManagerTest::testArchiveTar
RuntimeException: Failed to execute git checkout 'master' -- && git reset --hard 'master' --
fatal: invalid reference: master
```
This PR fixes the tests by ensuring that when running git init we ensure the default branch is called master regardless of how git is configured.
=> Fix running tests with non standard default branch

src/Composer/Util/Http/CurlDownloader.php
`сomposer-1` used for http requests `RemoteFilesystem` with context, with passed directly from `options` section of repository and there was not problems to pass client ssl-certificates to `stream-context`.
Upgrading to `composer-2` (with `ext-curl` installed) causes HTTP-requests to fail - `CurlDownloader` doesn't use client ssl-certificates.
Sample `config.json`:
```json
{
"repositories": {
"private-repo": {
"type": "composer",
"url": "https://private.repo.example.com",
"options": {
"ssl": {
"local_cert": "/users/user/.composer/certs.d/pravate-repo-user.cert",
"local_pk": "/users/user/.composer/certs.d/pravate-repo-user.key"
}
}
}
}
}
```
There is no need (for me) to store `passphrase` at `config.json`, but I think - let's make it possible to use it by anyone who needs this.
=> Update CurlDownloader enable support for client ssl-certificates

README.md
This PR adds a missing punctuation mark in the README file.
=> Add a missing punctuation mark in README

src/Composer/Util/RemoteFilesystem.php
The RemoteFileSystem currently throws `new TransportException('Failed to decode zlib stream')` in case the server returns an encoded empty string as response e.g. in case of a 403.
=> RemoteFileSystem: don't throw zlib error on empty response

src/Composer/Downloader/PathDownloader.php
Fixes #8322 
This PR resolves an issue that could prevent successful removal of a Windows junction, for a package that has been added from a path repository.
Using `realpath()` on a junctioned folder returns the source path, which will result in a false positive when compared. See https://bugs.php.net/bug.php?id=77639
To avoid this potential issue, the checking for, and removal of, Windows junctions can be handled before comparing realpaths.
=> Remove Windows junctions first in PathDownloader

doc/03-cli.md
There were a few missing options in the documentation that didn't align with the help from `composer self-update --help`. In particular, the `--1` and `--2` options.
=> Update `self-update` options

src/Composer/Autoload/AutoloadGenerator.php, tests/Composer/Test/Autoload/Fixtures/platform/no_extensions_required.php, tests/Composer/Test/Autoload/Fixtures/platform/no_php_required.php, tests/Composer/Test/Autoload/Fixtures/platform/no_php_upper_bound.php, tests/Composer/Test/Autoload/Fixtures/platform/replaced_provided_exts.php, tests/Composer/Test/Autoload/Fixtures/platform/specific_php_release.php, tests/Composer/Test/Autoload/Fixtures/platform/typical.php
Composer 2 is checking platform requirements in runtime. It can cause shut down production in a lot of cases.
Here is big trouble the Error message is printed to output and replaced the Web Application. And although Composer is produced an Error message, it's introduced as a serious response of Web application ([status `200 OK`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200)).
It's Fail because the robots aren't correctly notified the response is Error and accepts the response as a valid response. It can cause mass burning of Website SEO reputation because the error message is indexed Search engine's robots and replaces the main content.
**Trust me its't very serious problem**, try to [**search "Composer detected issues in your …
=> Fix HTTP status when Platform check failed

src/Composer/Autoload/AutoloadGenerator.php, tests/Composer/Test/Autoload/Fixtures/platform/no_extensions_required.php, tests/Composer/Test/Autoload/Fixtures/platform/no_php_required.php, tests/Composer/Test/Autoload/Fixtures/platform/no_php_upper_bound.php, tests/Composer/Test/Autoload/Fixtures/platform/replaced_provided_exts.php, tests/Composer/Test/Autoload/Fixtures/platform/specific_php_release.php, tests/Composer/Test/Autoload/Fixtures/platform/typical.php
Following up #9412 and #9410 I found current error handling with mechanism `header(); echo …; die(1+);` is not satisfied for success debugging on most implementations.
General monitoring tools prefers to monitor native error log instead to parsing response body (tested on [Google App Engine](https://cloud.google.com/appengine) and [Google Run](https://cloud.google.com/run)).
Here are two reasons:
- native error handling in any level (regardless to app-level or sys-level),
- **security** – printing too detailed internal error message in runtime is very sensitive, it can provide implementation details for attackers,
- indepentent to SAPI (cli, cgi, etc.), environment, and others, because it's produce native error state in app runtime lifecycle.
**This PR is replacement to #9410 and it's …
=> Platform check: Trigger native PHP error

src/Composer/Autoload/AutoloadGenerator.php, tests/Composer/Test/Autoload/Fixtures/platform/no_extensions_required.php, tests/Composer/Test/Autoload/Fixtures/platform/no_php_required.php, tests/Composer/Test/Autoload/Fixtures/platform/no_php_upper_bound.php, tests/Composer/Test/Autoload/Fixtures/platform/replaced_provided_exts.php, tests/Composer/Test/Autoload/Fixtures/platform/specific_php_release.php, tests/Composer/Test/Autoload/Fixtures/platform/typical.php
Fixes bug from commit: 8c1355f448ec8087bf7ed468208f8d63794de909
- ~~Prints error to output only when `ini_get('display_errors')` is truly,~~
- Add status `500 Internal server error` to error message (see #9410 discussion; ~~note the `trigger_error()` below doesn't change status, because `echo` is already sent data to output~~).
@Seldaek however, in any case, your solution is better than my previous solution. Thanks for your great work!
=> Fix platform check error message

src/Composer/Downloader/FileDownloader.php
In a project I'm working on, we have some dependencies on libraries _outside_ of the `composer` ecosystem.  
To do so, we are defining those external dependencies as `file`-typed packages.
We're currently working on migrating to `composer v2.x`, when I noticed an anomaly...
When installing a [package](https://getcomposer.org/doc/05-repositories.md#package-2) with `dist.type: 'file'`, it appears that the file gets installed in the wrong target destination?
I've created a minimal `composer.json` file that reproduces this issue in `composer v2.x`.
<details>
<summary>Sample <code>composer.json</code></summary>
<div class="highlight highlight-source-json"><pre>
{
{
"type": "package",
"package": {
"name": "composer/readme-file",
"version": "2.0.4",
"dist": {
"url": …
=> Fix missing directory separator in FileDownloader

src/Composer/Downloader/ArchiveDownloader.php
The method just called its parent without further logic.
I guess this method was more complex in the past and what we have right now is just the leftovers
=> Remove unnecessary overridden method

src/Composer/Util/HttpDownloader.php
An infinite loop was caused by promises which weren't either resolved or rejected within the [`Composer\Util\HttpDownloader::startJob`](https://github.com/composer/composer/blob/master/src/Composer/Util/HttpDownloader.php#L243) when an exception was thrown by the [`Composer\Util\Http\CurlDownloader::download`](https://github.com/composer/composer/blob/master/src/Composer/Util/Http/CurlDownloader.php#L112) method.
A promise and reject callback are passed to the aforementioned methods but are only passed through to [`$this->jobs`](https://github.com/composer/composer/blob/master/src/Composer/Util/Http/CurlDownloader.php#L223) but not invoked if there is an exception within [`Composer\Util\Http\CurlDownloader::initDownload`](https://github.com/composer/composer/blob/master/src/Composer/Util/H …
=> Reject promise within "HttpDownloader" when an exception is thrown

src/Composer/Console/Application.php, src/Composer/Util/ProcessExecutor.php
The change in 380dce9a6b2886f1ff89103ea170092abe8866f5 ~effectively renders the earlier change superfluous.~
~This reverts commit 14962776971e753b31a062783ad758ed0e8dde24.~
=> Reference co-relating code sequence for tty test, refs #9454

src/Composer/DependencyResolver/LockTransaction.php, src/Composer/DependencyResolver/Pool.php, src/Composer/DependencyResolver/Rule.php, src/Composer/DependencyResolver/RuleSetGenerator.php, tests/Composer/Test/DependencyResolver/SolverTest.php, tests/Composer/Test/Fixtures/installer/alias-in-lock2.test, tests/Composer/Test/Fixtures/installer/alias-on-unloadable-package.test, tests/Composer/Test/Fixtures/installer/aliases-with-require-dev.test, tests/Composer/Test/Fixtures/installer/root-alias-gets-loaded-for-locked-pkgs.test
Fixes https://github.com/composer/composer/issues/9448
Replaces PR https://github.com/composer/composer/pull/9473 with some more tests, new rule type for error reporting and some generator cleanup.
=> Make sure the root aliases always get installed when a package is updated

bin/compile, bin/composer
ini_set is taking a string as parameter, not an integer: https://www.php.net/manual/en/function.ini-set.php
=> Fix a type-juggling issue

phpstan/config.neon, src/Composer/Command/SelfUpdateCommand.php, src/Composer/DependencyResolver/Operation/OperationInterface.php, src/Composer/Installer/PackageEvent.php, src/Composer/Repository/PlatformRepository.php, src/Composer/Util/Bitbucket.php, src/Composer/Util/Http/ProxyManager.php, src/Composer/Util/NoProxyPattern.php, tests/Composer/Test/Repository/PlatformRepositoryTest.php, tests/Composer/Test/Util/AuthHelperTest.php
Hi,
after reading #9450, I think we can adopt an intermediate step when increasing phpstan level.
Level 2 show ~280 errors and could be hard fixing them without a baseline. Instead of increase full level we can add explicit rules from a higher level and fix errors progressively easier.
This PR fixes phpdocs issues and add some phpstan level 2 rules to config file.
=> Fix phpstan phpdocs issues

doc/articles/scripts.md
I wasn't entirely clear the difference between post-root-package-install and post-create-project-cmd, so this is an effort to clarify (as to the best of my understanding.)
=> Clarify difference in create-project related scripts

src/Composer/Package/Loader/ArrayLoader.php
The `bin` config is supposed to be an array, but before PHP8 it could also be a string and it worked fine.
From PHP8 the behaviour has changed and now a warning is emitted: `Only the first byte will be assigned to the string offset`.
It's worth mentioning it affects Composer v1 & Composer v2.
=> Fix error with bin config in PHP8

src/Composer/DependencyResolver/PoolBuilder.php, src/Composer/DependencyResolver/Problem.php, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/partial-update-unfixing-locked-deps.test, tests/Composer/Test/Fixtures/installer/partial-update-keeps-older-dep-if-still-required-with-provide.test, tests/Composer/Test/Fixtures/installer/partial-update-keeps-older-dep-if-still-required.test
This fixes an issue experienced by user as an unexplainable conflict:
```
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
Problem 1
- root/req1 is locked to version 1.0.0 and an update of this package was not requested.
- root/req1 1.0.0 requires dep/pkg1 1.* -> found dep/pkg1[1.0.0] but these were not loaded, likely because it conflicts with another require.
```
The explanation "because it conflicts with another require" is false in this case. The package simply didn't get loaded into the pool because of a bug.
Fixes https://github.com/composer/composer/issues/9489
=> PoolBuilder: Ensure versions matching locked constraints get loaded

src/Composer/Command/SelfUpdateCommand.php
Changing the compose already up to date message from 'You are already using composer version #' to 'You are already using the latest available composer version #'.
=> Improving Composer self-update (version up-to date) info message

src/Composer/Cache.php
Running parallel writes to cache may lead to race condition, when .tmp file is already renamed.
I'm getting error during tests via GitLab CI:
- using docker-runners with shared composer cache (by mounting `/var/composer/cache`)
- 3 parallel jobs (phpstan, phpcs, phpunit)
- each make own `composer install`
- usually all jobs pass install-phase without errors
- sometimes one of jobs fails to install (see #9568)
May be there is other way:
- to reproduce this race condition (it is necessary?)
- workaround this problem with locks (ex. flock+timeout) - for me using locks is a proper way, but it would be a bit more complicated rather then just using more unique temporary filenames for every file/install.
Closes #9568
=> feat(Cache): make cache writes more atomic

src/Composer/Downloader/TransportException.php, src/Composer/Util/Http/CurlDownloader.php, src/Composer/Util/Http/CurlResponse.php, src/Composer/Util/Http/Response.php
This PR adds a way to expose response information for HTTP requests in CurlDownloader. The response information stored is from `curl_getinfo()`.
This makes it possible to log certain data, like for instance the total response time per HTTP request.
=> Add response info for HTTP requests in CurlDownloader

src/Composer/Util/Http/CurlDownloader.php, src/Composer/Util/HttpDownloader.php, src/Composer/Util/Loop.php
The current sleeps mean that large files download slowly as select would return quickly when data has arrived and needs to be processed, but the sleep waits while the buffers are full.
On the flipside we need to ensure that some code that would keep the CPU busy if run too often does not get run every time select returns.
=> Remove sleeps from curl handling, select it is responsible for waiting

src/Composer/Util/Filesystem.php
this reproducible saves 1-2 seconds while running `COMPOSER_DISABLE_NETWORK=1 php
composer/bin/composer install -vvv --profile` on the [rector/rector project](https://github.com/rectorphp/rector)
before: 63-65 seconds
after (with this patch): 61-63 seconds
```
...
[14.3MiB/54.17s] Generating autoload files
[16.2MiB/56.32s] > post-autoload-dump: PackageVersions\Installer->dumpVersionsClass
[16.3MiB/56.32s] composer/package-versions-deprecated: Generating version class...
[16.3MiB/56.33s] composer/package-versions-deprecated: ...done generating version class
[15.5MiB/56.42s] 80 packages you are using are looking for funding.
[15.5MiB/56.42s] Use the `composer fund` command to find out more!
[15.5MiB/56.42s] > post-install-cmd: Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->on …
```
=> Filesystem: use is_dir() instead of file_exists() which is faster

doc/faqs/how-to-install-composer-programmatically.md
Some people have wget, others have cURL, but we all have PHP. ;)
It looks silly, but e.g. the `debian:buster-slim` Docker image has neither `curl` nor `wget` installed by default.
=> Remove dependency on wget from install docs

doc/articles/versions.md
I couldn't find a place in the docs that explains what makes a stable version stable or not stable.
=> Docs: explain how Composer gets the stability from a version

src/Composer/Downloader/GitDownloader.php, tests/Composer/Test/Downloader/GitDownloaderTest.php
use a single process instead of 3 to improve performance
this saves 0.5-1 second while running `COMPOSER_DISABLE_NETWORK=1 php
composer/bin/composer install -vvv --profile` on the [rector/rector project](https://github.com/rectorphp/rector)
=> GitDownloader: combine checkout + reset commands into a single process

src/Composer/Autoload/ClassLoader.php
A recent change in the ClassAutoloader (#9635) added support for specifying a vendorDir, and `\Composer\Autoload\ClassLoader::register` now has a if-elseif-else chain.
The first block has a `// no-op` comment, followed by an `elseif` block. It's more readable to `return;`, and remove the `elseif` for readability.
=> Minor improvement to ClassLoader::register no-op block

src/Composer/Installer.php
I need this for my https://www.composer-resolver.cloud service.
Right now the cloud resolver is sort of broken because while it's true that you have to send your local platform along with the composer.json and composer.lock, these are only handled as overrides. Which means that if you e.g. do not send libsodium (because you don't have it locally) the cloud (which does provide it) will still happily resolve the dependencies. Hence, I cannot work with platform overrides, I have to replace the whole PlatformRepository.
I don't think this is a very common use case though :) So I figured just allowing me to replace it in an extended child class would be enough. No need for a setter or a factory.
=> Allow to override Installer::createPlatformRepo

src/Composer/DependencyResolver/SolverProblemsException.php, tests/Composer/Test/Fixtures/installer/conflict-with-all-dependencies-option-dont-recommend-to-use-it.test
Fixes #9665
- Add a check to avoid hinting the user for --with-all-dependencies on solver problem exception when he already used it
=> Fixes #9665

src/Composer/Json/JsonFile.php
Hi,
while developing a composer plugin, I missed some throws annotations from `Composer\Json\JsonFile`
This PR adds `@throws ParsingException` to methods:
- `parseJson`
- `read`
- `validateSchema`
=> JsonFile: add missing ParsingException throws annotations

src/Composer/Repository/Vcs/GitDriver.php, src/Composer/Util/ProcessExecutor.php
=> Fix processes silently ignoring the CWD when it does not exist

src/Composer/Repository/PlatformRepository.php
PackageRepository assumes that if the `libsodium`/`sodium` extension is installed, that the `SODIUM_LIBRARY_VERSION` constant will be defined, however that constant wasn’t added until v2 of the Sodium extension.
This PR checks to make sure the constant is defined before attempting to reference it.
=> Check if SODIUM_LIBRARY_VERSION is defined

src/Composer/Autoload/ClassMapGenerator.php, tests/Composer/Test/Autoload/ClassMapGeneratorTest.php, tests/Composer/Test/Autoload/Fixtures/php8.1/enum_backed.php, tests/Composer/Test/Autoload/Fixtures/php8.1/enum_basic.php, tests/Composer/Test/Autoload/Fixtures/php8.1/enum_class_semantics.php, tests/Composer/Test/Autoload/Fixtures/php8.1/enum_namespaced.php
PHP 8.1 supports Enums, and [Enums follow class-semantics](https://php.watch/versions/8.1/enums#class-semantics-autoload).
Composer's class-map generator currently looks for `class`, `interface`, and `trait` keywords. If Composer is run in PHP 8.1 or later, Composer now additionally looks for `enum` keyword as well. This is similar to how Hack's `enum` support is added.
This PR also adds tests for basic enums, backed enums, namespaced enums, and an enum that implements an interface and extends a class.
=> Add support for autoloading Enums

src/Composer/InstalledVersions.php, src/Composer/Repository/FilesystemRepository.php, tests/Composer/Test/InstalledVersionsTest.php, tests/Composer/Test/Repository/FilesystemRepositoryTest.php, tests/Composer/Test/Repository/Fixtures/installed.php, tests/bootstrap.php
Will help to fix issues like https://github.com/symfony/symfony/issues/40136
=> Allow querying InstalledVersions::isInstalled() for no-dev packages

src/Composer/Command/FundCommand.php
Hey,
currently building a little GUI around composer. I want to show funding information in the GUI.
Therefore i added `--format` option to the `composer fund` command which allows to output
fund details as JSON.
=> Add --format option to `composer fund` command

doc/03-cli.md, doc/articles/scripts.md, src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Command/DumpAutoloadCommand.php, src/Composer/Installer.php
Triggered by https://github.com/composer/package-versions-deprecated/issues/23 - I realized this now can be automated. IMO there really should be no reason to dump an autoloader without dev packages, if you installed dev packages. This causes inconsistencies like InstalledVersions having packages which are then not autoloadable, so should be discouraged.
=> Auto-detect dev-mode in autoload-dump and deprecate dump-autoload --no-dev

src/Composer/Downloader/ArchiveDownloader.php, src/Composer/Util/Filesystem.php
this turns half of the `rm -rf ...` executions async and therefore improves performance.
before:
```
COMPOSER_DISABLE_NETWORK=1 php ../../../Users/mstaab/Documents/GitHub/composer/bin/composer install -vvv --profile
...
[15.5MiB/27.04s] Memory usage: 15.5MiB (peak: 17.53MiB), time: 27.04s
```
after:
```
COMPOSER_DISABLE_NETWORK=1 php ../../../Users/mstaab/Documents/GitHub/composer/bin/composer install -vvv --profile
...
[15.5MiB/25.83s] Memory usage: 15.5MiB (peak: 17.53MiB), time: 25.83s
```
=> Filesystem: added removeDirectoryAsync() and use it in ArchiveDownloader

src/Composer/Command/BaseDependencyCommand.php, src/Composer/Command/DependsCommand.php, src/Composer/Command/ProhibitsCommand.php
Refs #9693
Strictly speaking a minor break but as it's really the way this was intended to be used and kinda just enforces the expectations instead of loosely allowing misuse, I think it's fine.
=> Remove version argument from why and enforce it for why-not command

src/Composer/Compiler.php
I guess I'm the only one who runs the compiler on Windows PHP.
=> Fix compiler on Windows

src/Composer/Command/SelfUpdateCommand.php
Windows PHP `rename` uses MoveFileEx which preserves the source file
permissions when creating the destination file*. If the user is running
as an Admin and the destination file is in a common (non-user) location,
then the permission for other users will be replaced by the admin user.
This means that other users will no longer be able to run
composer.phar
Additionally, the UAC elevation feature uses the cmd.exe `move` command
which behaves as above, rather than the `copy` command which creates the
destination file with permissions inherited from the parent folder - but
only if inheritance is enabled, which is the default.
This fix runs `icacls` after admin operations to reset the inherited
permissions. This is equivalent to deleting the destination file first,
then creating it as new from …
=> Reset file access on Windows admin self-update

doc/03-cli.md
`composer fund -f summary` does not exist, this pr will remove "summary" option in the docs.
=> Remove output "summary" from fund command

src/Composer/Command/CreateProjectCommand.php, src/Composer/Installer/InstallationManager.php
We are seeing the following PHP error when Composer is run from a web request using Windows:
> Error updating Composer requirements: CTRL events trapping is only supported on console
Here’s where it originates in PHP: https://github.com/php/php-src/blob/cb7b49dcf84846a79a19d75d0cdb82a9869c0465/win32/signal.c#L107-L110
We’ve verified that this PR fixes it, by checking if it’s a CLI request in addition to whether the `sapi_windows_set_ctrl_handler()` function exists.
=> Only call sapi_windows_set_ctrl_handler() for CLI requests

src/Composer/Downloader/FileDownloader.php, src/Composer/Util/Http/CurlDownloader.php
MaxFileSizeExceededException didn't trigger the job reject callback and never deleted the temporary file with the `~` at the end.
=> MaxFileSizeExceededException should reject download job

src/Composer/Command/RunScriptCommand.php
I propose to add COMPOSER_DEV_MODE env var for run-scripts command.
It's useful if i want to run some shell(or any non-php) script in hook, so It's impossible to check passed php var inside event.
=> Add dev mode env var for scripts run command

src/Composer/Repository/ComposerRepository.php
This is spun off from discussion in #9740.
The php-tuf/composer-integration plugin, which aims to help secure Composer operations with The Update Framework, has to do some..._interesting_ things to work properly. Amongst those interesting things is the roundabout use of a specialized package loader in order to set certain transport options on packages. @Seldaek pointed out that it would be easier and cleaner to just override ComposerRepository::configurePackageTransportOptions(), but unfortunately that's a private method. This PR proposes to change it to protected so that it can be extended and overridden by subclasses of ComposerRepository.
=> Make ComposerRepository::configurePackageTransportOptions() protected.

src/Composer/DependencyResolver/LockTransaction.php, src/Composer/Installer.php, tests/Composer/Test/Fixtures/installer/update-mirrors-changes-url.test
Fixes #9812
Note that without the fix, the test I changed would have an output of:
```
Updating dependencies
Lock file operations: 0 installs, 5 updates, 0 removals
- Upgrading a/a (dev-master 1111111 => dev-master 2222222)
- Upgrading b/b (2.0.3 1111111 => 2.0.3 2222222)
- Upgrading c/c (1.0.0 1111111 => 1.0.0 2222222)
- Upgrading f/f (dev-master 1111111 => dev-master 2222222)
- Upgrading g/g (dev-master 0000000 => dev-master 1111111)
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
```
The issue is we do output the update operations which do happen but then in LockTransaction::getNewLockPackages those changes are internally reverted by …
=> Fix output listing some updates that do not really happen when updating mirrors/--lock

src/Composer/Downloader/FileDownloader.php, src/Composer/Plugin/PluginInterface.php, src/Composer/Plugin/PostFileDownloadEvent.php, src/Composer/Plugin/PreFileDownloadEvent.php, src/Composer/Repository/ComposerRepository.php, tests/Composer/Test/Plugin/Fixtures/plugin-v8/composer.json
This is spun off from discussion in #9740 and #9819.
Right now, it's not possible for plugins (in this case, specifically php-tuf/composer-integration) to react to Composer downloading package metadata. The methods which do that grunt work cannot be overridden because they're private, and no event is dispatched after the metadata is downloaded. @Seldaek suggested modifying ComposerRepository to fire the POST_FILE_DOWNLOAD plugin event after metadata is downloaded, but before it is cached. This PR implements that.
This requires changes to the PostFileDownloadEvent class. Namely, it has be able to accept a type (`package` or `metadata`, similar to what PreFileDownloadEvent already does) and additional context beyond just an instance of `PackageInterface`.
=> Fire POST_FILE_DOWNLOAD event for metadata fetched by ComposerRepository

bin/composer, composer.json, composer.lock, src/Composer/Command/DiagnoseCommand.php, src/Composer/Console/Application.php, tests/Composer/Test/ApplicationTest.php
This adds support for Xdebug3 modes and changes the default behaviour from always restarting if Xdebug is loaded, to only restarting if Xdebug is active.
Xdebug is considered active if it is loaded, and for Xdebug3, if it is running in a mode other than `xdebug.mode=off`.
=> Upgrade to xdebug-handler 2

doc/03-cli.md, src/Composer/Command/InitCommand.php, tests/Composer/Test/Command/InitCommandTest.php
Hello,
This PR extends the "composer init" command. It adds the "--autoload" parameter.
**Automatically generates a PSR-4 autoload** entry in your composer.json based on your **package name** and the interactive **configured src** path. The configured path is created automatically. The autoload feature is **optional**.
This is **helpful to kickstart a new project**, because PSR-4 autoload is required most of the time for new projects.
**Example info:**
In the following examples, the name of the new composer package is: `new_projects.acme-extra/package-name`
**Interactive mode**
`composer init`
...
`Add PSR-4 autoload mapping? Map namespace "Acme\Package" to the entered relative path. [src/, n to skip]:`
**Command parameter**
`composer init --autoload src/`
**Command --help**
`-a, …
=> "composer init --autoload" - Interactive generates PSR-4 autoloader in composer.json

src/Composer/Installer/BinaryInstaller.php, src/Composer/Util/Platform.php
feature detect WSL and install all binaries in this case.
this is usefull to get the *.bat files on a windows host, which can then be invoked from the regular CLI, or used within IDEs etc.
closes https://github.com/composer/composer/issues/9841
tested on Windows10x64 in WSL, CMD and git-bash-for-windows
=> BinaryInstaller: install full binaries on WSL when bin-compat=auto

src/Composer/Package/Version/VersionSelector.php, tests/Composer/Test/Package/Version/VersionSelectorTest.php
=> Use a simpler suggested require version of * to keep things simple for extensions which are versioned like PHP

doc/02-libraries.md
If i understand correctly, package names are required to be lower case since composer 2.0, so these docs were no longer up to date.
=> Make a note about lower casing of package names

src/Composer/Repository/PlatformRepository.php, src/Composer/Util/StreamContextFactory.php
Just an idea.. not sure what others think, but this would let us collect info on what the actual php-deploy-target version of the project is, vs using what the developers are running.
For composer this results in something like `User-Agent: Composer/2.0.999-dev+source (Linux; 4.19.104-microsoft-standard; PHP 8.0.3; cURL 7.68.0; Platform-PHP 5.3.9)` - where we see although I'm using php 8, my stats for this should actually count as 5.3.9 because it's what we "deploy" to.
I am not sure if the two versions differ often enough to be important/relevant/interesting though.
=> Add Platform-PHP version to user-agent header to improve targetted-php stats

res/composer-schema.json, src/Composer/Json/JsonFile.php, tests/Composer/Test/Json/ComposerSchemaTest.php
According to documentation [name](https://getcomposer.org/doc/04-schema.md#name) and [description](https://getcomposer.org/doc/04-schema.md#description) are optional for non-published packages
=> Allow optional name and description fields for project type

src/Composer/InstalledVersions.php
Since 2.0.9 returns packages from all loaded vendors, I think this method became kinda bad.  I doubt it's in broad use anyway but might as well be clear that it's not recommended anymore.
=> Deprecate InstalledVersions::getRawData in favor of getAllRawData

doc/04-schema.md, res/composer-schema.json, src/Composer/Json/JsonFile.php, src/Composer/Util/ConfigValidator.php, tests/Composer/Test/Json/ComposerSchemaTest.php, tests/Composer/Test/Json/JsonFileTest.php
Refs https://github.com/composer/composer/pull/9782#issuecomment-844983851:
> We could make the name/description optional in the schema, and change the rules at runtime to make them required instead of the opposite (which is what we do now). I think that probably makes the schema the most re-usable while not changing much for composer users.
This PR basically reverts the recently merged #9782 (and the follow-up commit 458bd41d8fe8df7e3da7dad8cfd09ea4dfc0d3cd) and inverts the original logic.
So name/description become always optional for pure JSON schema validation [even for non-project type], and are still always required at runtime for `composer validate` (strict errors, or warnings with `--no-check-publish`) [even for project type].
Similarly, additional properties become allowed in the …
=> Invert strict/lax schema validation

doc/06-config.md, src/Composer/Config.php, src/Composer/Repository/Vcs/GitLabDriver.php, tests/Composer/Test/Repository/Vcs/GitLabDriverTest.php
Follow-on to https://github.com/composer/composer/pull/8001, also references https://github.com/composer/satis/issues/419 and https://github.com/composer/composer/issues/4744.
Introduces a `gitlab-protocol` option to force the use of a particular protocol for the `source` value when writing `composer.lock`. E.g., this is helpful when you may reference private repositories on a GitLab instance which will be pulled in using a GitLab CI token. This basic HTTP auth for dependencies is obviously not possible over git+ssh.
Includes a test and update to docs.
=> Introduce gitlab-protocol option to force source repository URL (e.g., to HTTPS)

doc/06-config.md, src/Composer/Factory.php
Other popular CLI apps that put caches in `~/Library/Caches` in macOS:
- [helm](https://helm.sh/)
- [heroku](https://devcenter.heroku.com/articles/heroku-cli)
- [homebrew](https://brew.sh/)
- [pip](https://pypi.org/project/pip/)
- [vercel](https://vercel.com/cli)
- [yarn](https://yarnpkg.com/)
Those apps may also leverage `~/Library/Application Support` or `~/Library/Preferences` which may be a place for `$COMPOSER_HOME`
=> macOS cache dir

doc/03-cli.md, src/Composer/Command/ReinstallCommand.php, src/Composer/Console/Application.php
Fixes #3112
Long time requested feature, and while I was not so convinced at first, a few points were made that i.e. with custom-install paths and packages relying on files autoloading, "rm -rf vendor/foo/bar && composer install" isn't always as easy as it sounds.
=> Add a reinstall command

src/Composer/DependencyResolver/Rule.php, tests/Composer/Test/Fixtures/installer/conflict-against-provided-by-dep-package-works.test, tests/Composer/Test/Fixtures/installer/conflict-against-provided-package-works.test, tests/Composer/Test/Fixtures/installer/conflict-against-replaced-by-dep-package-problem.test, tests/Composer/Test/Fixtures/installer/conflict-against-replaced-package-problem.test
Fixes #9834
This also adds tests to cover the case for conflicts against provides, which does not conflict. I don't think it was covered before.
=> Add better error reporting for cases where a package conflicts with a replace and not directly a package

src/Composer/DependencyResolver/PoolBuilder.php, tests/Composer/Test/Fixtures/installer/partial-update-always-updates-symlinked-path-repos.test
Fixes #9751
I still don't know if it's a good idea but the implementation is quite clean at least.
=> Always mark symlinked path packages for update even during partial updates to make sure they always reflect the current state on disk

src/Composer/Platform/Version.php
As reported in #9931.
Unfortunately I gave not been able to track down the input which is causing the notices to be thrown, which is why I haven't added a test case to the unit tests. Would be great if someone would known the exact input to use for those.
The issue (and fix) can be verified by using the "quick preview" option and choosing `git.master` with this code sample: https://3v4l.org/1fr2g
Fixes #9931
=> PHP 8.1 | Fix "Implicit conversion from non-compatible float" deprecation notice

src/Composer/Command/CreateProjectCommand.php, src/Composer/Command/DumpAutoloadCommand.php, src/Composer/Command/InstallCommand.php, src/Composer/Command/ReinstallCommand.php, src/Composer/Command/RemoveCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Command/UpdateCommand.php, src/Composer/EventDispatcher/EventDispatcher.php, src/Composer/Installer.php
Right now, when composer runs with `--no-scripts`, it not only disables "scripts" entries from the composer.json file, but it also prevents plugins from actually doing anything. This PR fixes it.
=> Fix --no-scripts disabling events for plugins

doc/06-config.md, res/composer-schema.json, src/Composer/Command/ConfigCommand.php, src/Composer/Installer/BinaryInstaller.php
=> Add "symlink" option for "bin-compat" config

.github/workflows/continuous-integration.yml, .github/workflows/lint.yml
Turns out the default setting for `error_reporting` used by the SetupPHP action is `error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT` and `display_errors` is set to `Off`.
For the purposes of CI, I'd recommend running with `E_ALL` and `display_errors=On` to ensure **all** PHP notices are shown.
`latest` in the matrix will always refer to the latest stable PHP release, which would now be PHP 8.0.
=> GH Actions: set error_reporting to E_ALL

src/Composer/Package/CompletePackage.php
Hello there :slightly_smiling_face: :wave: 
in the [ArrayLoader](https://github.com/composer/composer/blob/master/src/Composer/Package/Loader/ArrayLoader.php#L281-L283) the authors are only set if the value is an array. If this is not the case or simply no authors are given in the composer.json, the [`$authors` property](https://github.com/composer/composer/blob/master/src/Composer/Package/CompletePackage.php#L25) stays `null`
So the annotation on the interface for `getAuthors` is not correct. 
I guess this is also the case for other properties, but this just showed up for us, as we need to tell PHPStan, that `getAuthors` returns `array|null`
Let me know, if I should also fix the other properties :slightly_smiling_face: 
EDIT:
As suggested, I changed the initial values of the properties …
=> Fix initial values of CompletePackage properties

src/Composer/Factory.php, src/Composer/Repository/FilesystemRepository.php, src/Composer/Util/Filesystem.php, tests/Composer/Test/Mock/FactoryMock.php, tests/Composer/Test/Repository/FilesystemRepositoryTest.php, tests/Composer/Test/Util/FilesystemTest.php
=> Fix UNC/WSL-path issues when running in Windows

doc/04-schema.md
From the Symfony Dev #french slack channel (symfony-devs.slack.com), people look confused regarding the value to use as license for proprietary projects, even though it's written in the documentation.
Because proprietary software is still a massive part of composer's usage, I think it can be interesting to have it as a note, more readable to people.
Extract from the conversation:
> J’étais sur la bonne page, il me manquait deux lignes de scroll pour voir ça -.- On a tous nos petits moments de faiblesse
Which roughly translates to:
> I was looking at the right page, just about two lines above... We all have our weak moments
=> Highlight the proprietary license trick

src/Composer/Console/Application.php
I just fell in a case where I had the following code, that always have to return result or exception, and during some commands execution, I was leading to nothing.
```php
$application = new Application();
$application->setAutoExit(false);
$application->setCatchExceptions(false);
$input = new StringInput($command);
try {    
$exitCode = $application->run($input, $this->getOutput());
} catch (\Exception $exception) {
$this->error($exception->getMessage());
$exitCode = 1;
} finally {
return $this->printResult($exitCode, $command);
}
```
Debugging the code, it lead me to this error:
```bash
Composer could not find a composer.json file in /app/public
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```
Although, …
=> Respect parent setting, handling exceptions

composer.lock
Changes:
- Added: support for xdebug_info('mode') in Xdebug 3.1.
- Added: support for Psr\Log versions 2 and 3.
- Fixed: remove ini directives from non-cli HOST/PATH sections.
Note that although Xdebug 3.1 has not yet been released, the new API `xdebug_info('mode')` has been documented: https://xdebug.org/docs/all_functions#xdebug_info
=> Update to xdebug-handler 2.0.2

src/Composer/Package/Archiver/PharArchiver.php, src/Composer/Repository/Vcs/BitbucketDriver.php, src/Composer/Util/GitLab.php, src/Composer/Util/NoProxyPattern.php, tests/Composer/Test/AllFunctionalTest.php, tests/Composer/Test/DependencyResolver/PoolBuilderTest.php, tests/Composer/Test/InstallerTest.php
To "ignore" an optional parameter when another optional parameter after it needs to be passed, the default value should be passed, not `null`.
The default value for the `preg_split()` `$limit` parameter is `-1`, not `null`.
Fixes numerous `preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated` notices when running the test suite.
Ref: https://www.php.net/manual/en/function.preg-split.php
The default value for the `preg_split()` `$limit` parameter is `-1`, not `null`.
Fixes some `preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated` notices when running the test suite.
```
Deprecation triggered by Composer\Test\Util\Http\ProxyManagerTest::testGetProxyForRequest:
preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated …
```
=> PHP 8.1: fix deprecation warnings about incorrect default values

src/Composer/Package/Archiver/ArchivableFilesFilter.php, src/Composer/Package/Archiver/ArchivableFilesFinder.php
Follow up on #10008 and the various commits made for that.
=> PHP 8.1: fix more return type deprecation warnings

src/Composer/Util/Url.php, tests/Composer/Test/Util/UrlTest.php
New GitHub tokens have one of the following prefixes:
* ghp for GitHub personal access tokens
* gho for OAuth access tokens
* ghu for GitHub user-to-server tokens
* ghs for GitHub server-to-server tokens
* ghr for refresh tokens
I am not sure what the comment above was referring to `or a modern github token (e.g. gp1_xxx)` this is now using the same regex as the ProcessExecutor https://github.com/composer/composer/blob/master/src/Composer/Util/ProcessExecutor.php#L93
=> Url: fix sanitize for new github tokens

src/Composer/Autoload/ClassMapGenerator.php, tests/Composer/Test/Autoload/ClassMapGeneratorTest.php, tests/Composer/Test/Autoload/Fixtures/classmap/StripNoise.php, tests/Composer/Test/Autoload/Fixtures/pcrebacktracelimit/StripNoise.php, tests/Composer/Test/Autoload/Fixtures/pcrebacktracelimit/VeryLongHeredoc.php, tests/Composer/Test/Autoload/Fixtures/pcrebacktracelimit/VeryLongNowdoc.php, tests/Composer/Test/Autoload/Fixtures/pcrebacktracelimit/VeryLongPHP73Heredoc.php, tests/Composer/Test/Autoload/Fixtures/pcrebacktracelimit/VeryLongPHP73Nowdoc.php
... to proof the existence of the bug and demonstrate the effect.
Note: in the test the backtrack limit is being lowered (and restored back to the default afterwards) to prevent the tests needing ridiculously huge test fixture files.
In PHP < 7.3, the heredoc/nowdoc marker was allowed to occur in the text, as long as it did not occur at the very start of the line.
This was also not handled correctly.
Ref: https://www.php.net/manual/en/migration73.incompatible.php#migration73.incompatible.core.heredoc-nowdoc
By using a look ahead assertion to match "new line - maybe whitespace - marker", the negative performance impact of the `.*` is significantly mitigated and backtracing will be severely limited.
This fixes the bug as reported in #10037.
The bug was discovered due to a PHP 8.1 "passing …
=> ClassMapGenerator: fix two bugs (long heredocs + markers in text)

doc/articles/plugins.md
=> Update the Composer plugin API version to 2.1.0

doc/articles/versions.md
The single pipe (the old alternative to logical OR) is treated as a logical OR but is not currently documented. This can be confusing to developers new to composer who encounter a single pipe and look to the docs for an explaination.
See this issue for more detail: https://github.com/composer/composer/issues/6755#issuecomment-898537753
=> Note in docs about how single pipes are treated

tests/Composer/Test/Installer/LibraryInstallerTest.php
The `LibraryInstallerTest::testUninstall()` method mocks a `Package` object, but did not set an expectation for a call to `getName()`, while that method _is_ called in the `LibraryInstaller::uninstall()` method.
Without expectation, the mock returns `null`, which was subsequently being passed on to `strpos()` leading to the below error.
Fixes:
```
Deprecation triggered by Composer\Test\Installer\LibraryInstallerTest::testUninstall:
strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
Stack trace:
0 [internal function]: Symfony\Bridge\PhpUnit\DeprecationErrorHandler->handleError(8192, '...', '...', 202)
1 src/Composer/Installer/LibraryInstaller.php(202): strpos(NULL, '...')
2 vendor/react/promise/src/FulfilledPromise.php(28): …
```
=> PHP 8.1/LibraryInstallerTest: add missing mock expectation

src/Composer/Package/Package.php
Discovered while running the existing unit tests on PHP 8.1.
The default state of the protected `$distUrl` property is "not set" and the property may not be set when the `Package::setSourceDistReferences()` method gets called.
Fixes a total of 9 deprecation notices along the lines of:
```
Deprecation triggered by Composer\Test\DependencyResolver\PoolBuilderTest::testPoolBuilder:
preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated
Stack trace:
0 [internal function]: Symfony\Bridge\PhpUnit\DeprecationErrorHandler->handleError(8192, '...', '...', 597)
1 src/Composer/Package/Package.php(597): preg_match('...', NULL)
2 src/Composer/DependencyResolver/PoolBuilder.php(360): Composer\Package\Package->setSourceDistReferences('...')
3 …
```
=> PHP 8.1: prevent a "null to non-nullable" deprecation notice [1]

tests/Composer/Test/InstallerTest.php
Not all tests in the `InstallerTest` class actually create a temporary directory and set the `$this->tempComposerHome` property.
Those tests which didn't, throw a notice in PHP 8.1.
Fixes 3 notices along the lines of:
```
Deprecation triggered by Composer\Test\InstallerTest::tearDown:
is_dir(): Passing null to parameter #1 ($filename) of type string is deprecated
Stack trace:
0 [internal function]: Symfony\Bridge\PhpUnit\DeprecationErrorHandler->handleError(8192, '...', '...', 53)
1 tests/Composer/Test/InstallerTest.php(53): is_dir(NULL)
...
```
=> PHP 8.1: prevent a "null to non-nullable" deprecation notice [2] (test only fix)

phpunit.xml.dist, src/Composer/IO/ConsoleIO.php, src/Composer/Json/JsonValidationException.php, src/Composer/Package/Archiver/ArchiveManager.php, src/Composer/Package/BasePackage.php, src/Composer/Package/Package.php, src/Composer/Package/PackageInterface.php, src/Composer/Util/Bitbucket.php, src/Composer/Util/Perforce.php, src/Composer/Util/ProcessExecutor.php, tests/Composer/Test/Downloader/FileDownloaderTest.php, tests/Composer/Test/Downloader/FossilDownloaderTest.php, tests/Composer/Test/Downloader/GitDownloaderTest.php, tests/Composer/Test/Downloader/HgDownloaderTest.php, tests/Composer/Test/Downloader/PerforceDownloaderTest.php, tests/Composer/Test/EventDispatcher/EventDispatcherTest.php, tests/Composer/Test/Fixtures/installer/update-installed-reference.test, tests/Composer/Test/InstalledVersionsTest.php, tests/Composer/Test/InstallerTest.php, tests/Composer/Test/Mock/ProcessExecutorMock.php, tests/Composer/Test/Package/Loader/RootPackageLoaderTest.php, tests/Composer/Test/Package/Version/VersionGuesserTest.php, tests/Composer/Test/Package/Version/VersionSelectorTest.php, tests/Composer/Test/Repository/Vcs/GitHubDriverTest.php, tests/Composer/Test/Repository/Vcs/PerforceDriverTest.php, tests/Composer/Test/Repository/Vcs/SvnDriverTest.php, tests/Composer/Test/Util/BitbucketTest.php, tests/Composer/Test/Util/GitLabTest.php, tests/Composer/Test/Util/GitTest.php, tests/Composer/Test/Util/MetadataMinifierTest.php
This should get us the deprecations right on the CI for PHP 8.1, so easy to keep an eye out for more.
Fixes #10038
/cc @jrfnl
=> Output deprecations in CI results

.github/CONTRIBUTING.md, .github/workflows/continuous-integration.yml, .gitignore, phpunit.xml.dist, tests/complete.phpunit.xml
... to make it easier on contributors to get the tests running locally with the current setup.
Also includes:
* Adding the typical PHPUnit 8/9 cache file to `.gitignore`.
* Adding information on how to get the tests running locally on PHP 8.0/8.1 to the CONTRIBUTING file.
Related to #10038
=> PHPUnit: move environment variable into PHPUnit config file

doc/05-repositories.md
Adds documentation for the v2 fields in repositories, copied from the upgrading guide and reformatted. See #10032.
=> Add documentation for v2 repository fields

src/Composer/Installer/InstallationManager.php
This fixes https://github.com/composer/composer/issues/10069
When the type of a package changes, Composer does an uninstall and install instead of an update. 78d7792eb810319f86421071bf795ce41eca24f2 added support for handling promises of the installer, but because it returns the `uninstall` promise instead of the resulting `install` promise, the `cleanup` operation in https://github.com/composer/composer/blob/master/src/Composer/Installer/InstallationManager.php#L420 runs before `install` is executed.
---
FYI instead of setting `$promise = $promise->then(…)` we could also just `return $promise->then(…)`
=> Correctly resolve promises when package type changes

doc/articles/troubleshooting.md
* `self-update` should be run first, because it may affect the results of `diagnose`. 
* `clear-cache` should be run before `update`, otherwise `update` would need to be run again after clearing the cache.
=> Docs: Place general troubleshooting steps in a more logical order

src/Composer/Repository/Vcs/GitHubDriver.php
Currently getting 2 notices on PHP 8.1 (on preview and snapshot channel) Dont get confused by the version number in the path its come from brew but the tested version is `Composer version 2.1.6 2021-08-19 17:11:08` and `Composer version 2.1-dev (2.1-dev+5b16d61762579fcd86507292789f1c92432d9e8b) 2021-09-02 15:22:14`:
> `Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/Cellar/composer/2.0.8/bin/composer/vendor/symfony/console/Descriptor/TextDescriptor.php:120`
This one I think was already fixed by the symfony team.
> `Deprecation Notice: explode(): Passing null to parameter #2 ($string) of type string is deprecated in phar:///usr/local/Cellar/composer/2.0.8/bin/composer/src/Composer/Repository/Vcs/GitHubDriver.php:579` …
=> Fix GithubDriver nextPage deprecation notice with no link header

src/Composer/Package/Archiver/ZipArchiver.php
ZipArchive::setExternalAttributesName() is only available when libzip 0.11.2 or higher is present. 
This is not the case with at least SUSE SLES 12, so a simple PHP version check will not work here.
As stated in #8330 and fixed in #8331, Composer is adding the file permissions to ZIPs, but the version check is insufficient to detect if the zip extension is powered by a recent enough libzip version. The extension will transparently not provide the called method if libzip is too old, so the `method_exists()` check has to be added.
Should be able to fix the underlying issue in https://github.com/composer/satis/issues/653
=> Add ability check for ZipArchive

src/Composer/Util/GitLab.php
Currently, Composer shows the following text:
```
To revoke access to this token you can visit https://gitlab.com/profile/applications
```
But this URL returns 404. The correct URL is https://gitlab.com/-/profile/applications
There is another way to get needed credentials in GitLab - [Personal Access Tokens](https://gitlab.com/-/profile/personal_access_tokens) - maybe we should display that URL instead?
=> Changed GitLab's applications URL

src/Composer/Autoload/ClassMapGenerator.php, src/Composer/Autoload/PhpFileCleaner.php, tests/Composer/Test/Autoload/Fixtures/classmap/NonUnicode.php, tests/Composer/Test/Autoload/Fixtures/classmap/StripNoise.php
Fixes #10106
The only downside here as far as I can tell is a slight slowdown, I see a `composer dump-autoload -o --profile` currently taking around 1.3x as long as it did before. The upside is that it's passing the whole test suite while the old code doesn't.
This means it's fine as is IMO, but **if someone wants to poke at it with a profiler to try to extract some last bits of perf, that'd be great**! I already did what I could to remove obvious unnecessary allocation and co but didn't have time to profile.
/cc @jrfnl this last issue was finally the one drop too many and I got rid of the whole thing, happy to get your review here if you have time
=> Rewrite php file cleaning step to be less regex intensive and support extreme cases better

src/Composer/Util/Git.php
Error message might contain git credentials. The simplest way to reproduce it:
1. Setup `github-oauth` in `~/.composer/auth.json`
2. Add some public package to your project:
```
composer require contextualcode/public-package
```
3. Switch the previously added package Git repository into private, and make sure current `github-oauth` has no access to it.
4. Remove the caches:
```
composer clearcache
```
5. Remove the previously checked out sources for `contextualcode/public-package`:
```
rm -Rf vendor/contextualcode/public-package
```
6. Run the composer install
```
composer clearcache
```
7. You will get error message similar to:
```
[RuntimeException] …
```
=> Mask Git credentials in the error message

src/Composer/Repository/VcsRepository.php
Currently Composer ignores all TransportExceptions (except 401 and 403) while fetching composer.json files to import all available versions and then skips those versions.
This pull request changes this behaviour for rate limit errors with a 429 status code. After a rate limit error response was received all future requests to that resource will most likely receive the same error status code which make it unlikely that Composer is able to finish the command.
Sample Composer output for such a scenario:
```
Reading composer.json of acme/package (2.0.0) 
Downloading https://api.bitbucket.org/2.0/repositories/acme/package/src/hash/composer.json
[429] https://api.bitbucket.org/2.0/repositories/acme/package/src/hash/composer.json
Skipped tag 2.0.0, no composer file was found (429 HTTP status …
```
=> VcsRepository: do not continue when receiving 429 rate limit exception

tests/Composer/Test/DependencyResolver/PoolBuilderTest.php, tests/Composer/Test/DependencyResolver/PoolTest.php, tests/Composer/Test/DependencyResolver/SolverTest.php, tests/Composer/Test/DependencyResolver/TransactionTest.php
=> phpstan: update tests/Composer/Test/DependencyResolver/* to level 6 standard

src/Composer/Installer/BinaryInstaller.php, tests/Composer/Test/Installer/BinaryInstallerTest.php
Fixes #10246
Also finally adds some tests for this so we can guarantee it's running well everywhere at least in full compat mode. 
The upside is phar files are now fully supported too by those php proxies.
=> Fix handling of php bin proxies combined with declare() on php <8

src/Composer/Console/GithubActionError.php
When I initially created this class in composer I wasn't aware that there are more chars to escape. 
Now I know :-)
see https://github.com/actions/toolkit/blob/4f7fb6513a355689f69f0849edeb369a4dc81729/packages/core/src/command.ts#L80
=> GithubActionError: escape more special chars

src/Composer/Repository/ArrayRepository.php, src/Composer/Repository/ComposerRepository.php, src/Composer/Repository/RepositoryInterface.php, tests/Composer/Test/Repository/ArrayRepositoryTest.php, tests/Composer/Test/Repository/ComposerRepositoryTest.php
This also fixes the abandoned info via interactive search in the init command.
Was mistakenly removed in https://github.com/composer/composer/commit/4940009f8377d06b9fb48df0cbe67193e0989830#diff-fcfc43da4ed67efe626640158c4aa49d5a162efd01e8844f0fbbc655fcffbddeL431-R433 in the ComposerRepository and apparently never implemented in the ArrayRepository
Noticed via https://github.com/Seldaek/composer/pull/5 
Test case for the init command: add deps interactively and search for e.g. "faker", which should list "fzaninotto/faker" as being abandoned.
=> Add back abandoned key in repository search results

src/Composer/Util/GitHub.php
When the documentation at https://getcomposer.org/doc/articles/authentication-for-private-packages.md#github-oauth is accurate, only limited token scopes are needed:
> For public repositories when rate limited, the public_repo scope is required, for private repositories the repo:status scope is needed. 
This can be indicated in the URL to create tokens with limited capabilities.
It turns out the documentation is not accurate, #10257 updates it.
This PR has been amended to better explain to the user what options they have and to provide different URLs.
=> Limit GitHub token scope when authorizing interactively

doc/articles/authentication-for-private-packages.md
Be more explicit and better explain to users the implications of using GitHub tokens with broad permissions.
Follows up on https://github.com/composer/composer/pull/10256.
=> Update what GitHub token scope is needed and what it implies

src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Command/CreateProjectCommand.php, src/Composer/Command/DumpAutoloadCommand.php, src/Composer/Command/InitCommand.php, src/Composer/Command/InstallCommand.php, src/Composer/Command/ReinstallCommand.php, src/Composer/Command/RemoveCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Command/UpdateCommand.php, src/Composer/DependencyResolver/RuleSetGenerator.php, src/Composer/DependencyResolver/Solver.php, src/Composer/Filter/PlatformRequirementFilter/IgnoreAllPlatformRequirementFilter.php, src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php, src/Composer/Filter/PlatformRequirementFilter/IgnoreNothingPlatformRequirementFilter.php, src/Composer/Filter/PlatformRequirementFilter/PlatformRequirementFilter.php, src/Composer/Filter/PlatformRequirementFilter/PlatformRequirementFilterFactory.php, src/Composer/Filter/PlatformRequirementFilter/PlatformRequirementFilterInterface.php, src/Composer/Installer.php, src/Composer/Package/Version/VersionSelector.php, tests/Composer/Test/Autoload/AutoloadGeneratorTest.php, tests/Composer/Test/Filter/PlatformRequirementFilter/IgnoreAllPlatformRequirementFilterTest.php, tests/Composer/Test/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilterTest.php, tests/Composer/Test/Filter/PlatformRequirementFilter/IgnoreNothingPlatformRequirementFilterTest.php, tests/Composer/Test/Filter/PlatformRequirementFilter/PlatformRequirementFilterFactoryTest.php, tests/Composer/Test/Filter/PlatformRequirementFilter/PlatformRequirementFilterTest.php, tests/Composer/Test/InstallerTest.php, tests/Composer/Test/Package/Version/VersionSelectorTest.php
Introduces a `PlatformRequirementFilter` with methods that help to decide if a requirement is ignored or not as discussed in #10045 but without changing behaviour.
The idea behind this is to be able to adapt simple wildcard or regex ignores in a follow-up.
I changed as much as needed so that the filter and its logic is used everywhere where the `bool|string[]` config was before, because it felt inconsistent otherwise. But I also tried to change as less as possible which is the reason the argument is nullable in some cases and falls back to the nothing filter then or is defined like that in the constructor.
Initially I only had one filter class, but this became already too complex and mixed regarding types in my opinion, so I split responsibilities into dedicated filter classes, which is …
=> Refactor ignore platform reqs checks

src/Composer/Repository/VcsRepository.php
As the name implies, all exceptions are always of type `TransportException`
=> VcsRepository: limit type of versionTransportExceptions

doc/03-cli.md, src/Composer/Command/ConfigCommand.php, src/Composer/Command/CreateProjectCommand.php, src/Composer/Command/DiagnoseCommand.php, src/Composer/Config.php, src/Composer/Factory.php, tests/Composer/Test/ConfigTest.php
Implements: https://github.com/composer/composer/issues/10085
Can be used either to output a specific config e.g.
```
composer config http-basic.repo.example.org.username --source
glaubinix (/Users/glaubinix/.composer/auth.json)
```
or can be used with listing the entire configuration e.g. 
```
composer config -l --source
[process-timeout] 300 (default)
[use-include-path] false (default)
[preferred-install] dist (default)
[notify-on-install] true (default)
[github-protocols] [https, ssh] (default)
[gitlab-protocol]  (default)
[vendor-dir] vendor (/Users/glaubinix/Projects/example/vendor) (default)
[bin-dir] bin (/Users/glaubinix/Projects/example/bin) (./composer.json)
```
=> Config: add source option for command to show where a config value is loaded from

src/Composer/Package/Loader/ArrayLoader.php, src/Composer/Package/Package.php, src/Composer/Package/PackageInterface.php, src/Composer/Repository/PlatformRepository.php, tests/Composer/Test/Autoload/AutoloadGeneratorTest.php, tests/Composer/Test/DependencyResolver/SolverTest.php
This is already relied on in a few places for getRequires at least, so IMO good thing to codify it.
=> Explicitly deprecate misuse of the link setters to enforce the fact they expect maps

doc/articles/troubleshooting.md
Isn't "to" missing before "raise awareness" ?
=> (Probable) typo fix

src/Composer/Downloader/GitDownloader.php
Running `git clone` with the `--dissociate` flag can take several minutes for large git repositories. In certain scenarios, like creating archives, we don't need a fully working copy of the git repository that works independent of the local cache. The archiver removes the clone at the end anyway.
I moved the transport option into a `git` key instead of setting it in the root in case the transport options get passed to `StreamContextFactory::getContext` then this would throw a `Options should have the form ["wrappername"]["optionname"] = $value` error.
=> GitDownloader: add option for single use git clone to avoid --dissociate flag when cloning from local copy

doc/05-repositories.md
* Removed reference to Bitbucket supporting Mercurial
* Added transport options example and reworded the description to differentiate between cURL and stream options
For cURL, shall I list all available options to make it clearer what is possible, e.g. that using `['ssl']['allow_self_signed'] = true` results in streams being used instead of cURL?
=> Docs: add transport options example and differentiate between cURL and stream options

src/Composer/DependencyResolver/PoolBuilder.php, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/multi-repo-replace-partial-update-all.test, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/partial-update-unfixing-replacers.test, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/partial-update-unfixing-with-replacers-providers.test, tests/Composer/Test/Fixtures/installer/github-issues-4795.test, tests/Composer/Test/Fixtures/installer/partial-update-with-dependencies-provide.test, tests/Composer/Test/Fixtures/installer/partial-update-with-dependencies-replace.test, tests/Composer/Test/Fixtures/installer/partial-update-with-deps-warns-root.test, tests/deprecations-8.1.json
Note that the only relevant test is the added one (which failed before by adding way too few packages to the pool).
The other test changes are simply output order changes due to https://github.com/composer/composer/commit/ad4c9671432bad61661ed90d53b627beac16c985
=> Fix unlocking of replacers when a replaced package is unlocked

doc/03-cli.md, src/Composer/Command/OutdatedCommand.php, src/Composer/Command/ShowCommand.php
This allows users to also find libraries that require major platform
changes to unlock updates.
Closes #10291.
=> Support ignore-platform-reqs in `composer outdated`

doc/03-cli.md, src/Composer/Command/BaseCommand.php
This works fine in practice, but the tests fail because it doesn't call the initialization function, so the setup isn't done. I don't see how to fix that.
As discussed in https://github.com/composer/composer/discussions/9974
=> Add COMPOSER_NO_DEV environment variable

doc/04-schema.md, doc/06-config.md, doc/07-runtime.md, doc/articles/vendor-binaries.md, res/composer-schema.json, src/Composer/Composer.php, src/Composer/Config.php, src/Composer/Factory.php, src/Composer/Installer/BinaryInstaller.php, src/Composer/Installer/LibraryInstaller.php
For binaries of packages to be able include the autoload file,
a global variable is now exposed and a proxy file now generated
by default, which exposes the path and includes the original
binary file.
Additionally it is now checked on binary creation whether
the reference binary has a shebang and if not, generates
a much simple proxy code with no magic and eval involved.
Fixes: #10119
=> Expose path to autoload in a global var for binaries

src/Composer/DependencyResolver/PoolBuilder.php, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/mirrored-path-repo/composer.json, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/partial-update-unfixes-path-repo-replacer-with-transitive-deps.test, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/partial-update-unfixes-path-repos-always-but-not-their-transitive-deps.test, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/symlinked-path-repo-replacer/composer.json, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/symlinked-path-repo-with-replaced-deps/composer.json, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/symlinked-path-repo/composer.json, tests/Composer/Test/DependencyResolver/PoolBuilderTest.php, tests/Composer/Test/Fixtures/installer/partial-update-with-symlinked-path-repos.test, tests/deprecations-8.1.json
Refs https://github.com/composer/composer/discussions/10093
As @stof said: 
> @Seldaek maybe this forced inclusion of path packages should be done after building the whitelist with -w/-W, so that the path packages don't automatically whitelist their dependencies when this option are used (they would still whitelist their dependencies if the path packages are explicitly marked for update in the whitelist in the command)
=> Prevent auto-unlocked path repo packages from also unlocking their transitive deps when -w/-W is used

res/composer-schema.json
In continuation of the [discussion](https://github.com/ergebnis/composer-normalize/issues/779), this PR was created.
Only the order of the elements has been changed. Codestyle has remained the same.
=> Feature proposal: sorting keys by logical blocks

src/Composer/Repository/Vcs/GitBitbucketDriver.php, src/Composer/Repository/Vcs/GitHubDriver.php, src/Composer/Repository/Vcs/SvnDriver.php, src/Composer/Repository/VcsRepository.php
Initializing `$this->branches` and `$this->tags` before the data is fetched can lead to wrong/inconsistent data
Example:
calling `$this->getBranches()` once while it throw a 5XX error on the first request (including retries) and then catching that exception here https://github.com/composer/composer/blob/012556d/src/Composer/Repository/VcsRepository.php#L214 results in the driver having an empty branches array stored. Calling it further down will then just return an empty array.
In addition to this PR, I am not sure the VcsRepository should just catch any kind of exception here and ignore it. I feel at least 5XX responses, request timeouts, network errors and such should be thrown again https://github.com/composer/composer/blob/012556d/src/Composer/Repository/VcsRepository.php#L214
=> Drivers: avoid early initialize of tags and branches

src/Composer/Installer/BinaryInstaller.php
A bug was introduced in #10137 that leads
to the situation that by default .bat binaries
are not installed on Windows any more.
Check the correct variable to install .bat
files on Windows by default again.
=> Install full binaries on Windows by default

doc/03-cli.md
=> Fixed documentation for cache-dir location in case of XDG

composer.json, doc/03-cli.md, src/Composer/DependencyResolver/Problem.php, src/Composer/DependencyResolver/RuleSetGenerator.php, src/Composer/DependencyResolver/Solver.php, src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php, src/Composer/Installer.php, tests/Composer/Test/Fixtures/installer/platform-ext-solver-problems.test, tests/Composer/Test/Fixtures/installer/solver-problems.test, tests/Composer/Test/Fixtures/installer/update-ignore-platform-package-requirement-list-upper-bounds.test, tests/deprecations-8.1.json
e.g. `--ignore-platform-req=php+` ignores the upper bound of the php requirements.
Fixes https://github.com/composer/composer/issues/9534
=> Add support for ignoring the upper bound of platform requirements using "name+" notation

doc/03-cli.md
I see that if `extension=bz2` is enabled in php.ini, then archive --format=tar.bz2 works as well.
=> Document archive --format=tar.gz

doc/05-repositories.md
According to https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository, "you should prefix your custom branch name with 'dev-'", but doing so doesn't work.  It needs to be stated that this should only happen in `composer.json`, not the actual branch name.
I've been confused by this [along with many others](https://stackoverflow.com/questions/13498519/how-to-require-a-fork-with-composer#comment82782412_13500676).
Please update the docs with the request to save others some trouble.  Thanks!
I chose the `main` branch because there were too many unrelated changed, but feel free to cherry-pick for 2.1 .
=> Make it explicitly clear that `dev-` shouldn't be in the actual branch name

doc/06-config.md, res/composer-schema.json, src/Composer/Command/ConfigCommand.php, src/Composer/Config.php, src/Composer/Config/JsonConfigSource.php, src/Composer/Plugin/PluginManager.php, tests/Composer/Test/Fixtures/functional/installed-versions/composer.json, tests/Composer/Test/Fixtures/functional/installed-versions2/composer.json, tests/Composer/Test/Plugin/PluginInstallerTest.php
Fixes #5659
Still a few TODOs / open questions
=> Add allow-plugins config value

src/Composer/DependencyResolver/PoolBuilder.php, src/Composer/DependencyResolver/PoolOptimizer.php, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages.test, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/partial-update-unfixes-path-repos-always-but-not-their-transitive-deps.test, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/partial-update-unfixing-locked-deps.test
I have noticed updates of some Drupal packages can be fairly slow. This seems to affect at varying levels. One module I found it reproduces with is if you have `drupal/block_permissions` installed. It appears to be due to the fact it has a requires of `drupal/core ~8` and in the latest version `drupal/core ^8 || ^9`.
When processing the update of the module it then causes the drupal/core package to be downloaded and added to the pool in all versions since 8.0.0 all the way to 8.9 and then 9.0 all the way to 9.2, and all symfony packages that are depended on in-between those versions. This then generates a significant number of conflict rules.
Using the composer.json at https://github.com/drupal/recommended-project/blob/8.9.x/composer.json to reproduce. When editing with nano change the …
=> Filter impossible packages from the pool

doc/03-cli.md, src/Composer/Cache.php, src/Composer/Command/SearchCommand.php, src/Composer/Repository/ArrayRepository.php, src/Composer/Repository/ComposerRepository.php, src/Composer/Repository/PlatformRepository.php, src/Composer/Repository/RepositoryInterface.php
- Performance improvements by caching the /packages.json (only when searching) and /packages/list.json responses for up to 600 seconds and optimizing some code (fixes #10123)
- Add SEARCH_VENDOR search type (fixes #10325)
- Fixes and documents regex searchability at API level, preg_quote user content in search cmd (fixes #10324)
This lays groundwork to be able to further speed up #10320
=> Search improvements

bin/composer, src/Composer/Console/Application.php, src/Composer/Util/ErrorHandler.php
Ports changes from 2.1/main that load `ErrorHandler` early, ignore all deprecation warnings from `vendor/symfony/`, and ignores all return type related deprecation warnings for both the `Symfony` and `Composer` namespaces.
As discussed in #10008.
Broken before:
```
~ $ php -v
PHP 8.1.0 (cli) (built: Dec  8 2021 20:43:30) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies
with Zend OPcache v8.1.0, Copyright (c), by Zend Technologies
with blackfire v1.71.0~linux-x64-non_zts81, https://blackfire.io, by Blackfire
~ $ composer --version
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used …
```
=> ErrorHandler PHP 8.1 compatibility

doc/06-config.md
for conclusion of the change please see discussion in PR comments below.
---
<details>
<summary>original description (outdated)</summary>
the HOME environment parameter is upper-case in most of all systems.
> HOME
>
> The system will initialise this variable at the time of login to be a pathname of the user's home directory. See <pwd.h>.
(from: https://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html)
change case to upper-case (US-ASCII; ref RFC 4790  9.2.1.  ASCII Casemap Collation Description)
</details>
---
=> $home -> $COMPOSER_HOME (doc: config)

doc/00-intro.md, doc/01-basic-usage.md, doc/03-cli.md, doc/04-schema.md, doc/05-repositories.md, doc/06-config.md, doc/articles/authentication-for-private-packages.md, doc/articles/custom-installers.md, doc/articles/plugins.md, doc/articles/repository-priorities.md, doc/articles/resolving-merge-conflicts.md, doc/articles/scripts.md, doc/articles/troubleshooting.md, doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md
=> Fix minor spelling & grammar issues in docs

doc/03-cli.md, src/Composer/Command/BaseCommand.php, src/Composer/Command/CreateProjectCommand.php, src/Composer/Command/DumpAutoloadCommand.php, src/Composer/Command/InstallCommand.php, src/Composer/Command/ReinstallCommand.php, src/Composer/Command/RemoveCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Command/UpdateCommand.php, src/Composer/Console/Application.php, src/Composer/Factory.php, tests/Composer/Test/ApplicationTest.php
Was trying to fix #10351 and figured it would be cleaner if --no-scripts was implicitly handled instead of doing it in every command.
=> Add --no-scripts to all commands and disable plugins/scripts when running self-update

src/Composer/EventDispatcher/EventDispatcher.php
Plugin dependencies still get files autoloaded, but for scripts we keep the old restrictions which is documented at https://getcomposer.org/doc/articles/scripts.md#defining-scripts
> Callbacks can only autoload classes from psr-0, psr-4 and classmap definitions. If a defined callback relies on functions defined outside of a class, the callback itself is responsible for loading the file containing these functions.
Otherwise defining any PHP-callback script would automatically load all `files` from all packages installed, not giving you a chance to review what's present before they execute code, which goes against the new allow-plugin model.
cc @helhum @nicolas-grekas
=> Disable files autoloading for scripts to avoid untrusted code execution at runtime

src/Composer/Repository/Vcs/GitLabDriver.php, tests/Composer/Test/Repository/Vcs/GitLabDriverTest.php
Currently, when using Gitlab VCS, the **support.issues** provides an API endpoint. That was added in a PR related to an other topic (#8510).
Before, with this sample project : https://packagist.org/packages/codingpaws/gitlab-feature
```json
"support": {
"issues": "https://gitlab.com/api/v4/projects/28361162/issues"
}
```
This PR provide web UI URL, inspired by the `GitHubDriver`:
```json
"support": {
"source": "https://gitlab.com/codingpaws/gitlab-feature/-/tree/1.3",
"issues": "https://gitlab.com/codingpaws/gitlab-feature/-/issues"
},
```
=> Use web URL for Gitlab support metadata

src/Composer/Installer/BinaryInstaller.php
Fixes #10389 - or at least adds a utility for packages with problems to fix it by doing something like this:
```
if [[ -z "$COMPOSER_BIN_DIR" ]]; then
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
else
DIR="$COMPOSER_BIN_DIR"
fi
```
Instead of simply `DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"` to find the Composer bin dir.
The problem is before Composer 2.2, when a binary was symlinked into bin-dir, it got executed as `vendor/bin/foo` which ran the script really stored in `vendor/foo/bar/bin/foo`, but `$BASH_SOURCE[0]` was set to `vendor/bin/foo` still, so that allowed people to discover the bin dir. Composer 2.2 always creates proxies instead of symlinking, so now the proxy runs `vendor/foo/bar/bin/foo` directly and so the resolved dir is `vendor/foo/bar/bin` …
=> Make COMPOSER_BIN_DIR env or _composer_bin_dir global available to binaries

src/Composer/DependencyResolver/PoolOptimizer.php, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages-locked-replacer.test, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages-only-required-provides.test, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages-only-required-replaces.test, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages-only-required.test, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages-provides.test, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages-replaces.test, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/filter-impossible-packages.test
Fixes #10394, introduced by #9620
As explained in that issue when I did the optimisation to filter out packages from the pool that would ultimately never be installed due to a locked packages requirements, I hadn't considered that when packages are removed... they may still be in the set of locked packages.
This PR updates the optimisation to ignore any locked package which isn't required by any package in the pool - as that will, as I understand, mean the package is going to be removed and it's requirements will be moot. I have considered the case where a package IS required somewhere in the pool, or even an older version for example, and in those cases the package would have been unlocked when using `-W` anyway. So I believe this is the correct fix.
I tested it against the scenario in …
=> fix: Do not optimise away packages due to a requirement by a locked package that will be uninstalled

src/Composer/Installer/BinaryInstaller.php
Fixes ```self=$(realpath $0 >/dev/null 2>&1)```, which pipes stdout to /dev/null (and is obviously not the intention).
=> Fix symlink resolution in shell proxy

src/Composer/Autoload/ClassMapGenerator.php, src/Composer/Cache.php, src/Composer/Command/DiagnoseCommand.php, src/Composer/Command/InitCommand.php, src/Composer/Console/Application.php, src/Composer/Factory.php, src/Composer/Json/JsonFile.php, src/Composer/Json/JsonFormatter.php, src/Composer/Package/Archiver/ZipArchiver.php, src/Composer/Util/Git.php, src/Composer/Util/RemoteFilesystem.php, src/Composer/Util/StreamContextFactory.php, tests/Composer/Test/Autoload/ClassMapGeneratorTest.php, tests/Composer/Test/Json/JsonFileTest.php, tests/Composer/Test/Platform/HhvmDetectorTest.php, tests/Composer/Test/Util/RemoteFilesystemTest.php
This PR removes a couple of codeblocks that exists just to keep the codebase compatible with deprecated php versions.
Let me know if a different behaviour is needed anywhere instead of removal, I'll be happy to update the PR!
=> Remove codeblocks for php 5 compatibilities

doc/articles/plugins.md
Fixing the API version in the documentation, to be concise with the change done in https://github.com/composer/composer/commit/1b5b5c48bf91f256745740b6b60e460180213d7d
=> Fixing the API version

src/Composer/Command/ConfigCommand.php, src/Composer/Command/FundCommand.php, src/Composer/Command/LicensesCommand.php, src/Composer/Command/SearchCommand.php, src/Composer/Command/ShowCommand.php, src/Composer/Repository/RepositoryInterface.php, src/Composer/Util/PackageInfo.php
fixes #9367
If someone thinks of another good use case for this, do tell.
=> Add links to repo to show/outdated commands package lists

composer.json, composer.lock
cc @johnstevenson see the hack I had to do in bootstrap.php - I am not sure why this is required with v3, or rather I am not sure why it worked before :) 
But it would be nice if [isXdebugActive](https://github.com/composer/xdebug-handler/blob/main/src/XdebugHandler.php#L257) would be working standalone as it is static.
I guess all of the following could be moved into it really, I don't know why this stuff is stored on instance props and not static ones: 
https://github.com/composer/xdebug-handler/blob/ec6aa897c8b6cab05ebaeddade62bb6e4a69ef38/src/XdebugHandler.php#L94-L100
Keeping this PR open as reminder, if it gets fixed in xdebug-handler I will drop the hack on this end.
=> Allow xdebug-handler 3.x, update deps

src/Composer/Repository/Vcs/GitLabDriver.php
Can otherwise cause `Warning: Undefined array key "default_branch" /src/Composer/Repository/Vcs/GitLabDriver.php:287`
=> GitLab: detect repository functionality disabled in Driver

src/Composer/Util/AuthHelper.php, src/Composer/Util/GitHub.php
Fix #10366
This might be a little rough, I tried to keep it consistent with the rest of the auth helper methods which I found a little hard to parse. But if you're happy with the overall approach and provide feedback, I'll clean it up.
=> Fix #10366: Improve messaging when GitHub tokens need SSO authorization

doc/articles/versions.md
- [semver.mwl.be](https://semver.mwl.be) returns a permanent redirect to [semver.madewithlove.com](https://semver.madewithlove.com). We should use the target domain directly.
=> Use new url for semver testing tool

composer.json, composer.lock
Same as in https://github.com/composer/composer/pull/10158
=> Allow psr/log ^3.0

src/Composer/Plugin/PluginManager.php
Instead of  #10354
Inspired by @stof's comment at https://github.com/composer/composer/pull/10354#issuecomment-1013108766
The goal here is to free the ecosystem from having to reference a legacy plugin in their composer.json files.
=> Disable "composer/package-versions-deprecated" by default

src/Composer/Command/SelfUpdateCommand.php
Fixes #10444 and allows PHP 8.1.0 and 8.1.1 versions to keep working
=> Use copy in selfupdate to fix Windows PHP-8.1 regression

src/Composer/Installer/BinaryInstaller.php
=> Add stream_seek to BinProxyWrapper

src/Composer/Command/SelfUpdateCommand.php
If self-update fails because the downloaded file cannot be renamed or copied, it is left wherever it was downloaded to. Because it was always given the same name (`composer-temp.phar`), this didn't seem much of a problem - and could allow the user to manually move it if things got hairy.
However, it is now given a randomized name (3bb78fd1e) which produces multiple files, so this fix deletes the downloaded file on self-update failure.
=> Clean up properly if self-update fails

src/Composer/Installer/BinaryInstaller.php
file_exists is true also for directory and symlink. but later in generateUnixyProxyCode we call `file_get_contents` on the binary, which fails with `file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory` if the binary is a directory.
maybe we can just change file_exists to is_file, but that would probably mess with symlinks.
this problem only started to occur with composer 2.2, in 2.1.16, the problem was silently ignored. because the error in 2.2 is a fatal error, we get no context about the composer package that causes the problem, nor the path that is a directory instead of a file.
=> report error if binary is a directory

src/Composer/Package/Loader/ArrayLoader.php, src/Composer/Package/Loader/ValidatingArrayLoader.php, tests/Composer/Test/Package/Loader/ArrayLoaderTest.php
Asserting that `Package::getVersion/Package::getPrettyVersion` always return a string. Currently this can return bool/int/float/string.
Additionally catching cases where version is not an array/object which currently throws a `TypeError : trim(): Argument #1 ($string) must be of type string, array given`
=> ArrayLoader: handle none string values for version/version_normalized

src/Composer/Command/ShowCommand.php
Hey there,
we are using the `composer outdated --format=json` output to create scheduled JSON files we can use to notify us when projects needs some maintenance. I'd love to have some `abandoned` flag in there so we do not have to parse the `warning` string. 
I'm open for additional changes but this flag would definitely help us and maybe others who are consuming this JSON.
Feedback welcome.
=> Add abandoned flag to show/outdated commands package lists

src/Composer/Installer/BinaryInstaller.php
This fixes a regression introduced in 2.2.2 due to a name clash (as COMPOSER_BIN_DIR already existed and is read by Composer's Config to override the default bin-dir parameter)
Fixes #10504
I'm open to feedback on the new name, and I still need to update the docs to clarify all this, but in principle the fix should work and as the COMPOSER_BIN_DIR var for bin proxies has been available for just over a month it's a small BC break I'm ok making.. I doubt it's in much use if at all.
=> Rename COMPOSER_BIN_DIR (in bin proxies) to COMPOSER_RUNTIME_BIN_DIR 

src/Composer/Repository/ComposerRepository.php, tests/Composer/Test/Repository/ComposerRepositoryTest.php
Hello there :vulcan_salute: 
I found out while using `composer search` that I can not search for two words with a space in between:
```bash
$ composer search ramsey commits
[Composer\Downloader\TransportException]
curl error 3 while downloading https://packagist.org/search.json?q=ramsey commits&type=: URL using bad/illegal format or missing URL
search [-N|--only-name] [-t|--type TYPE] [-f|--format FORMAT] [--] <tokens> (<tokens>)...
```
Same is true for using `composer require`:
```bash
$ composer require
Search for a package: ramsey commits
[Composer\Downloader\TransportException]
curl error 3 while downloading https://packagist.org/search.json?q=ramsey commits&type=: URL using bad/illegal format or missing URL
```
I do not know for the `composre require` command, but for the `composer …
=> Fix usage of spaces for package names in `composer search`/`composer require` commands

src/Composer/Command/ReinstallCommand.php, src/Composer/Repository/FilesystemRepository.php, src/Composer/Repository/InstalledRepositoryInterface.php, src/Composer/Repository/WritableArrayRepository.php
=> Fix reinstall command not firing pre-install-cmd/post-install-cmd events

doc/05-repositories.md, src/Composer/Repository/PathRepository.php, tests/Composer/Test/Repository/PathRepositoryTest.php
Example of composer.json
```
{
"name": "example/example",
"require": {
"pathExample/example": "^1.0"
},
{
"type": "path",
"url": "./pathExample"
}
]  
}
```
Source code in folder pathExample is under git version control and offently updated by developers, and after each update "reference" in composer.lock for this package is update, but it caused a conflict between different branches. So it will be great to have opportunity to configure reference updating like this
```
{
"name": "example/example",
"require": {
"pathExample/example": "^1.0"
},
{
"type": "path",
"url": "./pathExample",
"reference": "none"
}
]  
}
```
Related to https://github.com/composer/composer/issues/10482
=> Add config option for update reference in path repository

src/Composer/Repository/ComposerRepository.php
There is no guarantee that `ComposerRepository::providerListing` is ever initialized. For instance, if the root response doesn't include a `provider-includes` key or the value is an empty array. This currently results in:
```
TypeError: array_keys(): Argument #1 ($array) must be of type array, null given at path/to/composer/src/Composer/Repository/ComposerRepository.php:661
```
=> ComposerRepository: fix array_keys(): Argument #1 () must be of type array, null given

src/Composer/Command/LicensesCommand.php
Currently the LicensesCommand fails, when getting the summary (-f summary) and one of the packages is missing the license information.
This fixes the issue by simply using 'none' as the license, as is used in the text output already.
=> Handle missing license when showing license summary

src/Composer/Package/Package.php, src/Composer/Package/PackageInterface.php, src/Composer/Package/RootPackageInterface.php
To be clear, and to be DRY.
I propose refactor autoload ~~mapping array~~ array type with type alias.
NOTES: `exclude-from-classmap` key is defined in composer-schema, but current array type does not have it. I don't know what to do it. 
https://github.com/composer/composer/blob/main/res/composer-schema.json#L670
In additionally, first of all, there are some duplicates in BetterReflection too. Therefore, I do this PR for clarification about autoload mapping array.
https://github.com/Roave/BetterReflection/blob/5.1.x/src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
=> Introduce phpstan-type about autoload array type to be DRY

src/Composer/DependencyResolver/PoolBuilder.php
I would like to give the pool optimizer another shot 😇 
`--profile` is nice but it doesn't help me at the moment as I don't know when the pool optimizer starts working and I think for quick comparisons of improvements to come (I'm pretty sure I'll find something), a separate message like we also have it in the solver would be great.
=> Improve the pool optimizer logging

src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Util/PackageSorter.php, tests/Composer/Test/Autoload/AutoloadGeneratorTest.php, tests/Composer/Test/Autoload/Fixtures/autoload_static_files_by_dependency.php, tests/Composer/Test/Util/PackageSorterTest.php
Fixes #10614
- Do not read require-dev except for the root package when sorting packages-
- Sort packages with the same weight alphabetically to have a completely stable sort not dependent on input order
=> More deterministic package sorting

src/Composer/DependencyResolver/DefaultPolicy.php
The `$policy->selectPreferredPackages()` is another bottleneck in the `PoolOptimizer` as we call it for every dependency group which can easily happen for 10 000+ times on medium size projects. Most packages match to a lot of dependency groups so we actually compare the same packages over and over again to sort them within one `selectPreferredPackages()` call. The respective 2 `usort()` calls were actually responsible for up to 25% of the whole `PoolOptimizer::optimize()` process.
With this PR we're now caching the result so the sorting can be way faster (another 0.5 - 1 seconds down on the `PoolOptimizer`).
Because we're using the `PolicyInterface` and `Pool $pool` is an argument, we have to make sure the cache is specific to the `$pool` instance. Thanks to the new PHP 7.2 requirement, …
=> Improve performance of DefaultPolicy

src/Composer/Command/OutdatedCommand.php, src/Composer/Command/ShowCommand.php
Add new option --patch-only for `show` and `outdated` commands
[Issue #10503 ](https://github.com/composer/composer/issues/10503)
=> `--patch-only` option for `show` and `outdated` commands

doc/articles/plugins.md, src/Composer/Plugin/PluginManager.php, src/Composer/Util/PackageSorter.php, tests/Composer/Test/Util/PackageSorterTest.php
Fixes #10618
Pinned composer/installers in there already, will add the extra flag to it anyway later but this is needed to fix the immediate issue and avoid BC problems.
=> Load plugins which modify install path early

src/Composer/Package/Version/VersionGuesser.php, src/Composer/Util/ProcessExecutor.php, tests/Composer/Test/Mock/ProcessExecutorMock.php, tests/Composer/Test/Package/Loader/RootPackageLoaderTest.php, tests/Composer/Test/Repository/Vcs/GitHubDriverTest.php, tests/Composer/Test/TestCase.php
Fixes #10568
On a huge repo with many branches like symfony/symfony, this speeds up bootstrap for me from 9sec to 3sec which is quite nice.
=> Parallellize the branch comparisons to speed up bootstrapping/version guessing when on a feature branch

src/Composer/Repository/Vcs/SvnDriver.php
```
In SvnDriver.php line 403:
[TypeError]                                                                  
Composer\Repository\Vcs\SvnDriver::buildIdentifier(): Argument #2 ($revisio  
n) must be of type int, string given, called in src/Composer/Reposi  
tory/Vcs/SvnDriver.php on line 273  
```
=> SvnDriver: buildIdentifier  must be of type int, string given

src/Composer/Package/Loader/ArrayLoader.php, tests/Composer/Test/Package/Loader/ArrayLoaderTest.php
Source and dist reference from third party repositories can contain int values. Example in wpackagist: https://wpackagist.org/p/wpackagist-theme/blankslate%2491eb3d60b45cca3c230a8bbb96e88b06ce3d7ea22a4af26caeaeaaab2f16869d.json
=> ArrayLoader: assert that source/dist reference are string values

src/Composer/Package/Loader/ValidatingArrayLoader.php, tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php
Resolves:
```
Warning: Undefined array key "url"
Uncaught Error: Composer\Pcre\Preg::isMatch(): Argument #2 ($subject) must be of type string, null given in ValidatingArrayLoader.php on line 367
```
=> ValidatingArrayLoader: only validate source/dist properties if they are set

src/Composer/Util/RemoteFilesystem.php
Fixes: `Uncaught Error: Composer\Util\Platform::strlen(): Argument #1 ($str) must be of type string, bool given, called in src/Composer/Util/RemoteFilesystem.php on line 529`
=> RemoteFilesystem: fix result length check

src/Composer/Package/Archiver/ArchivableFilesFinder.php
Fixes: `TypeError(code: 0): strpos(): Argument #1 ($haystack) must be of type string, bool given at src/Composer/Package/Archiver/ArchivableFilesFinder.php:61`
Happens for instance if files in the bin folder are pointing to the vendor directory and vendors are not installed
=> SplFileInfo: getRealPath can return false in ArchivableFilesFinder

src/Composer/Package/Loader/ArrayLoader.php, tests/Composer/Test/Package/Loader/ArrayLoaderTest.php
Fixes `Console Exception: strtolower(): Argument #1 ($string) must be of type string, int given in ArrayLoader.php:440`
For example, happens for package "silverstripe/crontask" from packagist.org which has an `extra` key with value `{"branch-alias":{"1":"1.3.x-dev"}}` in version `1.x-dev`
=> ArrayLoader: fix integer index of branch alias

src/Composer/Repository/Vcs/GitBitbucketDriver.php
Bitbucket now seems to return a 404 status code with the below body if you access a repository you don't have access to
```
{"type": "error", "error": {"message": "The requested repository either does not exist or you do not have access. If you believe this repository exists and you have access, make sure you're authenticated."}}
```
=> Bitbucket: handle missing authentication response from API returning 404 status code

src/Composer/Package/Loader/ArrayLoader.php, tests/Composer/Test/Package/Loader/ArrayLoaderTest.php
Resolves: `Uncaught Console Exception: strtolower(): Argument #1 ($string) must be of type string, int given in ArrayLoader.php:373`
Traces:
```
src/Composer/Package/Loader/ArrayLoader.php:373",
src/Composer/Package/Loader/ArrayLoader.php:68",
src/Composer/Repository/VcsRepository.php:306",
src/Composer/Repository/ArrayRepository.php:311",
```
=> ArrayLoader: handle links where target is invalid numeric package name

src/Composer/Downloader/ArchiveDownloader.php, src/Composer/Downloader/ZipDownloader.php, tests/Composer/Test/Downloader/ZipDownloaderTest.php
=> Fix deletion of corrupt 0-bytes zip archives from the cache

tests/Composer/Test/Mock/ProcessExecutorMock.php
=> fix phpdoc type in ProcessExecutorMock 

src/Composer/Console/Application.php
Symfony Console 2.8 used to print 'version ' in between name and version, and Composer 2.3 still does for -dev snapshots, so we're going back to the old formatting for consistency (and anyone out there who parses the version output of Composer)
Fixes #10683
=> restore --version output to pre-2.3

src/Composer/Repository/Vcs/GitDriver.php, tests/Composer/Test/Repository/Vcs/GitDriverTest.php
The initial clone determined what the default branch of the cache git repository was. Changing it on the remote didn't have any impact on the local data. However, cloning it on a different machine would then store a different default branch on that machine. This could lead to different results for the same command on different machines.
Unfortunately, I couldn't find a way to update the default branch on the local cache because checkout and symbolic-ref are both unavailable.
=> GitDriver: try to fetch default branch from remote

src/Composer/EventDispatcher/EventDispatcher.php
Fixes #10699.
`getenv` is case-insensitive as far as I understand it, which makes it not work correctly.
Not entirely sure why it works on 2.2, because the same code should be there.
It was changed here: https://github.com/composer/composer/commit/bd4d624cc7468623b29e56fa800b1750886b04c7#diff-4ec8bee1b3bdbc03e2097675b4586f3bb92ff70afff4e6ee5e4cc25847816e97L569
=> Fix run-script not setting Path correctly on Windows

phpstan/baseline.neon, src/Composer/Command/RunScriptCommand.php, tests/Composer/Test/Command/RunScriptCommandTest.php
Fixes #10705
Fixes #10707
After #10476 the ability to list scripts from the `run-script` command without passing a script name (i.e. `composer run-script -l`) was lost because the `script` argument was made required.  This restores the ability to list the scripts without needing to pass something to fill the `script` argument while also failing if not listing scripts and a script name wasn't provided.
=> Restore the ability to list the scripts in the 'run-script' command without providing a script

src/Composer/Repository/Vcs/GitDriver.php, src/Composer/Util/Git.php, tests/Composer/Test/Repository/Vcs/GitDriverTest.php
Building on top of https://github.com/composer/composer/pull/10687
Just running `git remote show origin` works fine if authentication is set up via public/private key. Fetching the data from a remote that requires username/password authentication requires updating the remote URL first.
This also exposed the command output of `Git:: runCommand` which previously was just ignore because not necessary anywhere.
=> GitDriver: try to fetch default branch form remote using auth

src/Composer/Config.php, src/Composer/Util/Http/CurlDownloader.php, tests/Composer/Test/ConfigTest.php
Similar to the warning about accessing a host via insecure protocol, this adds a warning about accessing a host with verify_peer or verify_peer_name disabled.
```
composer update
Warning: Accessing api.github.com with verify_peer disabled.
```
=> Add warning if host is accessed via verify_peer or verify_peer_name disabled

doc/06-config.md, phpstan/baseline.neon, src/Composer/Factory.php, src/Composer/Util/Platform.php
=> Fixed lock file being used when lock:false is in config

doc/06-config.md, phpstan/config.neon, src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Config.php
=> Clarify that autoloader-suffix should be a non-empty-string

phpstan/baseline.neon, src/Composer/Command/ValidateCommand.php
if no lock-file is configured, turn lock file validation errors into warnings (implicit --no-check-lock) unless those are explicitly promoted via the new `--check-lock` option.
- `{"config": {"lock": false}}` is an implicit `--no-check-lock` for   composer validate.
- `--check-lock` overrides an (implicit or explicit) `--no-check-lock`, always.
rationale is that if no composer.lock file is configured in composer.json, the validate command should not _fatal_ over it but instead demote to _warning_ as the suggestion given in the warning won't work unless composer.lock is configured again (and there is no error as the lock-file is ignored by composer).
the difference this makes is the one between an exit status of zero or non-zero, between success and failure.
that is, if (and as) composer …
=> Patch "validate --no-check-lock"

doc/articles/versions.md
Make it clearer that `^0.0.3` does not allow installing `0.0.4`
=> Docs: clarify carret contraint with ^0.0.x constraint

src/Composer/Repository/Vcs/GitBitbucketDriver.php, tests/Composer/Test/Repository/Vcs/GitBitbucketDriverTest.php
The `mainbranch` information is already available when fetching the repo data. The HTTP call in `getMainBranchData` was calling the same endpoint as `getRepoData` but only fetch the `mainbranch` data.
Windows test failing with a random timeout
=> BitbucketDriver: remove unnecessary HTTP call to fetch the root identifier

src/Composer/Command/ConfigCommand.php
```
$ composer config --global --editor
In ConfigCommand.php line 217:
[TypeError]                                                                  
escapeshellcmd(): Argument #1 ($command) must be of type string, bool given  
...
Exception trace:
at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/ConfigCommand.php:217
escapeshellcmd() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/ConfigCommand.php:217
Composer\Command\ConfigCommand->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php:298
Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:1015 …
```
=> Fix TypeError in ConfigCommand

src/Composer/Command/ConfigCommand.php
Fix #10738 
Allows unsetting any config key and not only the ones from the recognised schema.
Because key removal is done without matching the key in the recognized composer.json schema, leaving the key removal before other checks would have stopped the execution there without reaching the specific config add (eg. `composer config repo [--unset]` which was right after the removal)
=> #10738 - Allow config unset for unrecognized keys

phpstan/config.neon, phpstan/rules.neon, res/composer-schema.json, src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Command/DiagnoseCommand.php, src/Composer/Command/RemoveCommand.php, src/Composer/Config.php, src/Composer/Downloader/FileDownloader.php, src/Composer/Factory.php, src/Composer/IO/BaseIO.php, src/Composer/PHPStan/ConfigReturnTypeExtension.php, src/Composer/Package/Locker.php, src/Composer/Repository/Vcs/FossilDriver.php, src/Composer/Repository/Vcs/GitDriver.php, src/Composer/Repository/Vcs/GitLabDriver.php, src/Composer/Repository/Vcs/HgDriver.php, src/Composer/Repository/Vcs/PerforceDriver.php, src/Composer/Util/Git.php, src/Composer/Util/GitLab.php, src/Composer/Util/Url.php, tests/Composer/Test/Autoload/AutoloadGeneratorTest.php, tests/Composer/Test/Repository/PathRepositoryTest.php
as discussed in https://github.com/composer/composer/commit/ca3b8744144ec223aa87f90aec7aa7c7be0b73bc#commitcomment-68913659
=> added phpstan ConfigReturnTypeExtension

src/Composer/Util/AuthHelper.php, src/Composer/Util/GitLab.php, tests/Composer/Test/Util/AuthHelperTest.php
Resolves https://github.com/composer/composer/issues/10353
To reproduce: have a Composer project using GitLab with a composer.lock file.
Have invalid authentication configured like
```
composer config http-basic.gitlab.example.com random string
```
Then run
```
composer install
```
Current output
```
composer install -vvv                                                                                                                                      ◼
Running 2.3.5 (2022-04-13 16:43:00) with PHP 8.0.17 on Darwin / 21.4.0
[...]
Dependency resolution completed in 0.000 seconds
Package operations: 1 install, 0 updates, 0 removals
Installs: one-more/test:dev-main 8cb508d
- Downloading one-more/test (dev-main 8cb508d)
Using HTTP basic authentication with username "random"
Downloading …
```
=> GitLab: handle infinite loop during composer install

src/Composer/Util/Http/CurlDownloader.php
GitHub does not always set the `Content-Type` header on `500 Internal Server Error` responses.
```
2022-05-11T11:42:37+00:00 app.CRITICAL Uncaught Console Exception: strtolower(): Argument #1 ($string) must be of type string, null given
{
"exception": {
"class": "TypeError",
"message": "strtolower(): Argument #1 ($string) must be of type string, null given",
"code": 0,
"file": "\/vendor\/composer\/composer\/src\/Composer\/Util\/Http\/CurlDownloader.php:609",
"trace": [
"\/vendor\/composer\/composer\/src\/Composer\/Util\/Http\/CurlDownloader.php:609",
"\/vendor\/composer\/composer\/src\/Composer\/Util\/Http\/CurlDownloader.php:434",
"\/vendor\/composer\/composer\/src\/Composer\/Util\/HttpDownloader.php:378",
"\/vendor\/composer\/composer\/src\/Composer\/Util\/HttpDownloader.php:347", …
```
=> CurlDownloader: Always cast Content-Type header value to string when passing to strtolower()

doc/03-cli.md
Probably by merging other PR the arrows were not at the bottom. 
I have checked the rest of the pages and none was having this behavior, so I understand is a mistake. Keep the good work!
=> Move navigation arrows to the bottom

src/Composer/Util/ProcessExecutor.php, tests/Composer/Test/Util/ProcessExecutorTest.php
Cmd apparently splits paths on commas, which can have bad consequences when calling destructive commands like `rmdir`.
Simply fixed by double-quoting the param (as with white-space).
See https://github.com/composer/composer/issues/10745#issuecomment-1118604588
=> Fix cmd splitting paths on commas

src/Composer/Command/ArchiveCommand.php, src/Composer/Command/BaseDependencyCommand.php, src/Composer/Command/HomeCommand.php, src/Composer/Command/InitCommand.php, src/Composer/Command/PackageDiscoveryTrait.php, src/Composer/Command/ShowCommand.php, src/Composer/Repository/RepositoryFactory.php, tests/Composer/Test/DependencyResolver/PoolBuilderTest.php
[..] And make sure async is always enabled on the process executor, fixes #10783
=> Make sure repos are always initialized with a repo manager if possible

src/Composer/Command/UpdateCommand.php, src/Composer/DependencyResolver/PoolBuilder.php, src/Composer/DependencyResolver/Problem.php, src/Composer/Installer.php, src/Composer/Repository/RepositorySet.php, tests/Composer/Test/Command/UpdateCommandTest.php, tests/Composer/Test/TestCase.php
=> Allow using temporary update constraints on all packages (incl non-root)

doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md
Using caret over tilde is better since it behaves the same as in npm: https://jubianchi.github.io/semver-check/#/constraint/~3.0
But when this change was introduced in https://github.com/composer/composer/pull/5396, it was not complete.
=> docs: Fix inconsist semver operator suggestion

res/composer-schema.json, tests/Composer/Test/Json/ComposerSchemaTest.php
This PR is an attempt to fix #10805 by removing all possessive quantifiers from the regex pattern.
https://jsfiddle.net/wj345vsa/
I'm sending this to 2.2 since it's the oldest branch the issue applies to.
=> Fix JSON schema regex pattern

phpstan/baseline.neon, src/Composer/Json/JsonFile.php
Hi,
I got the following error with Composer 2.3.5 but it affects also the 2.2 branch.
It happened after running `composer install`, but unfortunately I didn't manage to reproduce the problem afterwards.
```
Fatal error: Uncaught TypeError: Composer\Json\JsonFile::parseJson(): Argument #1 ($json) must be of type ?string, bool given, called in phar:///usr/local/bin/composer/src/Composer/Json/JsonFile.php on line 117 and defined in phar:///usr/local/bin/composer/src/Composer/Json/JsonFile.php:311
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Json/JsonFile.php(117): Composer\Json\JsonFile::parseJson(false, '/var/www/vendor...')
#1 phar:///usr/local/bin/composer/src/Composer/Repository/FilesystemRepository.php(82): Composer\Json\JsonFile->read()
#2 …
```
=> Fix TypeError when a JSON file can not be read

doc/articles/authentication-for-private-packages.md
Bearer Auth has been added here:
- https://github.com/composer/composer/commit/548505f103d4e55a4044bedcd17bd93eba2fe68b
- https://github.com/composer/composer/commit/f964b8301837a49ee1a4cf77dbfb38d0c2c2a340
- #8671
- #8642
but it was not documented in this file.
Committing a draft here, will polish it up later.
=> WIP: Added documentation about HTTP Bearer Auth

doc/03-cli.md, src/Composer/Command/OutdatedCommand.php, src/Composer/Command/ShowCommand.php
=> Add --major-only flag to outdated/show commands to restrict the list to packages with major updates available

doc/03-cli.md, src/Composer/Cache.php, src/Composer/Command/ClearCacheCommand.php
=> Add --gc flag to clear-cache command and ability to GC vcs/repo caches

src/Composer/Installer/BinaryInstaller.php
I noticed an issue with a composer vendor binary. If the current working directory path contains a space, upon running a composer vendor binary the following error is thrown:
`./vendor/bin/sail: 26: export: PART_OF_PATH/vendor/bin: bad variable name`
PART_OF_PATH would be `website` if working directory path was `/home/user/my website` for example
Identified issue and tested fix on Ubuntu 20.04. The package/binary I was using: https://github.com/laravel/sail
This PR just quotes the export value in the shell script to allow for paths with spaces.
=> Fix exported path with space in binary installer proxy

src/Composer/Command/BumpCommand.php
Change warning text 'Alternatively you can use --dev-only to only bump dependencies within "require-dev"' that said `--dev` instead of `--dev-only`.
=> `composer bump` - Fix typo in the warning message

src/Composer/Command/InitCommand.php
Master functions shall be used instead of aliases.
=> No alias functions

src/Composer/Command/RequireCommand.php, src/Composer/Repository/Vcs/VcsDriver.php
There should not be an empty return statement at the end of a function.
=> No useless return

src/Composer/Repository/Vcs/HgDriver.php
There must be no sprintf calls with only the first argument.
=> No useless sprintf

src/Composer/DependencyResolver/SolverProblemsException.php
I'm using a custom php docker image and all my .ini files are located in the conf.d directory.
This means that `php_ini_loaded_file()` returns `false`, the result is then casted to an empty string.
ini files from the conf.d directory are retrieved from `php_ini_scanned_files()`.
The problem is that `SolverProblemsException::createExtensionHint()` uses these results to display the list of all php ini files, leaving a blank line in place of the missing loaded file :
```
To enable extensions, verify that they are enabled in your .ini files:
-
- /usr/local/etc/php/conf.d/docker-php-ext-intl.ini
- /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini
- /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
- /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
- …
```
=> Removed blank line in missing extensions hint when having no php.ini loaded file

tests/Composer/Test/Autoload/AutoloadGeneratorTest.php, tests/Composer/Test/IO/NullIOTest.php, tests/Composer/Test/Repository/CompositeRepositoryTest.php, tests/Composer/Test/Util/FilesystemTest.php
PHPUnit assertions like assertInternalType, assertFileExists, should be used over assertTrue.
=> Php unit dedicate assert

doc/03-cli.md
- No reason to state that the audit command "currently" only checks packagist.org. It should stay that way, if we need to add more sources, we can add them to packagist.org.
=> Audit command docs: Remove currently restriction

src/Composer/Package/Loader/ValidatingArrayLoader.php, tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php
Fixes https://github.com/composer/packagist/issues/1318
=> Fix: ValidatingArrayLoader [TypeError]: strcasecmp(): Argument #1() must be of type string, int given

src/Composer/Command/BaseDependencyCommand.php, src/Composer/Command/DependsCommand.php, src/Composer/Command/ProhibitsCommand.php
Fixes #10790 by adding an error message that tells users how to recover / get the information they wanted.
Fixes #10717 by adding the ability to use `--locked` on `composer depends` and `composer prohibits` commands (to read the dependency information from `composer.lock`).
=> Allow use of --locked with depends and prohibits

src/Composer/Config.php, tests/Composer/Test/ConfigTest.php
This attempts to fix https://github.com/composer/composer/issues/10907
- if global config has `allow-plugins: true` and local has `allow-plugins: [some-array]`, only local would be allowed
- if local has `allow-plugins: true` and global has an array, local would win and allow everything
I guess that's how it's supposed to work?
=> Correctly merge boolean flag of allow-plugin config

src/Composer/Command/InitCommand.php
Fix string type requirement in case of NULL value:
[TypeError]                                                                                                                                                                  
Composer\Command\InitCommand::parseAuthorString(): Argument #1 ($author) must be of type string, null given, called in phar:///composer.phar/src/Composer/Command/InitCommand.php on line 345
=> Fix TypeError

src/Composer/Util/GitHub.php
Deprecation Notice: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/bin/composer/src/Composer/Util/GitHub.php:103
=> Fix deprecation notice

doc/03-cli.md, src/Composer/Command/RequireCommand.php
I think `require` command is one of most frequency used by developers. Why do not create shortcut alias for it? 
Most commands like `install` or `update` already have shortcut aliases.
Much easy to write `composer r package:version` instead of `composer require package:version`. It will also pretend typo in `require` word within fast-writing cases. 
The PR kindly adds `r` alias to `require` command.
=> Add alias to require command

doc/03-cli.md
Stumbled upon this with the output
```
❯ composer show -Dlop
The --direct (-D) option is not usable in combination with --all, --platform (-p) or --available (-a)
```
=> Remove -p from --patch-only, --platform took it

doc/04-schema.md, src/Composer/Command/RequireCommand.php, src/Composer/Util/PackageSorter.php
First suggested in https://github.com/composer/composer/discussions/10939
This implements the idea discussed here tho https://github.com/composer/composer/discussions/10939#discussioncomment-3156267
Currently taking `dev`, `testing`, `static analysis` tags as indicator that a package is meant to be in require-dev, then it does this:
IMO `testing` and `static analysis` are fairly safe bets. `dev` is almost unused atm, and I took a look at all the top download packages there and only one is arguably not meant to be in require-dev, but they can fix that by removing the tag from the default branch.
=> Add prompt suggesting using --dev when require command is used with dev packages

doc/03-cli.md, src/Composer/Advisory/Auditor.php, src/Composer/Command/AuditCommand.php, src/Composer/Command/CreateProjectCommand.php, src/Composer/Command/InstallCommand.php, src/Composer/Command/RemoveCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Command/UpdateCommand.php
Follow up on #10798 and #10898, as suggested in https://github.com/composer/composer/pull/10798#issuecomment-1152782931
This adds a `format=json` option to the command, to allow for. Currently in the same format it already is (because why not?). In the 'advisories' object, so a summary or the list of packages can still be added later if required. So grouped by package:
No actual real-life use case for this, except for opening the possibility to process it during a pipeline/action (and perhaps suggest updates or format an advisory yourself)
=> Add json format to Audit command

tests/Composer/Test/Command/SearchCommandTest.php
This PR adds functional tests for `SearchCommand` - searching in the local repository only. See #10796
Please take note of additional changes in `RequireCommandTest` , adding `'packagist.org' => false` to avoid HTTP hit in the tests and causing tests to fail due to unexpected `Info from https://repo.packagist.org: #StandWithUkraine` message in the output. 
@Seldaek Is there a better way to disable `packagist.org` in tests to make sure no additional requests are performed? I noticed `$this->getApplicationTester()` uses `Factory` instead of `FactoryMock` but not sure how to improve that.
Coverage changes from 16.98% to 94.34% for this class.
=> Add SearchCommand tests

src/Composer/Repository/Vcs/GitHubDriver.php, tests/Composer/Test/Repository/Vcs/GitHubDriverTest.php
Example composer.json
```
{
{"type": "vcs", "url":  "https://github.com/php-fig/log/releases"}
],
"require": {
"psr/log": "^3.0"
}
}
```
composer update output with current stable:
```
composer update -vvv
Running 2.3.10 (2022-07-13 15:48:23) with PHP 8.1.8 on Darwin / 21.5.0
Reading ./composer.json (/tmp/update-error/composer.json)
Loading config file /Users/glaubinix/.composer/config.json
Loading config file /Users/glaubinix/.composer/auth.json
Loading config file ./composer.json (/tmp/update-error/composer.json)
Checked CA file /usr/local/etc/ca-certificates/cert.pem: valid
Executing command (/tmp/update-error): 'git' 'branch' '-a' '--no-color' '--no-abbrev' '-v'
Reading /Users/glaubinix/.composer/composer.json
Loading config file …
```
=> GitHubDriver: stricter URL validation to avoid issues with undefined index owner

doc/03-cli.md
The COMPOSER_NO_DEV option is relatively hard to find, let's make it easier.
=> Crosslink COMPOSER_NO_DEV

doc/03-cli.md
Running the example command `composer prohibits php:8` returns an error, "Not enough arguments (missing: "version")."
=> Correct prohibits/why-not example command

phpstan/baseline.neon, res/composer-schema.json, src/Composer/IO/BaseIO.php, src/Composer/Repository/Vcs/GitLabDriver.php, src/Composer/Util/GitLab.php, tests/Composer/Test/Util/GitLabTest.php
=> Added token refresh for GitLab 

doc/03-cli.md, src/Composer/Command/CheckPlatformReqsCommand.php
Some very basic json output support for CheckPlatformReqs.
=> CheckPlatformReqs: basic json format support

doc/03-cli.md, src/Composer/Command/BaseCommand.php, src/Composer/Command/CreateProjectCommand.php, src/Composer/Command/RemoveCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Command/UpdateCommand.php
=> Environment variable for `--no-audit`.

src/Composer/Downloader/GitDownloader.php
performance: Do not create a local cache repo for local repos
=> performance: Do not create a local cache repo for local repos

src/Composer/Command/SelfUpdateCommand.php
The 'Y' is capital, so Yes should be the default choice and is what most people would want, but No was the default.
=> Match default choice to actual default

src/Composer/Downloader/GitDownloader.php, src/Composer/Util/Git.php
=> Fix cache invalidation issue when a git tag gets created on an old ref after the cache is populated

src/Composer/Package/Loader/ArrayLoader.php, tests/Composer/Test/Package/Loader/ArrayLoaderTest.php
Fix type error when a non-array package link is provided in config array.
Encountered when the following `composer.json` was submitted:
```json
{
...,
"require": {
"psr/log": {
"random-string": ""
}
}
}
```
=> Do not apply non-string package link constraints in ArrayLoader

src/Composer/Package/Loader/ArrayLoader.php, tests/Composer/Test/Package/Loader/ArrayLoaderTest.php
Fix type error when a non-array package link is provided in config array.
Encountered when the following `composer.json` was submitted:
```json
{
...,
"replace": "vendor/package"
}
```
=> Do not apply non-array package links in ArrayLoader

tests/bootstrap.php
This causes issues for PHPStan in the latest version. Because PHPStan itself loads its own InstalledVersions from inside the PHAR, this bootstrap line makes it crash.
If we find out that loading this class is indeed necessary for Composer's test suite to run, I'll create a separate PHPStan bootstrap next to this one.
=> Tests bootstrap - remove require InstalledVersions

doc/05-repositories.md
The headings don't make sense before this change:
=> Fix the heading levels for the doc about composer repositories

src/Composer/Util/GitLab.php
`https://gitlab.com/-/profile/personal_access_token` is not correct, the current URL for personal access token settings is `https://gitlab.com/-/profile/personal_access_tokens`. This is the only occurrence of the bad URL, we use the proper URL elsewhere.
=> Update gitlab fetch failure message with new path

src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Autoload/ClassLoader.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_files_by_dependency.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_functions.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_functions_with_include_paths.php, tests/Composer/Test/Autoload/Fixtures/autoload_real_target_dir.php
It occurred to me that with static lambdas we can achieve the same effect as with those public functions, except we don't leave them open for use by third parties.
As a side-note @mir-hossein pointed out to me that it's sometimes used in attacks to bypass restrictions, I am not entirely sure how this would work but I guess some filtering may allow calls to `includeFile()` but not to include/require? In any case it seems like a good thing to close this potential vector.
I would target 2.5.0 with this because it may cause disruption to people using this function (even tho they really should not..) for "legit" cases, so I'd rather not have this in a patch release.
=> Lock down include wrappers to avoid abuse from third parties

src/Composer/DependencyResolver/RuleSetGenerator.php, src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php, tests/Composer/Test/Fixtures/installer/update-ignore-platform-package-requirement-list-upper-bounds.test
=> Fix handling of upper-bound platform req ignores to not act on conflicts

doc/08-community.md
At the top of https://www.php-fig.org/psr/psr-2/, it says:
> Deprecated - As of 2019-08-10 PSR-2 has been marked as deprecated. PSR-12 is now recommended as an alternative.
Looking at the PSR-12 docs, the summary of changes implies that they mostly took PSR-2 and extended it to clarify new language features.
=> Replace deprecated `PSR-2` with `PSR-12`

doc/03-cli.md, src/Composer/Command/BumpCommand.php, tests/Composer/Test/Command/BumpCommandTest.php
With this flag it would be possible to run `composer bump --dry-run` as a part of CI - to keep synced `composer.json` and `composer.lock`.
When run on this repo:
```console
$ php ./bin/compile 
$ php composer.phar bump --dry-run
Warning: Bumping dependency constraints is not recommended for libraries as it will narrow down your dependencies and may cause problems for your users.
./composer.json would be updated with:
- require.composer/ca-bundle: ^1.3.3
- require.composer/semver: ^3.3.2
- require.justinrainbow/json-schema: ^5.2.12
- require.psr/log: ^1.1.4 || ^2.0 || ^3.0
- require.seld/jsonlint: ^1.9
- require.seld/phar-utils: ^1.2.1
- require.symfony/console: ^5.4.12 || ^6.0.11
- require.symfony/filesystem: ^5.4.12 || ^6.0
- require.symfony/finder: ^5.4.11 || ^6.0
- …
```
=> Add "--dry-run" to bump command

doc/03-cli.md, tests/Composer/Test/DocumentationTest.php
It would be great to have the CLI docs consistent, as currently some aliases of commands are skipped, some are in parenthesis, and some are with a slash.
Maybe the better format would be to use parenthesis e.g. `## update (u, upgrade)`, but that's up to @Seldaek to decide.
Both TODOs will be done in separate PRs - if this one goes through.
=> Unify command names in the docs

src/Composer/Command/ShowCommand.php, src/Composer/Package/Version/VersionSelector.php, tests/Composer/Test/Command/ShowCommandTest.php
=> Add warning when outdated command rejects an existing version due to platform requirements

doc/03-cli.md, tests/Composer/Test/Command/AuditCommandTest.php
Related to #10796
I wanted to add tests to commands, and my thought was to add test to interesting behaviours that were worth validating. As far as I can tell, most code in the commands is related to output formatting or calling other components which implements the behaviours.
I found the audit command, which has a successful response code when no packages are required, and thought that it was a behaviour worth documenting/testing
Let me know what you think!
=> Add test and documentation regarding audit command when no packages are required

tests/Composer/Test/Command/ExecCommandTest.php
This PR belongs to #10796
This increases the line coverage of ExecCommand to 80%.
At the moment this test only affects the listing of binaries, but not the execution.
=> #10796 Add test for ExecCommand

src/Composer/Console/Application.php
This affects the banner at the head of the help screen and the version info. Symfony's base object offers the same signature but composer does not allow to override it in constructor.
Yet there are public setter methods to change both after initializing the object. This is the workaround satis cli currently uses.
=> Allow other CLIs (like satis in standalone mode) to re-brand composer.

doc/08-community.md
This PR updates the link text that links to the "Runtime" page on the "Community" page.
=> Update link text to runtime page in documentation

src/Composer/Advisory/PartialSecurityAdvisory.php, src/Composer/Advisory/SecurityAdvisory.php
Fixes #11104
This fixes the affectedVersions missing from the output, but also changes the reportedAt output from
```
"reportedAt": {
"date": "2022-02-04 06:52:21.000000",
"timezone_type": 3,
"timezone": "UTC"
},
```
to `"reportedAt": "2022-02-04T06:52:21+00:00"`
This is strictly speaking a BC break but the old format was kinda garbage so I think we rather fix this now while it's still early. It's an easy fix anyway and should trigger hard failures for anyone accessing the `reportedAt>date` field so it shouldn't get missed.
=> Fix json format of audit command missing affectedVersions, fix reportedAt format (BC BREAK!)

.github/workflows/phpstan.yml
GitHub has deprecated the use of `set-output` (and `set-state`) in favour of new environment files.
This commit updates workflows to use the new methodology.
Refs:
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
=> GH Actions: fix use of deprecated `set-output`

doc/articles/scripts.md, src/Composer/Command/ScriptAliasCommand.php, src/Composer/EventDispatcher/EventDispatcher.php, tests/Composer/Test/Command/RunScriptCommandTest.php
=> Add support for adding Command classes as scripts, 

src/Composer/Command/PackageDiscoveryTrait.php, src/Composer/Command/RequireCommand.php, tests/Composer/Test/Command/RequireCommandTest.php
If no version is provided we usually select the latest working version but in some cases this leads to problems if that conflicts with other stuff you have installed.
This PR makes it instead use a `*` constraint temporarily, effectively delegating the job to the solver (except if called with --no-update then we still use the best-effort version selector stuff). Once we have a solution we then replace version constraints again with whatever the locked version is.
This should improve the `require` experience especially for people that do not have very up to date dependencies.
=> Make the require command guess versions more accurately

src/Composer/Command/RemoveCommand.php
Currently, the command 'composer remove --unused' doesn't work in non-interactive mode. This prevents it from being run in github actions for example;
```
COMPOSER_NO_INTERACTION=true composer remove --unused
```
```
Error: Not enough arguments (missing: "packages").
Not enough arguments (missing: "packages").  
remove [--dev] [--dry-run] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-all-dependencies] [--no-update-with-dependencies] [--unused] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] <packages>... …
```
=> Allow the 'composer remove --unused' command to run in non-interactive mode

doc/00-intro.md
Document optimal way of copying Composer binary using `COPY --from` in Dockerfiles by using binary-only image.
See: https://blog.codito.dev/2022/11/composer-binary-only-docker-images/
=> Use binary-only images for installing Composer

src/Composer/Repository/ComposerRepository.php, tests/Composer/Test/Mock/HttpDownloaderMock.php, tests/Composer/Test/Repository/ComposerRepositoryTest.php
`composer audit` ignore any configured repository options of repositories of type `composer`
Sample composer.json
```
{
"repositories": {
"packagist.org": false,
"other": {
"type": "composer",
"url":  "https://packagist.org",
"options": {
"ssl": {
"verify_peer": false,
"verify_peer_name": false
}
}
}
},
"require": {
"symfony/debug": "^3.0"
}
}
```
Expected output:
```
composer audit
Warning: Accessing packagist.org with verify_peer and verify_peer_name disabled.
No security vulnerability advisories found
```
Actual output:
```
composer audit
No security vulnerability advisories found
```
=> Audit: ignores configured repository options

src/Composer/IO/IOInterface.php
`IOInterface::select()` either returns any of `int`, `string`, `bool` or an array of `string` values. However, since the returned array is always a list, we can safely change the return type annotation to `list<string>`, making it more explicit in terms of static code analysis.
=> Make possible return type in `IOInterface::select()` more explicit

src/Composer/Util/GitHub.php
Currently, when hitting the github rate limit the following errors is shown, where the remaining requests and time are not displayed:
```diff
GitHub API limit (0 calls/hr) is exhausted, could not fetch https://api.github.com/repos/reponame. 
Review your configured GitHub OAuth token or enter a new one to go over the API rate limit. 
You can also wait until ? for the rate limit to reset.
```
This caused some confusion here, we were wondering if our token was expired and that's why the 0 calls/hr was displayed.
A while ago (februari 2nd 2022), the headers were corrected in the documentation though (https://github.com/github/docs/pull/14912). This PR makes it so the lower case header format is used, and the information is filled:
```diff
-GitHub API limit (0 calls/hr) is exhausted, could not …
```
=> Use lowercase Github ratelimit headers to determine the ratelimit limit and reset time

src/Composer/Config.php, src/Composer/Factory.php, src/Composer/Util/Bitbucket.php, src/Composer/Util/GitHub.php, src/Composer/Util/GitLab.php
When in interactive mode with missing credentials, the credentials are always stored in the local auth.json file if it exists, even though credentials in the auth.json might be shared through git and the user wants to store their credentials in their global auth.json:
```diff
Your GitHub credentials are required to fetch private repository metadata (https://github.com/vendor/package)
When working with _public_ GitHub repositories only, head to https://github.com/settings/tokens/new?scopes=&description=MachineName+TIMESTAMP to retrieve a token.
This token will have read-only permission for public information only.
When you need to access _private_ GitHub repositories as well, go to https://github.com/settings/tokens/new?scopes=repo&description=MachineName+TIMESTAMP
Note that such tokens …
```
=> Allow storing credentials globally when 'local' auth.json file exists

src/Composer/Package/Version/VersionBumper.php, tests/Composer/Test/Package/Version/VersionBumperTest.php
=> Fix preserving of major.minor.patch version when running `composer bump` and installed patch version is `0`, and add bumping of >=x to >=latest

src/Composer/Cache.php, src/Composer/Repository/ComposerRepository.php
=> Allow underscores in cache keys to avoid conflicts with package names containing underscore vs dashes

CHANGELOG.md, src/Composer/Command/DependsCommand.php, src/Composer/Command/DumpAutoloadCommand.php, src/Composer/Command/ProhibitsCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Command/RunScriptCommand.php, src/Composer/Command/ScriptAliasCommand.php, src/Composer/Command/SelfUpdateCommand.php, src/Composer/Command/ShowCommand.php, src/Composer/Command/UpdateCommand.php, src/Composer/Package/Locker.php, tests/Composer/Test/Command/ValidateCommandTest.php, tests/Composer/Test/Fixtures/installer/install-from-incomplete-lock.test, tests/Composer/Test/Fixtures/installer/root-requirements-do-not-affect-locked-versions.test
Following the [Composer 2.5 release](https://github.com/composer/composer/releases/tag/2.5.0), I presented the interactive prompt run script https://github.com/composer/composer/pull/11157 to colleagues. In addition, I found that the deep links to the documentation website do not work properly.
Initially searched within `src/Composer/Command`, after that a refinement of the entire project.
**Before/after (diff)**
- ~https://getcomposer.org/doc/03-cli.md#run-script~
- https://getcomposer.org/doc/03-cli.md#run-script-run
```shell
composer run-script --help
```
```diff
Description:
Runs the scripts defined in composer.json
Usage:
run-script [options] [--] [<script> [<args>...]]
run
Arguments:
script                         Script name to run.
args
Options:
--timeout=TIMEOUT          Sets …
```
=> Docs: fix documention deep links

doc/03-cli.md, doc/articles/resolving-merge-conflicts.md
Hi @Seldaek, It's been a while since my previous PR regarding documenting correctly resolving merge conflicts in #9386 and subsequently detecting missing packages after incorrect merges in #9899, but I now work at a different company and I am once again trying to recover from an incorrect merge without walking through months of git logs or removing the lock file. ;)
When walking through code from #9386 and trying to figure out if there is an easy way to check unused packages in the validate command, I noticed there was already code present for an undocumented feature added in #8786 where the remove command can be run with the '--unused' flag to remove unused packages.
Would you be open to use the code in the 'interact' method in the 'removeCommand' to also display errors when running …
=> Document recovering from invalid merges on composer.lock and composer.json

.github/workflows/continuous-integration.yml, src/Composer/Autoload/ClassLoader.php, tests/Composer/Test/Autoload/ClassLoaderTest.php
Refs https://github.com/sebastianbergmann/phpunit/issues/5117
=> Fix ClassLoader to be serializable

phpunit.xml.dist, src/Composer/Command/RemoveCommand.php, tests/Composer/Test/Command/AuditCommandTest.php, tests/Composer/Test/Command/RemoveCommandTest.php, tests/Composer/Test/Command/SuggestsCommandTest.php, tests/complete.phpunit.xml
As per #10796 I'm contributing tests mainly for the SuggestsCommand (and a small test for the AuditCommand). This bumps coverage for the SuggestsCommand up to 100%.
Please do request changes, give feedback, etc. to help make these tests better.
Coverage improvements:
- Coverage for `AuditCommand` goes from `62.96%` to `70.37%`.
- Coverage for `RemoveCommand` goes from `14.91%` to `94.41%`.
- Coverage for `SuggestCommand` goes from `27.03%` to `100.00%`.
Other improvements:
- Excluded the PHPStan extensions from PHPUnit's coverage analysis because they aren't used within the Composer runtime codebase.
=> Tests for Audit/Remove/Suggests Commands

src/Composer/Package/Locker.php, tests/Composer/Test/Fixtures/installer/root-requirements-do-not-affect-locked-versions.test
Fixes #11274
I don't think it is worth it to check self.version here as the version is very likely to change and break things.
=> Fix self.version requirements failing the lock file integrity check if on a different version

doc/articles/plugins.md, src/Composer/Plugin/PluginManager.php
https://github.com/composer/composer/pull/10920 added a protection against inadvertently *not* running a plugin. But not all plugins are mandatory to run, and this check creates needless friction to plugin adoption.
I propose to fix this by allowing composer to auto-disable a plugin in non-interactive mode with a new extra.plugin-optional flag.
=> Add extra.plugin-optional to auto-disable plugins in non-interactive mode

src/Composer/PHPStan/ConfigReturnTypeExtension.php, tests/Composer/Test/ConfigTest.php
see https://phpstan.org/blog/why-is-instanceof-type-wrong-and-getting-deprecated
after this fix the PHPStan extension supports cases like
```php
if (..) {
$property = 'license';
} else {
$property = 'description';
}
$value = Config::get($property);
```
which it did not before
=> PHPStan: Fixed handling of union types in ConfigReturnTypeExtension

src/Composer/Installer/PluginInstaller.php
This is the code I used to produce the expected* output for https://github.com/composer/composer/issues/11317 - skipping the optional plugin installation.
*expected from my point of view - not sure if it's correct
=> Added optional plugin check in PluginInstaller

doc/articles/authentication-for-private-packages.md
Small doc update: there are 4 configuration locations for auth.
=> Doc: clarify possible credential storage locations

doc/03-cli.md, src/Composer/Command/RemoveCommand.php
Inspired from #11163
As you know most `deleting|removing` commands have shortcut `rm`, for example, `rm a.txt`, `npm rm --help`.
So I think it will be great have the same keyboard shortcut here. 
p.s. `composer rem` is not easy to remember
=> Add rm alias to composer remove command

src/Composer/Installer.php
Fixes #11357 by adding a new `ERROR_AUDIT_FAILED = 5` exit code used when running `composer install --audit`.
=> Exit with non-zero code if post-install audit fails

src/Composer/Repository/Vcs/SvnDriver.php
`SvnDriver::getTags` and `SvnDriver::getBranches` both fail to compose valid reference to `composer.json` if repository root was moved after their creation. Pick highest available revision from the list to raise chances for success.
=> Pick higher revision number to guarantee successful file retrieval

doc/articles/versions.md
This was caused by
> Add note about issue with caret operator in PowerShell (#11351)
Related: #11288, #11351
=> Fix markdown: Move headline out of quote

src/Composer/Repository/Vcs/GitBitbucketDriver.php, src/Composer/Repository/Vcs/GitHubDriver.php, src/Composer/Repository/Vcs/GitLabDriver.php, tests/Composer/Test/Repository/Vcs/GitBitbucketDriverTest.php, tests/Composer/Test/Repository/Vcs/GitHubDriverTest.php, tests/Composer/Test/Repository/Vcs/GitLabDriverTest.php
Fixes `getComposerInformation` call if `support` is not an array but instead a string for example:
```
{"name": "acme/package", "support": "https://github.com/org/repo"}
```
Error
```
"exception": {
"class": "TypeError",
"message": "Cannot access offset of type string on string",
"code": 0,
"file": "src\/Composer\/Repository\/Vcs\/GitHubDriver.php:179",
"trace": [
"src\/Composer\/Repository\/VcsRepository.php:248",
```
=> Composer support string

src/Composer/Repository/PlatformRepository.php, tests/Composer/Test/Repository/PlatformRepositoryTest.php
Self-explanatory :)
Both info sources have been around in the respective extensions for many, many years, see https://github.com/m6w6/ext-pq/commit/6840072b9e4fe5269d0f36a9cb8cd9cde04525af (2015) and https://github.com/arnaud-lb/php-rdkafka/commit/a38b32e43c68dd796595c4daa44c487fc8acd117 (2016).
=> PlatformRepository library support for libpq (from ext-pq) and librdkafka (from ext-rdkafka)

src/Composer/Package/Loader/ArrayLoader.php, tests/Composer/Test/Package/Loader/ArrayLoaderTest.php
Fixes `Uncaught Console Exception: Composer\Package\CompletePackage::setSupport(): Argument #1 ($support) must be of type array, string given, called in src/Composer/Package/Loader/ArrayLoader.php on line 286`
=> ArrayLoader: handle invalid support value

doc/03-cli.md
Updates documentation of COMPOSER_NO_DEV variable.
Further to: [10995](https://github.com/composer/composer/pull/10995)
Currently the --update-no-dev [option](https://github.com/composer/composer/blob/main/doc/03-cli.md#options-3) links to the documentation for COMPOSER_NO_DEV.
The documentation for COMPOSER_NO_DEV only references the --no-dev option for install and update.  The option above it (COMPOSER_NO_AUDIT) references require so it makes it seem as though perhaps this doesn't apply to require - although it would be strange if it did not.
Testing suggest that it does in fact work as indicated on the --update-no-dev option.
Before
After
Referenced require first as otherwise it seems less confusing with multiple levels of or.
=> Documentation clarification: COMPOSER_NO_DEV scope

src/Composer/DependencyResolver/PoolBuilder.php, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/load-replaced-package-if-replacer-dropped.test, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/multi-repo-replace-partial-update-all.test, tests/Composer/Test/DependencyResolver/PoolBuilderTest.php, tests/Composer/Test/Fixtures/installer/load-replaced-package-if-replacer-dropped.test
Another attempt to fix https://github.com/composer/composer/pull/10410 and https://github.com/composer/composer/pull/9619.
The goal here is to not load replaced packages into the pool if no other package actually requires them. We have to treat all `replace` definitions as "optional packages".
/cc @driskell @stof @naderman @Seldaek
=> Optimize PoolBuilder to not load replaced targets if not required

doc/articles/custom-installers.md, src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Command/ShowCommand.php, src/Composer/Command/StatusCommand.php, src/Composer/Command/ValidateCommand.php, src/Composer/Installer/InstallationManager.php, src/Composer/Installer/InstallerInterface.php, src/Composer/Installer/LibraryInstaller.php, src/Composer/Installer/MetapackageInstaller.php, src/Composer/Installer/ProjectInstaller.php, src/Composer/Package/Locker.php, src/Composer/Plugin/PluginManager.php
As the empty string then resolves to the root package's path when used with realpath()
Fixes #11389
The good news is this does not impact InstalledVersions::getInstallPath which was already correctly returning null
The bad news is this may impact plugins or other integrators relying on getInstallPath if they have strict types enabled and do not cover the null case. So I'm not sure if this should be shipped in a bugfix release..
=> Return null for install path for metapackages instead of an empty string as path

src/Composer/Util/AuthHelper.php, tests/Composer/Test/Util/AuthHelperTest.php
This PR fixes an issue with installing multiple packages from private bitbucket repositories.
**What happens now?**
In case multiple dependencies are needed from private bitbucket repositories, only one will succeed in downloading the dist file, all others will fail and fall back to a git clone.
```
- Downloading vendor/package1 (2.0.7)
- Downloading vendor/package2 (2.1.2)
- Downloading vendor/package3 (1.1.2)
- Downloading vendor/package4 (1.0.6)
Failed to download vendor/package2 from dist: Could not authenticate against bitbucket.org
Now trying to download from source
- Syncing vendor/package2 (2.1.2) into cache
Failed to download vendor/package1 from dist: Could not authenticate against bitbucket.org
Now trying to download from source
- Syncing vendor/package1 (2.0.7) into cache …
```
=> Fix authentication issues with multiple private bitbucket repos

tests/Composer/Test/Repository/FilterRepositoryTest.php
The behavior in `FilterRepository` is currently correct, but not explicitly tested.
Also add a test that ensures both filters can't be there simultaneously.
=> Tests for empty or absent repository filters

tests/Composer/Test/Command/CheckPlatformReqsCommandTest.php
Adds a single test for covering failed requirements. I have passed the `--format=json` flag to this test to also cover off a branch of `CheckPlatformReqsCommand::printTable`.
Bumps coverage for this command from ~70% to ~90%.
=> Test json format on failed platform reqs

src/Composer/Downloader/ArchiveDownloader.php, src/Composer/Downloader/FileDownloader.php
- Remove unused argument from method `FileDownloader::getFileName()`
- Reuse package dist path parsing of filename and extension
=> Refactor downloader package dist path parsing

phpstan/baseline.neon, src/Composer/Util/SyncHelper.php
=> Update `SyncHelper` - Remove 3 phpstan issues

src/Composer/Plugin/PluginInterface.php, src/Composer/Util/SyncHelper.php
This PR:
This simple change would prevent duplicating code related to the download logic in `DownloadManager::download` where the source of the package is automatically detected (_this would also prevent me from copying the complete function [in my plugin](https://github.com/drupol/composer-local-repo-plugin/blob/main/src/Service/RepoBuilder.php#L24) and modify its signature only_).
WDYT ?
=> refactor: update `SyncHelper::downloadAndInstallPackageSync`

src/Composer/Command/CreateProjectCommand.php
In my local environment ([Contao Manager](https://github.com/contao/contao-manager)), I always have the `COMPOSER` environment variable set to the root of my project directory. When using the `create-project` command with an new, empty directory target (because my project dir is not empty), Composer correctly downloads the files into the new directory, but then fails when calling [`Factory::create`](https://github.com/composer/composer/blob/main/src/Composer/Command/CreateProjectCommand.php#L205) because that uses the `COMPOSER` environment variable instead of the newly downloaded files.
I'm not sure what implications this could have on a running command, but I would assume that the variable is gone as soon as the `create-project` command is finished?
=> Force CreateProjectCommand to use the installed composer.json

src/Composer/Downloader/FileDownloader.php
=> Add fallback dist type extension to temp archive files for URLs without extension

src/Composer/Command/PackageDiscoveryTrait.php
=> Add prompt to require command if a package name is not found but there are similar names that could be used

doc/04-schema.md
The regular expression used to validate the package name in the `composer.json` as specified in https://getcomposer.org/schema.json differs from the example given in the documentation.
This PR seeks to update the documentation against the current pattern:
```json
"name": {
"type": "string",
"description": "Package name, including 'vendor-name/' prefix.",
"pattern": "^[a-z0-9]([_.-]?[a-z0-9]+)*\/[a-z0-9](([_.]|-{1,2})?[a-z0-9]+)*$"
},
```
=> Fix outdated package name regex pattern in documentation

README.md, doc/00-intro.md
Hi !
I'm currently working on improving the integration of Composer within the Nix ecosystem. I was looking for the dependencies it requires and I noted that it lacks a list of binary dependencies required for Composer to function optimally.
To bridge this gap, I created this pull request. It delineates the requisite input dependencies essential for Composer's operation. My primary aim is to provide users with a clear list, allowing them to pre-install these necessary dependencies, thereby facilitating a more efficient packaging and use of Composer.
To identify these dependencies, I examined the source code, specifically the strings `->execute(` and `->find(`.
I look forward to your feedback on this, let me know if I forgot anything.
=> docs: add binary dependencies

src/Composer/Command/BaseDependencyCommand.php, src/Composer/Util/PackageInfo.php
Hi!
This pull request adds a source/homepage link to packages when the aliases who depends on BaseDependencyCommand gets called. Currently "why" and "why-not".
Fixes https://github.com/composer/composer/issues/11289
I hope this can help,
Agostino.
=> Add source link to composer packages

src/Composer/Util/Filesystem.php, tests/Composer/Test/Util/FilesystemTest.php
Fixes #11549
Root Cause: When changing the project folder, existing junctions in Windows **(created using absolute paths)** become invalid. The "mklink /J" command used to create junctions results in an error ("Cannot create a file when that file already exists.") if a previous junction with a different target exists, as the junction is stored as an absolute path. This error causes package folders to have junctions with the wrong target directory, leading to [mkdir(): No such file or directory](https://github.com/composer/composer/issues/11549)
Windows Behavior: Windows prohibits creating a new junction if a file or junction with the same name already exists.
Solution: The bug fix ensures a clean execution by removing any previous junctions before creating new ones, regardless of whether …
=> Fix broken junctions leads to installation failure

src/Composer/Repository/PlatformRepository.php, tests/Composer/Test/Repository/PlatformRepositoryTest.php
On macOS, if libcurl is built against SecureTransport, the platform repository will contain an invalid package name:
% composer show --platform | grep curl
ext-curl                           8.2.7    The curl PHP extension
lib-curl                           8.1.2    The curl library
lib-curl-(securetransport) openssl 3.1.1    curl (securetransport) openss...
lib-curl-libssh2                   1.11.0   curl libssh2 version
lib-curl-zlib                      1.2.11   curl zlib version
This change fixes it:
% bin/composer show --platform | grep curl
lib-curl                 8.1.2              The curl library
lib-curl-libssh2         1.11.0             curl libssh2 version
lib-curl-securetransport 3.1.1              curl (securetransport) openssl ...
lib-curl-zlib            1.2.11 …
=> Fix lib-curl-openssl parsing for SecureTransport

src/Composer/Repository/Vcs/GitHubDriver.php, tests/Composer/Test/Repository/Vcs/GitHubDriverTest.php
Having a GitHub repository with an empty composer.json file in the default branch currently fails with `\RuntimeException('Could not retrieve composer.json for main')`. This PR changes the behavior to match all other VCS drivers, where an empty composer.json file is treated the same as if there were no composer.json file.
Example GitHub response for empty files: https://api.github.com/repos/pcom-test-group/empty-composer-json/contents/composer.json?ref=main
=> GitHubDriver: better handle empty composer.json file

src/Composer/Command/ShowCommand.php, tests/Composer/Test/Command/ShowCommandTest.php
Sort of related to #11046 (although this is not a regression, but didn't work before, either)
This now skips output of the `path` field entirely (it previously was always empty)... fine IMO, since this could happen previously (e.g. if `realpath()` failed in case of JSON output), and the path has always been `null` anyway for platform packages.
Also think this should maybe get backported to 2.2? Would you like me to rebase on top of that branch instead of `main`? Or should I target 2.5?
=> Fix 'composer show --platform <package>' erroring without composer.json

src/Composer/Command/ShowCommand.php, tests/Composer/Test/Command/ShowCommandTest.php
The name column was always padded to maximum width, even if no other columns were printed.
This makes it difficult to use the output e.g. in pipelines.
Fixed for all possible columns, and with tests for two cases (regular show and show outdated).
Again, lmk if I should rebase against 2.2 or 2.5.
=> Fix trailing whitespace in 'composer show -N'

src/Composer/Util/Http/CurlDownloader.php
With the latest curl release I sometimes encounter the following error:
> curl error 55 while downloading [PACKAGE_JSON_URL]: Failed sending data to the peer
This seems to happen because of a curl issue with HTTP/2: https://github.com/curl/curl/issues/10591
In order to work around this issue I tried two things and noticed they both worked equally as well:
1. Retry the download job and downgrade to HTTP/1.1
2. Retry the download job, but don't change the HTTP version
This PR adds a new check for for curl error 55 and restarts the download job if it was encountered, so composer doesn't error and finish the update/install command as expected.
I added a separate if-statement for that, since this can be removed again, once the curl issue is resolved.
Let me know what you think about this! This …
=> curl: Retry download if error 55 is encountered

phpstan/config.neon, tests/Composer/Test/Autoload/MinimumVersionSupport/.gitignore
When contributing to this project, I like to run the test suite locally to make sure that I'm not introducing regressions and that my changes are suitably covered by tests. I tend to run functional tests before stylistic checks because I think there's less value in making the code look pretty if it doesn't yet work as expected.
If I run the checks in https://github.com/composer/composer/blob/82bc8cf94e06e388f8917cbde3f0331453216481/.github/workflows/autoloader.yml before those in https://github.com/composer/composer/blob/82bc8cf94e06e388f8917cbde3f0331453216481/.github/workflows/phpstan.yml, I get errors. This pull request makes those errors go away, and tells Git to ignore the files newly created by the autoloader test.
=> Avoid PHPStan errors after running autoloader tests

CHANGELOG.md
ICU CDLR -> ICU CLDR (issue has correct title).
please squash in where it fits @Seldaek  currently wrong on the website.
=> Minor Typo CHANGELOG.md 2.5.8 release

src/Composer/Installer/BinaryInstaller.php, tests/Composer/Test/Installer/BinaryInstallerTest.php
Fixes: https://github.com/composer/composer/issues/11555
Fixes: https://github.com/sebastianbergmann/phpunit/issues/5447
This produces something like the following. This specific example has been taken from the test suite.
```php
if (__FILE__ === realpath($_SERVER['SCRIPT_NAME'])) {
$_SERVER['SCRIPT_NAME'] = realpath(__DIR__ . '/..'.'/vendor/foo/bar/binary');
}
```
=> Set $_SERVER['SCRIPT_NAME'] within proxy command

CHANGELOG.md
- ..._PLATFOR_... -> ..._PLATFORM_... (missing M)
- Backticks style to streamlined with other environment parameters around.
Please squash in where it fits @Seldaek currently wrong on the website.
(Recently I filed PR #11564 with a different minor correction of the change log.)
=> Minor Typo CHANGELOG.md 2.3.0-RC1 release

.gitattributes
This fixes #11507 (for real this time 😄 )
#11508 was intended to fix #11507. However, I don't think it worked. If you exclude a directory via .gitattributes, you apparently can't later unexclude a file inside that directory.
The correct fix is to exclude the _contents_ of the directory rather than the directory itself. You can confirm this works locally by checking out this feature branch, running `git archive issue-11507 -o /tmp/composer.tar`, then inspecting the resulting archive to confirm phpstan/rules.neon (and _only_ phpstan/rules.neon) exists.
I was bit by this in https://github.com/acquia/cli/pull/1577 when upgrading to a Composer 2.x-dev release which included the new .gitattributes. Composer's rules.neon suddenly disappeared, producing errors like this:
> Config file …
=> Fix #11507: phpstan/rules.neon missing from archives

tests/Composer/Test/Command/BaseDependencyCommandTest.php
This PR adds test cases for `why` and `why-not` as mentioned in #10796
- It adds 20 test cases (now from 198 to 218)
- It increases the test coverage for `BaseDependencyCommand` from 0% to 97%
- It adds full coverage to the `DependsCommand` command (`why` command)
- It adds full coverage to the `ProhibitsCommand` command (`why-not` command)
- It adds poor coverage to `CompletionTrait`, maybe it could be addressed in other PR
Thanks in advantage for your feedback.
=> Tests for base dependency command

tests/Composer/Test/Downloader/ZipDownloaderTest.php, tests/Composer/Test/InstalledVersionsTest.php
_Re: branch selection: as Composer 2.2 is marked as an LTS release, by rights, this PR should be pulled to the 2.2 branch, but the 2.2 branch isn't being tested against PHP 8.2, which gives me the impression that the "LTS" is only about Composer native functionality, not about PHP version support._
_Might be a good idea to clarify this somewhere ?_
---
Calling `ReflectionProperty::setValue()` with only one argument (to set a static property) is deprecated.
Passing `null` as the first (`$object`) parameter will work cross-version.
As the `ZipDownloaderTest::setPrivateProperty()` method has a `null` default value for the `$obj` parameter anyway, this means the if/else toggle can be removed.
Ref: https://wiki.php.net/rfc/deprecate_functions_with_overloaded_signatures#reflectionpropertysetvalu …
=> PHP 8.3 | Tests: fix deprecation notices

tests/Composer/Test/Repository/ComposerRepositoryTest.php
Prior to PHP 8.3, `ReflectionMethod` could set a private method on a parent class to accessible. This is no longer possible in PHP 8.3 since php/php-src#9470 and breaks the `Composer\Test\Repository\ComposerRepositoryTest::testWhatProvides` test.
Also see: https://3v4l.org/8YcIk/rfc#vgit.master
Fixed now.
=> PHP 8.3 | ComposerRepositoryTest: fix test failure

.github/CONTRIBUTING.md
This doesn't appear to be needed anymore since 2a771dfb2d911754dd4d91aecb2f0778ef2a3f4c.
=> CONTRIBUTING: remove outdated suggestion

.github/workflows/continuous-integration.yml, .github/workflows/lint.yml
_Re: branch selection: as Composer 2.2 is marked as an LTS release, by rights, this PR should be pulled to the 2.2 branch, but the 2.2 branch isn't even being tested against PHP 8.2, which gives me the impression that the "LTS" is only about Composer native functionality, not about PHP version support._
_Might be a good idea to clarify this somewhere ?_
---
What with PHP 8.3 being close to the first RC, I'd like to suggest enabling runs against PHP 8.3 for the linting and test runs.
* Linting passes on PHP 8.3, so I propose to not allow new failures to be introduced there.
* The test runs, however, do not pass against PHP 8.3, so I'm marking those as `experimental` for now to allow for fixing the issue(s).
As for the compatibility issues (based on the test runs):
* PR #11599 fixes all …
=> GH Actions: run against PHP 8.3

tests/Composer/Test/Command/DumpAutoloadCommandTest.php
I might have found a tiny bug in `DumpAutoloadCommand`, but before fixing it I wanted to add tests. I'm not well accustomed to Composer or Command tests in general, so I'm not a 100% sure about the changes here.
Kind of open things:
- Is it a good idea to use the default application / composer.json for this? (e.g. could be faster with a temp composer.json I guess)
- ~~Is it a good idea to hardcode the dumped amount of classes? (e.g. dependency/code changs will break this test) Any better ideas of ensuring that the full output is correct without this, e.g. regex?~~ changed to regex since it was already failing here..
- I don't think I can cover actual PSR violations with `--strict-psr` with such a test, can I? I think I'd need to have a temp composer.json AND temp code? …
=> Add tests for `DumpAutoloadCommand`

src/Composer/Installer.php
When splitting the logic between the lock file management and the vendor folder management in composer 2.0, the logic playing nice with make was broken by running the logic based on operations performed in the lock file instead of operations performed in the vendor folder.
See https://github.com/composer/composer/pull/8529/files#r367302603 for a previous discussion about this feature giving the context.
=> Fix the mtime of the vendor folder when running composer install

src/Composer/Command/DiagnoseCommand.php
Make `diagnose` checks aware of COMPOSER_DISABLE_NETWORK (true) and skip Composer network operations that would otherwise spill stack traces into diagnostic messages and taint the result as error while the check itself is not applicable/useful within the environment.
`COMPOSER_DISABLE_NETWORK` was released with [2.0.0-alpha1] and introduced in fc03ab9bb (Add COMPOSER_DISABLE_NETWORK env var for debugging, 2019-01-14).
The previous behaviour was to exit with a status of two (2), denoting an error.
The new behaviour is to exit with a status of zero (0), showing the successful skipping of diagnostics that can only be run when Composer network is enabled - not disabled.
It is irrelevant for diagnose checks, as all diagnostic checks that spilled were with the HTTP Downloader and the check is …
=> COMPOSER_DISABLE_NETWORK aware `diagnose` checks

src/Composer/Command/DumpAutoloadCommand.php, tests/Composer/Test/Command/DumpAutoloadCommandTest.php
The "bug" I mentioned in https://github.com/composer/composer/pull/11581
Since `--classmap-authoritative` automatically enables level 1 optimisations (https://getcomposer.org/doc/articles/autoloader-optimization.md#what-does-it-do--2) `--strict-psr` should be useable too without having to pass `--optimise` again.
=> Allow --strict-psr in `DumpAutoloadCommand` also with --classmap-authoritative

src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Command/DumpAutoloadCommand.php
Fixes https://github.com/composer/composer/issues/11580.
Note: Because this indents a large block of code without actually changing it, I recommend reviewing the changes with whitespace hidden to reduce noise ([like so](https://github.com/composer/composer/pull/11608/files?w=1)).
=> Add `dumpautoload --dry-run` option

src/Composer/Package/Version/VersionBumper.php, tests/Composer/Test/Package/Version/VersionBumperTest.php
hi,
i think this is quite a straight forward thing and i think its very benefical to support bumping patch level constraints.
this will enable the mentioned constraint from #11579 to be updated
```json
{
"require-dev": {
"phpstan/phpstan": "~1.10.0"
}
}
```
what do you think?
=> allow bumping for patch level version constraints (fixes #11579)

tests/Composer/Test/Command/ArchiveCommandTest.php
Attempt to improve the coverage of the ArchiveCommand, from 55% to 76%, partially addressing issue: #10796.
I hope I did it right, this is my first contribution to open source 😄
=> Add test for `ArchiveCommand` with package name

src/Composer/Command/InstallCommand.php, src/Composer/Installer.php
After #11362, CI builds may fail with status code 5 if the composer command require/create-project is used.
This PR fix this BC break and the command will fail if the user has explicitly specified the `--audit` flag
```
composer install --audit
```
=> Fix exit code 5 on composer require/create-project command

src/Composer/Installer/BinaryInstaller.php, tests/Composer/Test/Installer/BinaryInstallerTest.php
reverts #11562
fixes #11615
why the PR should be reverted?
- `$_SERVER['SCRIPT_NAME']` is expected to be the entry file, this is a php-src convenction and it should be safe to assume it no matter how the script is started
- the entry file path must match the first path in a backtrace, otherwise shortening backtraces might not work (as in #11615)
- original problem #5447 mentioned https://github.com/sebastianbergmann/phpunit/blob/15a89f123d/build/templates/binary-phar-autoload.php.in#L58-L62 - so the fix was done to fix this - incorrect/not always valid assumption - and the proper fix should be to fix sebastianbergmann/phpunit instead (and possibly with some added global/API in composer like "entry target file" in https://github.com/mvorisek/composer/blob/6200985c2a/src/Composer/Installer/B …
=> Revert "Set $_SERVER['SCRIPT_NAME'] within proxy command"

doc/articles/troubleshooting.md
Updated docs to fix the updates on the memory limit errors mentioned in the issue below, that was approved by @Seldaek 
https://github.com/composer/composer/issues/11540#issue-1791143502
=> updated memory limit distinction for memory limit errors in docs

src/Composer/Installer/InstallationManager.php
Closes https://github.com/composer/composer/issues/11619
In reactphp/promise v3, passing an argument is mandatory.
=> Fix the promise resolution for the cleanup logic

src/Composer/Package/Archiver/ZipArchiver.php
I came across a few open issues, notably #10099, and the fix commented by @Seldaek resolved the issue. However, it has yet to be PR'd since Satis is now replaced by [Private Packagist](https://packagist.com/).
Nonetheless, here is the PR to resolve the issue where the archive paths are incorrect due to `ZipArchive::archive` not using the `realpath()`. Notably on MacOS where `sys_get_temp_dir()` returns a symlinked path. This change is inline with `PharArchive::archive` as it uses `realpath()` [already](https://github.com/composer/composer/blob/main/src/Composer/Package/Archiver/PharArchiver.php#L41).
There are other instances in the codebase which use `sys_get_temp_dir()`. However, since they are only used for storage, and not pathing information, I don't believe they require changes.
=> Get realpath for `ZipArchive`

src/Composer/DependencyResolver/PoolBuilder.php, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/load-replaced-root-package-if-replacer-dropped.test, tests/Composer/Test/DependencyResolver/Fixtures/poolbuilder/multi-repo-replace-partial-update-all.test
Fixes https://github.com/composer/composer/issues/11626
If the replaced package is part of the require request itself, we must also load it. We actually incorrectly adjusted the test in https://github.com/composer/composer/pull/11449.
I hope the changes are correct, requesting a review by @naderman :)
=> Fixed base package replacers being removed incorrectly

doc/06-config.md, res/composer-schema.json, src/Composer/Advisory/Auditor.php, src/Composer/Command/AuditCommand.php, src/Composer/Command/ConfigCommand.php, src/Composer/Config.php, src/Composer/Installer.php, tests/Composer/Test/Advisory/AuditorTest.php
=> Add audit.abandoned warnings for abandoned packages

doc/01-basic-usage.md, doc/06-config.md, src/Composer/Autoload/AutoloadGenerator.php, src/Composer/Command/DumpAutoloadCommand.php, src/Composer/Command/ReinstallCommand.php, src/Composer/Installer.php, src/Composer/Util/Filesystem.php, tests/Composer/Test/Autoload/AutoloadGeneratorTest.php, tests/Composer/Test/Command/DumpAutoloadCommandTest.php, tests/Composer/Test/TestCase.php
This PR:
Reproduce this at home, inside the `composer` source directory:
=> feat: improve Composer's output reproducibility

.gitattributes
This PR is mostly useful (_at first glance_) for the Nix community. This will allow us to improve the way Composer is being built on Nix by downloading a snapshot of Composer instead of downloading the whole git repository. It will also save some bandwidth on the Network.
This PR:
=> chore: remove `composer.lock` from `.gitattributes`

src/Composer/Repository/PlatformRepository.php, tests/Composer/Test/Repository/PlatformRepositoryTest.php
As suggested in https://github.com/composer/composer/issues/11683#issuecomment-1757311564, this pull request adds a performance optimisation for detecting the `libpq` version.
=> Use global constant if available for libpq version

src/Composer/Package/Version/VersionBumper.php, tests/Composer/Test/Package/Version/VersionBumperTest.php
I recently ran `composer bump` on a project which used a wildcard constraint (`*`) for a particular package.
The help text for the `bump` command reads:
> Increases the lower limit of your composer.json requirements to the currently installed versions
However the lower-limit for the wildcard constraint (`*`) was not changed. This pull request adds this functionality.
While I do not believe that unbound version constraints should be used generally, I recognise that others have different opinions and that there are valid use-cases for such constraints.
=> Bump wildcard constraint

doc/03-cli.md, src/Composer/Command/BaseCommand.php, src/Composer/Command/RemoveCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Command/UpdateCommand.php, src/Composer/DependencyResolver/DefaultPolicy.php, src/Composer/Installer.php, tests/Composer/Test/DependencyResolver/DefaultPolicyTest.php, tests/Composer/Test/Fixtures/installer/update-allow-list-minimal-changes.test, tests/Composer/Test/Fixtures/installer/update-allow-list-minimal-update.test, tests/Composer/Test/InstallerTest.php
Fixes the last point I mentioned in #11644
=> Add --minimal-update mode to perform partial updates --with-dependencies while upgrading only what is necessary

src/Composer/Command/UpdateCommand.php, tests/Composer/Test/Command/UpdateCommandTest.php
This was inspired by and might fix https://github.com/composer/composer/issues/11690
=> Display error instead of throwing exception when unable to update with temporary constraint

.github/workflows/continuous-integration.yml
Suggested change for the CI workflow what with the PHP 8.3 release expected later today.
PHP 8.4 has been added as experimental.
And the "high" PHP builds for the variations have been updated to use PHP 8.3.
=> GH Actions: update the CI workflow for the release of PHP 8.3

src/Composer/Installer.php, tests/Composer/Test/Command/UpdateCommandTest.php
=> Show package source in very verbose updates

src/Composer/Advisory/Auditor.php, src/Composer/Advisory/IgnoredSecurityAdvisory.php, src/Composer/Advisory/PartialSecurityAdvisory.php, src/Composer/Advisory/SecurityAdvisory.php, tests/Composer/Test/Advisory/AuditorTest.php
Resolves: https://github.com/composer/composer/issues/11633
```
composer audit --format=plain
The new audit.abandoned setting (currently defaulting to "report" will default to "fail" in Composer 2.7, make sure to set it to "report" or "ignore" explicitly by then if you do not want this.
Found 1 security vulnerability advisory affecting 1 package:
Package: api-platform/core
Severity: high
CVE: CVE-2023-25575
Title: CVE-2023-25575: Secured properties may be accessible within collections
URL: https://github.com/api-platform/core/security/advisories/GHSA-vr2x-7687-h6qv
Affected versions: >=2.6.0,<2.7.10|>=3.0.0,<3.0.12|>=3.1.0,<3.1.3
Reported at: 2023-02-28T10:37:00+00:00
```
```
composer audit --format=table
The new audit.abandoned setting (currently defaulting to "report" will default to …
```
=> Audit: add severity to plain and table output

doc/03-cli.md, src/Composer/Command/OutdatedCommand.php, src/Composer/Command/ShowCommand.php, tests/Composer/Test/Command/ShowCommandTest.php
=> Add release date to show command, and also release date for latest package in --latest/outdated mode

doc/articles/composer-platform-dependencies.md
=> Fix typo in composer-platform-dependencies.md

src/Composer/Repository/Vcs/GitLabDriver.php
This permits to directly access project's metadata from the GitLab driver, exactly as it already happens with the GitHub's one.
The main purpose of this change is to be then leveraged in Packagist to grab addictional informations about stars, forks, open issues and more, to be displayed in the web interface or be used for internals (e.g. "popularity" evaluation based on project's stars).
cfr. https://github.com/composer/packagist/blob/main/src/Package/Updater.php#L564
=> Exposing GitLab's project metadata

src/Composer/Command/DiagnoseCommand.php
=> Perform audit on Composer and its dependencies during diagnose

tests/Composer/Test/Command/ConfigCommandTest.php
re: #10796 
Adds a single test to cover an invalid argument combination on the config command.
=> Adds a test for invalid arg combo

src/Composer/Command/ShowCommand.php, tests/Composer/Test/Command/ShowCommandTest.php
=> Add support for combining show --self with --installed or --locked

src/Composer/Filter/PlatformRequirementFilter/IgnoreAllPlatformRequirementFilter.php, src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php, src/Composer/Filter/PlatformRequirementFilter/IgnoreNothingPlatformRequirementFilter.php, src/Composer/Filter/PlatformRequirementFilter/PlatformRequirementFilterInterface.php, src/Composer/Package/Version/VersionSelector.php, tests/Composer/Test/Filter/PlatformRequirementFilter/IgnoreAllPlatformRequirementFilterTest.php, tests/Composer/Test/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilterTest.php, tests/Composer/Test/Filter/PlatformRequirementFilter/IgnoreNothingPlatformRequirementFilterTest.php
=> Fix warnings incorrectly being shown when using require with upper bound ignored on platform requirements

src/Composer/Repository/ComposerRepository.php
=> Ensure we respect available-package-patterns and available-packages directives when fetching security advisories

src/Composer/Package/Loader/ValidatingArrayLoader.php, tests/Composer/Test/Package/Loader/ValidatingArrayLoaderTest.php
Fixes `Undefined array key "name"`
Wasn't sure if there is going to be another 2.6 release but commit can be applied on main too.
=> ValidatingArrayLoader: fix link validation with missing name

src/Composer/Console/Application.php
Current behaviour is to, no matter `--no-plugins` is used or not, to show the error, this is from `main` branch:
```cli
$ ./bin/compile
$ sudo php composer.phar -n --version
Composer plugins have been disabled for safety in this non-interactive session. Set COMPOSER_ALLOW_SUPERUSER=1 if you want to allow plugins to run as root/super user.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer version 2.7-dev+4e5be9ee7d924d8efc58d676439b0c7bd18a9ce4 (2.7-dev) 2024-01-12 13:20:59
$ sudo php composer.phar -n --version --no-plugins
Composer plugins have been disabled for safety in this non-interactive session. Set COMPOSER_ALLOW_SUPERUSER=1 if you want to allow plugins to run as root/super user.
Do not run Composer as root/super user! See …
```
=> Do not show error that plugins have been disabled when they are already disabled

doc/04-schema.md
I've asked a discussion on symfony slack and got this info, found it not documented so my I propose to add it
as per https://github.com/composer/composer/blob/d3aeb1357f8cb00474f0b640279d192301b3906f/CHANGELOG.md?plain=1#L1388
=> chore(doc): add `_comment` documentation inside `composer.json` schema

src/Composer/EventDispatcher/EventDispatcher.php
When executing a script, arguments are not displayed for execution. For example with the following scripts:
```json
{
"update": "FQN\\Update"
"update-all": {
"update-a": "@update A",
"update-b": "@update B"
}
}
```
results in the following output: when running `update-all`:
```bash
> FQN\\Update
> FQN\\Update
```
In this PR, the arguments supplied will be made visible:
```bash
> FQN\\Update (A)
> FQN\\Update (B)
```
=> Add arguments to command call output

tests/Composer/Test/Command/AuditCommandTest.php
Adds a test case for the happy path of the Audit Command where a given package has no security advisories.
=> test: Covers audit of pkg with no sec advisories

src/Composer/Command/DiagnoseCommand.php
GitHub's new fine-grained tokens have a cumpulsory expiration date, and their classic tokens also support an expiration date.
https://github.blog/changelog/2021-07-26-expiration-options-for-personal-access-tokens/
This improves the `composer diagnose` command to display the expiration date and time if it is provided by the response headers (via `GitHub-Authentication-Token-Expiration`).
=> Diagnose command: Add GitHub OAuth token expiration date information

src/Composer/Console/Application.php, src/Composer/Installer/InstallationManager.php, src/Composer/Installer/PluginInstaller.php, src/Composer/Plugin/PluginManager.php
Fixes #11839
This adds 3 warnings:
One during installation if plugins are disabled:
One additional line before a command fails to be found if plugins are disabled:
And one generic `Plugins have been disabled automatically as you are running as root, this may be the cause of the following exception. See also https://getcomposer.org/root` line if plugins are disabled and you're running as root + non-interactive, also just before a thrown exception is displayed.
=> Output more warnings about plugins being disabled to hint that it may cause problems

doc/05-repositories.md
Adds a small section to the repositories page of the docs based on [a comment](https://github.com/composer/composer/issues/11735#issuecomment-1830251947) from @stof on #11735
=> Repositories docs reference

doc/05-repositories.md
PR #11840 added docs.
The note section was missing angle brackets at the start of the line so the note section did not appear in the coloured block.
=> Makes note appear in a note section.

doc/articles/scripts.md
Since this was included in a minor version, it's nice to tell the user if this feature is available on the version they're running or if they need to upgrade. If it's not available, the only hint (besides the missing aliases on `composer list`) is the mild complaint at `composer validate`.
I also removed some dangling full stops on titles, since the other titles don't have that.
-----------
This was originally introduced at #11666.
=> [Docs] Explicit the version where script-aliases was included

doc/articles/troubleshooting.md, src/Composer/Config.php, src/Composer/Package/Loader/RootPackageLoader.php, src/Composer/Util/Platform.php, tests/Composer/Test/Command/LicensesCommandTest.php, tests/Composer/Test/Command/ShowCommandTest.php, tests/Composer/Test/Command/ValidateCommandTest.php
Hello,
I would like to propose this PR to help the user experience with Composer and such kind of issue: https://github.com/vimeo/psalm/issues/10721
Let me know if you would be OK with it.
=> Add a warning message when Composer is not able to guess the root package version

src/Composer/Console/Application.php
I spend a lot of time on Stack Overflow, and confusion about which version of PHP being used is a big driver of questions. This PR adds that information when calling `composer --version --verbose`. e.g.:
```none
Composer version 2.7.999-dev+source @release_date@
PHP version 8.3.2 (/usr/local/bin/php83)
```
I would prefer if it were shown by default, but I figured modifying any existing behaviour would reduce the chance of acceptance.
=> Include PHP information when showing Composer version verbosely

src/Composer/DependencyResolver/LockTransaction.php, tests/Composer/Test/Fixtures/installer/update-mirrors-changes-url.test
Hello,
Today I encountered an unexpected behaviour while attempting to upgrade from version 2.6.6 to 2.7.1. After making a thorough bisect, I pinpointed the introduction of the weird behaviour to this specific commit: [042a8c2](https://github.com/composer/composer/commit/042a8c212801aeac42b7a41b42cd1185ae28123a) (related to https://github.com/composer/composer/issues/11787).
Originally, this issue has been found while Composer is used in conjunction with a custom plugin: [nix-community/composer-local-repo-plugin](https://github.com/nix-community/composer-local-repo-plugin). Note, this issue cannot be reproduced (_pun intended!_) when using Composer < 2.7. 
<details>
<summary>Reproduce the issue with the Composer plugin</summary>
What makes this issue complicated is that the core of the …
=> Issue in `composer.lock` generation ? 

src/Composer/Package/Loader/RootPackageLoader.php
https://github.com/composer/composer/pull/11858 is too broad imho because for a lot of project skeletons that you'd use `create-project` for, this will now show a warning. However, if you are of `type` `project`, it's extremely unlikely  ou have circular deps on yourself then. The warning only confuses people in this case.
=> Only show warning about default version when not "project" type

src/Composer/Advisory/Auditor.php
Fixes https://github.com/composer/composer/issues/11891
=> Surface the advisory ID when CVE not present.

src/Composer/Util/Hg.php
This fixes ticket #11874
It was declared a feature, so I've chosen the main branch. I also applied a few minor fixups to docblocks for example. I hope that's ok, otherwise let me know and I'll remove them.
For the fix itself, I basically just adjusted the regex to allow "ssh" and to grab the password more reliably, even though the latter isn't even used. Worked fine with the repo I'm using, if the SSH key is set up in both the repo and the workstation you're issuing the pull from.
=> Allow for SSH URLs when using hg repository type

doc/04-schema.md, res/composer-schema.json, src/Composer/DependencyResolver/PoolBuilder.php, src/Composer/Package/AliasPackage.php, src/Composer/Package/Loader/ArrayLoader.php, src/Composer/Package/Loader/ValidatingArrayLoader.php, src/Composer/Package/Package.php, src/Composer/Package/PackageInterface.php, src/Composer/Repository/RepositorySet.php, tests/Composer/Test/Fixtures/installer/install-package-and-its-provider-skips-original.test, tests/Composer/Test/Json/ComposerSchemaTest.php
Basic infrastructure to let pie reuse Composer code for PHP extension packages.
=> Add support for php extension packages

doc/04-schema.md
The character set for keywords is limited due to Packagist indexing.
Fixes #11897.
=> Update keywords documentation

src/Composer/Repository/Vcs/GitHubDriver.php
Github's funding now has official support for buy_me_a_coffe but this doesn't work in packagist, everything is explained at https://github.com/composer/packagist/issues/1442
This PR should add support for this service
Fixes https://github.com/composer/packagist/issues/1442
Fixes https://github.com/composer/composer/issues/11901
=> Added support for buy_me_a_coffee in github's funding

doc/03-cli.md, doc/faqs/how-to-use-composer-behind-a-proxy.md, src/Composer/Console/Application.php
Provides a separate FAQ about using Composer behind a proxy, replacing the information from the environment variables section.
Please improve and polish where appropriate.
I've included a section at the end that documents the recent proxy requirement changes and explains the behaviour during the transition period. If you want to keep this, it could be linked to in the warning message.
Alternatively, this document could be linked to if a `TransportException` message starts with 'Unable to use a proxy'.
=> Add FAQ about using a proxy

src/Composer/Console/Application.php
Load the ProxyManager before running a command (eg the install or autoload), to make sure we load the internal class, not the application in which Composer is installed. Refs https://github.com/composer/composer/issues/11940
=> Load ProxyManager before running command to fix autoload order

src/Composer/Console/Application.php, src/Composer/Util/Platform.php
Podman creates the file `/run/.containerenv` (or `/var/run/.containerenv`) instead of /.dockerenv, so I added these two paths to the existing checks.
> Additionally, a container environment file is created in each container to indicate to programs they are running in a container. This file is located at `/run/.containerenv` (or `/var/run/.containerenv` for FreeBSD containers).
https://docs.podman.io/en/latest/markdown/podman-run.1.html
Follow up of #8395
=> Don't show root warning for Podman containers

src/Composer/Command/RemoveCommand.php
I've looked through the repository and realized I've never actually seen this proposed either in issue or pull request form.
Some package managers use `uninstall` as the convention for removing/uninstalling dependencies, and as a result I've found myself in the habit of typing `composer uninstall (packagename)` instead of `composer remove (packagename)`.
Composer doesn't currently handle this all that gracefully...it suggests "Did you mean install/reinstall?" without suggesting the actual proper `remove` command.
I think, perhaps to save folks like me the trouble, Composer can follow in the footsteps of package managers like NPM and make `remove` and `uninstall` refer to the same command, so there's no retyping involved if you slip up and forget which is which.
=> Add `uninstall` as alias to `composer remove`.

phpstan/baseline-8.1.neon, phpstan/baseline.neon, src/Composer/EventDispatcher/EventDispatcher.php
=> Fix Composer autoloader being hijackable by script/plugin event handlers

src/Composer/DependencyResolver/DefaultPolicy.php
No need for thousands of `strpos()` calls as we already have this information on the package itself. Shaves off about 0.1 seconds on the `PoolOptimizer` step in my case.
=> Re-use precalculated information

src/Composer/Command/PackageDiscoveryTrait.php, src/Composer/Console/Application.php
When I ran `composer require vendor/package:version` in order to get a specific version of a package, I noticed that the colour of the "normal" text was different from when I ran `composer require vendor/package`. I have tracked this down to an unterminated Symfony style tag used in the warning message about specifying a "too strict" restraint. I then scanned all of `src/` and found one other instance of this. This pull request fixes both instances.
=> Close style tags to avoid colour bleed

src/Composer/Command/DiagnoseCommand.php
Syncing from https://github.com/composer/getcomposer.org/blob/main/web/installer
We seemed to have missed this one.
=> Add uopz warning from installer code

src/Composer/Console/Application.php
To enable to the TransportException code to be accessed in PHP < 8.1 make reflection property accessible
Without this change, I get this error in PHP versions below 8.1:
```
$ composer why-not [package name] [version]
In Application.php line 449:
Cannot access non-public member Composer\Downloader\TransportException::$code  
prohibits [-r|--recursive] [-t|--tree] [--locked] [--] <package> <version>
```
This issue seems to have been introduced in [Composer 2.7.5](https://github.com/composer/composer/releases/tag/2.7.5).
This bug will not be present with PHP 8.1 +, according to [setAccessible docs](https://www.php.net/manual/en/reflectionproperty.setaccessible.php).
=> Fix issue with TransportException

src/Composer/Util/ProcessExecutor.php, tests/Composer/Test/ApplicationTest.php
=> Fix composer error when git config safe.bareRepository is set to explicit

src/Composer/Util/Http/CurlDownloader.php
Just adjusting the blocked IP handling to match `MaxFileSizeExceededException`.
=> BlockedIPs: reject download jobs like other exceptions

src/Composer/Plugin/PluginManager.php, src/Composer/Repository/RepositoryUtils.php, tests/Composer/Test/Repository/RepositoryUtilsTest.php
Composer now skips it and does not prompt if it is not allowed to run, fixes #11944
=> Fix UX when a non-required plugin is still present in vendor dir

src/Composer/Installer.php, tests/Composer/Test/Fixtures/installer/outdated-lock-file-fails-install.test, tests/Composer/Test/Fixtures/installer/outdated-lock-file-with-new-platform-reqs-fails.test
=> Fix new platform requirements from composer.json not being checked when composer.lock is outdated

tests/Composer/Test/IO/ConsoleIOTest.php, tests/Composer/Test/IO/NullIOTest.php
There are a few typo mistakes (camel case) in IO tests, so I fixed them.
=> Fix typo for IO tests

phpstan/baseline.neon, src/Composer/Package/Locker.php
Don't store `transport-options.ssl` within the lock-file otherwise the installation or updates will (in most cases) fail for repositories that use client TLS certificates, because during installation `transport-options` from `composer.lock` will be used instead of repository settings (certificates) from composer configuration file.
<hr />
Minimal configuration for case "private registry with client-certificates" (`~/.composer/config.json`)
```json
{
"repositories": {
"private.registry": {
"type": "composer",
"url": "https://composer.registry.example.com",
"options": {
"ssl": {
"local_cert": "/home/user/.composer/certs.d/private.cert",
"local_key": "/home/user/.composer/certs.d/private.key"
}
}
}
}
}
```
Dummy project (`~/project/composer.json`)
```json
{
"name": "exmaple/dummy",
"type": …
```
=> fix(Locker): don't store transport-options.ssl within the lock-file

src/Composer/Cache.php, src/Composer/Config.php, src/Composer/EventDispatcher/EventDispatcher.php, src/Composer/Installer.php, src/Composer/Question/StrictConfirmationQuestion.php
These parameters are declared as boolean and composer also uses `declare(strict_types=1);`. If we pass non-boolean values, it'll raise `TypeError`. So, we needn't to use type casts for them.
=> Remove redundant boolean type casts

.github/workflows/lint.yml
=> Bump highest php lint to use nightly

src/Composer/Downloader/TransportException.php
PHP 8.4 requires nullable arguments to be explicitly declared as such.
=> Fix deprecation notice on PHP 8.4

src/Composer/DependencyResolver/Problem.php, src/Composer/Repository/VcsRepository.php, tests/Composer/Test/Fixtures/installer/solver-problem-with-hash-in-branch.test, tests/Composer/Test/Repository/VcsRepositoryTest.php
Fixes #12029
This makes sure that VCS branches containing `#` signs get it replaced by a `+`. That makes them addressable (right now they are not at all).
And also it adds proper error reporting suggesting a solution if someone requires `dev-foo#bar` meaning to require that branch and not `dev-foo` at ref `bar`.
=> Fix addressability of branches containing # characters

phpstan/baseline.neon, src/Composer/Installer.php, src/Composer/Util/RemoteFilesystem.php
Requires a new PHPStan release with https://github.com/phpstan/phpstan-src/pull/3221
=> Make use of new PHP 8.4.0 function to replace implicit $http_response_header var

src/Composer/Autoload/AutoloadGenerator.php
=> Normalize namespaces in psr-0/psr-4 rules to fix edge cases

doc/articles/scripts.md
Adds missing semicolon to a code example, which cannot be executed otherwise.
=> Add missing semicolon to code example in documentation

tests/Composer/Test/Command/RequireCommandTest.php
re: #10796
Added four cases for conflicting keys
- with package in require or in require-dev
- with interactive or non interactive
For the interactive mode I'm testing for 'yes' input only.  I can test for 'no' too, but I didn't find an obvious way to do it without making the code too unreadable.
For the way I wrote the command part, I had to structure the code in that weird way to get it to work.  See commit message of d6479b8a for more.
=> Add "require command with conflicting keys" test

tests/Composer/Test/Command/GlobalCommandTest.php
re: #10796
- `testGlobal` to check `COMPOSER_HOME` is followed correctly + check `COMPOSER` is unset.
- `testNotCreateHome` to test handling invalid `COMPOSER_HOME`.
=> Add `GlobalCommandTest.php`

src/Composer/Downloader/PathDownloader.php, src/Composer/Util/Filesystem.php, tests/Composer/Test/Util/FilesystemTest.php
=> Fix relative:true not being respected in path repo installs

src/Composer/Package/Loader/RootPackageLoader.php, src/Composer/Package/Version/VersionGuesser.php, src/Composer/Repository/PathRepository.php, tests/Composer/Test/Package/Version/VersionGuesserTest.php
fixes #12101
This will turn COMPOSER_ROOT_VERSION=1.0-dev into 1.0.x-dev which is kinda what people mean, and this can sometimes have a material impact on resolution.
=> Fix handling of COMPOSER_ROOT_VERSION to normalize according to expectations

src/Composer/Command/BaseDependencyCommand.php, src/Composer/DependencyResolver/PoolBuilder.php, tests/Composer/Test/Command/BaseDependencyCommandTest.php
Fixes #12104
This actually lets one check for platform packages upgrades which is great:
```
$ composer why-not php 9.0
composer/composer                 2.7.x-dev requires php (^7.2.5 || ^8.0)
composer/ca-bundle                1.5.1     requires php (^7.2 || ^8.0)
composer/class-map-generator      1.3.4     requires php (^7.2 || ^8.0)
composer/metadata-minifier        1.0.0     requires php (^5.3.2 || ^7.0 || ^8.0)
composer/pcre                     2.3.1     requires php (^7.2 || ^8.0)
composer/semver                   3.4.2     requires php (^5.3.2 || ^7.0 || ^8.0)
composer/spdx-licenses            1.5.8     requires php (^5.3.2 || ^7.0 || ^8.0)
composer/xdebug-handler           3.0.5     requires php (^7.2.5 || ^8.0)
phpstan/phpstan                   1.12.1    requires php (^7.2|^8.0) …
```
=> Fix handling of platform packages in why-not command and partial updates

src/Composer/Command/UpdateCommand.php, tests/Composer/Test/Command/UpdateCommandTest.php
An improvement on updating packages with the `--interactive` flag.
The last time I updated some dependencies, I had difficulty remembering which packages to update when running the update command. Adding a list of packages and their current and latest versions should help developers select the right package to update more easily.
=> Improve interactive package updates

doc/articles/scripts.md, src/Composer/EventDispatcher/EventDispatcher.php, tests/Composer/Test/EventDispatcher/EventDispatcherTest.php
fixes #10734
This is so far fairly experimental/MVP.
Using the example from https://github.com/composer/composer/issues/10734#issuecomment-1179164480 as a base, I got this test case:
```
{
"scripts": {
"command-name": [
"@composer install --no-dev @no_additional_args",
"@php runner.php command-name @additional_args",
"@php runner.php @additional_args command-name"
]
}
}
```
Then running that script outputs:
```
c run command-name -vv -- foo bar
> command-name: @composer install --no-dev
Installing dependencies from lock file
[...]
> command-name: @php runner.php command-name 'foo' 'bar'
> command-name: @php runner.php 'foo' 'bar' command-name
```
=> Add a way to control which scripts get args and where

src/Composer/Util/ErrorHandler.php, src/Composer/Util/Silencer.php
The `E_STRICT` constant is deprecated as of PHP 8.4 and will be removed in PHP 9.0 (commit finally went in today).
The error level hasn't been in use since PHP 8.0 anyway and was only barely still used in PHP 7.x, so removing the exclusion from the `error_reporting()` setting in these script shouldn't really make any difference in practice.
Ref:
* https://wiki.php.net/rfc/deprecations_php_8_4#remove_e_strict_error_level_and_deprecate_e_strict_constant
=> PHP 8.4 | Remove use of `E_STRICT`

src/Composer/Package/Version/VersionSelector.php
Fixes #10736
e.g. 
(previously only the first warning was shown)
=> Show warnings for each missing platform package in create-project

src/Composer/Command/InitCommand.php, tests/Composer/Test/Command/InitCommandTest.php
=> Validate licenses passed into init command

doc/03-cli.md, src/Composer/Command/UpdateCommand.php, tests/Composer/Test/Command/UpdateCommandTest.php
Fixes #11446
cc @MajPay as you requested the feature
Still needs tests to be written but otherwise implementation is ready to review.
=> Add --patch-only flag to update command to restrict updates to patch versions and make them safer

doc/03-cli.md
While looking through the dump-autoload code, I spotted this argument that was currently not documented
=> Add dry-run argument to dump-autoload documentation

src/Composer/PHPStan/ConfigReturnTypeExtension.php
This fixes a deprecation warning being reported by PHPStan in the `ConfigReturnTypeExtension`, as part of the bleeding edge rules:
```
Line   Composer/PHPStan/ConfigReturnTypeExtension.php
------ ------------------------------------------------------------------------------------------------------------------------------
68     Call to deprecated method selectSingle() of class PHPStan\Reflection\ParametersAcceptorSelector:
See https://github.com/phpstan/phpstan-src/blob/2.0.x/UPGRADING.md#removed-deprecated-parametersacceptorselectorselectsingle
```
After this fix PHPStan analysis passes again.
=> Fix deprecated ParametersAcceptorSelector::selectSingle

src/Composer/Command/DumpAutoloadCommand.php
Currently, there is no error when the vendor folder is not complete or when there are no dependencies installed at all when running `composer dump-autoload`. This PR fixes that, and this results in an exit code 1 when one or more dependencies are not installed.
=> Handle dump-autoload where vendor folder is not installed or not complete

res/composer-schema.json, src/Composer/Package/Package.php, src/Composer/Package/PackageInterface.php
Adds `build-path` option for :pie: PIE - refs ThePHPF/pie-design#28
Also made the definition for the `php-ext` shape re-usable to avoid copy/pasta errors in future
=> Add build-path to php-ext config options for PIE

src/Composer/Advisory/Auditor.php, tests/Composer/Test/Advisory/AuditorTest.php
=> Use a bitmask to produce deterministic exit codes for the "audit" command

src/Composer/Util/Http/CurlDownloader.php, src/Composer/Util/Http/ProxyManager.php
I'm behind a corporate proxy and was hitting a `Curl 2 (...) [CONN-1-0] send: no filter connected` error when trying to download some packages.
Some google research led me to https://github.com/rust-lang/cargo/issues/12202 and its fix https://github.com/rust-lang/cargo/pull/12234.
This PR backports this fix to composer.
> In certain versions of libcurl when proxy is in use with HTTP/2
multiplexing, connections will continue stacking up. This was fixed in libcurl 8.0.0 in curl/curl@821f6e2
=> disable multiplexing for some versions of curl

doc/06-config.md
Cleans up the description of process-timeout to better separate the config setting from the static helper for script commands.
=> Update wording of process-timeout description

doc/03-cli.md
Fixes #12210. The current documentation does not indicate that modifying the repositories section in composer.json also changes the source of security vulnerability advisories.
=> fix(docs): Audit command dependency from custom repositories

res/composer-schema.json, src/Composer/Package/PackageInterface.php
This adds `os-families` and `os-families-exclude` options to tell PIE if an extension is compatible or not with an OS family.
The design was discussed here: https://github.com/ThePHPF/pie-design/pull/29 as well as https://github.com/php/pie/issues/106.
=> Add OS families to `php-ext` config options for PIE

bin/composer, src/Composer/Util/ErrorHandler.php
The `E_STRICT` constant is deprecated in PHP 8.4, and explicit nullable types are also advised with a deprecation notice.
As there are circumstances where people still have to run the 2.2 LTS with newer versions of PHP, we're now suppressing `E_DEPRECATED` (especially because some of the deprecation warnings may end up on stdout due to `display_errors` getting set to `1` in `bin/composer`).
Also see #12214
Targeting 2.2 as discussed in https://github.com/composer/composer/issues/12214#issuecomment-2504292057
=> Suppress E_DEPRECATED for PHP 8.4 compatibility

src/Composer/Command/SelfUpdateCommand.php, src/Composer/Util/Tar.php, tests/Composer/Test/AllFunctionalTest.php, tests/Composer/Test/Command/SelfUpdateCommandTest.php
=> Make use of Phar::running() to get the current phar path

src/Composer/Autoload/AutoloadGenerator.php
=> Fix unstable order of psr-0 and psr-4 rules

src/Composer/Util/Http/CurlDownloader.php, src/Composer/Util/RemoteFilesystem.php
Redirect responses can have a content too. This PR allows redirect responses to return warning(s)/info(s) which then appears as output during `composer install`
=> Allow redirect responses to output warnings/infos

doc/faqs/how-to-install-composer-programmatically.md
If the installer script linked from [this page](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md) is run using PHP 8, it generates the following deprecation notice.
```
Deprecated: Function openssl_free_key() is deprecated since 8.0, as OpenSSLAsymmetricKey objects are freed automatically in Standard input code on line 982
```
This issue was [addressed in the installer script](https://github.com/composer/getcomposer.org/pull/159), but the documentation was not updated to point to a version of it that includes the fix.
=> Update installer script URL to include openssl_free_key() deprecation fix

.github/workflows/release.yml
This will simplify secure installation of composer in GitHub Actions to two calls to `gh` cli with no need to manually import any PGP signing keys:
gh release --repo composer/composer download --pattern composer.phar
gh attestation verify --repo composer/composer composer.phar
Given that the current PGP signing key is stored as a GitHub Action secret, this type of attestation is no less secure than the existing PGP signing.
-----------
see also php/pie#128 and php/pie#139 /cc @asgrim 
I verified functionality in my fork:
```
$ gh attestation verify --owner TimWolla composer.phar
Loaded digest sha256:cd4878b271526ebe5640c51e1843916549c2b97ecaf3340953df2e3926193024 for file://composer.phar
Loaded 1 attestation from GitHub API
The following policy criteria will be enforced:
- OIDC Issuer …
```
=> Generate build provenance attestation during release

src/Composer/Repository/Vcs/GitHubDriver.php
This re-orders the cases in the `switch` to follow the same order as the GitHub documentation (largely alphabetic) for easier comparisons between the two lists.
Refs:
* https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
GitHub looks to have added a dedicated syntax for the thanks.dev funding platform when added to a `funding.yml` file.
However, it looks like Composer does not (yet) support this syntax as can be seen from failed Packagist updates of the dev branches of the [PHP_CodeSniffer](https://packagist.org/packages/squizlabs/php_codesniffer#dev-master) and [PHPCompatibility](https://packagist.org/packages/phpcompatibility/php-compatibility) packages.
The polar.sh funding …
=> Fix failing Packagist updates / GitHubDriver::getFundingInfo(): add support for thanks.dev and polar.sh

src/Composer/Repository/Vcs/GitHubDriver.php, tests/Composer/Test/Repository/Vcs/GitHubDriverTest.php
This patch is intended as an interim solution for #12245 but some form of this should probably be present anyway even after that issue is sorted.
At the moment if a GitHub repo uses a FUNDING.yml in the format documented by GitHub then that entire branch will be skipped from import into Packagist beacuse some of the documented formats are not supported by Packagist/Composer.
As a worst case I would expect the unsupported data to be removed. This isn't critical data - it's optional metadata which is not even present in the composer.json file and which is correct per the GitHub documentation.
On our side I'm trying to get the GitHub FUNDING.yml updated but many of the branches this issue exists on are archived branches which we do not normally modify.
At the moment the Packagist management …
=> Discard unsupported FUNDING.yml URL values

src/Composer/Repository/Vcs/GitHubDriver.php, tests/Composer/Test/Repository/Vcs/GitHubDriverTest.php
Glad that I added some tests as this meant I found a bug in the PR I pulled previously (#12257).
The `thanks_dev` key expects a username in the format `u/gh/USERNAME`, but the call to `basename()` was stripping the `u/gh/` part off.
If the use of `basename()` is preferred here, the alternative would be to add `u/gh/` to the default URL prefix for thanks.dev. Let me know if you want me to change that.
=> GitHubDriverTest::testFundingFormat(): expand the tests + fix bug

src/Composer/Util/GitLab.php
This PR fixes a wrong URL to GitLab personal access token overview.
=> Fix URL to GitLab personal access tokens

src/Composer/Console/Application.php
=> Fix command name parsing to take into account global input options

src/Composer/Command/BaseDependencyCommand.php, tests/Composer/Test/Command/BaseDependencyCommandTest.php
Closes #12227
I just did what you told me in https://github.com/composer/composer/issues/12227#issuecomment-2531797705 - don't really have an overview ;-)
`return` is still missing, right? Should I just copy this from further down?:
```php
$return = $inverted ? 1 : 0;
```
Or move it upwards?
=> Adding explicit message to `why-not` if package is already installed

src/Composer/Command/RequireCommand.php, src/Composer/Factory.php, src/Composer/PartialComposer.php
fixes #12253
Additionally this keeps track whether a Composer instance is the global one or not, which is a nice side effect/cleanup
=> Suppress require-dev hint when requiring things globally

src/Composer/InstalledVersions.php, tests/Composer/Test/InstalledVersionsTest.php, tests/bootstrap.php
=> Fix regression from #12233 in InstalledVersions when reload is used

doc/03-cli.md, src/Composer/EventDispatcher/EventDispatcher.php, tests/Composer/Test/EventDispatcher/EventDispatcherTest.php
This allows running `COMPOSER_SKIP_SCRIPTS="post-install-cmd" && composer install` to for instance skip a configured `post-install-cmd`
=> Scripts: add ENV variable to skip script execution for certain event names

res/composer-schema.json, src/Composer/Package/PackageInterface.php
Adds a new directive `override-download-url-method` to let extensions change the behaviour of where PIE downloads the source code package from. Ref: php/pie#187
=> Added override-download-url-method directive for php-ext

res/composer-schema.json, src/Composer/Package/PackageInterface.php
After discussion in https://github.com/php/pie/pull/187/files#r1942530187 this PR removes the `override-` prefix
=> Remove superfluous override- prefix from download-url-method

src/Composer/Package/Loader/RootPackageLoader.php
Following commit enabled async execution https://github.com/composer/composer/commit/b0665981c2e80578b6692da8604edcda7b2093ab in the VersionGuesser:
```php
$promises[] = $this->process->executeAsync($cmdLine, $path)->then(function (Process $process) use (&$length, &$version, &$prettyVersion, $candidateVersion, &$promises): void {
```
However, the VersionGuesser fallback instance created in [RootPackageLoader constructor](https://github.com/composer/composer/blob/e58aad45b51c6b29b9f47800a182d7e86e654201/src/Composer/Package/Loader/RootPackageLoader.php#L63) still passes a ProcessExecutor instance _wihtout_ async enabled:
```php
$this->versionGuesser = $versionGuesser ?: new VersionGuesser($config, new ProcessExecutor($io), $this->versionParser, $io);
```
I suppose the most backwards …
=> fix: RootPackageLoader.php constructor creates unusable fallback instance of VersionGuesser

src/Composer/Util/Platform.php
Composer now permits running as root when the container runtime is [containerd](https://github.com/containerd/containerd), aligning with existing behavior for Docker and Podman.
This additional check is useful for modern Kubernetes environments where Docker isn't used for managing containers.
```sh
sh-5.2# cat /proc/self/mountinfo
4029 2756 0:390 / / rw,relatime master:1322 - overlay overlay rw,lowerdir=/var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1591431/fs:/var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1591430/fs:/var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1591429/fs:/var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1591428/ …
```
=> feat: Detect containerd runtime and allow root execution

doc/03-cli.md, src/Composer/Util/ProcessExecutor.php
This PR introduces the environment variable COMPOSER_MAX_PARALLEL_PROCESSES to increase or decrease the number parallel processes initiated by the ProcessExecutor.
In our case we want to decrease the number as 10 simultaneous unzip processes puts a severe strain on our server. (Especially when there are multiple composer installs being performed at the same time.
=> feat: add COMPOSER_MAX_PARALLEL_PROCESSES 

src/Composer/Util/ErrorHandler.php
Fixes #12285
Workaround for symfony/symfony#60128 cc @sebastianbergmann this should work right?
=> Fix error handler to bypass some new php 8.5 warnings and avoid spamming output too much with deprecation notices

res/composer-schema.json, tests/Composer/Test/Json/ComposerSchemaTest.php
=> Fix support for various version schemes in the composer schema

src/Composer/EventDispatcher/EventDispatcher.php, tests/Composer/Test/Command/GlobalCommandTest.php
=> Do not output script being run when running via composer <script-name>

tests/Composer/Test/InstallerTest.php, tests/Composer/Test/Package/Archiver/ArchiveManagerTest.php
=> Fix deprecation warnings

src/Composer/Downloader/ZipDownloader.php
improvement for diagnosing issues like https://github.com/composer/composer/issues/12369
----
After installing composer from source and patching up the ZipDownloader as instructed, I managed to track down the issue to https://github.com/cebe/markdown which is a dependency of [Yii2](https://github.com/yiisoft/yii2/blob/master/composer.json#L77C10-L77C23), more specifically caused by [this file](https://github.com/cebe/markdown/blob/master/tests/markdown-data/dos.html) which would be best if it could be ignored since its a test file.
Since the library in question has last been released in 2018, I'm not holding my hopes up that it will be fixed, so we will be looking at alternatives. 
In any case, this proposed error message would have made it 1000x easier to figure out what went wrong and …
=> Improve error message on zip bomb

src/Composer/Command/DiagnoseCommand.php, src/Composer/Util/Http/CurlDownloader.php
PHP 8.4 should be able to support HTTP/3 if the Curl extension is compiled with an OpenSSL branch with HTTP/3 support.
GitHub, GitLab, and packagist.org do not seem to support HTTP/3 yet, but we can still safely enable HTTP/3 if it's available to future-proof it.
This also updates the `diagnose` command to show the HTTP versions supported.
=> CurlDownloader - Add support for HTTP/3

src/Composer/Repository/Vcs/GitLabDriver.php
GitLab's new Planner permission has access level 15, which prevents Composer from figuring out that the token does not have enough access to determine the main branch. 
See: https://docs.gitlab.com/api/access_requests/
=> Handle Planner role in GitLab

src/Composer/Plugin/PluginManager.php
Fixes https://github.com/composer/composer/issues/12433
=> Avoid marking a plugin as loaded until it is actually loaded

src/Composer/Command/SelfUpdateCommand.php, src/Composer/Console/Application.php, tests/Composer/Test/ApplicationTest.php
This will fail with a clear explanation why it is not available when not running from a phar
Fixes #12395
cc @joachim-n
=> Always allow running self-update, but with warning

src/Composer/Console/Application.php, src/Composer/EventDispatcher/EventDispatcher.php, tests/Composer/Test/ApplicationTest.php, tests/Composer/Test/InstallerTest.php
Following https://github.com/symfony/symfony/pull/60394. Please tell me if this should rather target main
=> Add forward compatibility layer for symfony/console >7.4

src/Composer/EventDispatcher/EventDispatcher.php, tests/Composer/Test/EventDispatcher/EventDispatcherTest.php
Only create autoloaders when needed, and avoid creating duplicate autoloaders.
In pathological cases like declaring a post-package-install script as `"Foo::bar"`, it would classmap-scan the whole project on every package being installed, causing 200ms of delay at every package. Trying this on a repo here this PR improves a fresh install time from 38 down to 9seconds, which is quite dramatic. I suppose other cases where large classmaps or listener-heavy plugins are present might also see significant speedups.
Targetting 2.9 though because it does carry some risk of regression in case I missed a corner.
Refs #8587
=> Improve performance of script handlers

src/Composer/Autoload/AutoloadGenerator.php, tests/Composer/Test/Autoload/Fixtures/autoload_phar_static.php, tests/Composer/Test/Autoload/Fixtures/autoload_static_include_path.php, tests/Composer/Test/Autoload/Fixtures/autoload_static_target_dir.php
PhpStorm trims trailing spaces (which I have specified in `.editorconfig`) when I do the Rename class refactoring.
=> Trim trailing spaces in autoload files

composer.json, composer.lock
Hey there :wave: 
If I execute `composer update --prefer-lowest` in our project, I have a problem while checking the code with PHPStan. It will install `composer/pcre` in version `2.2.0` and the `%featureToggles.narrowPregMatches%` config in `extension.neon` causes the problem. This file was changed with `2.3.0` and updating to at least this version fixes the problem on our end. 
As we are not directly depending on the `composer/pcre` package, I made the change here.
Thanks for having a look at this and I am looking for feedback 🙂 👍
Best regards
=> chore: Increase minimum version of composer/pcre

src/Composer/Util/Git.php
Change match index from 1 to 2 to account for recently changed regex expressions for Bitbucket URLs
Based on changes from PR [#12103](https://github.com/composer/composer/pull/12103). Bitbucket URL regex was changed, but following reference to $match for $bitbucketUtil->authorizeOAuthInteractively were not updated accordingly.
=> Fix Bitbucket oauth failure

doc/03-cli.md
remove redundant words in doc/03-cli.md
=> chore: remove redundant words in doc/03-cli.md

src/Composer/Util/Http/CurlDownloader.php
The function `curl_close()` doesn't have any effect since PHP 8.0: https://www.php.net/manual/en/function.curl-close.php
The deprecation of the function is implemented in PHP 8.5.
=> fix: deprecation of curl_close in CurlDownloader.php

src/Composer/Command/CreateProjectCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Console/Application.php, tests/Composer/Test/Command/RequireCommandTest.php
Not sure if this should be reported as a bug, I therefore opened this against `main`. Let me know if I should update.
I was mislead by some of the IO confirmation questions which were indicating an uppercase `Y` as valid answer. I checked, and the default regex used in `Composer\Question\StrictConfirmationQuestion` does in fact not allow an uppercase `Y`. I therefore propose to adjust the remaining questions which do not already indicate a lowercase `y`.
I searched for usages of `Composer\IO\ConsoleIO::askConfirmation()` and these were the remaining questions which did not already use `yes` or `y`.
=> Streamline IO confirmation questions to use lowercase 'y'.

src/Composer/Autoload/AutoloadGenerator.php, tests/Composer/Test/Autoload/AutoloadGeneratorTest.php
Fixes #12478 in 2.8
This PR fixes an issue where Composer generates incorrect PSR-4 compliance warnings when using `exclude-from-classmap` patterns with directories that are symlinks.
When a PSR-4 autoload path is a symlink (either relative or absolute) and the project uses `exclude-from-classmap` patterns (e.g., `**/vendor/`), Composer incorrectly reports that classes in the excluded directories don't comply with PSR-4 standards.
Example warning:
```
Class Doctrine\Instantiator\InstantiatorInterface located in ./tools/vendor/doctrine/instantiator/src/Doctrine/Instantiator/InstantiatorInterface.php does not comply with psr-4 autoloading standard (rule: MyTools\ => ./tools). Skipping.
```
The issue occurs because:
1. The `buildExclusionRegex` method was only matching exclude patterns …
=> Fix PSR-4 warnings when using exclude-from-classmap with symlinked directories

.github/workflows/continuous-integration.yml, composer.json, composer.lock, src/Composer/Command/BaseCommand.php, src/Composer/Command/DumpAutoloadCommand.php, src/Composer/Command/ExecCommand.php, src/Composer/Command/InitCommand.php, src/Composer/Command/InstallCommand.php, src/Composer/Command/RemoveCommand.php, src/Composer/Command/RequireCommand.php, src/Composer/Command/ShowCommand.php, src/Composer/Command/UpdateCommand.php, tests/Composer/Test/Plugin/Fixtures/plugin-v8/Installer/CommandProvider.php
Allows installing with Symfony 8 components (dev) and updates commands accordingly.
Breaking change:
`BaseCommand::initialize()` added return type: `void`
=> Add Symfony 8 support

src/Composer/Package/Version/VersionBumper.php, tests/Composer/Test/Package/Version/VersionBumperTest.php
the preg match was not updated to support major versions containing a zero :) like ~2025.1.x this should do the trick now. checkout the testcase for a proper example
=> fixes a regression introduced via 304107d breaking bumping versions containing a zero

src/Composer/Util/RemoteFilesystem.php
=> Fix php8.5 deprecation warning

src/Composer/Util/Git.php, tests/Composer/Test/Util/GitTest.php
Resolves: https://github.com/composer/composer/issues/12482
To verify:
Create an API token with `read:repository:bitbucket` scope at https://id.atlassian.com/manage-profile/security/api-tokens
Configure the token:
```
composer config --auth http-basic.bitbucket.org your-bitbucket-email@example.org ATAT_YOUR_BITBUCKET_API_TOKEN
```
Have a composer.json file and try with both `git` and `bitbucket` repository types
```
{
"require": {
"acme/private": "dev-main"
},
"repositories": {
"bitbucket": {
"type": "git",
"url": "https://bitbucket.org/acme/private"
}
}
}
```
Run `composer update` like:
```
Running 2.8.999-dev+source (@release_date@) with PHP 8.4.11 on Darwin / 24.6.0
Composer is operating slower than normal because you have Xdebug enabled. See https://getcomposer.org/xdebug
Reading …
```
=> Bitbucket: add support for API tokens

src/Composer/DependencyResolver/Transaction.php, tests/Composer/Test/Fixtures/installer/install-forces-reinstall-if-abandon-changes.test
=> Ensure packages where the abandoned state changes get reinstalled to sync up the state in installed.json

src/Composer/Advisory/Auditor.php, src/Composer/Command/AuditCommand.php, src/Composer/Repository/RepositorySet.php, tests/Composer/Test/Advisory/AuditorTest.php
As discussed in https://github.com/composer/composer/issues/12467 this adds the option `--ignore-unreachable` which will let the audit command run even if repositories are unreachable. They will be listed as unreachable in the report. 
No change has been made to the overall error handling.
=> feat: Added --ignore-unreachable flag to audit command for private/unreachable repositories
